#include "compute/qrx_aura_runtime_delivery.h"
#include <openssl/evp.h>
#include <stdio.h>
#ifndef _WIN32
#include <sys/stat.h>
#endif
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <process.h>
#define getpid _getpid
#else
#include <unistd.h>
#endif
#define CHECK(x) do{if(!(x)){fprintf(stderr,"CHECK failed %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)

typedef struct { QrxStorageFs *fs; } Remote;
static int rstat(void*v,const char*root,uint64_t*out){Remote*r=v;unsigned char*b=NULL;size_t n=0;if(qrx_storage_fs_read(r->fs,root,&b,&n))return-1;free(b);*out=n;return 0;}
static int rrange(void*v,const char*root,uint64_t off,size_t len,uint8_t**out,size_t*outn){Remote*r=v;return qrx_storage_fs_read_range(r->fs,root,off,len,out,outn);}
static int put_file(QrxStorageFs*fs,const char*path,char root[65]){return qrx_storage_fs_put_file(fs,path,root);}
static void init_pkg(QrxAuraRuntimePackageAnnouncement*p,const char*id,QrxAuraRuntimeAdapterKind ak,QrxAuraPackagePlatform plat,QrxAuraPackageArch arch,QrxMoeRuntimeBackend be,uint32_t feat,const char*root,const char*uri,const char*file){memset(p,0,sizeof(*p));p->version=1;snprintf(p->publisher_id,sizeof(p->publisher_id),"qrx:runtime:official");snprintf(p->package_id,sizeof(p->package_id),"%s",id);snprintf(p->package_version,sizeof(p->package_version),"0.0.9-test");p->sequence=1;p->valid_from_height=1;p->valid_until_height=100000;p->adapter_kind=ak;p->platform=plat;p->arch=arch;p->backend=be;p->required_accelerator_features=feat;p->min_device_memory_bytes=512ull<<20;if(be==QRX_MOE_BACKEND_CUDA){p->min_cuda_cc_major=6;p->min_cuda_cc_minor=1;}snprintf(p->content_root,sizeof(p->content_root),"%s",root);snprintf(p->download_uri,sizeof(p->download_uri),"%s",uri);snprintf(p->install_filename,sizeof(p->install_filename),"%s",file);}
static void add_unsigned(QrxAuraRuntimePackageCatalog*c,const QrxAuraRuntimePackageAnnouncement*p){c->entries[c->count++].announcement=*p;}
static QrxMoeRuntimeInventory one_device(QrxMoeRuntimeBackend b,uint32_t af,uint64_t mem,uint32_t maj,uint32_t min){QrxMoeRuntimeInventory i;memset(&i,0,sizeof(i));i.version=QRX_MOE_DISCOVERY_VERSION;i.device_count=1;i.devices[0].version=QRX_MOE_DISCOVERY_VERSION;i.devices[0].source=(b==QRX_MOE_BACKEND_CUDA)?QRX_MOE_DISCOVERY_CUDA_DRIVER:((af&QRX_MOE_ACCEL_FEAT_METAL)?QRX_MOE_DISCOVERY_APPLE_NATIVE:QRX_MOE_DISCOVERY_CPU_NATIVE);i.devices[0].runtime_present=1;i.devices[0].device.version=QRX_MOE_RUNTIME_VERSION;i.devices[0].device.backend=b;snprintf(i.devices[0].device.device_name,sizeof(i.devices[0].device.device_name),"phase177");i.devices[0].device.device_memory_bytes=mem;i.devices[0].device.accelerator_features=af;i.devices[0].device.cuda_cc_major=maj;i.devices[0].device.cuda_cc_minor=min;i.devices[0].device.max_batch_items=64;return i;}
int main(int argc,char**argv){
    CHECK(argc==2);const char*plugin=argv[1];long pid=(long)getpid();char rdir[256],ldir[256],work[256],install[256],cfg[256],catalogp[256];snprintf(rdir,sizeof(rdir),"phase177-remote-%ld",pid);snprintf(ldir,sizeof(ldir),"phase177-local-%ld",pid);snprintf(work,sizeof(work),"phase177-work-%ld",pid);snprintf(install,sizeof(install),"phase177-install-%ld",pid);snprintf(cfg,sizeof(cfg),"phase177-host-%ld.conf",pid);snprintf(catalogp,sizeof(catalogp),"phase177-runtime-%ld.qrx",pid);
#ifndef _WIN32
    char cmd[1200];snprintf(cmd,sizeof(cmd),"rm -rf '%s' '%s' '%s' '%s'",rdir,ldir,work,install);system(cmd);mkdir(install,0700);
#endif
    QrxStorageFs*remote=NULL,*local=NULL;CHECK(!qrx_storage_fs_open(rdir,0,0,&remote));CHECK(!qrx_storage_fs_open(ldir,0,0,&local));char root[65];CHECK(!put_file(remote,plugin,root));
    EVP_PKEY*key=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519");CHECK(key);QrxAuraRuntimeSinglePublisherKey sk={"qrx:runtime:official",key};QrxAuraRuntimePackageAnnouncement p;init_pkg(&p,"phase177-native-cpu",QRX_AURA_ADAPTER_LLAMA_CPP_CPU,QRX_AURA_PACKAGE_PLATFORM_ANY,QRX_AURA_PACKAGE_ARCH_ANY,QRX_MOE_BACKEND_CPU,QRX_MOE_ACCEL_FEAT_FP32,root,"https://origin.invalid/runtime","phase177-runtime.so");uint8_t*sig=NULL;size_t sn=0;CHECK(!qrx_aura_runtime_package_sign(key,&p,&sig,&sn));QrxAuraRuntimePackageCatalog cat;qrx_aura_runtime_package_catalog_init(&cat);CHECK(!qrx_aura_runtime_package_catalog_ingest(&cat,&p,sig,sn,100,qrx_aura_runtime_single_publisher_lookup,&sk));free(sig);CHECK(!qrx_aura_runtime_package_catalog_save_signed_file(catalogp,&cat));QrxAuraRuntimePackageCatalog loaded;qrx_aura_runtime_package_catalog_init(&loaded);CHECK(!qrx_aura_runtime_package_catalog_load_signed_file(catalogp,100,qrx_aura_runtime_single_publisher_lookup,&sk,&loaded));CHECK(loaded.count==1&&!strcmp(loaded.entries[0].announcement.content_root,root));
    QrxAuraProviderHostConfig host;qrx_aura_provider_host_config_defaults(&host);host.enabled=1;snprintf(host.provider_id,sizeof(host.provider_id),"provider177");snprintf(host.pod_id,sizeof(host.pod_id),"pod177");snprintf(host.network,sizeof(host.network),"alpha");snprintf(host.region,sizeof(host.region),"DE");snprintf(host.lease_journal_path,sizeof(host.lease_journal_path),"phase177.leases");snprintf(host.job_journal_path,sizeof(host.job_journal_path),"phase177.jobs");CHECK(!qrx_aura_provider_host_config_save(cfg,&host));
    Remote rr={remote};QrxAuraDriveModelFetchContext drive={0};drive.local_cache=local;drive.stat=rstat;drive.fetch_range=rrange;drive.remote_ctx=&rr;drive.range_bytes=1024;QrxAuraRuntimeDeliveryContext del;CHECK(!qrx_aura_runtime_delivery_defaults(&del,work));del.drive=&drive;del.local_cache=local;del.allow_https_origin=0;QrxAuraRuntimeProbeActivation probe={0};probe.model_cache=local;QrxAuraRuntimeOneClickResult res;CHECK(!qrx_aura_runtime_auto_bootstrap(cfg,catalogp,100,QRX_AURA_POWER_BALANCED,install,qrx_aura_runtime_single_publisher_lookup,&sk,&del,&probe,&res));CHECK(qrx_storage_fs_has(local,root)==1);CHECK(probe.plugin_open);QrxAuraProviderHostConfig after;CHECK(!qrx_aura_provider_host_config_load(cfg,&after));CHECK(after.runtime_adapter.kind==QRX_AURA_ADAPTER_LLAMA_CPP_CPU&&after.runtime_adapter.explicit_path[0]);qrx_aura_runtime_probe_activation_close(&probe);
    /* Developer fallback proves the same fetcher can seed CAS from an origin; production uses HTTPS. */
    QrxAuraRuntimeDeliveryContext fdel;CHECK(!qrx_aura_runtime_delivery_defaults(&fdel,work));fdel.local_cache=local;fdel.allow_https_origin=0;fdel.allow_file_origin=1;char uri[1024];snprintf(uri,sizeof(uri),"file://%s",plugin);snprintf(p.download_uri,sizeof(p.download_uri),"%s",uri);char dl[QRX_AURA_RUNTIME_ADAPTER_PATH_MAX];CHECK(!qrx_aura_runtime_fetch_drive_then_origin(&fdel,&p,dl));char got[65];CHECK(!qrx_aura_runtime_package_file_root(dl,got)&&!strcmp(got,root));remove(dl);
    /* Explicit cross-platform selection matrix: the end user never makes this choice. */
    QrxAuraRuntimePackageCatalog matrix;qrx_aura_runtime_package_catalog_init(&matrix);QrxAuraRuntimePackageAnnouncement q;
    init_pkg(&q,"linux-x64-cpu",QRX_AURA_ADAPTER_LLAMA_CPP_CPU,QRX_AURA_PACKAGE_PLATFORM_LINUX,QRX_AURA_PACKAGE_ARCH_X86_64,QRX_MOE_BACKEND_CPU,QRX_MOE_ACCEL_FEAT_FP32,root,"https://x","cpu.so");add_unsigned(&matrix,&q);
    init_pkg(&q,"linux-arm64-cpu",QRX_AURA_ADAPTER_LLAMA_CPP_CPU,QRX_AURA_PACKAGE_PLATFORM_LINUX,QRX_AURA_PACKAGE_ARCH_AARCH64,QRX_MOE_BACKEND_CPU,QRX_MOE_ACCEL_FEAT_FP32,root,"https://x","cpu.so");add_unsigned(&matrix,&q);
    init_pkg(&q,"mac-arm64-metal",QRX_AURA_ADAPTER_LLAMA_CPP_METAL,QRX_AURA_PACKAGE_PLATFORM_MACOS,QRX_AURA_PACKAGE_ARCH_AARCH64,QRX_MOE_BACKEND_OTHER,QRX_MOE_ACCEL_FEAT_METAL|QRX_MOE_ACCEL_FEAT_FP16,root,"https://x","metal.dylib");add_unsigned(&matrix,&q);
    init_pkg(&q,"windows-x64-cpu",QRX_AURA_ADAPTER_LLAMA_CPP_CPU,QRX_AURA_PACKAGE_PLATFORM_WINDOWS,QRX_AURA_PACKAGE_ARCH_X86_64,QRX_MOE_BACKEND_CPU,QRX_MOE_ACCEL_FEAT_FP32,root,"https://x","cpu.dll");add_unsigned(&matrix,&q);
    init_pkg(&q,"linux-x64-cuda",QRX_AURA_ADAPTER_LLAMA_CPP_CUDA,QRX_AURA_PACKAGE_PLATFORM_LINUX,QRX_AURA_PACKAGE_ARCH_X86_64,QRX_MOE_BACKEND_CUDA,QRX_MOE_ACCEL_FEAT_CUDA|QRX_MOE_ACCEL_FEAT_FP16,root,"https://x","cuda.so");add_unsigned(&matrix,&q);
    QrxAuraRuntimeActivationPlan pl;QrxMoeRuntimeInventory cpu=one_device(QRX_MOE_BACKEND_CPU,QRX_MOE_ACCEL_FEAT_FP32,8ull<<30,0,0);CHECK(!qrx_aura_runtime_package_select_for(&matrix,&cpu,100,QRX_AURA_POWER_BALANCED,QRX_AURA_PACKAGE_PLATFORM_LINUX,QRX_AURA_PACKAGE_ARCH_AARCH64,&pl)&&!strcmp(pl.package.package_id,"linux-arm64-cpu"));CHECK(!qrx_aura_runtime_package_select_for(&matrix,&cpu,100,QRX_AURA_POWER_BALANCED,QRX_AURA_PACKAGE_PLATFORM_WINDOWS,QRX_AURA_PACKAGE_ARCH_X86_64,&pl)&&!strcmp(pl.package.package_id,"windows-x64-cpu"));QrxMoeRuntimeInventory metal=one_device(QRX_MOE_BACKEND_OTHER,QRX_MOE_ACCEL_FEAT_METAL|QRX_MOE_ACCEL_FEAT_FP16|QRX_MOE_ACCEL_FEAT_FP32,8ull<<30,0,0);CHECK(!qrx_aura_runtime_package_select_for(&matrix,&metal,100,QRX_AURA_POWER_BALANCED,QRX_AURA_PACKAGE_PLATFORM_MACOS,QRX_AURA_PACKAGE_ARCH_AARCH64,&pl)&&pl.package.adapter_kind==QRX_AURA_ADAPTER_LLAMA_CPP_METAL);QrxMoeRuntimeInventory cuda=one_device(QRX_MOE_BACKEND_CUDA,QRX_MOE_ACCEL_FEAT_CUDA|QRX_MOE_ACCEL_FEAT_FP16|QRX_MOE_ACCEL_FEAT_FP32,24ull<<30,6,1);CHECK(!qrx_aura_runtime_package_select_for(&matrix,&cuda,100,QRX_AURA_POWER_PERFORMANCE,QRX_AURA_PACKAGE_PLATFORM_LINUX,QRX_AURA_PACKAGE_ARCH_X86_64,&pl)&&pl.package.adapter_kind==QRX_AURA_ADAPTER_LLAMA_CPP_CUDA);
    qrx_aura_runtime_package_catalog_free(&matrix);qrx_aura_runtime_package_catalog_free(&loaded);qrx_aura_runtime_package_catalog_free(&cat);qrx_storage_fs_close(local);qrx_storage_fs_close(remote);EVP_PKEY_free(key);remove(cfg);remove(catalogp);
#ifndef _WIN32
    snprintf(cmd,sizeof(cmd),"rm -rf '%s' '%s' '%s' '%s'",rdir,ldir,work,install);system(cmd);
#endif
    puts("phase177 AURA zero-touch runtime delivery matrix: PASS");return 0;
}
