#include "compute/qrx_aura_provider_service.h"
#include "resource/qrx_resource_provider_runtime.h"
#include <assert.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifndef _WIN32
#include <unistd.h>
#endif

#define MIB (1024ULL*1024ULL)
#define GIB (1024ULL*1024ULL*1024ULL)
#define H 700ULL

typedef struct {const char*id[16];EVP_PKEY*key[16];size_t count;} KeyRing;
typedef struct {char local[129];char remote[129];QrxAuraSecureSession session;} SessionEntry;
typedef struct {SessionEntry e[8];size_t count;} SessionMap;
typedef struct {QrxAuraPodAnnouncement a[8];uint8_t *sig[8];size_t sig_len[8];size_t count;} AdvertiseLog;
typedef struct {int calls;} FetchLog;

static int contains_bytes(const void *hay,size_t hn,const void *needle,size_t nn){
    if(!needle||!nn) return 1;
    if(!hay||nn>hn) return 0;
    const unsigned char *h=(const unsigned char*)hay,*n=(const unsigned char*)needle;
    for(size_t i=0;i+nn<=hn;i++) if(!memcmp(h+i,n,nn)) return 1;
    return 0;
}

static void hexfill(char out[65],char c){for(int i=0;i<64;i++)out[i]=c;out[64]=0;}
static EVP_PKEY*new_key(const char*name){EVP_PKEY_CTX*c=EVP_PKEY_CTX_new_from_name(NULL,name,NULL);EVP_PKEY*k=NULL;assert(c&&EVP_PKEY_keygen_init(c)==1&&EVP_PKEY_generate(c,&k)==1&&k);EVP_PKEY_CTX_free(c);return k;}
static void ring_add(KeyRing*r,const char*id,EVP_PKEY*k){assert(r&&id&&k&&r->count<16);r->id[r->count]=id;r->key[r->count]=k;r->count++;}
static int key_lookup(void*ctx,const char*id,EVP_PKEY**out){KeyRing*r=ctx;if(!r||!id||!out)return -1;for(size_t i=0;i<r->count;i++)if(!strcmp(r->id[i],id)){assert(EVP_PKEY_up_ref(r->key[i])==1);*out=r->key[i];return 0;}return -1;}
static int session_lookup(void*ctx,const char*local,const char*remote,QrxAuraSecureSession*out){SessionMap*m=ctx;if(!m||!local||!remote||!out)return -1;for(size_t i=0;i<m->count;i++)if(!strcmp(m->e[i].local,local)&&!strcmp(m->e[i].remote,remote)){*out=m->e[i].session;return 0;}return -1;}
static void session_add(SessionMap*m,const char*local,const char*remote,const QrxAuraSecureSession*s){assert(m&&local&&remote&&s&&m->count<8);snprintf(m->e[m->count].local,sizeof(m->e[m->count].local),"%s",local);snprintf(m->e[m->count].remote,sizeof(m->e[m->count].remote),"%s",remote);m->e[m->count].session=*s;m->count++;}
static uint64_t fixed_height(void*ctx){return *(uint64_t*)ctx;}

static QrxResourceProviderRuntime make_runtime(const char*provider){QrxResourceProviderPlan p;memset(&p,0,sizeof(p));p.version=QRX_RESOURCE_PROVIDER_VERSION;snprintf(p.region,sizeof(p.region),"EU-WEST");p.enabled_mask=QRX_PROVIDER_ENABLE_COMPUTE|QRX_PROVIDER_ENABLE_AI|QRX_PROVIDER_ENABLE_MODEL_CACHE|QRX_PROVIDER_ENABLE_NETWORK;p.compute_threads=8;p.network_egress_mbps=1000;p.model_cache_bytes=8*GIB;p.primary_action=QRX_PROVIDER_ENABLE_COMPUTE;p.opportunity_score=8000;p.expected_utilization_bps=4000;QrxResourceProviderRuntime rt;assert(qrx_resource_provider_runtime_init(&rt,provider,"alphanet",&p)==0);assert(qrx_resource_provider_runtime_mark_ready(&rt)==0);QrxResourceProviderMarketRegistration reg;assert(qrx_resource_provider_market_register(&rt,NULL,H,&reg)==0);assert(qrx_resource_provider_runtime_start_serving(&rt)==0);return rt;}
static int moe_worker(void*ctx,const void*in,size_t in_n,void*out,size_t cap,size_t*out_n){(void)ctx;QrxAuraMoeFragmentEnvelope e;if(qrx_aura_moe_fragment_payload_decode(in,in_n,&e))return -1;char b[256];int n=snprintf(b,sizeof(b),"F%u:E%u+%u:%.*s",e.fragment_index,e.expert_first,e.expert_count,(int)e.input_len,(const char*)e.input);qrx_aura_moe_fragment_envelope_free(&e);if(n<0||(size_t)n>cap)return -1;memcpy(out,b,(size_t)n);*out_n=(size_t)n;return 0;}
static QrxAuraRuntimeBinding make_binding(const char*provider,const char*pod,QrxResourceProviderRuntime*rt){QrxAuraRuntimeBinding b;memset(&b,0,sizeof(b));b.version=QRX_AURA_LIVE_DISPATCH_VERSION;snprintf(b.provider_id,sizeof(b.provider_id),"%s",provider);snprintf(b.pod_id,sizeof(b.pod_id),"%s",pod);b.provider_runtime=rt;b.local=1;b.device.version=QRX_MOE_RUNTIME_VERSION;b.device.backend=QRX_MOE_BACKEND_CPU;snprintf(b.device.device_name,sizeof(b.device.device_name),"phase164-cpu");b.device.accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;b.device.device_memory_bytes=64*GIB;b.device.max_batch_items=8;b.adapter.version=QRX_MOE_DISCOVERY_VERSION;snprintf(b.adapter.name,sizeof(b.adapter.name),"phase164-moe");b.adapter.backend=QRX_MOE_BACKEND_CPU;b.adapter.kernel_mask=QRX_MOE_KERNEL_FP32;b.adapter.ready=1;b.adapter.execute=moe_worker;assert(qrx_moe_runtime_device_validate(&b.device)==0);assert(qrx_moe_worker_adapter_validate(&b.adapter)==0);return b;}
static QrxAuraPodCapacity capacity(const char*provider,const char*pod){QrxAuraPodCapacity p;memset(&p,0,sizeof(p));p.version=QRX_AURA_FABRIC_VERSION;snprintf(p.provider_id,sizeof(p.provider_id),"%s",provider);snprintf(p.pod_id,sizeof(p.pod_id),"%s",pod);snprintf(p.region,sizeof(p.region),"EU-WEST");p.backend=QRX_MOE_BACKEND_CPU;p.accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;p.role_mask=QRX_AURA_POD_ROLE_INFERENCE|QRX_AURA_POD_ROLE_MODEL_CACHE|QRX_AURA_POD_ROLE_VERIFY;p.usable_memory_bytes=64*GIB;p.free_memory_bytes=48*GIB;p.model_cache_free_bytes=32*GIB;p.measured_milli_tokens_per_second=12000;p.network_egress_mbps=1000;p.latency_ms=15;p.utilization_bps=2000;p.reliability_bps=9950;p.cache_hit_bps=9000;p.expert_locality_bps=9000;p.max_context_tokens=32768;p.node_count=1;p.available=1;hexfill(p.calibration_commitment,'1');assert(qrx_aura_pod_capacity_validate(&p)==0);return p;}
static int advertise_cb(void*ctx,const QrxAuraPodAnnouncement*a,const uint8_t*sig,size_t sn){AdvertiseLog*l=ctx;if(!l||!a||!sig||!sn||l->count>=8)return -1;l->a[l->count]=*a;l->sig[l->count]=malloc(sn);assert(l->sig[l->count]);memcpy(l->sig[l->count],sig,sn);l->sig_len[l->count]=sn;l->count++;return 0;}
static int fake_fetch(void*ctx,const QrxAiModelRecord*m,const QrxAuraModelCachePlacement*p,char out[65]){FetchLog*l=ctx;if(!l||!m||!p||!p->bytes_to_place)return -1;l->calls++;return qrx_ai_model_commitment(m,out);}
static int aggregate(void*ctx,const uint8_t*const*parts,const size_t*sizes,uint32_t count,void*out,size_t cap,size_t*outn){(void)ctx;size_t n=0;for(uint32_t i=0;i<count;i++){if(n+sizes[i]+(i?1:0)>cap)return -1;if(i)((char*)out)[n++]='|';memcpy((char*)out+n,parts[i],sizes[i]);n+=sizes[i];}*outn=n;return 0;}

static QrxAuraRemoteFrame lease_frame(const char*provider,const char*pod,const char*requester,const char*lease,uint64_t seq,uint64_t exp){QrxAuraRemoteFrame f;memset(&f,0,sizeof(f));f.version=QRX_AURA_REMOTE_VERSION;f.kind=QRX_AURA_REMOTE_KIND_LEASE_OPEN;snprintf(f.signer_id,sizeof(f.signer_id),"%s",requester);f.sequence=seq;f.height=H;hexfill(f.admission_commitment,'a');snprintf(f.provider_id,sizeof(f.provider_id),"%s",provider);snprintf(f.pod_id,sizeof(f.pod_id),"%s",pod);snprintf(f.lease_id,sizeof(f.lease_id),"%s",lease);f.lease_expires_height=exp;f.compute_threads=2;f.network_egress_mbps=100;f.node_id=1;f.required_memory_bytes=MIB;f.max_output_bytes=4096;f.fragment_count=1;snprintf(f.runtime_id,sizeof(f.runtime_id),"qrx-llm-runtime-v1");snprintf(f.model_id,sizeof(f.model_id),"qrx/lease-test");snprintf(f.model_version,sizeof(f.model_version),"1");hexfill(f.model_commitment,'b');EVP_MD_CTX*m=EVP_MD_CTX_new();unsigned char h[32];unsigned hn=0;assert(m&&EVP_DigestInit_ex(m,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(m,"QRX/AURA/REMOTE-PAYLOAD/V1",strlen("QRX/AURA/REMOTE-PAYLOAD/V1"))==1&&EVP_DigestFinal_ex(m,h,&hn)==1&&hn==32);EVP_MD_CTX_free(m);static const char hx[]="0123456789abcdef";for(int i=0;i<32;i++){f.payload_commitment[i*2]=hx[h[i]>>4];f.payload_commitment[i*2+1]=hx[h[i]&15];}f.payload_commitment[64]=0;return f;}

static void test_secure_channel(void){
    EVP_PKEY *a=new_key("X25519"),*b=new_key("X25519");QrxAuraSecureSession sa,sb;assert(qrx_aura_secure_session_x25519(a,b,"requester-sec","provider-sec",&sa)==0);assert(qrx_aura_secure_session_x25519(b,a,"requester-sec","provider-sec",&sb)==0);assert(!memcmp(sa.key,sb.key,sizeof(sa.key))&&!strcmp(sa.session_id,sb.session_id));char lease[65];hexfill(lease,'c');QrxAuraRemoteFrame f=lease_frame("provider-sec","pod-sec","requester-sec",lease,1,H+10);f.kind=QRX_AURA_REMOTE_KIND_DISPATCH;const char secret[]="private-reasoning-prompt";uint8_t*sealed=NULL,*plain=NULL;size_t sn=0,pn=0;assert(qrx_aura_secure_payload_seal(&sa,&f,secret,sizeof(secret)-1,&sealed,&sn)==0);assert(qrx_aura_secure_payload_is_envelope(sealed,sn));assert(!contains_bytes(sealed,sn,secret,sizeof(secret)-1));assert(qrx_aura_secure_payload_open(&sb,&f,sealed,sn,&plain,&pn)==0&&pn==sizeof(secret)-1&&!memcmp(plain,secret,pn));sealed[sn-1]^=1;uint8_t*bad=NULL;size_t badn=0;assert(qrx_aura_secure_payload_open(&sb,&f,sealed,sn,&bad,&badn)!=0);free(bad);free(plain);free(sealed);EVP_PKEY_free(a);EVP_PKEY_free(b);
}

static void test_durable_lease_journal(void){
    char dir[]="/tmp/qrx164-lease-XXXXXX";assert(mkdtemp(dir));char path[512];snprintf(path,sizeof(path),"%s/leases.journal",dir);const char*provider="provider-journal",*pod="pod-journal";QrxResourceProviderRuntime rt=make_runtime(provider);QrxAuraRuntimeBinding b=make_binding(provider,pod,&rt);QrxAuraReservationLeaseTable t;qrx_aura_reservation_leases_init(&t);char lease[65];hexfill(lease,'d');QrxAuraRemoteFrame f=lease_frame(provider,pod,"requester-journal",lease,10,H+16);QrxAuraReservationLease l;assert(qrx_aura_reservation_lease_open(&t,&b,&f,H,&l)==0);assert(qrx_aura_reservation_leases_journal_save(path,&t)==0);
    QrxResourceProviderRuntime rt2=make_runtime(provider);QrxAuraRuntimeBinding b2=make_binding(provider,pod,&rt2);QrxAuraReservationLeaseTable t2;size_t rec=0,exp=0;assert(qrx_aura_reservation_leases_journal_recover(path,&t2,&b2,1,H+1,&rec,&exp)==0&&rec==1&&exp==0);assert(rt2.active_jobs==1&&rt2.reserved_compute_threads==2&&rt2.reserved_network_egress_mbps==100);QrxAuraRemoteFrame rel=f;rel.kind=QRX_AURA_REMOTE_KIND_LEASE_RELEASE;rel.sequence=11;assert(qrx_aura_reservation_lease_release(&t2,&b2,&rel)==0);assert(qrx_aura_reservation_leases_journal_save(path,&t2)==0);assert(rt2.active_jobs==0);
    QrxResourceProviderRuntime rt3=make_runtime(provider);QrxAuraRuntimeBinding b3=make_binding(provider,pod,&rt3);QrxAuraReservationLeaseTable t3;assert(qrx_aura_reservation_leases_journal_recover(path,&t3,&b3,1,H+20,&rec,&exp)==0&&rec==0);assert(rt3.active_jobs==0);FILE*x=fopen(path,"r+b");assert(x);assert(fseek(x,-1,SEEK_END)==0);int ch=fgetc(x);assert(ch!=EOF);assert(fseek(x,-1,SEEK_END)==0);fputc(ch^1,x);fclose(x);QrxAuraReservationLeaseTable bad;assert(qrx_aura_reservation_leases_journal_load(path,&bad)!=0);remove(path);rmdir(dir);
}

static void build_model(QrxAuraExpertManifest*em,QrxAiModelRecord*m,QrxAiModelRegistry*reg,char model_commit[65]){
    memset(em,0,sizeof(*em));em->version=QRX_AURA_EXPERT_MANIFEST_VERSION;snprintf(em->model_id,sizeof(em->model_id),"qrx/deepseek-moe-reasoning");snprintf(em->model_version,sizeof(em->model_version),"profile-39");snprintf(em->architecture,sizeof(em->architecture),"deepseek-moe-compatible");em->layer_count=24;em->expert_count=8;em->experts_per_token=2;char er[65];assert(qrx_aura_expert_manifest_root(em,er)==0);assert(!strcmp(er,"d95cbef3e610fe781942580b477f00c6718806557090975548d33d103ef749ae"));memset(m,0,sizeof(*m));m->registry_version=QRX_MODEL_REGISTRY_VERSION;snprintf(m->model_id,sizeof(m->model_id),"%s",em->model_id);snprintf(m->model_version,sizeof(m->model_version),"%s",em->model_version);snprintf(m->architecture,sizeof(m->architecture),"%s",em->architecture);snprintf(m->runtime_id,sizeof(m->runtime_id),"qrx-llm-runtime-v1");hexfill(m->manifest_root,'2');hexfill(m->tokenizer_root,'3');snprintf(m->expert_manifest_root,65,"%s",er);m->min_memory_bytes=4*GIB;m->min_storage_bytes=2*MIB;m->verification_profile=QRX_MODEL_VERIFY_HIGH;snprintf(m->license_id,sizeof(m->license_id),"registry-license");m->is_moe=1;assert(qrx_ai_model_validate(m)==0);memset(reg,0,sizeof(*reg));assert(qrx_ai_model_registry_add(reg,m)==0);assert(qrx_ai_model_commitment(m,model_commit)==0);
}

static void test_autonomous_secure_moe_service(void){
    uint64_t height=H;const char*requester="requester-live";EVP_PKEY*reqk=new_key("Ed25519"),*p1k=new_key("Ed25519"),*p2k=new_key("Ed25519");KeyRing requesters={0},providers={0};ring_add(&requesters,requester,reqk);ring_add(&providers,"provider-1",p1k);ring_add(&providers,"provider-2",p2k);
    unsigned char sec1[32],sec2[32];for(int i=0;i<32;i++){sec1[i]=(unsigned char)(i+1);sec2[i]=(unsigned char)(0xa0+i);}QrxAuraSecureSession s1,s2;assert(qrx_aura_secure_session_from_secret(sec1,sizeof(sec1),requester,"provider-1",&s1)==0);assert(qrx_aura_secure_session_from_secret(sec2,sizeof(sec2),requester,"provider-2",&s2)==0);SessionMap sm={0};session_add(&sm,"provider-1",requester,&s1);session_add(&sm,"provider-2",requester,&s2);
    QrxAuraExpertManifest em;QrxAiModelRecord model;QrxAiModelRegistry registry;char mc[65];build_model(&em,&model,&registry,mc);
    QrxResourceProviderRuntime rt1=make_runtime("provider-1"),rt2=make_runtime("provider-2");QrxAuraRuntimeBinding b1=make_binding("provider-1","pod-1",&rt1),b2=make_binding("provider-2","pod-2",&rt2);QrxAuraModelCacheCatalog c1,c2;qrx_aura_model_cache_catalog_init(&c1);qrx_aura_model_cache_catalog_init(&c2);FetchLog fl1={0},fl2={0};AdvertiseLog al1={0},al2={0};char d1[]="/tmp/qrx164-s1-XXXXXX",d2[]="/tmp/qrx164-s2-XXXXXX";assert(mkdtemp(d1)&&mkdtemp(d2));
    QrxAuraProviderServiceConfig cfg1;memset(&cfg1,0,sizeof(cfg1));cfg1.version=QRX_AURA_PROVIDER_SERVICE_VERSION;cfg1.binding=&b1;cfg1.model_cache=&c1;cfg1.model_registry=&registry;cfg1.requester_key_lookup=key_lookup;cfg1.requester_key_ctx=&requesters;cfg1.provider_private_key=p1k;cfg1.height_fn=fixed_height;cfg1.height_ctx=&height;cfg1.secure_session_lookup=session_lookup;cfg1.secure_session_ctx=&sm;cfg1.model_fetch=fake_fetch;cfg1.model_fetch_ctx=&fl1;snprintf(cfg1.listen_host,sizeof(cfg1.listen_host),"127.0.0.1");snprintf(cfg1.lease_journal_path,sizeof(cfg1.lease_journal_path),"%s/leases.journal",d1);cfg1.require_secure_dispatch=1;cfg1.auto_advertise=1;cfg1.advertised_capacity=capacity("provider-1","pod-1");cfg1.advertisement_ttl_blocks=30;cfg1.advertise=advertise_cb;cfg1.advertise_ctx=&al1;
    QrxAuraProviderServiceConfig cfg2=cfg1;cfg2.binding=&b2;cfg2.model_cache=&c2;cfg2.provider_private_key=p2k;cfg2.model_fetch_ctx=&fl2;snprintf(cfg2.lease_journal_path,sizeof(cfg2.lease_journal_path),"%s/leases.journal",d2);cfg2.advertised_capacity=capacity("provider-2","pod-2");cfg2.advertise_ctx=&al2;
    QrxAuraProviderService *sv1=NULL,*sv2=NULL;assert(qrx_aura_provider_service_start(&cfg1,&sv1)==0);assert(qrx_aura_provider_service_start(&cfg2,&sv2)==0);assert(qrx_aura_provider_service_port(sv1)>0&&qrx_aura_provider_service_port(sv2)>0);assert(al1.count>=1&&al2.count>=1);assert(!strcmp(al1.a[0].service_endpoint,qrx_aura_provider_service_endpoint(sv1)));assert(qrx_aura_pod_announcement_verify(p1k,&al1.a[0],al1.sig[0],al1.sig_len[0])==0);
    QrxAuraAdmission a;memset(&a,0,sizeof(a));a.version=QRX_AURA_LIVE_DISPATCH_VERSION;snprintf(a.route.model_id,sizeof(a.route.model_id),"%s",model.model_id);snprintf(a.route.model_version,sizeof(a.route.model_version),"%s",model.model_version);snprintf(a.route.runtime_id,sizeof(a.route.runtime_id),"%s",model.runtime_id);a.route.tier=QRX_AURA_TIER_CLUSTER;a.route.version=QRX_AURA_FABRIC_VERSION;a.route.mode=QRX_AURA_ROUTE_AUTO;a.route.task_class=QRX_AURA_TASK_REASONING;hexfill(a.route.decision_commitment,'4');snprintf(a.model_commitment,65,"%s",mc);hexfill(a.graph_commitment,'5');a.node_id=9;a.admitted_height=H;a.expires_height=H+50;a.pod_count=2;a.active=1;snprintf(a.pods[0].provider_id,sizeof(a.pods[0].provider_id),"provider-1");snprintf(a.pods[0].pod_id,sizeof(a.pods[0].pod_id),"pod-1");a.pods[0].compute_threads=1;a.pods[0].network_egress_mbps=50;snprintf(a.pods[1].provider_id,sizeof(a.pods[1].provider_id),"provider-2");snprintf(a.pods[1].pod_id,sizeof(a.pods[1].pod_id),"pod-2");a.pods[1].compute_threads=1;a.pods[1].network_egress_mbps=50;assert(qrx_aura_admission_commitment(&a,a.admission_commitment)==0);
    QrxAuraMoeFragmentPlan fp;assert(qrx_aura_moe_fragment_plan_build(&model,&em,&a,&fp)==0);assert(fp.strategy==QRX_AURA_FRAGMENT_EXPERT_RANGE&&fp.fragment_count==2&&fp.fragments[0].expert_first==0&&fp.fragments[0].expert_count==4&&fp.fragments[1].expert_first==4&&fp.fragments[1].expert_count==4);char pc[65];assert(qrx_aura_moe_fragment_plan_commitment(&fp,pc)==0&&!strcmp(pc,fp.plan_commitment));assert(!strcmp(pc,"8f595f57d7f5a0984a8ac713a8f7e194fb6135dbe3e50024f807df3d203a7a52"));
    QrxComputeJobNode node;memset(&node,0,sizeof(node));node.node_id=9;node.job_type=QRX_JOB_AI_INFERENCE;snprintf(node.runtime_id,sizeof(node.runtime_id),"%s",model.runtime_id);snprintf(node.model_id,sizeof(node.model_id),"%s",model.model_id);snprintf(node.model_version,sizeof(node.model_version),"%s",model.model_version);snprintf(node.input_ref,sizeof(node.input_ref),"drive:prompt");snprintf(node.output_ref,sizeof(node.output_ref),"drive:answer");node.min_memory_bytes=MIB;node.max_runtime_ms=60000;node.max_output_bytes=4096;node.max_fee_atoms=100000;node.capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_STREAM_OUTPUT|QRX_JOB_CAP_MODEL_INFERENCE;
    QrxAuraRemoteClientContext client;memset(&client,0,sizeof(client));snprintf(client.requester_id,sizeof(client.requester_id),"%s",requester);client.requester_private_key=reqk;client.provider_key_lookup=key_lookup;client.provider_key_ctx=&providers;client.current_height=height;client.lease_blocks=16;client.fragment_input=qrx_aura_moe_fragment_input_adapter;client.fragment_input_ctx=&fp;client.aggregate=aggregate;assert(qrx_aura_remote_client_add_peer(&client,"provider-1","pod-1",qrx_aura_provider_service_endpoint(sv1))==0);assert(qrx_aura_remote_client_add_peer(&client,"provider-2","pod-2",qrx_aura_provider_service_endpoint(sv2))==0);assert(qrx_aura_remote_client_set_peer_secure_session(&client,"provider-1","pod-1",&s1)==0);assert(qrx_aura_remote_client_set_peer_secure_session(&client,"provider-2","pod-2",&s2)==0);
    const char prompt[]="reason-about-this";char out[1024];size_t outn=0;assert(qrx_aura_remote_distributed_dispatch(&client,&a,&node,prompt,sizeof(prompt)-1,out,sizeof(out),&outn)==0);out[outn]=0;assert(strstr(out,"F0:E0+4:reason-about-this")&&strstr(out,"F1:E4+4:reason-about-this"));assert(fl1.calls==1&&fl2.calls==1);assert(c1.count==1&&c2.count==1);assert(rt1.active_jobs==0&&rt2.active_jobs==0&&qrx_aura_provider_service_active_leases(sv1)==0&&qrx_aura_provider_service_active_leases(sv2)==0);
    assert(qrx_aura_provider_service_stop(sv1)==0&&qrx_aura_provider_service_stop(sv2)==0);qrx_aura_provider_service_free(sv1);qrx_aura_provider_service_free(sv2);
    for(size_t i=0;i<al1.count;i++)free(al1.sig[i]);for(size_t i=0;i<al2.count;i++)free(al2.sig[i]);char jp[512];snprintf(jp,sizeof(jp),"%s/leases.journal",d1);remove(jp);snprintf(jp,sizeof(jp),"%s/leases.journal",d2);remove(jp);rmdir(d1);rmdir(d2);EVP_PKEY_free(reqk);EVP_PKEY_free(p1k);EVP_PKEY_free(p2k);
}

int main(void){test_secure_channel();test_durable_lease_journal();test_autonomous_secure_moe_service();return 0;}
