#include "compute/qrx_pouc_pipeline.h"
#include "compute/qrx_pouc_consensus.h"
#include "compute/qrx_pouc_verifier.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

static void hx(char x[65],char c){for(int i=0;i<64;i++)x[i]=c;x[64]=0;}
static void putu(QrxDB*d,const char*k,uint64_t v){char b[64];snprintf(b,sizeof(b),"%llu",(unsigned long long)v);assert(!qrxdb_put(d,k,b));}
static uint64_t getu(QrxDB*d,const char*k){char b[128];assert(!qrxdb_get(d,k,b,sizeof(b)));return strtoull(b,NULL,10);}
static void bond(QrxDB*d,const char*a,uint64_t p){char k[512];snprintf(k,sizeof(k),"staking:self:%s",a);putu(d,k,p);}
static void entropy(QrxDB*d,uint64_t h,char c){char bh[65];hx(bh,c);assert(!qrxdb_chain_put_block(d,h,bh,"finalized verifier entropy"));}
static void commit_effect(QrxDB*d,const QrxPoucPipelineEffect*e,const char*tx,uint64_t h){QrxDBBatch b;assert(!qrxdb_batch_begin(d,&b));assert(!qrx_pouc_pipeline_stage(d,&b,e,tx,h));assert(!qrxdb_batch_commit(&b));}
static void lock_job(QrxDB*d,const char*owner,const char*gc,uint64_t verify_reward,uint64_t h){char p[768];snprintf(p,sizeof(p),"graph_commitment=%s;max_compute_atoms=400000000;fasttrack_fee_atoms=0;verification_reward_atoms=%llu;expiry_height=5000",gc,(unsigned long long)verify_reward);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_ESCROW_LOCK",owner,owner,0,p,h,&e));assert(e.debit_atoms==400000000+verify_reward);commit_effect(d,&e,"tx-lock",h);}
static void assign_job(QrxDB*d,const char*owner,const char*provider,const char*gc,uint32_t mode,uint64_t h){char mc[65];hx(mc,'b');char p[1024];snprintf(p,sizeof(p),"graph_commitment=%s;node_id=7;quote_id=q156;quote_price_atoms=400000000;quote_expiry_height=4000;verification_mode=%u;assignment_nonce=%llu;runtime_id=qrx-ai-v1;model_commitment=%s",gc,mode,(unsigned long long)h,mc);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_ASSIGN",owner,provider,0,p,h,&e));commit_effect(d,&e,"tx-assign",h);}
static void receipt_payload(char*out,size_t n,const char*gc,const char*provider,uint32_t mode,uint64_t started,uint64_t completed){char a[65],b[65],c[65],d[65];hx(a,'a');hx(b,'b');hx(c,'c');hx(d,'d');snprintf(out,n,"graph_commitment=%s;node_id=7;provider_id=%s;runtime_id=qrx-ai-v1;input_commitment=%s;model_commitment=%s;execution_params_commitment=%s;result_commitment=%s;verified_compute_atoms=270000000;started_height=%llu;completed_height=%llu;verification_mode=%u",gc,provider,a,b,c,d,(unsigned long long)started,(unsigned long long)completed,mode);}
static void submit_receipt(QrxDB*d,const char*owner,const char*provider,const char*gc,uint32_t mode,uint64_t h,char rc[65]){char p[1600];receipt_payload(p,sizeof(p),gc,provider,mode,h-2,h-1);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_RECEIPT",provider,owner,0,p,h,&e));snprintf(rc,65,"%s",e.receipt_commitment);commit_effect(d,&e,"tx-receipt",h);}
static int prepare_verify(QrxDB*d,const char*v,const char*provider,const char*rc,const char*observed,uint64_t h,QrxPoucPipelineEffect*out){char p[512];snprintf(p,sizeof(p),"receipt_commitment=%s;observed_result_commitment=%s",rc,observed);return qrx_pouc_pipeline_prepare(d,"COMPUTE_VERIFY",v,provider,0,p,h,out);}
static void verify_vote(QrxDB*d,const char*v,const char*provider,const char*rc,const char*observed,uint64_t h,const char*tx,QrxPoucPipelineEffect*out){QrxPoucPipelineEffect e;assert(!prepare_verify(d,v,provider,rc,observed,h,&e));commit_effect(d,&e,tx,h);if(out)*out=e;}
static void challenge_vote(QrxDB*d,const char*v,const char*provider,const char*rc,const char*observed,uint64_t h,const char*tx,QrxPoucPipelineEffect*out){char p[512];snprintf(p,sizeof(p),"receipt_commitment=%s;observed_result_commitment=%s",rc,observed);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_CHALLENGE",v,provider,0,p,h,&e));commit_effect(d,&e,tx,h);if(out)*out=e;}
static void settlement_payload(char*out,size_t n,const char*gc,const char*provider,uint32_t mode,uint32_t vc,uint32_t mc,uint64_t nonce,uint64_t started,uint64_t completed){char a[65],b[65],c[65],d[65];hx(a,'a');hx(b,'b');hx(c,'c');hx(d,'d');snprintf(out,n,"graph_commitment=%s;node_id=7;provider_id=%s;runtime_id=qrx-ai-v1;input_commitment=%s;model_commitment=%s;execution_params_commitment=%s;result_commitment=%s;verified_compute_atoms=270000000;started_height=%llu;completed_height=%llu;verification_mode=%u;verifier_count=%u;matching_verifiers=%u;settlement_nonce=%llu",gc,provider,a,b,c,d,(unsigned long long)started,(unsigned long long)completed,mode,vc,mc,(unsigned long long)nonce);}
static int in_set(const QrxPoucVerifierSelection*s,const char*a){return qrx_pouc_verifier_is_primary(s,a)||qrx_pouc_verifier_is_challenger(s,a);}

int main(void){
 char dir[]="/tmp/qrx-pouc-vsel-XXXXXX";assert(mkdtemp(dir));QrxDB db;assert(!qrxdb_init(&db,dir));
 const char*vals[]={"qrx-val01","qrx-val02","qrx-val03","qrx-val04","qrx-val05","qrx-val06","qrx-val07","qrx-val08","qrx-val09","qrx-val10"};for(uint32_t i=0;i<10;i++)bond(&db,vals[i],100000000ULL*(i+1));
 entropy(&db,99,'7');entropy(&db,299,'8');char result[65],bad1[65],bad2[65],gh[65];hx(result,'d');hx(bad1,'e');hx(bad2,'f');hx(gh,'9');

 /* RANDOM committee is deterministic, exact, owner/provider excluded, and has an explicit user-funded micro-reward budget. */
 char gc[65];hx(gc,'4');lock_job(&db,"qrx-owner",gc,70000000,90);assign_job(&db,"qrx-owner","qrx-provider",gc,QRX_POUC_VERIFY_RANDOM,91);char rc[65];submit_receipt(&db,"qrx-owner","qrx-provider",gc,QRX_POUC_VERIFY_RANDOM,100,rc);
 QrxPoucVerifierSelection s1,s2;assert(!qrx_pouc_verifier_selection_get(&db,rc,&s1));assert(!qrx_pouc_verifier_selection_build(&db,rc,"qrx-owner","qrx-provider",QRX_POUC_VERIFY_RANDOM,99,100,70000000,&s2));assert(!strcmp(s1.selection_commitment,s2.selection_commitment));assert(s1.primary_count==2&&s1.challenge_count==3&&s1.primary_reward_atoms==20000000&&s1.challenge_reward_atoms==10000000);for(uint32_t i=0;i<s1.primary_count;i++){assert(strcmp(s1.primary[i],"qrx-owner")&&strcmp(s1.primary[i],"qrx-provider"));for(uint32_t j=0;j<s1.challenge_count;j++)assert(strcmp(s1.primary[i],s1.challenger[j]));}
 /* A bonded but non-primary identity cannot self-select into primary verification. */
 const char*nonprimary=NULL;for(uint32_t i=0;i<10&&!nonprimary;i++)if(!qrx_pouc_verifier_is_primary(&s1,vals[i]))nonprimary=vals[i];assert(nonprimary);QrxPoucPipelineEffect ve;assert(prepare_verify(&db,nonprimary,"qrx-provider",rc,result,101,&ve)!=0);
 verify_vote(&db,s1.primary[0],"qrx-provider",rc,result,101,"tx-v1",&ve);assert(ve.reward_credit_atoms==20000000&&ve.reward_role==1);verify_vote(&db,s1.primary[1],"qrx-provider",rc,bad1,102,"tx-v2",&ve);assert(ve.verification.finalized&&ve.challenge_status==QRX_POUC_CHALLENGE_PENDING&&ve.reward_credit_atoms==20000000);
 QrxComputeEscrow esc;assert(!qrx_pouc_journal_get_escrow(&db,gc,&esc)&&esc.verification_reward_spent_atoms==40000000);assert(getu(&db,"consensus:compute:escrow_pool")==430000000);
 QrxPoucPipelineEffect ce;challenge_vote(&db,s1.challenger[0],"qrx-provider",rc,result,103,"tx-c1",&ce);assert(ce.reward_credit_atoms==10000000&&ce.reward_role==2);challenge_vote(&db,s1.challenger[1],"qrx-provider",rc,result,104,"tx-c2",&ce);assert(ce.challenge_status==QRX_POUC_CHALLENGE_PASSED);assert(!qrx_pouc_journal_get_escrow(&db,gc,&esc)&&esc.verification_reward_spent_atoms==60000000);assert(getu(&db,"consensus:compute:escrow_pool")==410000000);
 char sp[1800];settlement_payload(sp,sizeof(sp),gc,"qrx-provider",QRX_POUC_VERIFY_RANDOM,2,1,15601,98,99);QrxPoucConsensusEffect se;assert(!qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer","qrx-provider",0,sp,1,105,&se));assert(se.decision.outcome==QRX_POUC_SETTLEMENT_PAYOUT&&se.provider_credit_atoms==270000000&&se.owner_credit_atoms==140000000&&se.escrow_pool_debit_atoms==410000000);QrxDBBatch b;assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage(&db,&b,&se,"tx-settle-reward",105));assert(!qrxdb_batch_commit(&b));assert(getu(&db,"consensus:compute:escrow_pool")==0);

 /* Fraud path: settlement-stage evidence now mutates authoritative bonded stake and height-based jail state using canonical policy parameters. */
 const char*fraud="qrx-fraud-provider";bond(&db,fraud,500000000);putu(&db,"staking:delegation:alice:qrx-fraud-provider",300000000);putu(&db,"staking:delegation:bob:qrx-fraud-provider",200000000);putu(&db,"staking:delegated_total:qrx-fraud-provider",500000000);putu(&db,QRX_POUC_FRAUD_SLASH_BPS_KEY,1000);putu(&db,QRX_POUC_FRAUD_JAIL_BLOCKS_KEY,100);
 char gc2[65];hx(gc2,'5');lock_job(&db,"qrx-owner2",gc2,0,290);assign_job(&db,"qrx-owner2",fraud,gc2,QRX_POUC_VERIFY_REDUNDANT_2_OF_3,291);char rc2[65];submit_receipt(&db,"qrx-owner2",fraud,gc2,QRX_POUC_VERIFY_REDUNDANT_2_OF_3,300,rc2);QrxPoucVerifierSelection sf;assert(!qrx_pouc_verifier_selection_get(&db,rc2,&sf)&&sf.primary_count==3&&sf.challenge_count==0);verify_vote(&db,sf.primary[0],fraud,rc2,bad1,301,"tx-f1",NULL);verify_vote(&db,sf.primary[1],fraud,rc2,bad2,302,"tx-f2",NULL);verify_vote(&db,sf.primary[2],fraud,rc2,result,303,"tx-f3",&ve);assert(ve.has_adversarial_verdict&&ve.adversarial.detected);
 settlement_payload(sp,sizeof(sp),gc2,fraud,QRX_POUC_VERIFY_REDUNDANT_2_OF_3,3,1,15602,298,299);assert(!qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer",fraud,0,sp,1,304,&se));assert(se.decision.outcome==QRX_POUC_SETTLEMENT_REJECTED&&se.decision.slash_candidate&&se.decision.jail_candidate&&se.owner_credit_atoms==400000000);assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage(&db,&b,&se,"tx-fraud-settle",304));assert(!qrxdb_batch_commit(&b));assert(getu(&db,"staking:self:qrx-fraud-provider")==450000000);assert(getu(&db,"staking:delegated_total:qrx-fraud-provider")==450000000);assert(getu(&db,"staking:delegation:alice:qrx-fraud-provider")==270000000);assert(getu(&db,"staking:delegation:bob:qrx-fraud-provider")==180000000);assert(getu(&db,QRX_POUC_COMPUTE_SLASH_POOL_KEY)==100000000);assert(qrx_pouc_verifier_is_compute_jailed(&db,fraud,304));assert(qrx_pouc_verifier_is_compute_jailed(&db,fraud,404));assert(!qrx_pouc_verifier_is_compute_jailed(&db,fraud,405));
 /* Duplicate penalty application is consensus-rejected. */
 assert(!qrxdb_batch_begin(&db,&b));uint64_t sl=0,ju=0;assert(qrx_pouc_stage_consensus_penalty(&db,&b,fraud,se.decision.receipt_commitment,305,1,1,&sl,&ju)==-5);qrxdb_batch_abort(&b);

 assert(!qrxdb_close(&db));char cmd[1200];snprintf(cmd,sizeof(cmd),"rm -rf '%s'",dir);system(cmd);puts("compute phase 156 deterministic verifiers/rewards/slashing: PASS");return 0;
}
