#include "compute/qrx_aura_release.h"
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"CHECK failed %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)
typedef struct{const char*id;EVP_PKEY*key;} K;typedef struct{K k[4];size_t n;} Ks;
static int lookup(void*ctx,const char*id,EVP_PKEY**out){Ks*k=ctx;for(size_t i=0;i<k->n;i++)if(!strcmp(k->k[i].id,id)){if(EVP_PKEY_up_ref(k->k[i].key)!=1)return-1;*out=k->k[i].key;return 0;}return-1;}
static int pub_auth(void*ctx,const char*id){(void)ctx;return strcmp(id,"publisher:model");}
static int gov_auth(void*ctx,const char*id){(void)ctx;return strcmp(id,"governor:model");}
static void h64(char out[65],char c){for(int i=0;i<64;i++)out[i]=c;out[64]=0;}
static int make_catalog(QrxAuraModelCatalogAnnouncement*a){memset(a,0,sizeof(*a));a->version=1;snprintf(a->publisher_id,sizeof(a->publisher_id),"publisher:model");a->sequence=1;a->valid_from_height=100;a->valid_until_height=1000;QrxAuraModelManifest*m=&a->manifest;m->version=1;snprintf(m->model_id,sizeof(m->model_id),"qrx:model:release:test");snprintf(m->model_version,sizeof(m->model_version),"1");snprintf(m->family,sizeof(m->family),"release-family");snprintf(m->architecture,sizeof(m->architecture),"dense-transformer");snprintf(m->format,sizeof(m->format),"gguf");snprintf(m->quantization,sizeof(m->quantization),"q4_k_m");snprintf(m->license_id,sizeof(m->license_id),"apache-2.0");snprintf(m->origin_uri,sizeof(m->origin_uri),"qrxdrive://bootstrap/release-model");m->max_context_tokens=32768;m->asset_count=1;m->assets[0].index=0;m->assets[0].kind=QRX_AURA_ASSET_SHARED_WEIGHTS;m->assets[0].bytes=1024;m->assets[0].required_for_boot=1;h64(m->assets[0].content_root,'a');m->total_bytes=1024;if(qrx_aura_model_manifest_commitment(m,a->manifest_root))return-1;a->capability.version=1;snprintf(a->capability.model_id,sizeof(a->capability.model_id),"%s",m->model_id);snprintf(a->capability.model_version,sizeof(a->capability.model_version),"%s",m->model_version);snprintf(a->capability.family,sizeof(a->capability.family),"%s",m->family);snprintf(a->capability.runtime_id,sizeof(a->capability.runtime_id),"auto");snprintf(a->capability.quantization,sizeof(a->capability.quantization),"%s",m->quantization);a->capability.tier=QRX_AURA_TIER_LOCAL;a->capability.min_memory_bytes=1;a->capability.recommended_memory_bytes=1;a->capability.min_storage_bytes=1;a->capability.min_aggregate_milli_tokens_per_second=1;a->capability.min_pods=1;a->capability.min_network_mbps=1;a->capability.max_latency_ms=1000;a->capability.min_reliability_bps=1;a->capability.max_context_tokens=32768;a->capability.quality_bps=9000;a->capability.coding_bps=9000;a->capability.reasoning_bps=9000;a->capability.rag_bps=9000;a->capability.tool_use_bps=9000;a->capability.supports_single_device=1;a->popularity_bps=8000;a->priority_bps=9000;a->recommended=1;return 0;}
int main(void){
    EVP_PKEY*runtime=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519"),*pub=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519"),*gov=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519");CHECK(runtime&&pub&&gov);Ks keys={{{"runtime:official",runtime},{"publisher:model",pub},{"governor:model",gov}},3};
    QrxAuraProviderHostConfig host;memset(&host,0,sizeof(host));host.enabled=1;snprintf(host.provider_id,sizeof(host.provider_id),"provider-release");snprintf(host.pod_id,sizeof(host.pod_id),"pod-release");snprintf(host.network,sizeof(host.network),"alpha");snprintf(host.region,sizeof(host.region),"DE");snprintf(host.listen_host,sizeof(host.listen_host),"127.0.0.1");QrxAuraReleaseMigrationReport mr;CHECK(qrx_aura_release_migrate_host_config(&host,"phase173-state",&mr)==0);CHECK(mr.changed&&mr.security_hardened&&mr.runtime_auto_initialized&&mr.job_journal_derived&&mr.lease_journal_derived&&mr.cache_budget_defaulted);CHECK(host.model_cache_bytes==(50ull<<30));
    QrxAuraRuntimePackageCatalog rc;qrx_aura_runtime_package_catalog_init(&rc);QrxAuraRuntimePackageAnnouncement rp;memset(&rp,0,sizeof(rp));rp.version=1;snprintf(rp.publisher_id,sizeof(rp.publisher_id),"runtime:official");snprintf(rp.package_id,sizeof(rp.package_id),"qrx-aura-llama-cpu");snprintf(rp.package_version,sizeof(rp.package_version),"1");rp.sequence=1;rp.valid_from_height=100;rp.valid_until_height=1000;rp.adapter_kind=QRX_AURA_ADAPTER_LLAMA_CPP_CPU;rp.platform=QRX_AURA_PACKAGE_PLATFORM_ANY;rp.arch=QRX_AURA_PACKAGE_ARCH_ANY;rp.backend=QRX_MOE_BACKEND_CPU;rp.required_accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;h64(rp.content_root,'b');snprintf(rp.download_uri,sizeof(rp.download_uri),"qrxdrive://runtime/cpu");snprintf(rp.install_filename,sizeof(rp.install_filename),"qrx-aura-llama-cpu.plugin");uint8_t*sig=NULL;size_t sn=0;CHECK(qrx_aura_runtime_package_sign(runtime,&rp,&sig,&sn)==0);CHECK(qrx_aura_runtime_package_catalog_ingest(&rc,&rp,sig,sn,100,lookup,&keys)==0);free(sig);
    QrxAuraModelCatalog *mc=calloc(1,sizeof(*mc));CHECK(mc);qrx_aura_model_catalog_init(mc);QrxAuraModelCatalogAnnouncement ca;CHECK(make_catalog(&ca)==0);CHECK(qrx_aura_model_catalog_announcement_sign(pub,&ca,&sig,&sn)==0);
    QrxAuraModelLicensePolicy lp;qrx_aura_model_license_policy_init(&lp);CHECK(qrx_aura_model_license_policy_add(&lp,"apache-2.0",QRX_AURA_LICENSE_ALLOW)==0);QrxAuraModelGovernanceState gs;qrx_aura_model_governance_state_init(&gs);QrxAuraModelGovernanceDecision gd;memset(&gd,0,sizeof(gd));gd.version=1;snprintf(gd.governor_id,sizeof(gd.governor_id),"governor:model");gd.sequence=1;gd.effective_height=100;snprintf(gd.model_id,sizeof(gd.model_id),"%s",ca.manifest.model_id);snprintf(gd.model_version,sizeof(gd.model_version),"%s",ca.manifest.model_version);snprintf(gd.manifest_root,sizeof(gd.manifest_root),"%s",ca.manifest_root);gd.action=QRX_AURA_MODEL_GOV_APPROVE;snprintf(gd.reason,sizeof(gd.reason),"release approved");uint8_t*gsig=NULL;size_t gsn=0;CHECK(qrx_aura_model_governance_decision_sign(gov,&gd,&gsig,&gsn)==0);CHECK(qrx_aura_model_governance_ingest(&gs,&gd,gsig,gsn,100,lookup,&keys,gov_auth,NULL)==0);free(gsig);
    QrxAuraReleaseModelEvidence ev;memset(&ev,0,sizeof(ev));ev.provenance.version=1;snprintf(ev.provenance.model_id,sizeof(ev.provenance.model_id),"%s",ca.manifest.model_id);snprintf(ev.provenance.model_version,sizeof(ev.provenance.model_version),"%s",ca.manifest.model_version);snprintf(ev.provenance.manifest_root,sizeof(ev.provenance.manifest_root),"%s",ca.manifest_root);snprintf(ev.provenance.publisher_id,sizeof(ev.provenance.publisher_id),"%s",ca.publisher_id);snprintf(ev.provenance.license_id,sizeof(ev.provenance.license_id),"%s",ca.manifest.license_id);snprintf(ev.provenance.source_uri,sizeof(ev.provenance.source_uri),"https://upstream.invalid/release");h64(ev.provenance.source_commit,'c');ev.provenance.recorded_at_height=100;
    CHECK(qrx_aura_model_catalog_ingest_governed(mc,&ca,sig,sn,100,lookup,&keys,pub_auth,NULL,&gs,&lp,&ev.provenance)==0);free(sig);QrxAuraModelProviderIndex pi;qrx_aura_model_provider_index_init(&pi);
    QrxAuraReleaseReadiness rr;CHECK(qrx_aura_release_readiness_check(&host,&rc,mc,&gs,&lp,&ev,1,&pi,100,&rr)==0);CHECK(rr.ready&&rr.failures==0&&rr.host_secure&&rr.runtime_ready&&rr.model_governance_ready&&rr.distribution_ready&&strlen(rr.readiness_commitment)==64);
    gd.sequence=2;gd.action=QRX_AURA_MODEL_GOV_BLOCK;snprintf(gd.reason,sizeof(gd.reason),"emergency block");CHECK(qrx_aura_model_governance_decision_sign(gov,&gd,&gsig,&gsn)==0);CHECK(qrx_aura_model_governance_ingest(&gs,&gd,gsig,gsn,100,lookup,&keys,gov_auth,NULL)==0);free(gsig);CHECK(qrx_aura_release_readiness_check(&host,&rc,mc,&gs,&lp,&ev,1,&pi,100,&rr)==0);CHECK(!rr.ready&&rr.failures>0&&!rr.model_governance_ready);
    qrx_aura_model_provider_index_free(&pi);qrx_aura_model_governance_state_free(&gs);qrx_aura_model_catalog_free(mc);free(mc);qrx_aura_runtime_package_catalog_free(&rc);EVP_PKEY_free(runtime);EVP_PKEY_free(pub);EVP_PKEY_free(gov);printf("phase173 AURA mainnet release hardening/migration/readiness: PASS\n");return 0;
}
