#include "compute/qrx_pouc_consensus.h"
#include "compute/qrx_pouc_verifier.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static void hx(char x[65],char c){for(int i=0;i<64;i++)x[i]=c;x[64]=0;}
static QrxPoucMainnetReadiness ready(void){QrxPoucMainnetReadiness r={0};r.version=1;r.verification_stable=r.rewards_simulated=r.fasttrack_fair=r.standard_tasks_protected=r.fasttrack_dev_share_transparent=r.model_integrity_verified=r.provider_fraud_controlled=r.resource_globe_privacy_checked=r.server_independence_verified=1;return r;}
static QrxComputeJobGraph graph(const char *id,const char *owner,uint64_t nonce){QrxComputeJobGraph g;memset(&g,0,sizeof(g));g.protocol_version=QRX_COMPUTE_JOB_PROTOCOL_VERSION;snprintf(g.graph_id,sizeof(g.graph_id),"%s",id);snprintf(g.owner,sizeof(g.owner),"%s",owner);g.nonce=nonce;g.max_total_fee_atoms=400000000;g.expiry_height=5000;g.node_count=1;QrxComputeJobNode*n=&g.nodes[0];n->node_id=1;n->job_type=QRX_JOB_AI_INFERENCE;snprintf(n->runtime_id,sizeof(n->runtime_id),"qrx-ai-v1");snprintf(n->model_id,sizeof(n->model_id),"qrx/model");snprintf(n->model_version,sizeof(n->model_version),"1");snprintf(n->input_ref,sizeof(n->input_ref),"drive:prompt");snprintf(n->output_ref,sizeof(n->output_ref),"drive:answer");n->min_memory_bytes=1024;n->max_runtime_ms=60000;n->max_output_bytes=1024;n->max_fee_atoms=400000000;n->capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_MODEL_INFERENCE|QRX_JOB_CAP_STREAM_OUTPUT;return g;}
static QrxComputeEscrow escrow_for(QrxComputeJobGraph*g){QrxComputeEscrow e;assert(!qrx_compute_escrow_lock(&e,g,100000000,10));assert(!qrx_compute_escrow_mark_assigned(&e));return e;}
static void payload(char*out,size_t n,const QrxComputeEscrow*e,const char*provider,uint32_t mode,uint32_t vc,uint32_t mc,uint64_t nonce){char a[65],b[65],c[65],d[65];hx(a,'a');hx(b,'b');hx(c,'c');hx(d,'d');snprintf(out,n,"graph_commitment=%s;node_id=7;provider_id=%s;runtime_id=qrx-ai-v1;input_commitment=%s;model_commitment=%s;execution_params_commitment=%s;result_commitment=%s;verified_compute_atoms=270000000;started_height=100;completed_height=110;verification_mode=%u;verifier_count=%u;matching_verifiers=%u;settlement_nonce=%llu",e->graph_commitment,provider,a,b,c,d,mode,vc,mc,(unsigned long long)nonce);}
static long long getll(QrxDB*db,const char*k){char b[128];assert(!qrxdb_get(db,k,b,sizeof(b)));return atoll(b);}
static void putll(QrxDBBatch*b,const char*k,long long v){char x[64];snprintf(x,sizeof(x),"%lld",v);assert(!qrxdb_batch_put(b,k,x));}
static void receipt_from(const QrxComputeEscrow*e,const char*provider,uint32_t mode,QrxPoucReceipt*r){memset(r,0,sizeof(*r));r->version=1;r->node_id=7;snprintf(r->provider_id,sizeof(r->provider_id),"%s",provider);snprintf(r->runtime_id,sizeof(r->runtime_id),"qrx-ai-v1");snprintf(r->graph_commitment,65,"%s",e->graph_commitment);hx(r->input_commitment,'a');hx(r->model_commitment,'b');hx(r->execution_params_commitment,'c');hx(r->result_commitment,'d');r->verified_compute_atoms=270000000;r->started_height=100;r->completed_height=110;r->verification_mode=mode;}
int main(void){
 char dir[]="/tmp/qrx-pouc-block-XXXXXX";assert(mkdtemp(dir));QrxDB db;assert(!qrxdb_init(&db,dir));QrxPoucMainnetReadiness rr=ready();
 QrxComputeJobGraph g=graph("pay","qrx-owner",1);assert(!qrx_compute_job_graph_validate(&g));QrxComputeEscrow e=escrow_for(&g);QrxDBBatch b;assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage_readiness(&b,&rr));assert(!qrx_pouc_consensus_stage_escrow_lock(&db,&b,&e));assert(!qrxdb_batch_commit(&b));assert(getll(&db,"consensus:compute:escrow_pool")==500000000);
 char p[1600];payload(p,sizeof(p),&e,"qrx-provider",QRX_POUC_VERIFY_REDUNDANT_2_OF_3,3,2,77);QrxPoucConsensusEffect eff;char gh[65];hx(gh,'9');assert(!qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer","qrx-provider",0,p,1,120,&eff));assert(eff.decision.outcome==QRX_POUC_SETTLEMENT_PAYOUT);assert(eff.provider_credit_atoms==360000000);assert(eff.owner_credit_atoms==130000000);assert(eff.development_credit_atoms==500000);assert(eff.network_credit_atoms==9500000);assert(eff.escrow_pool_debit_atoms==500000000);
 /* One block/apply batch: wallet effects + journal/replay/escrow + network accounting. */
 assert(!qrxdb_batch_begin(&db,&b));putll(&b,"acct:balance:qrx-provider",360000000);putll(&b,"acct:balance:qrx-owner",130000000);putll(&b,"acct:balance:qrx-dev",500000);putll(&b,"consensus:fee_pool:pending",9500000);assert(!qrx_pouc_consensus_stage(&db,&b,&eff,"tx-phase154-pay",120));assert(!qrxdb_batch_commit(&b));assert(getll(&db,"consensus:compute:escrow_pool")==0);QrxPoucJournalEntry je;assert(!qrx_pouc_journal_get(&db,eff.decision.replay_key,&je)&&je.state==QRX_POUC_JOURNAL_PAYOUT);QrxComputeEscrow pe;assert(!qrx_pouc_journal_get_escrow(&db,e.graph_commitment,&pe)&&pe.state==QRX_COMPUTE_ESCROW_SETTLED);assert(getll(&db,"acct:balance:qrx-provider")==360000000&&getll(&db,"acct:balance:qrx-owner")==130000000&&getll(&db,"acct:balance:qrx-dev")==500000&&getll(&db,"consensus:fee_pool:pending")==9500000);
 /* Terminal escrow cannot be paid again. */ assert(qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer","qrx-provider",0,p,1,121,&eff)!=0);

 /* Fraud path: canonical adversarial verdict causes full refund and configured consensus slash/jail enforcement. */
 assert(!qrxdb_put(&db,QRX_POUC_FRAUD_SLASH_BPS_KEY,"1000"));assert(!qrxdb_put(&db,QRX_POUC_FRAUD_JAIL_BLOCKS_KEY,"100"));
 QrxComputeJobGraph g2=graph("fraud","qrx-owner2",2);QrxComputeEscrow e2=escrow_for(&g2);assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage_escrow_lock(&db,&b,&e2));QrxPoucReceipt r2;receipt_from(&e2,"qrx-bad-provider",QRX_POUC_VERIFY_REDUNDANT_2_OF_3,&r2);char rc2[65];assert(!qrx_pouc_receipt_commitment(&r2,rc2));QrxComputeAdversarialVerdict av={0};av.version=QRX_COMPUTE_ADVERSARIAL_VERSION;av.attack=QRX_ADV_RESULT_MISMATCH;av.severity=QRX_ADV_SEVERITY_CRITICAL;av.action_mask=QRX_ADV_ACTION_REJECT_RESULT|QRX_ADV_ACTION_FREEZE_PAYOUT|QRX_ADV_ACTION_SLASH_CANDIDATE;av.risk_bps=10000;av.challenge_bps=10000;av.detected=1;av.block_new_work=1;av.payout_allowed=0;hx(av.evidence_commitment,'f');assert(!qrx_pouc_consensus_stage_adversarial(&b,rc2,&av));assert(!qrxdb_batch_commit(&b));payload(p,sizeof(p),&e2,"qrx-bad-provider",QRX_POUC_VERIFY_REDUNDANT_2_OF_3,3,2,88);assert(!qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer","qrx-bad-provider",0,p,1,130,&eff));assert(eff.decision.outcome==QRX_POUC_SETTLEMENT_REJECTED&&eff.owner_credit_atoms==500000000&&eff.provider_credit_atoms==0&&eff.decision.slash_candidate&&eff.decision.jail_candidate);assert(!qrxdb_batch_begin(&db,&b));putll(&b,"acct:balance:qrx-owner2",500000000);assert(!qrx_pouc_consensus_stage(&db,&b,&eff,"tx-phase154-fraud",130));assert(!qrxdb_batch_commit(&b));assert(getll(&db,"consensus:compute:escrow_pool")==0);char sk[512],jk[512],x[1024];snprintf(sk,sizeof(sk),"consensus:compute:slash_candidate:%s:%s",eff.provider,eff.decision.replay_key);snprintf(jk,sizeof(jk),"consensus:compute:jail_candidate:%s:%s",eff.provider,eff.decision.replay_key);assert(!qrxdb_get(&db,sk,x,sizeof(x)));assert(!qrxdb_get(&db,jk,x,sizeof(x)));assert(!qrx_pouc_journal_get_escrow(&db,e2.graph_commitment,&pe)&&pe.state==QRX_COMPUTE_ESCROW_REFUNDED);

 /* Challenge path is read from canonical DB state, not trusted from tx payload. */
 QrxComputeJobGraph g3=graph("challenge","qrx-owner3",3);QrxComputeEscrow e3=escrow_for(&g3);assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage_escrow_lock(&db,&b,&e3));assert(!qrxdb_batch_commit(&b));payload(p,sizeof(p),&e3,"qrx-provider3",QRX_POUC_VERIFY_SPOT,1,1,99);assert(!qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer","qrx-provider3",0,p,1,140,&eff));assert(eff.decision.outcome==QRX_POUC_SETTLEMENT_FROZEN&&eff.escrow_pool_debit_atoms==0);char replay3[65],rc3[65];snprintf(replay3,65,"%s",eff.decision.replay_key);snprintf(rc3,65,"%s",eff.decision.receipt_commitment);assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage(&db,&b,&eff,"tx-phase154-freeze",140));assert(!qrxdb_batch_commit(&b));assert(getll(&db,"consensus:compute:escrow_pool")==500000000);assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage_challenge(&b,rc3,QRX_POUC_CHALLENGE_PASSED));assert(!qrxdb_batch_commit(&b));assert(!qrx_pouc_consensus_prepare(&db,"qrx-mainnet",gh,"9","POUC_SETTLEMENT","qrx-relayer","qrx-provider3",0,p,1,141,&eff));assert(eff.decision.outcome==QRX_POUC_SETTLEMENT_PAYOUT&&!strcmp(replay3,eff.decision.replay_key));assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_consensus_stage(&db,&b,&eff,"tx-phase154-challenge-pass",141));assert(!qrxdb_batch_commit(&b));assert(getll(&db,"consensus:compute:escrow_pool")==0);
 assert(!qrxdb_close(&db));char cmd[1200];snprintf(cmd,sizeof(cmd),"rm -rf '%s'",dir);system(cmd);puts("compute phase 154 PoUC settlement block pipeline: PASS");return 0;
}
