#include "compute/qrx_os_compute.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

static QrxComputeJobNode mk(uint32_t id,QrxComputeJobType t,const char*in,const char*out){QrxComputeJobNode n;memset(&n,0,sizeof(n));n.node_id=id;n.job_type=t;snprintf(n.runtime_id,sizeof(n.runtime_id),"qrx-sandbox-v1");snprintf(n.input_ref,sizeof(n.input_ref),"%s",in);snprintf(n.output_ref,sizeof(n.output_ref),"%s",out);n.min_memory_bytes=128ULL<<20;n.max_runtime_ms=60000;n.max_output_bytes=8ULL<<20;n.max_fee_atoms=1000;n.capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_WRITE_ARTIFACTS|QRX_JOB_CAP_SANDBOX_EXEC;return n;}
static QrxComputeJobGraph build_graph(void){QrxComputeJobGraph g;memset(&g,0,sizeof(g));g.protocol_version=QRX_COMPUTE_JOB_PROTOCOL_VERSION;snprintf(g.graph_id,sizeof(g.graph_id),"os-build-1");snprintf(g.owner,sizeof(g.owner),"qrx:user1");g.nonce=1;g.max_total_fee_atoms=3000;g.expiry_height=9000;g.node_count=2;g.nodes[0]=mk(1,QRX_JOB_COMPILE,"qrxdrive:src","qrxdrive:bin");g.nodes[1]=mk(2,QRX_JOB_TEST,"qrxdrive:bin","qrxdrive:report");g.edge_count=1;g.edges[0]=(QrxComputeJobEdge){1,2};return g;}
static QrxOsComputeWorkspace workspace(void){QrxOsComputeWorkspace w;memset(&w,0,sizeof(w));w.version=QRX_OS_COMPUTE_VERSION;w.app=QRX_OS_APP_BUILD_TASKS;snprintf(w.workspace_id,sizeof(w.workspace_id),"workspace-1");snprintf(w.wallet_identity,sizeof(w.wallet_identity),"qrx:user1");snprintf(w.drive_namespace_ref,sizeof(w.drive_namespace_ref),"qrxdrive:projects/workspace-1");snprintf(w.payment_escrow_ref,sizeof(w.payment_escrow_ref),"chain:escrow:1");snprintf(w.settlement_ref,sizeof(w.settlement_ref),"chain:settlement:1");w.service_mask=QRX_OS_SERVICE_ALL;w.max_total_fee_atoms=4000;w.expiry_height=10000;w.private_pq=1;return w;}
static QrxAuraArtifact artifact(void){QrxAuraArtifact a;memset(&a,0,sizeof(a));a.version=QRX_AURA_ARTIFACT_VERSION;snprintf(a.artifact_id,sizeof(a.artifact_id),"artifact-build-1");snprintf(a.owner,sizeof(a.owner),"qrx:user1");snprintf(a.name,sizeof(a.name),"build-report.txt");snprintf(a.mime_type,sizeof(a.mime_type),"text/plain");snprintf(a.extension,sizeof(a.extension),".txt");a.type=QRX_AURA_ARTIFACT_TEXT;snprintf(a.drive_ref,sizeof(a.drive_ref),"qrxdrive:projects/workspace-1/build-report");snprintf(a.source_job_ref,sizeof(a.source_job_ref),"job:os-build-1");memset(a.content_commitment,'a',64);a.content_commitment[64]=0;a.size_bytes=100;a.private_pq=1;a.immutable=1;return a;}
int main(void){
 QrxOsComputeWorkspace w=workspace();assert(qrx_os_compute_required_services(QRX_OS_APP_BUILD_TASKS)==QRX_OS_SERVICE_ALL);assert(qrx_os_compute_workspace_validate(&w)==0);char wc1[65],wc2[65];assert(qrx_os_compute_workspace_commitment(&w,wc1)==0);assert(qrx_os_compute_workspace_commitment(&w,wc2)==0&&!strcmp(wc1,wc2));
 QrxComputeJobGraph g=build_graph();assert(qrx_compute_job_graph_validate(&g)==0);QrxOsComputeRun r;assert(qrx_os_compute_bind_graph(&w,&g,&r)==0);assert(r.state==QRX_OS_RUN_READY);assert(qrx_os_compute_submit(&r,100)==0);assert(qrx_os_compute_mark_running(&r)==0);
 QrxAuraArtifact a=artifact();assert(qrx_aura_artifact_validate(&a)==0);assert(qrx_os_compute_complete(&w,&g,&r,&a,1500,110)==0);assert(r.state==QRX_OS_RUN_COMPLETED&&r.charged_fee_atoms==1500);char rc1[65],rc2[65];assert(qrx_os_compute_run_commitment(&r,rc1)==0);assert(qrx_os_compute_run_commitment(&r,rc2)==0&&!strcmp(rc1,rc2));
 QrxComputeJobGraph wrong=build_graph();snprintf(wrong.owner,sizeof(wrong.owner),"qrx:other");QrxOsComputeRun x;assert(qrx_os_compute_bind_graph(&w,&wrong,&x)!=0);
 QrxComputeJobGraph missing=build_graph();missing.node_count=1;missing.edge_count=0;assert(qrx_compute_job_graph_validate(&missing)==0);assert(qrx_os_compute_bind_graph(&w,&missing,&x)!=0);
 QrxOsComputeWorkspace no_drive=w;no_drive.service_mask&=~QRX_OS_SERVICE_DRIVE;assert(qrx_os_compute_workspace_validate(&no_drive)!=0);
 QrxOsComputeWorkspace chat=w;chat.app=QRX_OS_APP_CHAT;chat.service_mask=QRX_OS_SERVICE_WALLET|QRX_OS_SERVICE_COMPUTE|QRX_OS_SERVICE_CHAIN;chat.drive_namespace_ref[0]=0;assert(qrx_os_compute_workspace_validate(&chat)==0);QrxComputeJobGraph chatg=build_graph();chatg.node_count=1;chatg.edge_count=0;chatg.nodes[0].job_type=QRX_JOB_AI_INFERENCE;snprintf(chatg.nodes[0].model_id,sizeof(chatg.nodes[0].model_id),"qrx/chat");snprintf(chatg.nodes[0].model_version,sizeof(chatg.nodes[0].model_version),"1");chatg.nodes[0].capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_MODEL_INFERENCE|QRX_JOB_CAP_STREAM_OUTPUT;assert(qrx_compute_job_graph_validate(&chatg)==0);assert(qrx_os_compute_bind_graph(&chat,&chatg,&x)==0);
 puts("compute_phase148_qrx_os_compute: PASS");return 0;
}
