#include "compute/qrx_aura_model_origin.h"
#include "compute/qrx_aura_runtime_adapters.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

static void md(const char*p){char x[2048];snprintf(x,sizeof(x),"%s",p);for(char*q=x+1;*q;q++)if(*q=='/'){*q=0;mkdir(x,0700);*q='/';}mkdir(x,0700);}
static void put(const char*p,const char*s){char d[2048];snprintf(d,sizeof(d),"%s",p);char*q=strrchr(d,'/');if(q){*q=0;md(d);}FILE*f=fopen(p,"wb");assert(f);assert(fwrite(s,1,strlen(s),f)==strlen(s));assert(!fclose(f));}
static const QrxAuraOriginModelSpec*find_spec(const QrxAuraOriginModelSpec*s,size_t n,const char*id){for(size_t i=0;i<n;i++)if(!strcmp(s[i].model_id,id))return &s[i];return NULL;}
static QrxAuraPodCapacity pod(const char*id,uint64_t usable,uint64_t freeb,uint64_t mtps){QrxAuraPodCapacity p;memset(&p,0,sizeof(p));p.version=QRX_AURA_FABRIC_VERSION;snprintf(p.provider_id,sizeof(p.provider_id),"provider-%s",id);snprintf(p.pod_id,sizeof(p.pod_id),"pod-%s",id);snprintf(p.region,sizeof(p.region),"DE-NW");p.backend=QRX_MOE_BACKEND_CPU;p.accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;p.role_mask=QRX_AURA_POD_ROLE_INFERENCE|QRX_AURA_POD_ROLE_MODEL_CACHE;p.usable_memory_bytes=usable;p.free_memory_bytes=freeb;p.model_cache_free_bytes=freeb;p.measured_milli_tokens_per_second=mtps;p.network_egress_mbps=1000;p.latency_ms=18;p.utilization_bps=1000;p.reliability_bps=9900;p.cache_hit_bps=7000;p.expert_locality_bps=6500;p.max_context_tokens=32768;p.node_count=1;p.available=1;memset(p.calibration_commitment,'a',64);p.calibration_commitment[64]=0;assert(!qrx_aura_pod_capacity_validate(&p));return p;}

int main(int argc,char**argv){assert(argc==3);
    QrxAuraOriginModelSpec specs[32];size_t n=0;assert(!qrx_aura_origin_catalog_load(argv[1],specs,32,&n));assert(n>=9);
    const QrxAuraOriginModelSpec*q06=find_spec(specs,n,"qrx/qwen3-0.6b-q8");
    const QrxAuraOriginModelSpec*ds=find_spec(specs,n,"qrx/deepseek-r1-distill-qwen-1.5b-q4");
    const QrxAuraOriginModelSpec*q17=find_spec(specs,n,"qrx/qwen3-1.7b-q8");
    const QrxAuraOriginModelSpec*mi=find_spec(specs,n,"qrx/ministral3-3b-instruct-q4");
    const QrxAuraOriginModelSpec*q4=find_spec(specs,n,"qrx/qwen3-4b-q4");
    assert(q06&&ds&&q17&&mi&&q4);
    const QrxAuraOriginModelSpec*small[]={q06,ds,q17,mi,q4};for(size_t i=0;i<5;i++){assert(small[i]->version==2);assert(small[i]->auto_default);assert(!small[i]->gated_optional);assert(!strcmp(small[i]->runtime_id,"llama.cpp"));assert(strstr(small[i]->file_filter,".gguf"));assert(small[i]->tier<=QRX_AURA_TIER_EDGE);}

    QrxAuraPodCapacity tiny=pod("tiny",3ull<<30,1800ull<<20,500);QrxAuraOriginAutoSelection sel;assert(!qrx_aura_origin_auto_select(specs,n,&tiny,QRX_AURA_TASK_CHAT,1000,0,&sel));assert(!strcmp(sel.spec.model_id,"qrx/qwen3-0.6b-q8"));assert(sel.spec.tier==QRX_AURA_TIER_NANO);

    QrxAuraPodCapacity pi5=pod("pi5",8ull<<30,6ull<<30,3500);assert(!qrx_aura_origin_auto_select(specs,n,&pi5,QRX_AURA_TASK_REASONING,2500,0,&sel));assert(!strcmp(sel.spec.model_id,"qrx/deepseek-r1-distill-qwen-1.5b-q4"));assert(!qrx_aura_origin_auto_select(specs,n,&pi5,QRX_AURA_TASK_CODING,2500,0,&sel));assert(!strcmp(sel.spec.model_id,"qrx/qwen3-1.7b-q8"));assert(!qrx_aura_origin_auto_select(specs,n,&pi5,QRX_AURA_TASK_TOOL_USE,6000,0,&sel));assert(!strcmp(sel.spec.model_id,"qrx/ministral3-3b-instruct-q4"));assert(!qrx_aura_origin_auto_select(specs,n,&pi5,QRX_AURA_TASK_CODING,6000,0,&sel));assert(!strcmp(sel.spec.model_id,"qrx/qwen3-4b-q4"));

    QrxAuraOriginModelSpec optional[8];size_t on=0;assert(!qrx_aura_origin_catalog_load(argv[2],optional,8,&on));assert(on>=2);for(size_t i=0;i<on;i++){assert(optional[i].gated_optional);assert(!optional[i].auto_default);assert(!strcmp(optional[i].family,"llama"));}

    /* Apple native Metal must choose llama.cpp Metal for GGUF without pretending the model is MLX. */
    QrxMoeRuntimeDevice metal;memset(&metal,0,sizeof(metal));metal.version=QRX_MOE_RUNTIME_VERSION;metal.backend=QRX_MOE_BACKEND_OTHER;snprintf(metal.device_name,sizeof(metal.device_name),"Apple M1 Metal");metal.device_memory_bytes=8ull<<30;metal.accelerator_features=QRX_MOE_ACCEL_FEAT_FP16|QRX_MOE_ACCEL_FEAT_FP32|QRX_MOE_ACCEL_FEAT_UNIFIED_MEM|QRX_MOE_ACCEL_FEAT_METAL;metal.max_batch_items=64;assert(!qrx_moe_runtime_device_validate(&metal));QrxAuraRuntimeAdapterConfig ac;memset(&ac,0,sizeof(ac));ac.version=QRX_AURA_RUNTIME_ADAPTER_VERSION;ac.kind=QRX_AURA_ADAPTER_AUTO;char ap[QRX_AURA_RUNTIME_ADAPTER_PATH_MAX];QrxAuraRuntimeAdapterKind ak;int arc=qrx_aura_runtime_adapter_resolve(&ac,&metal,ap,&ak);/* No plugin needs to exist in this test; selection is still observable on -4. */assert(ak==QRX_AURA_ADAPTER_LLAMA_CPP_METAL);assert(arc==0||arc==-3);assert(qrx_aura_runtime_adapter_backend(QRX_AURA_ADAPTER_LLAMA_CPP_METAL)==QRX_MOE_BACKEND_OTHER);

    /* Real GGUF-origin fixture: multiple upstream quantizations, but QRX imports only the pinned AUTO quantization. */
    const char*t=getenv("QRX_TEST_HTTPS_ROOT");const char*api_url=getenv("QRX_TEST_HTTPS_API");const char*base_url=getenv("QRX_TEST_HTTPS_BASE");const char*ca_file=getenv("QRX_TEST_HTTPS_CA");assert(t&&api_url&&base_url&&ca_file);char api[1024],base[1024],work[1024],fsp[1024];snprintf(api,sizeof(api),"%s/api",t);snprintf(base,sizeof(base),"%s/hf",t);snprintf(work,sizeof(work),"%s/work",t);snprintf(fsp,sizeof(fsp),"%s/cas",t);md(api);md(base);md(work);const char*sha="abcdef0123456789abcdef0123456789abcdef01";char p[2048];snprintf(p,sizeof(p),"%s/models/vendor/TinyGGUF",api);put(p,"{\"sha\":\"abcdef0123456789abcdef0123456789abcdef01\",\"gated\":false,\"cardData\":{\"license\":\"apache-2.0\"},\"siblings\":[{\"rfilename\":\"LICENSE\"},{\"rfilename\":\"params\"},{\"rfilename\":\"tiny-Q4_K_M.gguf\"},{\"rfilename\":\"tiny-Q8_0.gguf\"}]}\n");char r[2048];snprintf(r,sizeof(r),"%s/vendor/TinyGGUF/resolve/%s",base,sha);snprintf(p,sizeof(p),"%s/LICENSE",r);put(p,"Apache 2.0 fixture\n");snprintf(p,sizeof(p),"%s/params",r);put(p,"fixture params\n");snprintf(p,sizeof(p),"%s/tiny-Q4_K_M.gguf",r);put(p,"GGUF-Q4-fixture-weight-bytes-abcdefghijklmnopqrstuvwxyz\n");snprintf(p,sizeof(p),"%s/tiny-Q8_0.gguf",r);put(p,"GGUF-Q8-should-not-be-imported\n");
    QrxAuraOriginConfig oc;assert(!qrx_aura_origin_config_defaults(&oc));snprintf(oc.hf_api_base_url,sizeof(oc.hf_api_base_url),"%s",api_url);snprintf(oc.hf_base_url,sizeof(oc.hf_base_url),"%s",base_url);snprintf(oc.tls_ca_bundle,sizeof(oc.tls_ca_bundle),"%s",ca_file);snprintf(oc.work_dir,sizeof(oc.work_dir),"%s",work);assert(!strncmp(oc.hf_api_base_url,"https://",8)&&!strncmp(oc.hf_base_url,"https://",8));QrxAuraOriginModelSpec gs={0};gs.version=2;snprintf(gs.model_id,sizeof(gs.model_id),"qrx/tiny-gguf");snprintf(gs.family,sizeof(gs.family),"qwen");snprintf(gs.repo_id,sizeof(gs.repo_id),"vendor/TinyGGUF");snprintf(gs.revision,sizeof(gs.revision),"main");snprintf(gs.expected_license,sizeof(gs.expected_license),"apache-2.0");snprintf(gs.architecture_hint,sizeof(gs.architecture_hint),"qwen3");snprintf(gs.runtime_id,sizeof(gs.runtime_id),"llama.cpp");snprintf(gs.quantization,sizeof(gs.quantization),"Q4_K_M");gs.tier=QRX_AURA_TIER_NANO;gs.recommended=1;gs.min_memory_bytes=1536ull<<20;gs.recommended_memory_bytes=3ull<<30;gs.min_milli_tokens_per_second=250;gs.quality_bps=6500;gs.coding_bps=5800;gs.reasoning_bps=5600;gs.rag_bps=6200;gs.tool_use_bps=5800;gs.auto_default=1;snprintf(gs.file_filter,sizeof(gs.file_filter),"tiny-Q4_K_M.gguf");QrxAuraOriginRepoMetadata rm;assert(!qrx_aura_hf_repo_resolve(&oc,&gs,&rm));assert(rm.file_count==3);for(uint32_t i=0;i<rm.file_count;i++)assert(strcmp(rm.files[i].path,"tiny-Q8_0.gguf"));QrxStorageFs*fs=NULL;assert(!qrx_storage_fs_open(fsp,1ull<<30,0,&fs));QrxAuraOriginSeedResult*out=calloc(1,sizeof(*out));assert(out);assert(!qrx_aura_hf_seed_to_qrx_drive(&oc,&gs,fs,NULL,NULL,out));assert(!strcmp(out->distribution_manifest.format,"gguf"));assert(!strcmp(out->distribution_manifest.quantization,"Q4_K_M"));assert(strstr(out->distribution_manifest.origin_uri,"#tiny-Q4_K_M.gguf"));assert(out->distribution_manifest.asset_count==3);int q4seen=0,q8seen=0;for(uint32_t i=0;i<out->source_map.file_count;i++){q4seen|=!strcmp(out->source_map.files[i].path,"tiny-Q4_K_M.gguf");q8seen|=!strcmp(out->source_map.files[i].path,"tiny-Q8_0.gguf");}assert(q4seen&&!q8seen);assert(strlen(out->registry_record.tokenizer_root)==64);free(out);qrx_storage_fs_close(fs);
    puts("PASS: zero-touch NANO/EDGE catalog selects useful models for 3-8 GiB hosts, keeps Llama gated/advanced, routes Apple GGUF to llama.cpp Metal, and deterministically imports one pinned GGUF quantization");return 0;
}
