#include "compute/qrx_pouc_mainnet.h"
#include <stdio.h>
#include <string.h>
static void h(char*x,char c){for(int i=0;i<64;i++)x[i]=c;x[64]=0;}
static QrxPoucMainnetReadiness ready(void){QrxPoucMainnetReadiness r={0};r.version=1;r.verification_stable=r.rewards_simulated=r.fasttrack_fair=r.standard_tasks_protected=r.fasttrack_dev_share_transparent=r.model_integrity_verified=r.provider_fraud_controlled=r.resource_globe_privacy_checked=r.server_independence_verified=1;return r;}
static void setup_receipt(QrxPoucReceipt*r,const char*gc){memset(r,0,sizeof(*r));r->version=1;r->node_id=7;snprintf(r->provider_id,sizeof(r->provider_id),"provider-mainnet");snprintf(r->runtime_id,sizeof(r->runtime_id),"qrx-ai-v1");snprintf(r->graph_commitment,sizeof(r->graph_commitment),"%s",gc);h(r->input_commitment,'b');h(r->model_commitment,'c');h(r->execution_params_commitment,'d');h(r->result_commitment,'e');r->verified_compute_atoms=270000000;r->started_height=100;r->completed_height=110;r->verification_mode=QRX_POUC_VERIFY_REDUNDANT_2_OF_3;}
int main(void){
 QrxComputeJobGraph g;memset(&g,0,sizeof(g));g.protocol_version=QRX_COMPUTE_JOB_PROTOCOL_VERSION;snprintf(g.graph_id,sizeof(g.graph_id),"mainnet-pouc-job");snprintf(g.owner,sizeof(g.owner),"qrx-owner");g.nonce=1;g.max_total_fee_atoms=400000000;g.expiry_height=5000;g.node_count=1;QrxComputeJobNode*n=&g.nodes[0];n->node_id=1;n->job_type=QRX_JOB_AI_INFERENCE;snprintf(n->runtime_id,sizeof(n->runtime_id),"qrx-ai-v1");snprintf(n->model_id,sizeof(n->model_id),"qrx/model");snprintf(n->model_version,sizeof(n->model_version),"1");snprintf(n->input_ref,sizeof(n->input_ref),"drive:prompt");snprintf(n->output_ref,sizeof(n->output_ref),"drive:answer");n->min_memory_bytes=1024;n->max_runtime_ms=60000;n->max_output_bytes=1024;n->max_fee_atoms=400000000;n->capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_MODEL_INFERENCE|QRX_JOB_CAP_STREAM_OUTPUT;
 QrxComputeEscrow e;if(qrx_compute_escrow_lock(&e,&g,0,10)||qrx_compute_escrow_mark_assigned(&e))return 1;
 QrxPoucSettlementRequest r;memset(&r,0,sizeof(r));r.version=1;r.chain.version=1;h(r.chain.chain_id,'1');h(r.chain.genesis_hash,'2');snprintf(r.chain.protocol_version,sizeof(r.chain.protocol_version),"9");r.readiness=ready();char gc[65];if(qrx_compute_job_graph_commitment(&g,gc))return 2;setup_receipt(&r.receipt,gc);if(qrx_pouc_verify_result(&r.receipt,3,2,&r.verification))return 2;r.settlement_nonce=1;r.current_height=120;
 QrxPoucSettlementDecision d;if(qrx_pouc_mainnet_decide(&r,&e,&d)||d.outcome!=QRX_POUC_SETTLEMENT_PAYOUT||d.payout_compute_atoms!=270000000||d.refund_atoms!=130000000)return 3;
 QrxPoucReplayGuard guard;if(qrx_pouc_replay_guard_init(&guard)||qrx_pouc_replay_guard_accept(&guard,&d)==-1||qrx_pouc_replay_guard_accept(&guard,&d)!=-2)return 4;
 if(qrx_pouc_mainnet_apply_payout(&d,&e,120)||e.state!=QRX_COMPUTE_ESCROW_SETTLED||e.actual_compute_atoms!=270000000)return 5;
 QrxComputeEscrow f;if(qrx_compute_escrow_lock(&f,&g,0,10)||qrx_compute_escrow_mark_assigned(&f))return 6;snprintf(f.graph_commitment,sizeof(f.graph_commitment),"%s",r.receipt.graph_commitment);r.receipt.verification_mode=QRX_POUC_VERIFY_SPOT;if(qrx_pouc_verify_result(&r.receipt,1,1,&r.verification))return 7;r.settlement_nonce=2;r.challenge_finalized=0;r.challenge_passed=0;if(qrx_pouc_mainnet_decide(&r,&f,&d)||d.outcome!=QRX_POUC_SETTLEMENT_FROZEN)return 8;
 r.challenge_finalized=1;r.challenge_passed=0;r.settlement_nonce=3;if(qrx_pouc_mainnet_decide(&r,&f,&d)||d.outcome!=QRX_POUC_SETTLEMENT_REJECTED)return 9;
 r.receipt.verification_mode=QRX_POUC_VERIFY_REDUNDANT_2_OF_3;if(qrx_pouc_verify_result(&r.receipt,3,2,&r.verification))return 10;r.challenge_finalized=0;r.has_adversarial_verdict=1;memset(&r.adversarial,0,sizeof(r.adversarial));r.adversarial.version=QRX_COMPUTE_ADVERSARIAL_VERSION;r.adversarial.detected=1;r.adversarial.action_mask=QRX_ADV_ACTION_REJECT_RESULT|QRX_ADV_ACTION_FREEZE_PAYOUT|QRX_ADV_ACTION_SLASH_CANDIDATE;r.settlement_nonce=4;if(qrx_pouc_mainnet_decide(&r,&f,&d)||d.outcome!=QRX_POUC_SETTLEMENT_REJECTED||!d.slash_candidate||!d.jail_candidate)return 11;
 r.has_adversarial_verdict=0;r.readiness.server_independence_verified=0;r.settlement_nonce=5;if(qrx_pouc_mainnet_decide(&r,&f,&d)!=-2)return 12;
 puts("compute phase 152 PoUC mainnet activation gate: PASS");return 0;
}
