#include "compute/qrx_aura_provider_bootstrap.h"
#include "compute/qrx_aura_moe_aggregate.h"
#include <assert.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifndef _WIN32
#include <unistd.h>
#endif

#define GIB (1024ULL*1024ULL*1024ULL)
#define MIB (1024ULL*1024ULL)
#define H 900ULL

typedef struct { const char *id[8]; EVP_PKEY *key[8]; size_t count; } KeyRing;
typedef struct { int calls; } FetchLog;
typedef struct { int calls; QrxAuraPodAnnouncement last; } AdvertLog;

static EVP_PKEY *new_ed25519(void){EVP_PKEY_CTX*c=EVP_PKEY_CTX_new_from_name(NULL,"Ed25519",NULL);EVP_PKEY*k=NULL;assert(c&&EVP_PKEY_keygen_init(c)==1&&EVP_PKEY_generate(c,&k)==1&&k);EVP_PKEY_CTX_free(c);return k;}
static void ring_add(KeyRing*r,const char*id,EVP_PKEY*k){assert(r&&id&&k&&r->count<8);r->id[r->count]=id;r->key[r->count]=k;r->count++;}
static int key_lookup(void*ctx,const char*id,EVP_PKEY**out){KeyRing*r=ctx;if(!r||!id||!out)return-1;for(size_t i=0;i<r->count;i++)if(!strcmp(r->id[i],id)){assert(EVP_PKEY_up_ref(r->key[i])==1);*out=r->key[i];return 0;}return-1;}
static uint64_t fixed_height(void*ctx){return *(uint64_t*)ctx;}
static int advertise_cb(void*ctx,const QrxAuraPodAnnouncement*a,const uint8_t*sig,size_t sn){AdvertLog*l=ctx;if(!l||!a||!sig||!sn)return-1;l->calls++;l->last=*a;return 0;}
static int fake_fetch(void*ctx,const QrxAiModelRecord*m,const QrxAuraModelCachePlacement*p,char out[65]){FetchLog*l=ctx;if(!l||!m||!p||!out||!p->bytes_to_place)return-1;l->calls++;return qrx_ai_model_commitment(m,out);}
static void hexfill(char out[65],char c){for(int i=0;i<64;i++)out[i]=c;out[64]=0;}

static QrxMoeCalibrationProfile calibration(const char*id){QrxMoeCalibrationProfile c;memset(&c,0,sizeof(c));c.version=QRX_MOE_CALIBRATION_VERSION;snprintf(c.profile_id,sizeof(c.profile_id),"%s",id);c.device.version=QRX_MOE_RUNTIME_VERSION;c.device.backend=QRX_MOE_BACKEND_CPU;snprintf(c.device.device_name,sizeof(c.device.device_name),"QRX phase165 CPU");c.device.accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;c.device.device_memory_bytes=8*GIB;c.device.max_batch_items=8;c.model_milli_tokens_per_second=5000;c.model_batch_items=1;c.sample_count=3;c.transport_latency_us=1000;c.transport_bandwidth_mbps=1000;assert(qrx_moe_calibration_profile_validate(&c)==0);return c;}

static void build_model(QrxStorageFs*fs,QrxAuraExpertManifest*em,QrxAiModelRecord*m,QrxAiModelRegistry*reg,char commit[65]){
    static const char plugin_manifest[]="qrx-phase165-runtime-model-manifest-v1";char manifest_root[65];assert(qrx_storage_fs_put(fs,plugin_manifest,sizeof(plugin_manifest)-1,manifest_root)==0);
    memset(em,0,sizeof(*em));em->version=QRX_AURA_EXPERT_MANIFEST_VERSION;snprintf(em->model_id,sizeof(em->model_id),"qrx/deepseek-reasoning-test");snprintf(em->model_version,sizeof(em->model_version),"phase165");snprintf(em->architecture,sizeof(em->architecture),"deepseek-moe-compatible");em->layer_count=24;em->expert_count=8;em->experts_per_token=2;char er[65];assert(qrx_aura_expert_manifest_root(em,er)==0);
    memset(m,0,sizeof(*m));m->registry_version=QRX_MODEL_REGISTRY_VERSION;snprintf(m->model_id,sizeof(m->model_id),"%s",em->model_id);snprintf(m->model_version,sizeof(m->model_version),"%s",em->model_version);snprintf(m->architecture,sizeof(m->architecture),"%s",em->architecture);snprintf(m->runtime_id,sizeof(m->runtime_id),"qrx-test-runtime-v1");snprintf(m->manifest_root,sizeof(m->manifest_root),"%s",manifest_root);hexfill(m->tokenizer_root,'3');snprintf(m->expert_manifest_root,sizeof(m->expert_manifest_root),"%s",er);m->min_memory_bytes=2*GIB;m->min_storage_bytes=2*MIB;m->verification_profile=QRX_MODEL_VERIFY_HIGH;snprintf(m->license_id,sizeof(m->license_id),"phase165-test-license");m->is_moe=1;assert(qrx_ai_model_validate(m)==0);memset(reg,0,sizeof(*reg));assert(qrx_ai_model_registry_add(reg,m)==0);assert(qrx_ai_model_commitment(m,commit)==0);
}

static void test_pq_hybrid(void){EVP_PKEY*k=NULL;assert(qrx_aura_pq_hybrid_kem_generate(&k)==0&&k&&EVP_PKEY_is_a(k,QRX_AURA_PQ_HYBRID_KEM_NAME)==1);uint8_t*ct=NULL;size_t ctn=0;QrxAuraSecureSession a,b;assert(qrx_aura_pq_hybrid_encapsulate(k,"requester","provider",&ct,&ctn,&a)==0&&ctn>1000);assert(qrx_aura_pq_hybrid_decapsulate(k,ct,ctn,"requester","provider",&b)==0);assert(!strcmp(a.session_id,b.session_id)&&CRYPTO_memcmp(a.key,b.key,sizeof(a.key))==0);ct[ctn/2]^=1;QrxAuraSecureSession tampered;int rc=qrx_aura_pq_hybrid_decapsulate(k,ct,ctn,"requester","provider",&tampered);assert(rc!=0||strcmp(a.session_id,tampered.session_id)||CRYPTO_memcmp(a.key,tampered.key,sizeof(a.key)));free(ct);EVP_PKEY_free(k);OPENSSL_cleanse(&a,sizeof(a));OPENSSL_cleanse(&b,sizeof(b));OPENSSL_cleanse(&tampered,sizeof(tampered));}

static void test_aggregate(void){int32_t v0[3]={100,200,300},v1[3]={10,20,30};QrxAuraMoeContribution c0={0},c1={0};c0.version=c1.version=QRX_AURA_MOE_AGG_VERSION;hexfill(c0.plan_commitment,'a');snprintf(c1.plan_commitment,sizeof(c1.plan_commitment),"%s",c0.plan_commitment);c0.fragment_index=0;c1.fragment_index=1;c0.fragment_count=c1.fragment_count=2;c0.token_index=c1.token_index=7;c0.vector_length=c1.vector_length=3;c0.q_fraction_bits=c1.q_fraction_bits=8;c0.values=v0;c1.values=v1;uint8_t *b0=NULL,*b1=NULL;size_t n0=0,n1=0;assert(qrx_aura_moe_contribution_encode(&c0,&b0,&n0)==0&&qrx_aura_moe_contribution_encode(&c1,&b1,&n1)==0);const uint8_t*parts[2]={b0,b1};size_t sizes[2]={n0,n1};QrxAuraMoeAggregateResult r;assert(qrx_aura_moe_fixedpoint_aggregate(parts,sizes,2,&r)==0);assert(r.values[0]==110&&r.values[1]==220&&r.values[2]==330);assert(!strcmp(r.result_commitment,"56ba51171fc9c0ec708135ade6da301f4c23226c45caccaa4ee592254aeb4f75"));char golden[65];snprintf(golden,sizeof(golden),"%s",r.result_commitment);QrxAuraMoeAggregateResult rr;const uint8_t*rev[2]={b1,b0};size_t rsz[2]={n1,n0};assert(qrx_aura_moe_fixedpoint_aggregate(rev,rsz,2,&rr)==0&&!strcmp(golden,rr.result_commitment));const uint8_t*dup[2]={b0,b0};assert(qrx_aura_moe_fixedpoint_aggregate(dup,sizes,2,&rr)!=0);qrx_aura_moe_aggregate_result_free(&r);qrx_aura_moe_aggregate_result_free(&rr);free(b0);free(b1);}

static void init_admission(const QrxAiModelRecord*m,const char*mc,QrxAuraAdmission*a){memset(a,0,sizeof(*a));a->version=QRX_AURA_LIVE_DISPATCH_VERSION;a->route.version=QRX_AURA_FABRIC_VERSION;a->route.mode=QRX_AURA_ROUTE_AUTO;a->route.task_class=QRX_AURA_TASK_REASONING;a->route.tier=QRX_AURA_TIER_CLUSTER;snprintf(a->route.model_id,sizeof(a->route.model_id),"%s",m->model_id);snprintf(a->route.model_version,sizeof(a->route.model_version),"%s",m->model_version);snprintf(a->route.runtime_id,sizeof(a->route.runtime_id),"%s",m->runtime_id);hexfill(a->route.decision_commitment,'4');snprintf(a->model_commitment,65,"%s",mc);hexfill(a->graph_commitment,'5');a->node_id=9;a->admitted_height=H;a->expires_height=H+60;a->pod_count=2;a->active=1;for(uint32_t i=0;i<2;i++){snprintf(a->pods[i].provider_id,sizeof(a->pods[i].provider_id),"provider-%u",i+1);snprintf(a->pods[i].pod_id,sizeof(a->pods[i].pod_id),"pod-%u",i+1);a->pods[i].compute_threads=1;a->pods[i].network_egress_mbps=50;}assert(qrx_aura_admission_commitment(a,a->admission_commitment)==0);}
static void init_node(const QrxAiModelRecord*m,QrxComputeJobNode*n){memset(n,0,sizeof(*n));n->node_id=9;n->job_type=QRX_JOB_AI_INFERENCE;snprintf(n->runtime_id,sizeof(n->runtime_id),"%s",m->runtime_id);snprintf(n->model_id,sizeof(n->model_id),"%s",m->model_id);snprintf(n->model_version,sizeof(n->model_version),"%s",m->model_version);snprintf(n->input_ref,sizeof(n->input_ref),"drive:prompt");snprintf(n->output_ref,sizeof(n->output_ref),"drive:answer");n->min_memory_bytes=MIB;n->max_runtime_ms=60000;n->max_output_bytes=4096;n->max_fee_atoms=100000;n->capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_STREAM_OUTPUT|QRX_JOB_CAP_MODEL_INFERENCE;assert(qrx_compute_job_node_validate(n)==0);}

static QrxAuraProviderBootstrapConfig bootstrap_cfg(const char*provider,const char*pod,const char*plugin,const char*journal,QrxStorageFs*fs,const QrxAiModelRegistry*reg,EVP_PKEY*key,KeyRing*requesters,uint64_t*height,FetchLog*fetch,AdvertLog*adv){QrxAuraProviderBootstrapConfig c;memset(&c,0,sizeof(c));c.version=QRX_AURA_PROVIDER_BOOTSTRAP_VERSION;c.user_enabled=1;snprintf(c.provider_id,sizeof(c.provider_id),"%s",provider);snprintf(c.pod_id,sizeof(c.pod_id),"%s",pod);snprintf(c.network,sizeof(c.network),"alphanet");snprintf(c.region,sizeof(c.region),"EU-WEST");c.calibration=calibration(pod);c.compute_threads=4;c.model_cache_bytes=4*GIB;c.free_memory_bytes=6*GIB;c.network_egress_mbps=1000;c.model_registry=reg;c.model_cache_fs=fs;c.runtime_plugin_path=plugin;c.model_fetch=fake_fetch;c.model_fetch_ctx=fetch;c.requester_key_lookup=key_lookup;c.requester_key_ctx=requesters;c.provider_private_key=key;c.height_fn=fixed_height;c.height_ctx=height;snprintf(c.listen_host,sizeof(c.listen_host),"127.0.0.1");c.listen_port=0;snprintf(c.lease_journal_path,sizeof(c.lease_journal_path),"%s",journal);c.require_secure_dispatch=1;c.enable_pq_hybrid_sessions=1;c.pq_session_ttl_blocks=32;c.advertise=advertise_cb;c.advertise_ctx=adv;return c;}

static void test_plugin_and_autobootstrap(const char*plugin_path){
    char d1[]="/tmp/qrx165-p1-XXXXXX",d2[]="/tmp/qrx165-p2-XXXXXX";assert(mkdtemp(d1)&&mkdtemp(d2));QrxStorageFs *fs1=NULL,*fs2=NULL;assert(qrx_storage_fs_open(d1,16*GIB,0,&fs1)==0&&qrx_storage_fs_open(d2,16*GIB,0,&fs2)==0);
    QrxAuraExpertManifest em;QrxAiModelRecord model;QrxAiModelRegistry reg;char mc[65];build_model(fs1,&em,&model,&reg,mc);static const char manifest[]="qrx-phase165-runtime-model-manifest-v1";char root2[65];assert(qrx_storage_fs_put(fs2,manifest,sizeof(manifest)-1,root2)==0&&!strcmp(root2,model.manifest_root));
    /* Real dlopen + model-handle cache before networking. */
    QrxMoeRuntimeDevice dev=calibration("plugin-direct").device;QrxAuraRuntimePluginHost host;assert(qrx_aura_runtime_plugin_open(plugin_path,&dev,fs1,&host)==0);assert(!strcmp(qrx_aura_runtime_plugin_name(&host),"QRX Phase165 Test Runtime"));QrxAuraRemoteFrame dummy={0};dummy.version=QRX_AURA_REMOTE_VERSION;uint8_t tiny[96]={0};memcpy(tiny,"QRXMF39\0",8);tiny[11]=1;tiny[15]=64;memset(tiny+16,'a',64);tiny[87]=0;tiny[91]=1;uint8_t direct[256];size_t direct_n=0;assert(qrx_aura_runtime_plugin_execute(&host,&model,&dummy,tiny,sizeof(tiny),direct,sizeof(direct),&direct_n)==0);assert(host.model_count==1);assert(qrx_aura_runtime_plugin_execute(&host,&model,&dummy,tiny,sizeof(tiny),direct,sizeof(direct),&direct_n)==0&&host.model_count==1);qrx_aura_runtime_plugin_close(&host);

    uint64_t height=H;EVP_PKEY *requester=new_ed25519(),*p1k=new_ed25519(),*p2k=new_ed25519();KeyRing requesters={0},providers={0};ring_add(&requesters,"requester",requester);ring_add(&providers,"provider-1",p1k);ring_add(&providers,"provider-2",p2k);FetchLog f1={0},f2={0};AdvertLog a1={0},a2={0};char j1[512],j2[512];snprintf(j1,sizeof(j1),"%s/leases.journal",d1);snprintf(j2,sizeof(j2),"%s/leases.journal",d2);
    QrxAuraProviderBootstrapConfig c1=bootstrap_cfg("provider-1","pod-1",plugin_path,j1,fs1,&reg,p1k,&requesters,&height,&f1,&a1),c2=bootstrap_cfg("provider-2","pod-2",plugin_path,j2,fs2,&reg,p2k,&requesters,&height,&f2,&a2);QrxAuraProviderBootstrap disabled;QrxAuraProviderBootstrapConfig off=c1;off.user_enabled=0;assert(qrx_aura_provider_bootstrap_start(&off,&disabled)!=0);
    QrxAuraProviderBootstrap b1,b2;assert(qrx_aura_provider_bootstrap_start(&c1,&b1)==0&&qrx_aura_provider_bootstrap_start(&c2,&b2)==0);assert(qrx_aura_provider_bootstrap_runtime(&b1)->status==QRX_PROVIDER_RUNTIME_SERVING);assert(qrx_aura_provider_bootstrap_capacity(&b1)&&qrx_aura_pod_capacity_validate(qrx_aura_provider_bootstrap_capacity(&b1))==0);assert(a1.calls>=1&&a2.calls>=1);assert(!strcmp(qrx_aura_provider_service_pq_kem_name(b1.service),QRX_AURA_PQ_HYBRID_KEM_NAME));

    QrxAuraAdmission admission;init_admission(&model,mc,&admission);QrxAuraMoeFragmentPlan fp;assert(qrx_aura_moe_fragment_plan_build(&model,&em,&admission,&fp)==0&&fp.fragment_count==2);QrxComputeJobNode node;init_node(&model,&node);
    QrxAuraRemoteClientContext client;memset(&client,0,sizeof(client));snprintf(client.requester_id,sizeof(client.requester_id),"requester");client.requester_private_key=requester;client.provider_key_lookup=key_lookup;client.provider_key_ctx=&providers;client.current_height=height;client.lease_blocks=20;client.require_secure_peers=1;client.fragment_input=qrx_aura_moe_fragment_input_adapter;client.fragment_input_ctx=&fp;client.aggregate=qrx_aura_moe_fixedpoint_aggregate_adapter;
    assert(qrx_aura_remote_client_add_peer(&client,"provider-1","pod-1",qrx_aura_provider_bootstrap_endpoint(&b1))==0);assert(qrx_aura_remote_client_add_peer(&client,"provider-2","pod-2",qrx_aura_provider_bootstrap_endpoint(&b2))==0);assert(qrx_aura_remote_client_enable_peer_pq_hybrid(&client,"provider-1","pod-1",1)==0);assert(qrx_aura_remote_client_enable_peer_pq_hybrid(&client,"provider-2","pod-2",1)==0);
    const char prompt[]="deep reasoning";uint8_t out[512];size_t outn=0;int drc=qrx_aura_remote_distributed_dispatch(&client,&admission,&node,prompt,sizeof(prompt)-1,out,sizeof(out),&outn);assert(drc==0);QrxAuraMoeAggregateResult ar;assert(qrx_aura_moe_aggregate_result_decode(out,outn,&ar)==0);assert(ar.fragment_count==2&&ar.values[0]==110&&ar.values[1]==220&&ar.values[2]==330);assert(!strcmp(ar.plan_commitment,fp.plan_commitment));qrx_aura_moe_aggregate_result_free(&ar);assert(qrx_aura_provider_service_pq_session_count(b1.service)==1&&qrx_aura_provider_service_pq_session_count(b2.service)==1);assert(f1.calls==1&&f2.calls==1);assert(b1.runtime.active_jobs==0&&b2.runtime.active_jobs==0);
    qrx_aura_remote_client_cleanup(&client);assert(qrx_aura_provider_bootstrap_stop(&b1)==0&&qrx_aura_provider_bootstrap_stop(&b2)==0);qrx_storage_fs_close(fs1);qrx_storage_fs_close(fs2);EVP_PKEY_free(requester);EVP_PKEY_free(p1k);EVP_PKEY_free(p2k);remove(j1);remove(j2);char cmd[1200];snprintf(cmd,sizeof(cmd),"rm -rf '%s' '%s'",d1,d2);system(cmd);
}

int main(int argc,char**argv){assert(argc==2);test_pq_hybrid();test_aggregate();test_plugin_and_autobootstrap(argv[1]);puts("compute phase 165 AURA auto-bootstrap/PQ-hybrid/runtime-plugin/MoE aggregate: PASS");return 0;}
