#include "compute/qrx_aura_model_distribution.h"
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"CHECK failed %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)

typedef struct{const char*id;EVP_PKEY*key;} Key;
typedef struct{Key k[8];size_t n;} Keys;
static int lookup(void*ctx,const char*id,EVP_PKEY**out){Keys*k=ctx;for(size_t i=0;i<k->n;i++)if(!strcmp(k->k[i].id,id)){if(EVP_PKEY_up_ref(k->k[i].key)!=1)return-1;*out=k->k[i].key;return 0;}return-1;}
static int authorize(void*ctx,const char*id){(void)ctx;return strcmp(id,"gov:model");}
static EVP_PKEY*keygen(void){return EVP_PKEY_Q_keygen(NULL,NULL,"ED25519");}
static void root(char out[65],char c){for(int i=0;i<64;i++)out[i]=c;out[64]=0;}
static void make_manifest(QrxAuraModelManifest*m){
    memset(m,0,sizeof(*m));m->version=1;snprintf(m->model_id,sizeof(m->model_id),"qrx:model:qwen-family:next-small:instruct");snprintf(m->model_version,sizeof(m->model_version),"2026.09");snprintf(m->family,sizeof(m->family),"qwen-family");snprintf(m->architecture,sizeof(m->architecture),"moe-transformer");snprintf(m->format,sizeof(m->format),"gguf");snprintf(m->quantization,sizeof(m->quantization),"q4_k_m");snprintf(m->license_id,sizeof(m->license_id),"upstream-license");snprintf(m->origin_uri,sizeof(m->origin_uri),"https://origin.invalid/model");m->max_context_tokens=131072;m->asset_count=6;
    for(uint32_t i=0;i<m->asset_count;i++){QrxAuraModelAsset*a=&m->assets[i];a->index=i;a->bytes=(uint64_t)(i+1)*1024*1024;char c=(char)('a'+i);root(a->content_root,c);}
    m->assets[0].kind=QRX_AURA_ASSET_CONFIG;m->assets[0].required_for_boot=1;
    m->assets[1].kind=QRX_AURA_ASSET_TOKENIZER;m->assets[1].required_for_boot=1;
    m->assets[2].kind=QRX_AURA_ASSET_SHARED_WEIGHTS;m->assets[2].required_for_boot=1;
    m->assets[3].kind=QRX_AURA_ASSET_EXPERT_PACK;m->assets[3].expert_first=0;m->assets[3].expert_count=8;
    m->assets[4].kind=QRX_AURA_ASSET_EXPERT_PACK;m->assets[4].expert_first=8;m->assets[4].expert_count=8;
    m->assets[5].kind=QRX_AURA_ASSET_EXPERT_PACK;m->assets[5].expert_first=16;m->assets[5].expert_count=8;
    for(uint32_t i=0;i<m->asset_count;i++)m->total_bytes+=m->assets[i].bytes;
}
static void make_profile(QrxAuraModelCapabilityProfile*p,const QrxAuraModelManifest*m){memset(p,0,sizeof(*p));p->version=1;snprintf(p->model_id,sizeof(p->model_id),"%s",m->model_id);snprintf(p->model_version,sizeof(p->model_version),"%s",m->model_version);snprintf(p->family,sizeof(p->family),"%s",m->family);snprintf(p->runtime_id,sizeof(p->runtime_id),"llama.cpp");snprintf(p->quantization,sizeof(p->quantization),"%s",m->quantization);p->tier=QRX_AURA_TIER_CLUSTER;p->min_memory_bytes=4ull<<30;p->recommended_memory_bytes=8ull<<30;p->min_storage_bytes=m->total_bytes;p->min_aggregate_milli_tokens_per_second=1000;p->min_pods=1;p->min_network_mbps=10;p->max_latency_ms=500;p->min_reliability_bps=7000;p->min_cache_hit_bps=0;p->min_expert_locality_bps=0;p->max_context_tokens=m->max_context_tokens;p->quality_bps=9000;p->coding_bps=9000;p->reasoning_bps=9000;p->rag_bps=8500;p->tool_use_bps=8500;p->is_moe=1;p->supports_single_device=1;}
static int add_provider(QrxAuraModelProviderIndex*idx,Keys*keys,const QrxAuraModelManifest*m,const char*mr,const char*pid,const char*pod,const char*region,uint32_t latency,uint32_t first,uint32_t last,EVP_PKEY*k){QrxAuraModelAvailabilityAnnouncement a;memset(&a,0,sizeof(a));a.version=1;snprintf(a.provider_id,sizeof(a.provider_id),"%s",pid);snprintf(a.pod_id,sizeof(a.pod_id),"%s",pod);snprintf(a.region,sizeof(a.region),"%s",region);snprintf(a.endpoint,sizeof(a.endpoint),"qrxp2p://127.0.0.1:%u",19000u+(unsigned)idx->count);snprintf(a.model_id,sizeof(a.model_id),"%s",m->model_id);snprintf(a.model_version,sizeof(a.model_version),"%s",m->model_version);snprintf(a.manifest_root,65,"%s",mr);a.sequence=1;a.valid_from_height=90;a.valid_until_height=200;a.bandwidth_mbps=500;a.latency_ms=latency;a.reliability_bps=9800;for(uint32_t x=first;x<=last&&x<m->asset_count;x++)qrx_aura_model_availability_set_asset(&a,x,1);uint8_t*sig=NULL;size_t sn=0;if(qrx_aura_model_availability_sign(k,&a,&sig,&sn))return-1;int rc=qrx_aura_model_provider_index_ingest(idx,&a,sig,sn,100,lookup,keys);free(sig);return rc;}
int main(void){
    EVP_PKEY*gov=keygen(),*p1=keygen(),*p2=keygen(),*p3=keygen();CHECK(gov&&p1&&p2&&p3);Keys keys={{{"gov:model",gov},{"provider-1",p1},{"provider-2",p2},{"provider-3",p3}},4};
    QrxAuraModelManifest m;make_manifest(&m);CHECK(qrx_aura_model_manifest_validate(&m)==0);char mr[65];CHECK(qrx_aura_model_manifest_commitment(&m,mr)==0&&strlen(mr)==64);
    QrxAuraModelCatalogAnnouncement ca;memset(&ca,0,sizeof(ca));ca.version=1;snprintf(ca.publisher_id,sizeof(ca.publisher_id),"gov:model");ca.sequence=1;ca.valid_from_height=90;ca.valid_until_height=1000;snprintf(ca.manifest_root,65,"%s",mr);ca.manifest=m;make_profile(&ca.capability,&m);ca.popularity_bps=9000;ca.priority_bps=8500;ca.recommended=1;uint8_t*csig=NULL;size_t csn=0;CHECK(qrx_aura_model_catalog_announcement_sign(gov,&ca,&csig,&csn)==0);
    QrxAuraModelCatalog *catalog=calloc(1,sizeof(*catalog));QrxAuraModelProviderIndex *idx=calloc(1,sizeof(*idx));CHECK(catalog&&idx);qrx_aura_model_catalog_init(catalog);CHECK(qrx_aura_model_catalog_ingest(catalog,&ca,csig,csn,100,lookup,&keys,authorize,NULL)==0);free(csig);CHECK(qrx_aura_model_catalog_find(catalog,m.model_id,m.model_version)!=NULL);QrxAuraModelCapabilityProfile profiles[4];CHECK(qrx_aura_model_catalog_profiles(catalog,100,profiles,4)==1&&profiles[0].is_moe==1);
    qrx_aura_model_provider_index_init(idx);CHECK(add_provider(idx,&keys,&m,mr,"provider-1","pod-1","DE",2,0,3,p1)==0);CHECK(add_provider(idx,&keys,&m,mr,"provider-2","pod-2","NL",14,0,4,p2)==0);CHECK(add_provider(idx,&keys,&m,mr,"provider-3","pod-3","US",90,0,2,p3)==0);
    QrxAuraModelAssetHealth h0,h5;CHECK(qrx_aura_model_asset_health(&m,idx,100,0,9000,&ca,&h0)==0);CHECK(h0.provider_replicas==3&&h0.region_replicas==3&&h0.target_replicas>=QRX_AURA_MODEL_MIN_GLOBAL_REPLICAS&&h0.deficit>0);CHECK(qrx_aura_model_asset_health(&m,idx,100,5,9000,&ca,&h5)==0);CHECK(h5.provider_replicas==0&&h0.target_replicas>h5.target_replicas);
    QrxAuraZeroConfigProfile z;CHECK(qrx_aura_model_zero_config_profile(100ull<<30,QRX_AURA_POWER_BALANCED,&z)==0);CHECK(z.disk_budget_bytes==(50ull<<30)&&z.automatic_models&&z.predictive_prefetch);
    QrxAuraPodCapacity pod;memset(&pod,0,sizeof(pod));pod.version=1;snprintf(pod.provider_id,sizeof(pod.provider_id),"local");snprintf(pod.pod_id,sizeof(pod.pod_id),"local-pod");snprintf(pod.region,sizeof(pod.region),"DE");pod.backend=QRX_MOE_BACKEND_CPU;pod.role_mask=QRX_AURA_POD_ROLE_MODEL_CACHE;pod.usable_memory_bytes=16ull<<30;pod.free_memory_bytes=8ull<<30;pod.model_cache_free_bytes=80ull<<30;pod.node_count=1;pod.available=1;uint8_t local[QRX_AURA_MODEL_AVAILABILITY_BITS]={0};qrx_aura_model_availability_set_asset((QrxAuraModelAvailabilityAnnouncement*)&(QrxAuraModelAvailabilityAnnouncement){0},0,0);local[0]|=1u<<0;QrxAuraModelPlacementPlan pp;CHECK(qrx_aura_model_placement_plan(&ca,idx,100,&pod,&z,local,&pp)==0);CHECK(pp.item_count>=4&&pp.total_bytes>0);int saw5=0;for(uint32_t x=0;x<pp.item_count;x++)if(pp.items[x].asset_index==5)saw5=1;CHECK(saw5);
    QrxAuraModelDownloadPlan dp;CHECK(qrx_aura_model_download_plan(&m,idx,100,1,"DE",5,1,&dp)==0);CHECK(dp.source_count>=5);CHECK(dp.sources[0].tier==QRX_AURA_SOURCE_LAN_PEER);int drive=0,origin=0;for(uint32_t x=0;x<dp.source_count;x++){if(dp.sources[x].tier==QRX_AURA_SOURCE_QRX_DRIVE)drive=1;if(dp.sources[x].tier==QRX_AURA_SOURCE_EXTERNAL_ORIGIN)origin=1;}CHECK(drive&&origin);
    CHECK(qrx_aura_model_provider_index_prune(idx,201)==3);qrx_aura_model_provider_index_free(idx);qrx_aura_model_catalog_free(catalog);free(idx);free(catalog);EVP_PKEY_free(gov);EVP_PKEY_free(p1);EVP_PKEY_free(p2);EVP_PKEY_free(p3);printf("phase167 AURA zero-config model fabric: PASS\n");return 0;
}
