#include "compute/qrx_aura_model_governance.h"
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"CHECK failed %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)
typedef struct{const char*id;EVP_PKEY*key;} K;typedef struct{K k[4];size_t n;} Ks;
static int lookup(void*ctx,const char*id,EVP_PKEY**out){Ks*k=ctx;for(size_t i=0;i<k->n;i++)if(!strcmp(k->k[i].id,id)){if(EVP_PKEY_up_ref(k->k[i].key)!=1)return-1;*out=k->k[i].key;return 0;}return-1;}
static int pub_auth(void*ctx,const char*id){(void)ctx;return strcmp(id,"publisher:model");}
static int gov_auth(void*ctx,const char*id){(void)ctx;return strcmp(id,"governor:model");}
static void h64(char out[65],char c){for(int i=0;i<64;i++)out[i]=c;out[64]=0;}
static void manifest(QrxAuraModelManifest*m,char asset_char,const char*license){memset(m,0,sizeof(*m));m->version=1;snprintf(m->model_id,sizeof(m->model_id),"qrx:model:family:test");snprintf(m->model_version,sizeof(m->model_version),"1.0");snprintf(m->family,sizeof(m->family),"test-family");snprintf(m->architecture,sizeof(m->architecture),"dense-transformer");snprintf(m->format,sizeof(m->format),"gguf");snprintf(m->quantization,sizeof(m->quantization),"q4_k_m");snprintf(m->license_id,sizeof(m->license_id),"%s",license);snprintf(m->origin_uri,sizeof(m->origin_uri),"https://origin.invalid/test");m->max_context_tokens=32768;m->asset_count=1;m->assets[0].index=0;m->assets[0].kind=QRX_AURA_ASSET_SHARED_WEIGHTS;m->assets[0].bytes=4096;m->assets[0].required_for_boot=1;h64(m->assets[0].content_root,asset_char);m->total_bytes=4096;}
static int announce(QrxAuraModelCatalogAnnouncement*a,const QrxAuraModelManifest*m,uint64_t seq){memset(a,0,sizeof(*a));a->version=1;snprintf(a->publisher_id,sizeof(a->publisher_id),"publisher:model");a->sequence=seq;a->valid_from_height=100;a->valid_until_height=1000;a->manifest=*m;CHECK(qrx_aura_model_manifest_commitment(m,a->manifest_root)==0);a->capability.version=1;snprintf(a->capability.model_id,sizeof(a->capability.model_id),"%s",m->model_id);snprintf(a->capability.model_version,sizeof(a->capability.model_version),"%s",m->model_version);snprintf(a->capability.family,sizeof(a->capability.family),"%s",m->family);snprintf(a->capability.runtime_id,sizeof(a->capability.runtime_id),"llama.cpp");snprintf(a->capability.quantization,sizeof(a->capability.quantization),"%s",m->quantization);a->capability.tier=QRX_AURA_TIER_LOCAL;a->capability.min_memory_bytes=1ull<<30;a->capability.recommended_memory_bytes=2ull<<30;a->capability.min_storage_bytes=m->total_bytes;a->capability.min_aggregate_milli_tokens_per_second=1;a->capability.min_pods=1;a->capability.min_network_mbps=1;a->capability.max_latency_ms=1000;a->capability.min_reliability_bps=1;a->capability.max_context_tokens=m->max_context_tokens;a->capability.quality_bps=8000;a->capability.coding_bps=8000;a->capability.reasoning_bps=8000;a->capability.rag_bps=8000;a->capability.tool_use_bps=8000;a->capability.supports_single_device=1;a->popularity_bps=5000;a->priority_bps=5000;a->recommended=1;return 0;}
static void provenance(QrxAuraModelProvenance*p,const QrxAuraModelCatalogAnnouncement*a,char source_char){memset(p,0,sizeof(*p));p->version=1;snprintf(p->model_id,sizeof(p->model_id),"%s",a->manifest.model_id);snprintf(p->model_version,sizeof(p->model_version),"%s",a->manifest.model_version);snprintf(p->manifest_root,sizeof(p->manifest_root),"%s",a->manifest_root);snprintf(p->publisher_id,sizeof(p->publisher_id),"%s",a->publisher_id);snprintf(p->license_id,sizeof(p->license_id),"%s",a->manifest.license_id);snprintf(p->source_uri,sizeof(p->source_uri),"https://upstream.invalid/repository");h64(p->source_commit,source_char);p->recorded_at_height=100;}
static int ingest_decision(QrxAuraModelGovernanceState*s,Ks*keys,EVP_PKEY*gov,QrxAuraModelGovernanceDecision*d){uint8_t*sig=NULL;size_t sn=0;if(qrx_aura_model_governance_decision_sign(gov,d,&sig,&sn))return-1;int rc=qrx_aura_model_governance_ingest(s,d,sig,sn,100,lookup,keys,gov_auth,NULL);free(sig);return rc;}
int main(void){
    EVP_PKEY*pub=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519"),*gov=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519"),*rogue=EVP_PKEY_Q_keygen(NULL,NULL,"ED25519");CHECK(pub&&gov&&rogue);Ks keys={{{"publisher:model",pub},{"governor:model",gov},{"rogue",rogue}},3};
    QrxAuraModelLicensePolicy policy;qrx_aura_model_license_policy_init(&policy);policy.default_allow=0;CHECK(qrx_aura_model_license_policy_add(&policy,"apache-2.0",QRX_AURA_LICENSE_ALLOW)==0);CHECK(qrx_aura_model_license_policy_add(&policy,"noncommercial",QRX_AURA_LICENSE_DENY)==0);
    QrxAuraModelGovernanceState state;qrx_aura_model_governance_state_init(&state);QrxAuraModelCatalog *catalog=calloc(1,sizeof(*catalog));CHECK(catalog);qrx_aura_model_catalog_init(catalog);
    QrxAuraModelManifest ma;manifest(&ma,'a',"apache-2.0");QrxAuraModelCatalogAnnouncement aa;CHECK(announce(&aa,&ma,1)==0);QrxAuraModelProvenance pa;provenance(&pa,&aa,'1');
    QrxAuraModelGovernanceDecision d;memset(&d,0,sizeof(d));d.version=1;snprintf(d.governor_id,sizeof(d.governor_id),"governor:model");d.sequence=1;d.effective_height=100;snprintf(d.model_id,sizeof(d.model_id),"%s",ma.model_id);snprintf(d.model_version,sizeof(d.model_version),"%s",ma.model_version);snprintf(d.manifest_root,sizeof(d.manifest_root),"%s",aa.manifest_root);d.action=QRX_AURA_MODEL_GOV_APPROVE;snprintf(d.reason,sizeof(d.reason),"initial audited release");CHECK(ingest_decision(&state,&keys,gov,&d)==0);
    uint8_t*sig=NULL;size_t sn=0;CHECK(qrx_aura_model_catalog_announcement_sign(pub,&aa,&sig,&sn)==0);CHECK(qrx_aura_model_catalog_ingest_governed(catalog,&aa,sig,sn,100,lookup,&keys,pub_auth,NULL,&state,&policy,&pa)==0);free(sig);
    /* Provenance mismatch is rejected even with valid publisher/governance signatures. */QrxAuraModelProvenance mismatch=pa;mismatch.source_commit[0]='g';CHECK(qrx_aura_model_catalog_announcement_sign(pub,&aa,&sig,&sn)==0);CHECK(qrx_aura_model_catalog_ingest_governed(catalog,&aa,sig,sn,100,lookup,&keys,pub_auth,NULL,&state,&policy,&mismatch)==-10);free(sig);
    /* Approved update B. */QrxAuraModelManifest mb;manifest(&mb,'b',"apache-2.0");QrxAuraModelCatalogAnnouncement ab;CHECK(announce(&ab,&mb,2)==0);QrxAuraModelProvenance pb;provenance(&pb,&ab,'2');snprintf(pb.parent_manifest_root,sizeof(pb.parent_manifest_root),"%s",aa.manifest_root);d.sequence=2;snprintf(d.manifest_root,sizeof(d.manifest_root),"%s",ab.manifest_root);d.action=QRX_AURA_MODEL_GOV_APPROVE;d.rollback_manifest_root[0]=0;snprintf(d.reason,sizeof(d.reason),"audited update");CHECK(ingest_decision(&state,&keys,gov,&d)==0);CHECK(qrx_aura_model_catalog_announcement_sign(pub,&ab,&sig,&sn)==0);CHECK(qrx_aura_model_catalog_ingest_governed(catalog,&ab,sig,sn,100,lookup,&keys,pub_auth,NULL,&state,&policy,&pb)==0);free(sig);CHECK(!strcmp(qrx_aura_model_catalog_find(catalog,mb.model_id,mb.model_version)->manifest_root,ab.manifest_root));
    /* Governance rollback authorizes the previous manifest, which must still carry valid provenance and a higher catalog sequence. */d.sequence=3;snprintf(d.manifest_root,sizeof(d.manifest_root),"%s",ab.manifest_root);snprintf(d.rollback_manifest_root,sizeof(d.rollback_manifest_root),"%s",aa.manifest_root);d.action=QRX_AURA_MODEL_GOV_ROLLBACK;snprintf(d.reason,sizeof(d.reason),"runtime regression");CHECK(ingest_decision(&state,&keys,gov,&d)==0);QrxAuraModelCatalogAnnouncement rollback=aa;rollback.sequence=3;CHECK(qrx_aura_model_catalog_announcement_sign(pub,&rollback,&sig,&sn)==0);CHECK(qrx_aura_model_catalog_ingest_governed(catalog,&rollback,sig,sn,100,lookup,&keys,pub_auth,NULL,&state,&policy,&pa)==0);free(sig);CHECK(!strcmp(qrx_aura_model_catalog_find(catalog,ma.model_id,ma.model_version)->manifest_root,aa.manifest_root));
    /* License denial wins even if governance attempted to approve it. */QrxAuraModelManifest mc;manifest(&mc,'c',"noncommercial");QrxAuraModelCatalogAnnouncement ac;CHECK(announce(&ac,&mc,4)==0);QrxAuraModelProvenance pc;provenance(&pc,&ac,'3');d.sequence=4;snprintf(d.manifest_root,sizeof(d.manifest_root),"%s",ac.manifest_root);d.rollback_manifest_root[0]=0;d.action=QRX_AURA_MODEL_GOV_APPROVE;CHECK(ingest_decision(&state,&keys,gov,&d)==0);CHECK(qrx_aura_model_catalog_announcement_sign(pub,&ac,&sig,&sn)==0);CHECK(qrx_aura_model_catalog_ingest_governed(catalog,&ac,sig,sn,100,lookup,&keys,pub_auth,NULL,&state,&policy,&pc)==-10);free(sig);
    /* Unauthorized governor identity cannot alter state. */QrxAuraModelGovernanceDecision rd=d;snprintf(rd.governor_id,sizeof(rd.governor_id),"rogue");rd.sequence=5;CHECK(qrx_aura_model_governance_decision_sign(rogue,&rd,&sig,&sn)==0);CHECK(qrx_aura_model_governance_ingest(&state,&rd,sig,sn,100,lookup,&keys,gov_auth,NULL)==-1);free(sig);
    qrx_aura_model_catalog_free(catalog);free(catalog);qrx_aura_model_governance_state_free(&state);EVP_PKEY_free(pub);EVP_PKEY_free(gov);EVP_PKEY_free(rogue);printf("phase171 AURA model governance/provenance/license/rollback: PASS\n");return 0;
}
