#include "compute/qrx_pouc_pipeline.h"
#include "compute/qrx_pouc_liveness.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
static void hx(char x[65],char c){for(int i=0;i<64;i++)x[i]=c;x[64]=0;}
static void putu(QrxDB*d,const char*k,uint64_t v){char b[64];snprintf(b,sizeof(b),"%llu",(unsigned long long)v);assert(!qrxdb_put(d,k,b));}
static uint64_t getu0(QrxDB*d,const char*k){char b[128];if(qrxdb_get(d,k,b,sizeof(b)))return 0;return strtoull(b,NULL,10);}
static void bond(QrxDB*d,const char*a,uint64_t p){char k[512];snprintf(k,sizeof(k),"staking:self:%s",a);putu(d,k,p);}
static void entropy(QrxDB*d,uint64_t h,char c){char bh[65];hx(bh,c);assert(!qrxdb_chain_put_block(d,h,bh,"reselection entropy"));}
static void commit(QrxDB*d,const QrxPoucPipelineEffect*e,const char*tx,uint64_t h){QrxDBBatch b;assert(!qrxdb_batch_begin(d,&b));assert(!qrx_pouc_pipeline_stage(d,&b,e,tx,h));assert(!qrxdb_batch_commit(&b));}
static void lockj(QrxDB*d,const char*o,const char*gc,uint64_t h){char p[512];snprintf(p,sizeof(p),"graph_commitment=%s;max_compute_atoms=400000000;fasttrack_fee_atoms=0;verification_reward_atoms=0;expiry_height=5000",gc);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_ESCROW_LOCK",o,o,0,p,h,&e));commit(d,&e,"lock",h);}
static void assignj(QrxDB*d,const char*o,const char*pr,const char*gc,uint32_t mode,uint64_t h){char mc[65],p[1024];hx(mc,'b');snprintf(p,sizeof(p),"graph_commitment=%s;node_id=7;quote_id=q157;quote_price_atoms=400000000;quote_expiry_height=4000;verification_mode=%u;assignment_nonce=%llu;runtime_id=qrx-ai-v1;model_commitment=%s",gc,mode,(unsigned long long)h,mc);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_ASSIGN",o,pr,0,p,h,&e));commit(d,&e,"assign",h);}
static void receiptj(QrxDB*d,const char*o,const char*pr,const char*gc,uint32_t mode,uint64_t h,char rc[65]){char a[65],b[65],c[65],r[65],p[1600];hx(a,'a');hx(b,'b');hx(c,'c');hx(r,'d');snprintf(p,sizeof(p),"graph_commitment=%s;node_id=7;provider_id=%s;runtime_id=qrx-ai-v1;input_commitment=%s;model_commitment=%s;execution_params_commitment=%s;result_commitment=%s;verified_compute_atoms=270000000;started_height=%llu;completed_height=%llu;verification_mode=%u",gc,pr,a,b,c,r,(unsigned long long)(h-2),(unsigned long long)(h-1),mode);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_RECEIPT",pr,o,0,p,h,&e));snprintf(rc,65,"%s",e.receipt_commitment);commit(d,&e,"receipt",h);}
static void vote(QrxDB*d,const char*v,const char*pr,const char*rc,const char*obs,uint64_t h,const char*tx){char p[512];snprintf(p,sizeof(p),"receipt_commitment=%s;observed_result_commitment=%s",rc,obs);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_VERIFY",v,pr,0,p,h,&e));commit(d,&e,tx,h);}
static void challenge(QrxDB*d,const char*v,const char*pr,const char*rc,const char*obs,uint64_t h,const char*tx){char p[512];snprintf(p,sizeof(p),"receipt_commitment=%s;observed_result_commitment=%s",rc,obs);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_CHALLENGE",v,pr,0,p,h,&e));commit(d,&e,tx,h);}
static void reselect(QrxDB*d,const char*from,const char*pr,const char*rc,uint64_t h,QrxPoucPipelineEffect*out){char p[256];snprintf(p,sizeof(p),"receipt_commitment=%s",rc);QrxPoucPipelineEffect e;assert(!qrx_pouc_pipeline_prepare(d,"COMPUTE_RESELECT",from,pr,0,p,h,&e));commit(d,&e,"reselect",h);if(out)*out=e;}
int main(void){char dir[]="/tmp/qrx-pouc-live-XXXXXX";assert(mkdtemp(dir));QrxDB db;assert(!qrxdb_init(&db,dir));const char*vals[]={"v01","v02","v03","v04","v05","v06","v07","v08","v09","v10","v11","v12"};for(int i=0;i<12;i++)bond(&db,vals[i],100000000ULL*(i+1));putu(&db,QRX_POUC_MISS_THRESHOLD_KEY,1);putu(&db,QRX_POUC_MISS_JAIL_BLOCKS_KEY,50);entropy(&db,99,'7');entropy(&db,120,'8');char good[65],bad[65];hx(good,'d');hx(bad,'e');
 char gc[65],rc[65];hx(gc,'4');lockj(&db,"owner",gc,90);assignj(&db,"owner","provider",gc,QRX_POUC_VERIFY_RANDOM,91);receiptj(&db,"owner","provider",gc,QRX_POUC_VERIFY_RANDOM,100,rc);QrxPoucVerifierSelection before;assert(!qrx_pouc_verifier_selection_get(&db,rc,&before));vote(&db,before.primary[0],"provider",rc,good,101,"vote1");const char*timed=before.primary[1];QrxPoucPipelineEffect re;reselect(&db,"keeper","provider",rc,121,&re);assert(re.reselection.phase==QRX_POUC_TIMEOUT_PRIMARY&&re.reselection.timeout_count==1&&!strcmp(re.reselection.timed_out[0],timed));QrxPoucVerifierSelection after;assert(!qrx_pouc_verifier_selection_get(&db,rc,&after));assert(strcmp(after.selection_commitment,before.selection_commitment));assert(!strcmp(after.primary[0],before.primary[0])||!strcmp(after.primary[1],before.primary[0]));assert(!qrx_pouc_verifier_is_primary(&after,timed));assert(qrx_pouc_verifier_is_compute_jailed(&db,timed,121));char mk[256];snprintf(mk,sizeof(mk),"%s%s",QRX_POUC_MISS_COUNT_PREFIX,timed);assert(getu0(&db,mk)==1);
 uint32_t lr=0;assert(!qrx_pouc_liveness_revert_above_height(&db,120,&lr)&&lr==1);QrxPoucVerifierSelection restored;assert(!qrx_pouc_verifier_selection_get(&db,rc,&restored)&&!strcmp(restored.selection_commitment,before.selection_commitment));assert(getu0(&db,mk)==0);assert(!qrx_pouc_verifier_is_compute_jailed(&db,timed,121));QrxPoucPipelineEffect re2;reselect(&db,"keeper2","provider",rc,121,&re2);assert(!strcmp(re2.reselection.after.selection_commitment,after.selection_commitment));vote(&db,re2.reselection.after.primary[0][0]&&strcmp(re2.reselection.after.primary[0],before.primary[0])?re2.reselection.after.primary[0]:re2.reselection.after.primary[1],"provider",rc,good,122,"vote2");QrxPoucVerificationAggregate ag;assert(!qrx_pouc_pipeline_get_verification(&db,rc,&ag)&&ag.finalized&&ag.verifier_count==2);
 /* Challenge timeout: one challenger votes, two silent challengers are deterministically replaced. */entropy(&db,299,'9');entropy(&db,340,'a');char gc2[65],rc2[65];hx(gc2,'5');lockj(&db,"owner2",gc2,290);assignj(&db,"owner2","provider2",gc2,QRX_POUC_VERIFY_RANDOM,291);receiptj(&db,"owner2","provider2",gc2,QRX_POUC_VERIFY_RANDOM,300,rc2);QrxPoucVerifierSelection cs;assert(!qrx_pouc_verifier_selection_get(&db,rc2,&cs));vote(&db,cs.primary[0],"provider2",rc2,good,301,"cv1");vote(&db,cs.primary[1],"provider2",rc2,bad,302,"cv2");challenge(&db,cs.challenger[0],"provider2",rc2,good,303,"cc1");QrxPoucPipelineEffect cre;reselect(&db,"keeper3","provider2",rc2,341,&cre);assert(cre.reselection.phase==QRX_POUC_TIMEOUT_CHALLENGE&&cre.reselection.timeout_count==2);QrxPoucVerifierSelection ca=cre.reselection.after;const char*newc=NULL;for(int i=0;i<3;i++)if(strcmp(ca.challenger[i],cs.challenger[0])){newc=ca.challenger[i];break;}assert(newc);challenge(&db,newc,"provider2",rc2,good,342,"cc2");char ck[200],cv[32];snprintf(ck,sizeof(ck),"consensus:compute:challenge:%s",rc2);assert(!qrxdb_get(&db,ck,cv,sizeof(cv))&&!strcmp(cv,"PASSED"));
 /* Fraud penalty journal restores slash + jail state on canonical rollback and permits canonical re-application. */const char*fraud="fraud-v";bond(&db,fraud,1000000000);putu(&db,QRX_POUC_FRAUD_SLASH_BPS_KEY,1000);putu(&db,QRX_POUC_FRAUD_JAIL_BLOCKS_KEY,100);char frc[65];hx(frc,'f');QrxDBBatch b;uint64_t sl=0,ju=0;assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_stage_consensus_penalty(&db,&b,fraud,frc,500,1,1,&sl,&ju));assert(!qrxdb_batch_commit(&b));assert(getu0(&db,"staking:self:fraud-v")==900000000&&getu0(&db,QRX_POUC_COMPUTE_SLASH_POOL_KEY)==100000000&&qrx_pouc_verifier_is_compute_jailed(&db,fraud,500));uint32_t pr=0;assert(!qrx_pouc_penalty_journal_revert_above_height(&db,499,&pr)&&pr==1);assert(getu0(&db,"staking:self:fraud-v")==1000000000&&getu0(&db,QRX_POUC_COMPUTE_SLASH_POOL_KEY)==0&&!qrx_pouc_verifier_is_compute_jailed(&db,fraud,500));assert(!qrxdb_batch_begin(&db,&b));assert(!qrx_pouc_stage_consensus_penalty(&db,&b,fraud,frc,501,1,1,&sl,&ju));assert(!qrxdb_batch_commit(&b));
 assert(!qrxdb_close(&db));char cmd[1200];snprintf(cmd,sizeof(cmd),"rm -rf '%s'",dir);system(cmd);puts("compute phase 157 verifier timeout/reselection/reorg penalty: PASS");return 0;}
