#include "compute/qrx_aura_production_routing.h"
#include <stdio.h>
#include <string.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"CHECK failed %s:%d: %s\n",__FILE__,__LINE__,#x);return 1;}}while(0)
static void model(QrxAuraModelCapabilityProfile*m,const char*id,uint32_t quality,uint32_t reasoning,uint32_t coding){memset(m,0,sizeof(*m));m->version=1;snprintf(m->model_id,sizeof(m->model_id),"%s",id);snprintf(m->model_version,sizeof(m->model_version),"1");snprintf(m->family,sizeof(m->family),"test");snprintf(m->runtime_id,sizeof(m->runtime_id),"auto");snprintf(m->quantization,sizeof(m->quantization),"auto");m->tier=QRX_AURA_TIER_LOCAL;m->min_memory_bytes=1;m->recommended_memory_bytes=1;m->min_storage_bytes=1;m->min_aggregate_milli_tokens_per_second=1;m->min_pods=1;m->min_network_mbps=1;m->max_latency_ms=1000;m->min_reliability_bps=1;m->max_context_tokens=131072;m->quality_bps=quality;m->reasoning_bps=reasoning;m->coding_bps=coding;m->rag_bps=quality;m->tool_use_bps=quality;m->supports_single_device=1;}
static void offer(QrxAuraProductionOffer*o,const char*provider,const char*region,const char*modelid,QrxMoeRuntimeBackend b,uint64_t tps,uint32_t lat,uint32_t rel,uint32_t quality,uint64_t price,uint64_t energy){memset(o,0,sizeof(*o));o->version=1;snprintf(o->provider_id,sizeof(o->provider_id),"%s",provider);snprintf(o->pod_id,sizeof(o->pod_id),"pod-%s",provider);snprintf(o->region,sizeof(o->region),"%s",region);snprintf(o->model_id,sizeof(o->model_id),"%s",modelid);snprintf(o->model_version,sizeof(o->model_version),"1");o->backend=b;o->milli_tokens_per_second=tps;o->latency_ms=lat;o->reliability_bps=rel;o->observed_quality_bps=quality;o->price_microqub_per_million_tokens=price;o->energy_mwh_per_1000_tokens=energy;o->wan_mbps=500;o->available=1;}
static QrxAuraProductionRouteRequest req(QrxAuraProductionOptimization opt,QrxAuraTaskClass task){QrxAuraProductionRouteRequest r;memset(&r,0,sizeof(r));r.version=1;r.optimization=opt;r.task_class=task;r.min_quality_bps=7000;r.max_latency_ms=500;r.max_price_microqub_per_million_tokens=1000;r.max_energy_mwh_per_1000_tokens=1000;r.min_reliability_bps=9000;r.min_context_tokens=4096;snprintf(r.preferred_region,sizeof(r.preferred_region),"DE");r.allow_cross_region=1;return r;}
int main(void){
    QrxAuraModelCapabilityProfile models[2];model(&models[0],"qrx:model:fast",8500,8000,8200);model(&models[1],"qrx:model:deep",9700,9800,9600);
    QrxAuraProductionOffer offers[6];offer(&offers[0],"mac-m1","DE","qrx:model:fast",QRX_MOE_BACKEND_MLX_METAL,45000,8,9900,8500,100,60);offer(&offers[1],"p40","NL","qrx:model:deep",QRX_MOE_BACKEND_CUDA,90000,22,9850,9600,180,220);offer(&offers[2],"cpu-arm","DE","qrx:model:fast",QRX_MOE_BACKEND_CPU,10000,12,9950,8400,60,40);offer(&offers[3],"gpu-us","US","qrx:model:deep",QRX_MOE_BACKEND_CUDA,250000,95,9950,9700,500,600);offer(&offers[4],"edge-sg","SG","qrx:model:fast",QRX_MOE_BACKEND_OTHER,30000,190,9700,8300,80,50);offer(&offers[5],"bad","DE","qrx:model:deep",QRX_MOE_BACKEND_CUDA,500000,3,7000,9900,5,5);
    QrxAuraProductionRouteDecision eco,perf,bal;QrxAuraProductionRouteRequest re=req(QRX_AURA_OPT_ECO,QRX_AURA_TASK_CHAT);CHECK(qrx_aura_production_route(&re,models,2,offers,6,&eco)==0);CHECK(!strcmp(eco.provider_id,"cpu-arm")||!strcmp(eco.provider_id,"mac-m1"));QrxAuraProductionRouteRequest rp=req(QRX_AURA_OPT_PERFORMANCE,QRX_AURA_TASK_REASONING);CHECK(qrx_aura_production_route(&rp,models,2,offers,6,&perf)==0);CHECK(!strcmp(perf.model_id,"qrx:model:deep"));CHECK(strcmp(perf.provider_id,"bad")!=0);QrxAuraProductionRouteRequest rb=req(QRX_AURA_OPT_BALANCED,QRX_AURA_TASK_CODING);CHECK(qrx_aura_production_route(&rb,models,2,offers,6,&bal)==0);CHECK(strlen(bal.decision_commitment)==64);
    QrxAuraProductionTelemetry t;qrx_aura_production_telemetry_init(&t,perf.provider_id,perf.model_id,perf.model_version);CHECK(qrx_aura_production_telemetry_record(&t,1000,offers[perf.offer_index].latency_ms,9600,20,30,500000,0)==0);CHECK(qrx_aura_production_telemetry_record(&t,500,100,9000,15,25,300000,1)==0);CHECK(t.requests==2&&t.tokens==1500);CHECK(qrx_aura_production_telemetry_failure_bps(&t)==5000);CHECK(qrx_aura_production_telemetry_avg_quality_bps(&t)>=9399&&qrx_aura_production_telemetry_avg_quality_bps(&t)<=9401);char tc[65];CHECK(qrx_aura_production_telemetry_commitment(&t,tc)==0&&strlen(tc)==64);
    QrxAuraProductionRouteRequest tasks[6]={req(QRX_AURA_OPT_ECO,QRX_AURA_TASK_CHAT),req(QRX_AURA_OPT_BALANCED,QRX_AURA_TASK_CODING),req(QRX_AURA_OPT_PERFORMANCE,QRX_AURA_TASK_REASONING),req(QRX_AURA_OPT_BALANCED,QRX_AURA_TASK_RAG),req(QRX_AURA_OPT_ECO,QRX_AURA_TASK_TOOL_USE),req(QRX_AURA_OPT_PERFORMANCE,QRX_AURA_TASK_CODING)};QrxAuraProductionCampaignResult cr;CHECK(qrx_aura_production_campaign_run(tasks,6,models,2,offers,6,&cr)==0);CHECK(cr.tasks_total==6&&cr.tasks_routed==6&&cr.tasks_failed==0&&strlen(cr.campaign_commitment)==64);printf("phase172 AURA heterogeneous WAN quality/cost/energy routing telemetry: PASS\n");return 0;
}
