#include "compute/qrx_compute_provider_identity.h"
#include "compute/qrx_aura_live_dispatch.h"
#include "compute/qrx_pouc_undo.h"
#include <assert.h>
#include <openssl/pem.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define MIB (1024ULL*1024ULL)
#define GIB (1024ULL*1024ULL*1024ULL)

static void hexfill(char out[65],char c){for(int i=0;i<64;i++)out[i]=c;out[64]=0;}
static EVP_PKEY*new_key(const char*name){EVP_PKEY_CTX*c=EVP_PKEY_CTX_new_from_name(NULL,name,NULL);EVP_PKEY*k=NULL;assert(c&&EVP_PKEY_keygen_init(c)==1&&EVP_PKEY_generate(c,&k)==1&&k);EVP_PKEY_CTX_free(c);return k;}
static char*pub_b64(EVP_PKEY*k){BIO*b=BIO_new(BIO_s_mem());assert(b&&PEM_write_bio_PUBKEY(b,k)==1);BUF_MEM*m=NULL;BIO_get_mem_ptr(b,&m);size_t cap=4*((m->length+2)/3)+1;char*out=calloc(1,cap);assert(out);int n=EVP_EncodeBlock((unsigned char*)out,(const unsigned char*)m->data,(int)m->length);assert(n>0);out[n]=0;BIO_free(b);return out;}
static int fetch_ok(void*ctx,const QrxAiModelRecord*m,const QrxAuraModelCachePlacement*p,char out[65]){(void)m;assert(p&&p->bytes_to_place);snprintf(out,65,"%s",(const char*)ctx);return 0;}
static int worker(void*ctx,const void*in,size_t in_n,void*out,size_t cap,size_t*out_n){(void)ctx;const char*prefix="AURA:";size_t pn=strlen(prefix);if(cap<pn+in_n)return -1;memcpy(out,prefix,pn);memcpy((char*)out+pn,in,in_n);*out_n=pn+in_n;return 0;}

static QrxAuraPodCapacity make_pod(const char*id){QrxAuraPodCapacity p;memset(&p,0,sizeof(p));p.version=QRX_AURA_FABRIC_VERSION;snprintf(p.provider_id,sizeof(p.provider_id),"%s",id);snprintf(p.pod_id,sizeof(p.pod_id),"pod-compute-1");snprintf(p.region,sizeof(p.region),"EU-WEST");p.backend=QRX_MOE_BACKEND_CPU;p.accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;p.role_mask=QRX_AURA_POD_ROLE_INFERENCE|QRX_AURA_POD_ROLE_MODEL_CACHE|QRX_AURA_POD_ROLE_VERIFY;p.usable_memory_bytes=10*GIB;p.free_memory_bytes=8*GIB;p.model_cache_free_bytes=2*GIB;p.measured_milli_tokens_per_second=5000;p.network_egress_mbps=1000;p.latency_ms=12;p.utilization_bps=1800;p.reliability_bps=9950;p.cache_hit_bps=9000;p.expert_locality_bps=9000;p.max_context_tokens=32768;p.node_count=1;p.available=1;hexfill(p.calibration_commitment,'a');assert(qrx_aura_pod_capacity_validate(&p)==0);return p;}
static QrxAuraModelCapabilityProfile make_profile(void){QrxAuraModelCapabilityProfile m;memset(&m,0,sizeof(m));m.version=QRX_AURA_FABRIC_VERSION;snprintf(m.model_id,sizeof(m.model_id),"qrx/aura-nano");snprintf(m.model_version,sizeof(m.model_version),"1");snprintf(m.family,sizeof(m.family),"Qwen-class");snprintf(m.runtime_id,sizeof(m.runtime_id),"qrx-llm-runtime-v1");snprintf(m.quantization,sizeof(m.quantization),"Q4");m.tier=QRX_AURA_TIER_NANO;m.min_memory_bytes=2*GIB;m.recommended_memory_bytes=4*GIB;m.min_storage_bytes=512*MIB;m.min_aggregate_milli_tokens_per_second=500;m.min_pods=1;m.max_latency_ms=250;m.min_reliability_bps=8000;m.max_context_tokens=8192;m.quality_bps=6000;m.coding_bps=6500;m.reasoning_bps=6200;m.rag_bps=6200;m.tool_use_bps=6000;m.supports_single_device=1;assert(qrx_aura_model_profile_validate(&m)==0);return m;}
static QrxAiModelRecord make_model(void){QrxAiModelRecord m;memset(&m,0,sizeof(m));m.registry_version=QRX_MODEL_REGISTRY_VERSION;snprintf(m.model_id,sizeof(m.model_id),"qrx/aura-nano");snprintf(m.model_version,sizeof(m.model_version),"1");snprintf(m.architecture,sizeof(m.architecture),"dense-transformer");snprintf(m.runtime_id,sizeof(m.runtime_id),"qrx-llm-runtime-v1");hexfill(m.manifest_root,'b');hexfill(m.tokenizer_root,'c');memset(m.expert_manifest_root,'0',64);m.expert_manifest_root[64]=0;m.min_memory_bytes=2*GIB;m.min_storage_bytes=512*MIB;m.verification_profile=QRX_MODEL_VERIFY_STANDARD;snprintf(m.license_id,sizeof(m.license_id),"open-model-license");m.is_moe=0;assert(qrx_ai_model_validate(&m)==0);return m;}

int main(void){
    char dir[]="/tmp/qrx937-XXXXXX";assert(mkdtemp(dir));QrxDB db;assert(qrxdb_init(&db,dir)==0);
    EVP_PKEY*kp=new_key("ML-DSA-65");char*b64=pub_b64(kp);char payload[20000];snprintf(payload,sizeof(payload),"public_key_pem_b64=%s;sequence=1",b64);QrxServiceEconomicEffect eff={0};const char*provider="qrx-provider-compute-1";
    assert(qrx_compute_provider_identity_prepare(&db,QRX_COMPUTE_PROVIDER_BIND_TX,provider,provider,0,payload,100,&eff)==0);QrxDBBatch batch;assert(qrxdb_batch_begin(&db,&batch)==0);assert(qrx_compute_provider_identity_stage(&db,&batch,QRX_COMPUTE_PROVIDER_BIND_TX,provider,provider,0,payload,100)==0);assert(qrxdb_batch_commit(&batch)==0);
    QrxComputeProviderIdentity ident;assert(qrx_compute_provider_identity_get(&db,provider,&ident)==0);assert(ident.sequence==1&&!strcmp(ident.key_scheme,"ML-DSA-65"));char ic[65];assert(qrx_compute_provider_identity_commitment(&ident,ic)==0);EVP_PKEY*lookup=NULL;assert(qrx_compute_provider_identity_key_lookup(&db,provider,&lookup)==0&&lookup);EVP_PKEY_free(lookup);
    assert(qrx_compute_provider_identity_prepare(&db,QRX_COMPUTE_PROVIDER_BIND_TX,provider,provider,0,payload,101,&eff)==-3); /* replay sequence */
    /* Key rotation is journaled in the same QRXDB batch and can be reverted on reorg. */
    EVP_PKEY*kp2=new_key("ML-DSA-65");char*b642=pub_b64(kp2);char payload2[20000];snprintf(payload2,sizeof(payload2),"public_key_pem_b64=%s;sequence=2",b642);
    assert(qrx_compute_provider_identity_prepare(&db,QRX_COMPUTE_PROVIDER_BIND_TX,provider,provider,0,payload2,101,&eff)==0);assert(qrxdb_batch_begin(&db,&batch)==0);assert(qrx_compute_provider_identity_stage(&db,&batch,QRX_COMPUTE_PROVIDER_BIND_TX,provider,provider,0,payload2,101)==0);assert(qrx_pouc_tx_undo_stage(&db,&batch,"phase162-identity-rotation",QRX_COMPUTE_PROVIDER_BIND_TX,101)==0);assert(qrxdb_batch_commit(&batch)==0);assert(qrx_compute_provider_identity_get(&db,provider,&ident)==0&&ident.sequence==2);uint32_t reverted=0;assert(qrx_pouc_tx_undo_revert_above_height(&db,100,&reverted)==0&&reverted==1);assert(qrx_compute_provider_identity_get(&db,provider,&ident)==0&&ident.sequence==1);free(b642);EVP_PKEY_free(kp2);

    QrxAuraPodAnnouncement pa;memset(&pa,0,sizeof(pa));pa.version=QRX_AURA_GOSSIP_VERSION;pa.sequence=1;pa.valid_from_height=95;pa.valid_until_height=200;snprintf(pa.service_endpoint,sizeof(pa.service_endpoint),"qrxp2p://compute-1:39100");pa.capacity=make_pod(provider);uint8_t*sig=NULL;size_t sl=0;assert(qrx_aura_pod_announcement_sign(kp,&pa,&sig,&sl)==0);QrxAuraPodGossipTable pods;qrx_aura_pod_gossip_init(&pods);assert(qrx_aura_pod_gossip_ingest(&pods,&pa,sig,sl,110,qrx_compute_provider_identity_key_lookup,&db)==0);assert(pods.count==1);

    QrxAiModelRegistry reg;memset(&reg,0,sizeof(reg));QrxAiModelRecord mr=make_model();assert(qrx_ai_model_registry_add(&reg,&mr)==0);char mc[65];assert(qrx_ai_model_commitment(&mr,mc)==0);
    QrxAuraModelProfileAnnouncement ma;memset(&ma,0,sizeof(ma));ma.version=QRX_AURA_GOSSIP_VERSION;snprintf(ma.publisher_id,sizeof(ma.publisher_id),"governance-root-1");ma.sequence=1;ma.valid_from_height=90;ma.valid_until_height=200;snprintf(ma.model_registry_commitment,65,"%s",mc);ma.profile=make_profile();QrxAiModelRecord check;assert(qrx_aura_model_profile_registry_verify(&ma,&reg,&check)==0);
    QrxAuraModelGossipTable models;qrx_aura_model_gossip_init(&models);models.entries=calloc(1,sizeof(*models.entries));assert(models.entries);models.capacity=1;models.count=1;models.entries[0].announcement=ma;

    QrxAuraModelCacheCatalog cache;qrx_aura_model_cache_catalog_init(&cache);QrxAuraModelCachePlan cp;assert(qrx_aura_model_cache_plan_build(&ma,&reg,&pods,110,1,&cp)==0);assert(cp.placement_count==1&&cp.planned_bytes>=mr.min_storage_bytes);assert(!strcmp(cp.plan_commitment,"837be3a4651abae82a24ca6da5bd92848a2be2ddef2f690d68e86ca40cc48b3b"));assert(qrx_aura_model_cache_plan_execute(&cp,&reg,&cache,110,fetch_ok,mc)==0);const QrxAuraModelCacheEntry*ce=qrx_aura_model_cache_find(&cache,"pod-compute-1",mr.model_id,mr.model_version);assert(ce&&ce->verified&&ce->bytes_present>=mr.min_storage_bytes);

    QrxResourceProviderPlan plan;memset(&plan,0,sizeof(plan));plan.version=QRX_RESOURCE_PROVIDER_VERSION;snprintf(plan.region,sizeof(plan.region),"EU-WEST");plan.enabled_mask=QRX_PROVIDER_ENABLE_COMPUTE|QRX_PROVIDER_ENABLE_AI|QRX_PROVIDER_ENABLE_MODEL_CACHE|QRX_PROVIDER_ENABLE_NETWORK;plan.model_cache_bytes=4*GIB;plan.compute_threads=4;plan.network_egress_mbps=1000;plan.primary_action=QRX_PROVIDER_ENABLE_COMPUTE;plan.opportunity_score=8000;plan.expected_utilization_bps=5000;QrxResourceProviderRuntime rt;assert(qrx_resource_provider_runtime_init(&rt,provider,"alphanet",&plan)==0);assert(qrx_resource_provider_runtime_mark_ready(&rt)==0);QrxResourceProviderMarketRegistration mreg;assert(qrx_resource_provider_market_register(&rt,NULL,110,&mreg)==0);assert(qrx_resource_provider_runtime_start_serving(&rt)==0);
    QrxAuraRuntimeBinding rb;memset(&rb,0,sizeof(rb));rb.version=QRX_AURA_LIVE_DISPATCH_VERSION;snprintf(rb.pod_id,sizeof(rb.pod_id),"pod-compute-1");snprintf(rb.provider_id,sizeof(rb.provider_id),"%s",provider);rb.provider_runtime=&rt;rb.local=1;rb.device.version=QRX_MOE_RUNTIME_VERSION;rb.device.backend=QRX_MOE_BACKEND_CPU;snprintf(rb.device.device_name,sizeof(rb.device.device_name),"generic-cpu");rb.device.accelerator_features=QRX_MOE_ACCEL_FEAT_FP32;rb.device.device_memory_bytes=8*GIB;rb.device.max_batch_items=8;rb.adapter.version=QRX_MOE_DISCOVERY_VERSION;snprintf(rb.adapter.name,sizeof(rb.adapter.name),"test-cpu-adapter");rb.adapter.backend=QRX_MOE_BACKEND_CPU;rb.adapter.kernel_mask=QRX_MOE_KERNEL_FP32;rb.adapter.ready=1;rb.adapter.execute=worker;

    QrxComputeJobGraph g;memset(&g,0,sizeof(g));g.protocol_version=QRX_COMPUTE_JOB_PROTOCOL_VERSION;snprintf(g.graph_id,sizeof(g.graph_id),"graph-aura-937");snprintf(g.owner,sizeof(g.owner),"user-1");g.nonce=1;g.max_total_fee_atoms=100000;g.expiry_height=180;g.node_count=1;QrxComputeJobNode*n=&g.nodes[0];n->node_id=1;n->job_type=QRX_JOB_AI_INFERENCE;snprintf(n->runtime_id,sizeof(n->runtime_id),"qrx-llm-runtime-v1");snprintf(n->model_id,sizeof(n->model_id),"qrx/aura-nano");snprintf(n->model_version,sizeof(n->model_version),"1");snprintf(n->input_ref,sizeof(n->input_ref),"drive:input");snprintf(n->output_ref,sizeof(n->output_ref),"drive:output");n->min_memory_bytes=2*GIB;n->max_runtime_ms=30000;n->max_output_bytes=4096;n->max_fee_atoms=100000;n->capability_mask=QRX_JOB_CAP_READ_INPUTS|QRX_JOB_CAP_STREAM_OUTPUT|QRX_JOB_CAP_MODEL_INFERENCE;assert(qrx_compute_job_graph_validate(&g)==0);
    QrxAuraRouteRequest req;memset(&req,0,sizeof(req));req.version=QRX_AURA_FABRIC_VERSION;req.mode=QRX_AURA_ROUTE_AUTO;req.task_class=QRX_AURA_TASK_CHAT;req.complexity_bps=1000;req.allow_degradation=1;QrxAuraAdmission ad;assert(qrx_aura_live_scheduler_admit(&pods,&models,&reg,&cache,&req,&g,1,&rb,1,110,16,&ad)==0);assert(ad.active&&ad.pod_count==1&&rt.active_jobs==1&&rt.reserved_compute_threads==1);assert(!strcmp(ad.admission_commitment,"030794d382bd8c981b96b56959763b7165de278598b39288c8c6a4b57a142432"));
    char outbuf[128];size_t outn=0;QrxAuraDispatchResult dr;const char*input="hello";assert(qrx_aura_runtime_dispatch_execute(&ad,n,&rb,1,input,strlen(input),outbuf,sizeof(outbuf),&outn,NULL,NULL,&dr)==0);assert(outn==10&&!memcmp(outbuf,"AURA:hello",10));assert(dr.output_commitment[0]&&dr.result_commitment[0]);assert(!strcmp(dr.output_commitment,"6ec929712e6148f91ad4b378c18fd2ee260d194bf633366f8bb945ca3ba2b40d"));assert(!strcmp(dr.result_commitment,"b9b6d59e3047c6c2e6b979598ec2fcd01769450cfd09443b235397dcf51df739"));
    char inputc[65];hexfill(inputc,'d');QrxPoucReceipt receipt;assert(qrx_aura_dispatch_build_pouc_receipt(&ad,&dr,inputc,500,111,112,QRX_POUC_VERIFY_RANDOM,&receipt)==0);assert(!strcmp(receipt.execution_params_commitment,ad.admission_commitment)&&!strcmp(receipt.result_commitment,dr.result_commitment)&&!strcmp(receipt.provider_id,provider));
    assert(qrx_aura_live_scheduler_release(&ad,&rb,1)==0);assert(!ad.active&&rt.active_jobs==0&&rt.reserved_compute_threads==0);

    /* Fail closed without a verified local model cache. */
    QrxAuraModelCacheCatalog empty;qrx_aura_model_cache_catalog_init(&empty);assert(qrx_aura_live_scheduler_admit(&pods,&models,&reg,&empty,&req,&g,1,&rb,1,113,16,&ad)!=0);

    free(models.entries);qrx_aura_pod_gossip_free(&pods);free(sig);free(b64);EVP_PKEY_free(kp);qrxdb_close(&db);
    return 0;
}
