#include "compute/qrx_aura_model_origin.h"
#include "compute/qrx_aura_model_autoplacement.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

static void md(const char*p){char x[2048];snprintf(x,sizeof(x),"%s",p);for(char*q=x+1;*q;q++)if(*q=='/'){*q=0;mkdir(x,0700);*q='/';}mkdir(x,0700);}
static void put(const char*p,const char*s){char d[2048];snprintf(d,sizeof(d),"%s",p);char*q=strrchr(d,'/');if(q){*q=0;md(d);}FILE*f=fopen(p,"wb");assert(f);assert(fwrite(s,1,strlen(s),f)==strlen(s));assert(!fclose(f));}
static int allzero(const char*s){for(int i=0;i<64;i++)if(s[i]!='0')return 0;return s[64]==0;}
typedef struct { QrxStorageFs *fs; } CasRemote;
static int cas_stat(void*v,const char*root,uint64_t*out){CasRemote*c=v;uint8_t*b=NULL;size_t n=0;if(!c||!c->fs||!out||qrx_storage_fs_read(c->fs,root,&b,&n)){free(b);return-1;}free(b);*out=(uint64_t)n;return 0;}
static int cas_range(void*v,const char*root,uint64_t off,size_t len,uint8_t**out,size_t*outn){CasRemote*c=v;uint8_t*b=NULL;size_t n=0;if(!c||!c->fs||!out||!outn||qrx_storage_fs_read(c->fs,root,&b,&n)){free(b);return-1;}if(off>n||len>n-(size_t)off){free(b);return-1;}uint8_t*r=malloc(len?len:1);if(!r){free(b);return-1;}memcpy(r,b+(size_t)off,len);free(b);*out=r;*outn=len;return 0;}
int main(int argc,char**argv){assert(argc==2);
  QrxAuraOriginModelSpec official[16];size_t on=0;assert(!qrx_aura_origin_catalog_load(argv[1],official,16,&on));assert(on>=9);int have_qwen_big=0,have_k2=0,have_k3=0,have_ds=0;for(size_t i=0;i<on;i++){have_qwen_big|=!strcmp(official[i].repo_id,"Qwen/Qwen3.8-27B");have_k2|=!strcmp(official[i].repo_id,"moonshotai/Kimi-K2-Instruct");have_k3|=!strcmp(official[i].repo_id,"moonshotai/Kimi-K3");have_ds|=!strcmp(official[i].repo_id,"deepseek-ai/DeepSeek-V3.2");}assert(have_qwen_big&&have_k2&&have_k3&&have_ds);

  const char*t=getenv("QRX_TEST_HTTPS_ROOT");const char*api_url=getenv("QRX_TEST_HTTPS_API");const char*base_url=getenv("QRX_TEST_HTTPS_BASE");const char*ca_file=getenv("QRX_TEST_HTTPS_CA");assert(t&&api_url&&base_url&&ca_file);char api[1024],base[1024],work[1024],fsp[1024];snprintf(api,sizeof(api),"%s/api",t);snprintf(base,sizeof(base),"%s/hf",t);snprintf(work,sizeof(work),"%s/work",t);snprintf(fsp,sizeof(fsp),"%s/cas",t);md(api);md(base);md(work);
  const char*sha="0123456789abcdef0123456789abcdef01234567";char p[2048];
  snprintf(p,sizeof(p),"%s/models/vendor/TestMoE",api);put(p,"{\"sha\":\"0123456789abcdef0123456789abcdef01234567\",\"gated\":false,\"cardData\":{\"license\":\"mit\"},\"siblings\":[{\"rfilename\":\"LICENSE\"},{\"rfilename\":\"config.json\"},{\"rfilename\":\"tokenizer.json\"},{\"rfilename\":\"model.safetensors.index.json\"},{\"rfilename\":\"model-00001-of-00002.safetensors\"},{\"rfilename\":\"model-00002-of-00002.safetensors\"}]}\n");
  char r[2048];snprintf(r,sizeof(r),"%s/vendor/TestMoE/resolve/%s",base,sha);snprintf(p,sizeof(p),"%s/LICENSE",r);put(p,"MIT fixture\n");snprintf(p,sizeof(p),"%s/config.json",r);put(p,"{\"model_type\":\"test_moe\",\"num_hidden_layers\":4,\"n_routed_experts\":4,\"num_experts_per_tok\":2,\"max_position_embeddings\":4096}\n");snprintf(p,sizeof(p),"%s/tokenizer.json",r);put(p,"{\"fixture\":true}\n");snprintf(p,sizeof(p),"%s/model.safetensors.index.json",r);put(p,"{\"weight_map\":{\"model.layers.0.mlp.experts.0.w1.weight\":\"model-00001-of-00002.safetensors\",\"model.layers.1.mlp.experts.1.w1.weight\":\"model-00001-of-00002.safetensors\",\"model.layers.2.mlp.experts.2.w1.weight\":\"model-00002-of-00002.safetensors\",\"model.layers.3.mlp.experts.3.w1.weight\":\"model-00002-of-00002.safetensors\"}}\n");snprintf(p,sizeof(p),"%s/model-00001-of-00002.safetensors",r);put(p,"fixture-weight-shard-one-abcdefghijklmnopqrstuvwxyz\n");snprintf(p,sizeof(p),"%s/model-00002-of-00002.safetensors",r);put(p,"fixture-weight-shard-two-ABCDEFGHIJKLMNOPQRSTUVWXYZ\n");

  QrxAuraOriginConfig c;assert(!qrx_aura_origin_config_defaults(&c));snprintf(c.hf_api_base_url,sizeof(c.hf_api_base_url),"%s",api_url);snprintf(c.hf_base_url,sizeof(c.hf_base_url),"%s",base_url);snprintf(c.tls_ca_bundle,sizeof(c.tls_ca_bundle),"%s",ca_file);snprintf(c.work_dir,sizeof(c.work_dir),"%s",work);assert(!strncmp(c.hf_api_base_url,"https://",8)&&!strncmp(c.hf_base_url,"https://",8));
  QrxAuraOriginModelSpec s={0};s.version=1;snprintf(s.model_id,sizeof(s.model_id),"qrx/test-moe");snprintf(s.family,sizeof(s.family),"test");snprintf(s.repo_id,sizeof(s.repo_id),"vendor/TestMoE");snprintf(s.revision,sizeof(s.revision),"main");snprintf(s.expected_license,sizeof(s.expected_license),"mit");snprintf(s.architecture_hint,sizeof(s.architecture_hint),"test_moe");snprintf(s.runtime_id,sizeof(s.runtime_id),"vllm");snprintf(s.quantization,sizeof(s.quantization),"fixture");s.tier=QRX_AURA_TIER_CLUSTER;s.recommended=1;s.moe_hint=1;
  /* Transport policy regression: production model origin is HTTPS-only. */
  QrxAuraOriginRepoMetadata blocked_meta;QrxAuraOriginConfig blocked=c;snprintf(blocked.hf_api_base_url,sizeof(blocked.hf_api_base_url),"file:///tmp/qrx-blocked");assert(qrx_aura_hf_repo_resolve(&blocked,&s,&blocked_meta)!=0);
  blocked=c;snprintf(blocked.hf_api_base_url,sizeof(blocked.hf_api_base_url),"http://127.0.0.1:9/api");assert(qrx_aura_hf_repo_resolve(&blocked,&s,&blocked_meta)!=0);
  blocked=c;snprintf(blocked.tls_ca_bundle,sizeof(blocked.tls_ca_bundle),"/definitely/not/a/qrx/ca.pem");assert(qrx_aura_hf_repo_resolve(&blocked,&s,&blocked_meta)!=0);
  QrxAuraOriginRepoMetadata mdx;assert(!qrx_aura_hf_repo_resolve(&c,&s,&mdx));assert(!strcmp(mdx.resolved_revision,sha)&&mdx.file_count==6&&!strcmp(mdx.license_id,"mit"));
  QrxStorageFs*fs=NULL;assert(!qrx_storage_fs_open(fsp,1ull<<30,0,&fs));QrxAuraOriginSeedResult*out=calloc(1,sizeof(*out));assert(out);int rc=qrx_aura_hf_seed_to_qrx_drive(&c,&s,fs,NULL,NULL,out);if(rc){fprintf(stderr,"seed rc=%d\n",rc);return 2;}assert(!strcmp(out->registry_record.model_version,sha));assert(out->registry_record.is_moe&&out->has_expert_manifest);assert(out->expert_manifest.layer_count==4&&out->expert_manifest.expert_count==4&&out->expert_manifest.experts_per_token==2);assert(!allzero(out->registry_record.expert_manifest_root));assert(qrx_storage_fs_has(fs,out->drive_bundle_root)==1&&qrx_storage_fs_has(fs,out->source_map_root)==1);assert(out->distribution_manifest.asset_count==6);int ranges=0;for(uint32_t i=0;i<out->source_map.file_count;i++)if(out->source_map.files[i].kind==QRX_AURA_ASSET_WEIGHT_CHUNK&&out->source_map.files[i].expert_count){ranges++;}assert(ranges==2);
  QrxAuraModelCatalogAnnouncement ca;assert(!qrx_aura_origin_catalog_announcement(out,&s,"qrx:model-governance",1,100,1000,&ca));
  QrxAuraModelCatalog *cat=calloc(1,sizeof(*cat));assert(cat);cat->entries[0].announcement=ca;cat->count=1;
  char freshp[1024];snprintf(freshp,sizeof(freshp),"%s/fresh-cas",t);QrxStorageFs*fresh=NULL;assert(!qrx_storage_fs_open(freshp,1ull<<30,0,&fresh));QrxAuraOriginFallbackFetchContext ofc;memset(&ofc,0,sizeof(ofc));ofc.catalog=cat;ofc.origin=c;ofc.local_cache=fresh;ofc.allow_origin_fallback=1;QrxAuraModelCachePlacement plc;memset(&plc,0,sizeof(plc));snprintf(plc.pod_id,sizeof(plc.pod_id),"fresh-pod");snprintf(plc.provider_id,sizeof(plc.provider_id),"fresh-provider");plc.bytes_to_place=1;char verified[65];int frc=qrx_aura_model_fetch_drive_then_origin(&ofc,&out->registry_record,&plc,verified);if(frc){fprintf(stderr,"fallback rc=%d\n",frc);return 11;}char expectmc[65];assert(!qrx_ai_model_commitment(&out->registry_record,expectmc)&&!strcmp(verified,expectmc));assert(qrx_storage_fs_has(fresh,out->drive_bundle_root)==1);qrx_storage_fs_close(fresh);
  QrxAuraModelAvailabilityAnnouncement av;assert(!qrx_aura_origin_availability_announcement(out,"seed-provider","seed-pod","DE-NW","qrxp2p://127.0.0.1:19001",1,100,1000,1000,5,9999,&av));assert(av.full_model&&qrx_aura_model_availability_has_asset(&av,0));
  QrxAuraModelProviderIndex *idxp=calloc(1,sizeof(*idxp));assert(idxp);idxp->entries[0].announcement=av;idxp->count=1;
  QrxAuraPlacementCandidate cand[1];memset(cand,0,sizeof(cand));cand[0].capacity.version=1;snprintf(cand[0].capacity.provider_id,sizeof(cand[0].capacity.provider_id),"replica-provider");snprintf(cand[0].capacity.pod_id,sizeof(cand[0].capacity.pod_id),"replica-pod");snprintf(cand[0].capacity.region,sizeof(cand[0].capacity.region),"US-EAST");cand[0].capacity.backend=QRX_MOE_BACKEND_CPU;cand[0].capacity.role_mask=QRX_AURA_POD_ROLE_MODEL_CACHE;cand[0].capacity.usable_memory_bytes=8ull<<30;cand[0].capacity.free_memory_bytes=4ull<<30;cand[0].capacity.model_cache_free_bytes=1ull<<30;cand[0].capacity.measured_milli_tokens_per_second=1;cand[0].capacity.network_egress_mbps=1000;cand[0].capacity.latency_ms=20;cand[0].capacity.reliability_bps=9900;cand[0].capacity.available=1;cand[0].capacity.node_count=1;
  QrxAuraReplicationRepairPlan rp;assert(!qrx_aura_model_repair_plan(&ca,idxp,100,cand,1,NULL,0,&rp));assert(rp.item_count>0&&!strcmp(rp.items[0].source_provider_id,"seed-provider")&&!strcmp(rp.items[0].target_provider_id,"replica-provider"));
  char replp[1024];snprintf(replp,sizeof(replp),"%s/replica-cas",t);QrxStorageFs*repl=NULL;assert(!qrx_storage_fs_open(replp,1ull<<30,0,&repl));CasRemote cr={fs};QrxAuraDriveModelFetchContext dfc={0};dfc.local_cache=repl;dfc.stat=cas_stat;dfc.fetch_range=cas_range;dfc.remote_ctx=&cr;dfc.range_bytes=16;QrxAuraReplicationDriveTargetContext dt={&dfc,"replica-provider","replica-pod"};QrxAuraReplicationExecutionStats es={0};assert(!qrx_aura_model_repair_execute(&rp,&ca.manifest,1,qrx_aura_model_repair_drive_target_transfer,&dt,&es));assert(es.attempted==1&&es.succeeded==1&&!es.failed);assert(qrx_storage_fs_has(repl,ca.manifest.assets[rp.items[0].asset_index].content_root)==1);qrx_storage_fs_close(repl);
  uint8_t*sm=NULL;size_t smn=0;assert(!qrx_storage_fs_read(fs,out->source_map_root,&sm,&smn));QrxAuraOriginSourceMap*map=calloc(1,sizeof(*map));assert(map&&!qrx_aura_origin_source_map_decode(sm,smn,map));free(sm);char mat[1024];snprintf(mat,sizeof(mat),"%s/materialized",t);assert(!qrx_aura_origin_materialize(map,fs,mat));snprintf(p,sizeof(p),"%s/model-00001-of-00002.safetensors",mat);assert(access(p,R_OK)==0);
  free(idxp);free(cat);free(map);free(out);qrx_storage_fs_close(fs);puts("PASS: real-origin bootstrap resolves immutable HF revision, license and files; resumes/downloads into QRX CAS; maps MoE experts; builds Drive bundle/model registry; and materializes runtime files");return 0;}
