#include "resource/qrx_storage_market.h"
#include <limits.h>
#include <string.h>

static uint64_t muldiv_u64(uint64_t a,uint64_t b,uint64_t d){if(!d)return 0;uint64_t q=a/d,r=a%d;if(b&&q>UINT64_MAX/b)return UINT64_MAX;uint64_t x=q*b;uint64_t y=(r*b)/d;return UINT64_MAX-x<y?UINT64_MAX:x+y;}
static uint32_t clamp_bps(uint32_t v,uint32_t lo,uint32_t hi){return v<lo?lo:(v>hi?hi:v);}
void qrx_storage_reputation_init(QrxStorageProviderReputation *r){if(!r)return;memset(r,0,sizeof(*r));r->availability_bps=QRX_STORAGE_REPUTATION_INITIAL_BPS;r->proof_success_bps=QRX_STORAGE_REPUTATION_INITIAL_BPS;r->performance_bps=10000;r->reputation_bps=QRX_STORAGE_REPUTATION_INITIAL_BPS;}
int qrx_storage_reputation_record_proof(QrxStorageProviderReputation *r,int ok,uint32_t latency){if(!r||latency>20000)return -1;uint32_t sample=ok?10000:0;r->proof_success_bps=(uint32_t)(((uint64_t)r->proof_success_bps*15+sample)/16);r->availability_bps=(uint32_t)(((uint64_t)r->availability_bps*31+sample)/32);uint32_t lp=clamp_bps(latency,5000,11500);r->performance_bps=(uint32_t)(((uint64_t)r->performance_bps*15+lp)/16);if(ok)r->proofs_ok++;else r->proofs_failed++;uint64_t rep=(uint64_t)r->proof_success_bps*5+(uint64_t)r->availability_bps*3+(uint64_t)clamp_bps(r->performance_bps,5000,11500)*2;r->reputation_bps=(uint32_t)(rep/10);if(r->reputation_bps<QRX_STORAGE_REPUTATION_MIN_BPS)r->reputation_bps=QRX_STORAGE_REPUTATION_MIN_BPS;if(r->reputation_bps>10000)r->reputation_bps=10000;return 0;}
uint64_t qrx_storage_required_bond(uint64_t bytes){uint64_t w=qrx_resource_capacity_weight(bytes);if(w> (UINT64_MAX-QRX_STORAGE_BOND_BASE_ATOMS)/QRX_STORAGE_BOND_WEIGHT_ATOMS)return UINT64_MAX;return QRX_STORAGE_BOND_BASE_ATOMS+w*QRX_STORAGE_BOND_WEIGHT_ATOMS;}
int qrx_storage_bond_register(QrxStorageBondState *s,uint64_t cap,uint64_t bond){if(!s||!cap||bond<qrx_storage_required_bond(cap))return -1;memset(s,0,sizeof(*s));s->status=QRX_PROVIDER_REGISTERED;s->bond_atoms=bond;s->proven_capacity_bytes=cap;return 0;}
int qrx_storage_bond_activate(QrxStorageBondState *s){if(!s||s->status!=QRX_PROVIDER_REGISTERED||!s->bond_atoms)return -1;s->status=QRX_PROVIDER_ACTIVE;return 0;}
int qrx_storage_bond_begin_exit(QrxStorageBondState *s,uint64_t h){if(!s||s->status!=QRX_PROVIDER_ACTIVE)return -1;s->status=QRX_PROVIDER_EXITING;s->exit_height=h;return 0;}
int qrx_storage_bond_withdrawable(const QrxStorageBondState *s,uint64_t h){if(!s||s->status!=QRX_PROVIDER_EXITING||s->allocated_bytes)return 0;if(h<s->exit_height)return 0;return h-s->exit_height>=QRX_STORAGE_EXIT_DELAY_BLOCKS;}
int qrx_storage_bond_withdraw(QrxStorageBondState *s,uint64_t h,uint64_t *out){if(!s||!out||!qrx_storage_bond_withdrawable(s,h))return -1;*out=s->bond_atoms;s->bond_atoms=0;s->status=QRX_PROVIDER_WITHDRAWN;return 0;}
int qrx_storage_bond_slash(QrxStorageBondState *s,uint64_t atoms,uint64_t *out){if(!s||!out||!atoms||!s->bond_atoms)return -1;uint64_t x=atoms<s->bond_atoms?atoms:s->bond_atoms;s->bond_atoms-=x;*out=x;if(!s->bond_atoms)s->status=QRX_PROVIDER_SLASHED;return 0;}
int qrx_storage_financial_init(uint64_t atoms,QrxStorageFinancialState *o){if(!o||!atoms)return -1;QrxStorageContractSplit sp;if(qrx_storage_split_contract_value(atoms,QRX_STORAGE_DEV_SHARE_BPS,QRX_STORAGE_RESILIENCE_RESERVE_BPS,&sp)!=0)return -1;memset(o,0,sizeof(*o));o->original_atoms=atoms;o->development_atoms=sp.development_atoms;o->resilience_atoms=sp.resilience_atoms;o->provider_escrow_atoms=sp.provider_budget_atoms;return 0;}
uint64_t qrx_storage_provider_reward(const QrxStorageRewardInput *i){if(!i||!i->stored_bytes||!i->epochs||!i->base_atoms_per_gib_epoch||i->availability_bps>10000||i->proof_factor_bps>10000)return 0;uint32_t perf=clamp_bps(i->performance_bps,5000,11500);uint64_t gib_epochs=muldiv_u64(i->stored_bytes,i->epochs,1024ULL*1024ULL*1024ULL);if(!gib_epochs)gib_epochs=1;uint64_t x=muldiv_u64(gib_epochs,i->base_atoms_per_gib_epoch,1);x=muldiv_u64(x,i->availability_bps,10000);x=muldiv_u64(x,i->proof_factor_bps,10000);x=muldiv_u64(x,perf,10000);return x;}
int qrx_storage_financial_pay_provider(QrxStorageFinancialState *s,uint64_t a){if(!s||!a||a>s->provider_escrow_atoms-s->provider_paid_atoms)return -1;s->provider_paid_atoms+=a;return 0;}
int qrx_storage_financial_pay_repair(QrxStorageFinancialState *s,uint64_t a){if(!s||!a||a>s->resilience_atoms-s->repair_paid_atoms)return -1;s->repair_paid_atoms+=a;return 0;}
int qrx_storage_financial_pay_egress(QrxStorageFinancialState *s,uint64_t a){if(!s||!a||a>s->provider_escrow_atoms-s->provider_paid_atoms-s->egress_paid_atoms)return -1;s->egress_paid_atoms+=a;return 0;}
uint64_t qrx_storage_financial_refundable(const QrxStorageFinancialState *s){if(!s)return 0;uint64_t p=s->provider_escrow_atoms-s->provider_paid_atoms-s->egress_paid_atoms;uint64_t r=s->resilience_atoms-s->repair_paid_atoms;return UINT64_MAX-p<r?UINT64_MAX:p+r;}
