#include "resource/qrx_drive_live.h"
#include "resource/qrx_storage_consensus.h"
#include "resource/qrx_storage_repair.h"
#include "resource/qrx_resource_live.h"
#include "qrxdb.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef struct { QrxDB *db; const char *owner; QrxDriveFileSnapshot *v; size_t n,cap; int failed; } ListCtx;
typedef struct { QrxDB *db; const char *cid; QrxDriveFileSnapshot *f; QrxDriveShardRoute *routes; size_t n,cap; QrxStorageAtlasCell *cells; size_t cell_n; int failed; } AssignCtx;

static uint32_t required_for_profile(const char*p,uint32_t count){if(!p)return count;if(!strcmp(p,"STANDARD"))return count>=10?10:count;if(!strcmp(p,"FAST"))return count>=3?1:count;if(!strcmp(p,"ARCHIVE"))return count>=16?16:count;return count;}
static int grow_files(ListCtx*c){if(c->n<c->cap)return 0;size_t nc=c->cap?c->cap*2:8;void*p=realloc(c->v,nc*sizeof(*c->v));if(!p)return -1;c->v=p;c->cap=nc;return 0;}
static int grow_routes(AssignCtx*c){if(c->n<c->cap)return 0;size_t nc=c->cap?c->cap*2:16;void*p=realloc(c->routes,nc*sizeof(*c->routes));if(!p)return -1;c->routes=p;c->cap=nc;return 0;}
static const char *cid_from_key(const char*k){const char*pre="storage/contract/";return strncmp(k,pre,strlen(pre))?NULL:k+strlen(pre);}
static int count_assign_cb(const char*k,const char*v,uint32_t vl,void*ctx){(void)k;(void)v;(void)vl;AssignCtx*c=(AssignCtx*)ctx;const char*slash=strrchr(k,'/');if(!slash||!*++slash)return 0;uint32_t sh=(uint32_t)strtoul(slash,NULL,10);QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(c->db,c->cid,sh,&a))return 0;if(a.state==QRX_ASSIGN_ACTIVE)c->f->healthy_shards++;else if(a.state==QRX_ASSIGN_DEGRADED)c->f->degraded_shards++;else if(a.state==QRX_ASSIGN_REPAIRING)c->f->repairing_shards++;if(!c->f->first_object_id[0]&&a.object_id[0])snprintf(c->f->first_object_id,sizeof(c->f->first_object_id),"%s",a.object_id);return 0;}
static int fill_file(QrxDB*db,const char*cid,QrxDriveFileSnapshot*f){QrxStorageContractState c;if(qrx_storage_contract_get(db,cid,&c))return -1;memset(f,0,sizeof(*f));snprintf(f->contract_id,sizeof(f->contract_id),"%s",cid);snprintf(f->owner,sizeof(f->owner),"%s",c.owner);snprintf(f->profile,sizeof(f->profile),"%s",c.profile);f->logical_bytes=c.logical_bytes;f->shard_bytes=c.shard_bytes;f->shard_count=c.shard_count;f->required_shards=required_for_profile(c.profile,c.shard_count);f->start_height=c.start_height;f->end_height=c.end_height;f->status=(uint32_t)c.status;AssignCtx ac={0};ac.db=db;ac.cid=cid;ac.f=f;char pre[360];snprintf(pre,sizeof(pre),"storage/assignment/%s/",cid);if(qrxdb_scan_prefix(db,pre,count_assign_cb,&ac))return -1;uint32_t known=f->healthy_shards+f->degraded_shards+f->repairing_shards;f->missing_shards=f->shard_count>known?f->shard_count-known:0;return 0;}
static int list_cb(const char*k,const char*v,uint32_t vl,void*ctx){(void)v;(void)vl;ListCtx*c=(ListCtx*)ctx;const char*cid=cid_from_key(k);if(!cid||!*cid)return 0;QrxDriveFileSnapshot f;if(fill_file(c->db,cid,&f)){c->failed=1;return -1;}if(c->owner&&*c->owner&&strcmp(c->owner,f.owner))return 0;if(grow_files(c)){c->failed=1;return -1;}c->v[c->n++]=f;return 0;}
int qrx_drive_live_list(const char*chain_dir,const char*owner,QrxDriveFileSnapshot**out,size_t*outn){if(!chain_dir||!out||!outn)return -1;*out=NULL;*outn=0;QrxDB db;if(qrxdb_init(&db,chain_dir))return -1;ListCtx c={&db,owner,NULL,0,0,0};int rc=qrxdb_scan_prefix(&db,"storage/contract/",list_cb,&c);qrxdb_close(&db);if(rc||c.failed){free(c.v);return -1;}*out=c.v;*outn=c.n;return 0;}
static int region_public(AssignCtx*c,const char*region){if(!region||!*region)return 0;for(size_t i=0;i<c->cell_n;i++)if(!strcmp(c->cells[i].region,region))return c->cells[i].publicly_visible?1:0;return 0;}
static int route_cb(const char*k,const char*v,uint32_t vl,void*ctx){(void)v;(void)vl;AssignCtx*c=(AssignCtx*)ctx;const char*slash=strrchr(k,'/');if(!slash||!*++slash)return 0;uint32_t sh=(uint32_t)strtoul(slash,NULL,10);QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(c->db,c->cid,sh,&a))return 0;if(grow_routes(c)){c->failed=1;return -1;}QrxDriveShardRoute*r=&c->routes[c->n++];memset(r,0,sizeof(*r));r->shard_index=sh;r->state=a.state;r->physical_bytes=a.physical_bytes;snprintf(r->provider_id,sizeof(r->provider_id),"%s",a.provider_id);snprintf(r->object_id,sizeof(r->object_id),"%s",a.object_id);QrxStorageProviderState p;if(qrx_storage_provider_get(c->db,a.provider_id,&p)==0&&p.attested_region[0]&&strcmp(p.attested_region,"-")){r->region_public=(uint8_t)region_public(c,p.attested_region);if(r->region_public)snprintf(r->region,sizeof(r->region),"%s",p.attested_region);else snprintf(r->region,sizeof(r->region),"privacy-protected");}else snprintf(r->region,sizeof(r->region),"unattested");return 0;}
int qrx_drive_live_routes(const char*chain_dir,const char*cid,size_t privacy,QrxDriveShardRoute**out,size_t*outn,QrxDriveFileSnapshot*fout){if(!chain_dir||!cid||!*cid||!out||!outn)return -1;*out=NULL;*outn=0;QrxDB db;if(qrxdb_init(&db,chain_dir))return -1;QrxDriveFileSnapshot f;if(fill_file(&db,cid,&f)){qrxdb_close(&db);return -1;}QrxResourceDashboardSnapshot dash;QrxStorageAtlasCell*cells=NULL;size_t cn=0;if(qrx_resource_live_snapshot(chain_dir,privacy,&dash,&cells,&cn)){qrxdb_close(&db);return -1;}AssignCtx c={0};c.db=&db;c.cid=cid;c.f=&f;c.cells=cells;c.cell_n=cn;char pre[360];snprintf(pre,sizeof(pre),"storage/assignment/%s/",cid);int rc=qrxdb_scan_prefix(&db,pre,route_cb,&c);qrx_storage_atlas_free(cells);qrxdb_close(&db);if(rc||c.failed){free(c.routes);return -1;}if(fout)*fout=f;*out=c.routes;*outn=c.n;return 0;}
void qrx_drive_live_files_free(QrxDriveFileSnapshot*p){free(p);}void qrx_drive_live_routes_free(QrxDriveShardRoute*p){free(p);}
