#include "resource/qrx_storage_atlas.h"
#include <stdlib.h>
#include <string.h>
static uint32_t clamp(uint64_t v,uint32_t hi){return v>hi?hi:(uint32_t)v;}
uint32_t qrx_storage_network_health_score(const QrxStorageNetworkCapacity *n,uint32_t proof,uint32_t diversity){if(!n)return 0;if(proof>10000)proof=10000;if(diversity>10000)diversity=10000;uint32_t cap=n->resilience_headroom_bps>5000?10000:(uint32_t)((uint64_t)n->resilience_headroom_bps*2);uint32_t red=0;if(n->redundancy_x10000>=14000)red=10000;else red=clamp((uint64_t)n->redundancy_x10000*10000/14000,10000);uint64_t v=(uint64_t)cap*25+(uint64_t)red*25+(uint64_t)proof*25+(uint64_t)diversity*25;return (uint32_t)(v/10000);}
uint32_t qrx_storage_dynamic_demand_factor_bps(const QrxStorageNetworkCapacity *n){if(!n||!n->proven_bytes)return 15000;uint64_t util=n->utilization_bps,head=n->resilience_headroom_bps;int64_t factor=10000;factor+=(int64_t)util*5000/10000;factor-=(int64_t)head*2000/10000;if(factor<8000)factor=8000;if(factor>15000)factor=15000;return (uint32_t)factor;}
static int asn_seen(const QrxStorageAtlasProvider *p,size_t upto,const char *region,const char *asn){for(size_t i=0;i<upto;i++)if(p[i].network_attested&&!strcmp(p[i].region,region)&&!strcmp(p[i].asn,asn))return 1;return 0;}
int qrx_storage_atlas_build(const QrxStorageAtlasProvider *p,size_t n,size_t privacy,QrxStorageAtlasCell **out,size_t *on){if(!out||!on||(n&&!p))return -1;*out=NULL;*on=0;QrxStorageAtlasCell *c=calloc(n?n:1,sizeof(*c));if(!c)return -1;size_t cn=0;for(size_t i=0;i<n;i++){if(!p[i].network_attested||!p[i].region[0]||qrx_storage_provider_capacity_validate(&p[i].capacity)!=0)continue;size_t j=0;for(;j<cn;j++)if(!strcmp(c[j].region,p[i].region))break;if(j==cn){strncpy(c[j].region,p[i].region,QRX_ATLAS_REGION_MAX);cn++;}QrxStorageAtlasCell *x=&c[j];x->provider_count++;x->proven_bytes+=p[i].capacity.proven_bytes;x->allocated_bytes+=p[i].capacity.allocated_physical_bytes;x->avg_availability_bps+=p[i].capacity.availability_bps;x->avg_proof_success_bps+=p[i].capacity.proof_success_bps;if(p[i].asn[0]&&!asn_seen(p,i,p[i].region,p[i].asn))x->unique_asns++;}
    for(size_t j=0;j<cn;j++){QrxStorageAtlasCell *x=&c[j];x->free_bytes=x->proven_bytes>=x->allocated_bytes?x->proven_bytes-x->allocated_bytes:0;x->utilization_bps=x->proven_bytes?(uint32_t)((x->allocated_bytes/100?x->allocated_bytes/100*10000/x->proven_bytes:(x->allocated_bytes*10000)/x->proven_bytes)):0;if(x->provider_count){x->avg_availability_bps/=x->provider_count;x->avg_proof_success_bps/=x->provider_count;}x->publicly_visible=x->provider_count>=privacy;uint64_t scarcity=x->utilization_bps;uint64_t provider_need=x->provider_count>=10?0:(10-x->provider_count)*1000;uint64_t asn_need=x->unique_asns>=6?0:(6-x->unique_asns)*1000;uint64_t proof_penalty=10000-x->avg_proof_success_bps;uint64_t score=(scarcity*45+provider_need*25+asn_need*20+proof_penalty*10)/10000;if(score>100)score=100;x->opportunity_score=(uint32_t)score;x->diversity_bonus_bps=10000+(uint32_t)(score*20);if(x->diversity_bonus_bps>12000)x->diversity_bonus_bps=12000;}
    *out=c;*on=cn;return 0;}
void qrx_storage_atlas_free(QrxStorageAtlasCell *c){free(c);}
int qrx_storage_missions_from_atlas(const QrxStorageAtlasCell *c,size_t n,uint64_t tf,uint64_t tp,QrxStorageMission **out,size_t *on){if(!out||!on||(n&&!c))return -1;*out=NULL;*on=0;QrxStorageMission *m=calloc(n?n:1,sizeof(*m));if(!m)return -1;size_t z=0;for(size_t i=0;i<n;i++){uint64_t wb=c[i].free_bytes<tf?tf-c[i].free_bytes:0;uint64_t wp=c[i].provider_count<tp?tp-c[i].provider_count:0;if(!wb&&!wp)continue;strncpy(m[z].region,c[i].region,QRX_ATLAS_REGION_MAX);m[z].wanted_additional_bytes=wb;m[z].wanted_additional_providers=wp;m[z].opportunity_score=c[i].opportunity_score;m[z].incentive_factor_bps=10000+c[i].opportunity_score*20;if(m[z].incentive_factor_bps>12000)m[z].incentive_factor_bps=12000;z++;}*out=m;*on=z;return 0;}
void qrx_storage_missions_free(QrxStorageMission *m){free(m);}

int qrx_storage_public_missions_from_atlas(const QrxStorageAtlasCell *c,size_t n,uint64_t tf,uint64_t tp,QrxStorageMission **out,size_t *on){
    if(!out||!on||(n&&!c))return -1; *out=NULL; *on=0;
    QrxStorageAtlasCell *visible=(QrxStorageAtlasCell*)calloc(n?n:1,sizeof(*visible)); if(!visible)return -1;
    size_t vn=0; for(size_t i=0;i<n;i++) if(c[i].publicly_visible) visible[vn++]=c[i];
    int rc=qrx_storage_missions_from_atlas(visible,vn,tf,tp,out,on); free(visible); return rc;
}
