#include "resource/qrx_storage_consensus.h"
#include "resource/qrx_capacity_proof.h"
#include "resource/qrx_resource.h"
#include "resource/qrx_storage_market.h"
#include "resource/qrx_storage_placement.h"
#include "resource/qrx_storage_repair.h"
#include "storage/qrx_postor.h"
#include <openssl/crypto.h>
#include <openssl/pem.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PROVIDER_PREFIX "storage/provider/"
#define CONTRACT_PREFIX "storage/contract/"
#define ASSIGN_PREFIX "storage/assignment/"
#define CAPACITY_PREFIX "storage/capacity/"
#define REPAIR_PREFIX "storage/repair/"
#define ATTEST_PREFIX "storage/attest/"

static int safe_token(const char *s,size_t max){if(!s||!*s||strlen(s)>=max)return 0;for(const unsigned char*p=(const unsigned char*)s;*p;p++)if(*p=='|'||*p==';'||*p=='\n'||*p=='\r'||*p<32)return 0;return 1;}
static char *field(const char *payload,const char *key){if(!payload||!key)return NULL;size_t k=strlen(key);const char*p=payload;while(*p){while(*p==';')p++;const char*e=strchr(p,';');size_t n=e?(size_t)(e-p):strlen(p);if(n>k&&!memcmp(p,key,k)&&p[k]=='='){char*v=malloc(n-k);if(!v)return NULL;memcpy(v,p+k+1,n-k-1);v[n-k-1]=0;return v;}if(!e)break;p=e+1;}return NULL;}
static int parse_u64(const char*s,uint64_t*out){if(!s||!*s||!out)return -1;char*e=NULL;unsigned long long v=strtoull(s,&e,10);if(!e||*e)return -1;*out=(uint64_t)v;return 0;}
static int parse_u32(const char*s,uint32_t*out){uint64_t v=0;if(parse_u64(s,&v)||v>UINT32_MAX)return -1;*out=(uint32_t)v;return 0;}
static int hexv(char c){return c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:c>='A'&&c<='F'?c-'A'+10:-1;}
static int unhex(const char*s,uint8_t*out,size_t n){if(!s||strlen(s)!=n*2)return -1;for(size_t i=0;i<n;i++){int a=hexv(s[i*2]),b=hexv(s[i*2+1]);if(a<0||b<0)return -1;out[i]=(uint8_t)((a<<4)|b);}return 0;}
static void hex64(const uint8_t in[64],char out[129]){static const char h[]="0123456789abcdef";for(int i=0;i<64;i++){out[i*2]=h[in[i]>>4];out[i*2+1]=h[in[i]&15];}out[128]=0;}
static int db_u64(QrxDB*db,const char*k,uint64_t def,uint64_t*out){char b[128];if(!db||!k||!out)return -1;if(qrxdb_get(db,k,b,sizeof(b))){*out=def;return 0;}return parse_u64(b,out);}
static int batch_u64(QrxDBBatch*b,const char*k,uint64_t v){char s[64];snprintf(s,sizeof(s),"%llu",(unsigned long long)v);return qrxdb_batch_put(b,k,s);}
static int pool_adjust(QrxDB*db,QrxDBBatch*b,const char*k,int64_t delta){uint64_t old=0;if(db_u64(db,k,0,&old))return -1;if(delta<0){uint64_t d=(uint64_t)(-delta);if(old<d)return -1;return batch_u64(b,k,old-d);}uint64_t d=(uint64_t)delta;if(UINT64_MAX-old<d)return -1;return batch_u64(b,k,old+d);}

static EVP_PKEY *provider_key_from_b64(const char *b64){
    if(!b64||!*b64)return NULL; size_t n=strlen(b64); if(n>16384)return NULL;
    unsigned char *buf=malloc(n+4); if(!buf)return NULL; int z=EVP_DecodeBlock(buf,(const unsigned char*)b64,(int)n);
    if(z<=0){free(buf);return NULL;} while(n&&b64[n-1]=='='){z--;n--;}
    BIO *bio=BIO_new_mem_buf(buf,z); EVP_PKEY *k=bio?PEM_read_bio_PUBKEY(bio,NULL,NULL,NULL):NULL; BIO_free(bio); free(buf); return k;
}
int qrx_storage_provider_discovery_key_lookup(void *ctx,const char *provider_id,EVP_PKEY **out){
    if(!ctx||!provider_id||!out||!safe_token(provider_id,129))return -1; *out=NULL; char key[320],b64[16384];
    snprintf(key,sizeof(key),"storage/provider-key/%s",provider_id); if(qrxdb_get((QrxDB*)ctx,key,b64,sizeof(b64)))return -1;
    EVP_PKEY *k=provider_key_from_b64(b64); if(!k)return -1; const char *name=EVP_PKEY_get0_type_name(k);
    if(!name||strcmp(name,"ML-DSA-65")){EVP_PKEY_free(k);return -1;} *out=k; return 0;
}

static int key_provider(const char*id,char out[300]){if(!safe_token(id,129))return -1;snprintf(out,300,PROVIDER_PREFIX"%s",id);return 0;}
static int key_contract(const char*id,char out[300]){if(!safe_token(id,129))return -1;snprintf(out,300,CONTRACT_PREFIX"%s",id);return 0;}
static int key_assign(const char*cid,uint32_t shard,char out[360]){if(!safe_token(cid,129))return -1;snprintf(out,360,ASSIGN_PREFIX"%s/%010u",cid,shard);return 0;}

static int provider_encode(const QrxStorageProviderState*p,char*out,size_t n){int z=snprintf(out,n,"1|%s|%u|%llu|%llu|%llu|%llu|%u|%u|%u|%u|%s|%s|%s|%s|%s|%llu",p->owner,p->status,(unsigned long long)p->bond_atoms,(unsigned long long)p->proven_capacity_bytes,(unsigned long long)p->allocated_bytes,(unsigned long long)p->exit_height,p->availability_bps,p->proof_success_bps,p->performance_bps,p->reputation_bps,p->operator_id[0]?p->operator_id:"-",p->claimed_asn[0]?p->claimed_asn:"-",p->claimed_region[0]?p->claimed_region:"-",p->attested_asn[0]?p->attested_asn:"-",p->attested_region[0]?p->attested_region:"-",(unsigned long long)p->attestation_epoch);return z>0&&(size_t)z<n?0:-1;}
static int provider_decode(const char*v,QrxStorageProviderState*p){if(!v||!p)return -1;char*t=strdup(v);if(!t)return -1;char*s=NULL,*a[17];int n=0;for(char*x=strtok_r(t,"|",&s);x&&n<17;x=strtok_r(NULL,"|",&s))a[n++]=x;if(n!=17||strcmp(a[0],"1")){free(t);return -1;}memset(p,0,sizeof(*p));if(!safe_token(a[1],160)||strlen(a[11])>=129||strlen(a[12])>=64||strlen(a[13])>=96||strlen(a[14])>=64||strlen(a[15])>=96){free(t);return -1;}strcpy(p->owner,a[1]);p->status=(uint32_t)strtoul(a[2],NULL,10);p->bond_atoms=strtoull(a[3],NULL,10);p->proven_capacity_bytes=strtoull(a[4],NULL,10);p->allocated_bytes=strtoull(a[5],NULL,10);p->exit_height=strtoull(a[6],NULL,10);p->availability_bps=(uint32_t)strtoul(a[7],NULL,10);p->proof_success_bps=(uint32_t)strtoul(a[8],NULL,10);p->performance_bps=(uint32_t)strtoul(a[9],NULL,10);p->reputation_bps=(uint32_t)strtoul(a[10],NULL,10);if(strcmp(a[11],"-"))strcpy(p->operator_id,a[11]);if(strcmp(a[12],"-"))strcpy(p->claimed_asn,a[12]);if(strcmp(a[13],"-"))strcpy(p->claimed_region,a[13]);if(strcmp(a[14],"-"))strcpy(p->attested_asn,a[14]);if(strcmp(a[15],"-"))strcpy(p->attested_region,a[15]);p->attestation_epoch=strtoull(a[16],NULL,10);free(t);return 0;}
int qrx_storage_provider_get(QrxDB*db,const char*id,QrxStorageProviderState*out){char k[300],v[1400];if(!db||!out||key_provider(id,k)||qrxdb_get(db,k,v,sizeof(v)))return -1;return provider_decode(v,out);}
static int provider_put(QrxDBBatch*b,const char*id,const QrxStorageProviderState*p){char k[300],v[1400];if(key_provider(id,k)||provider_encode(p,v,sizeof(v)))return -1;return qrxdb_batch_put(b,k,v);}

static int contract_encode(const QrxStorageContractState*c,char*out,size_t n){char mh[129];hex64(c->manifest_root,mh);int z=snprintf(out,n,"1|%s|%s|%llu|%llu|%u|%llu|%llu|%llu|%llu|%llu|%llu|%llu|%llu|%llu|%llu|%s|%u",c->owner,c->profile,(unsigned long long)c->logical_bytes,(unsigned long long)c->shard_bytes,c->shard_count,(unsigned long long)c->start_height,(unsigned long long)c->end_height,(unsigned long long)c->original_atoms,(unsigned long long)c->development_atoms,(unsigned long long)c->resilience_atoms,(unsigned long long)c->provider_escrow_atoms,(unsigned long long)c->provider_paid_atoms,(unsigned long long)c->repair_paid_atoms,(unsigned long long)c->egress_paid_atoms,(unsigned long long)c->base_atoms_per_gib_epoch,mh,c->status);return z>0&&(size_t)z<n?0:-1;}
static int contract_decode(const char*v,QrxStorageContractState*c){if(!v||!c)return -1;char*t=strdup(v);if(!t)return -1;char*s=NULL,*a[18];int n=0;for(char*x=strtok_r(t,"|",&s);x&&n<18;x=strtok_r(NULL,"|",&s))a[n++]=x;if(n!=18||strcmp(a[0],"1")||!safe_token(a[1],160)||strlen(a[2])>=16){free(t);return -1;}memset(c,0,sizeof(*c));strcpy(c->owner,a[1]);strcpy(c->profile,a[2]);c->logical_bytes=strtoull(a[3],NULL,10);c->shard_bytes=strtoull(a[4],NULL,10);c->shard_count=(uint32_t)strtoul(a[5],NULL,10);c->start_height=strtoull(a[6],NULL,10);c->end_height=strtoull(a[7],NULL,10);c->original_atoms=strtoull(a[8],NULL,10);c->development_atoms=strtoull(a[9],NULL,10);c->resilience_atoms=strtoull(a[10],NULL,10);c->provider_escrow_atoms=strtoull(a[11],NULL,10);c->provider_paid_atoms=strtoull(a[12],NULL,10);c->repair_paid_atoms=strtoull(a[13],NULL,10);c->egress_paid_atoms=strtoull(a[14],NULL,10);c->base_atoms_per_gib_epoch=strtoull(a[15],NULL,10);if(unhex(a[16],c->manifest_root,64)){free(t);return -1;}c->status=(QrxStorageContractStatus)strtoul(a[17],NULL,10);free(t);return 0;}
int qrx_storage_contract_get(QrxDB*db,const char*id,QrxStorageContractState*out){char k[300],v[1800];if(!db||!out||key_contract(id,k)||qrxdb_get(db,k,v,sizeof(v)))return -1;return contract_decode(v,out);}
static int contract_put(QrxDBBatch*b,const char*id,const QrxStorageContractState*c){char k[300],v[1800];if(key_contract(id,k)||contract_encode(c,v,sizeof(v)))return -1;return qrxdb_batch_put(b,k,v);}

static int assign_encode(const QrxStorageAssignmentRecord*a,char*out,size_t n){char rh[129];hex64(a->merkle_root,rh);int z=snprintf(out,n,"1|%s|%u|%llu|%s|%s|%llu|%llu|%llu|%llu|%llu",a->provider_id,a->state,(unsigned long long)a->physical_bytes,a->object_id,rh,(unsigned long long)a->leaf_count,(unsigned long long)a->accepted_height,(unsigned long long)a->last_proof_epoch,(unsigned long long)a->last_proof_height,(unsigned long long)a->last_settled_epoch);return z>0&&(size_t)z<n?0:-1;}
static int assign_decode(const char*v,QrxStorageAssignmentRecord*a){if(!v||!a)return -1;char*t=strdup(v);if(!t)return -1;char*s=NULL,*p[11];int n=0;for(char*x=strtok_r(t,"|",&s);x&&n<11;x=strtok_r(NULL,"|",&s))p[n++]=x;if(n!=11||strcmp(p[0],"1")||strlen(p[1])>=129||strlen(p[4])!=64){free(t);return -1;}memset(a,0,sizeof(*a));strcpy(a->provider_id,p[1]);a->state=(uint32_t)strtoul(p[2],NULL,10);a->physical_bytes=strtoull(p[3],NULL,10);strcpy(a->object_id,p[4]);if(unhex(p[5],a->merkle_root,64)){free(t);return -1;}a->leaf_count=strtoull(p[6],NULL,10);a->accepted_height=strtoull(p[7],NULL,10);a->last_proof_epoch=strtoull(p[8],NULL,10);a->last_proof_height=strtoull(p[9],NULL,10);a->last_settled_epoch=strtoull(p[10],NULL,10);free(t);return 0;}
int qrx_storage_assignment_get(QrxDB*db,const char*cid,uint32_t shard,QrxStorageAssignmentRecord*out){char k[360],v[1200];if(!db||!out||key_assign(cid,shard,k)||qrxdb_get(db,k,v,sizeof(v)))return -1;return assign_decode(v,out);}
int qrx_storage_repair_get(QrxDB*db,const char*cid,uint32_t shard,QrxStorageRepairRecord*out){
    if(!db||!cid||!out||!safe_token(cid,129))return -1;char k[400],v[900];snprintf(k,sizeof(k),REPAIR_PREFIX"%s/%010u",cid,shard);if(qrxdb_get(db,k,v,sizeof(v)))return -1;
    char*t=strdup(v),*sv=NULL,*a[10];int n=0;if(!t)return -1;for(char*x=strtok_r(t,"|",&sv);x&&n<10;x=strtok_r(NULL,"|",&sv))a[n++]=x;
    if(n!=10||strcmp(a[0],"1")||strlen(a[1])>=129||strlen(a[2])>=129||strlen(a[6])!=64||strlen(a[7])!=128){free(t);return -1;}
    memset(out,0,sizeof(*out));snprintf(out->old_provider_id,sizeof(out->old_provider_id),"%s",a[1]);snprintf(out->replacement_provider_id,sizeof(out->replacement_provider_id),"%s",a[2]);out->state=(uint32_t)strtoul(a[3],NULL,10);out->start_height=strtoull(a[4],NULL,10);out->physical_bytes=strtoull(a[5],NULL,10);snprintf(out->object_id,sizeof(out->object_id),"%s",a[6]);if(unhex(a[7],out->merkle_root,64)){free(t);return -1;}out->leaf_count=strtoull(a[8],NULL,10);out->accepted_height=strtoull(a[9],NULL,10);free(t);return 0;
}
static int assign_put(QrxDBBatch*b,const char*cid,uint32_t shard,const QrxStorageAssignmentRecord*a){char k[360],v[1200];if(key_assign(cid,shard,k)||assign_encode(a,v,sizeof(v)))return -1;return qrxdb_batch_put(b,k,v);}

static int block_hash_at(QrxDB*db,uint64_t h,uint8_t out[64]){char x[160];if(qrxdb_chain_get_block_hash_by_height(db,h,x,sizeof(x)))return -1;return unhex(x,out,64);}
static int parse_merkle_proof(const char*siblings,uint64_t leaf_index,uint64_t leaf_count,QrxMerkleProof*out){if(!out||!leaf_count)return -1;memset(out,0,sizeof(*out));out->leaf_index=leaf_index;out->leaf_count=leaf_count;if(!siblings||!*siblings||!strcmp(siblings,"-")){out->depth=0;return leaf_count==1?0:-1;}size_t n=strlen(siblings);if(n%128)return -1;size_t d=n/128;if(d>QRX_MERKLE_MAX_DEPTH)return -1;out->depth=(uint32_t)d;for(size_t i=0;i<d;i++){char x[129];memcpy(x,siblings+i*128,128);x[128]=0;if(unhex(x,out->siblings[i],64))return -1;}return 0;}

typedef struct {QrxStoragePlacementCandidate *v;size_t n,cap;QrxDB*db;} CandCtx;
static int candidate_cb(const char*k,const char*v,uint32_t vl,void*ctxp){(void)vl;CandCtx*c=ctxp;QrxStorageProviderState p;if(strncmp(k,PROVIDER_PREFIX,strlen(PROVIDER_PREFIX))||provider_decode(v,&p))return 0;if(p.status!=QRX_PROVIDER_ACTIVE||p.proven_capacity_bytes<=p.allocated_bytes)return 0;if(c->n==c->cap){size_t nc=c->cap?c->cap*2:16;void*np=realloc(c->v,nc*sizeof(*c->v));if(!np)return -1;c->v=np;c->cap=nc;}QrxStoragePlacementCandidate*x=&c->v[c->n++];memset(x,0,sizeof(*x));snprintf(x->provider_id,sizeof(x->provider_id),"%s",k+strlen(PROVIDER_PREFIX));snprintf(x->operator_id,sizeof(x->operator_id),"%.96s",p.operator_id[0]?p.operator_id:x->provider_id);snprintf(x->asn,sizeof(x->asn),"%s",p.attested_asn[0]?p.attested_asn:p.claimed_asn);snprintf(x->region,sizeof(x->region),"%s",p.attested_region[0]?p.attested_region:p.claimed_region);x->failure_domain_attested=p.attested_asn[0]&&p.attested_region[0];x->proven_free_bytes=p.proven_capacity_bytes-p.allocated_bytes;x->bond_atoms=p.bond_atoms;x->availability_bps=p.availability_bps;x->proof_success_bps=p.proof_success_bps;x->performance_bps=p.performance_bps;x->price_atoms_per_gib_epoch=1;x->active=1;return 0;}
typedef struct{const char*cid;char **providers,**operators,**asns,**regions;size_t n,cap;QrxDB*db;} ExCtx;
static int exclusions_cb(const char*k,const char*v,uint32_t vl,void*ctxp){(void)k;(void)vl;ExCtx*c=ctxp;QrxStorageAssignmentRecord a;if(assign_decode(v,&a)||a.state==QRX_ASSIGN_REPLACED)return 0;if(c->n==c->cap){size_t nc=c->cap?c->cap*2:16;char**p=realloc(c->providers,nc*sizeof(char*));char**o=realloc(c->operators,nc*sizeof(char*));char**as=realloc(c->asns,nc*sizeof(char*));char**r=realloc(c->regions,nc*sizeof(char*));if(!p||!o||!as||!r){free(p);free(o);free(as);free(r);return -1;}c->providers=p;c->operators=o;c->asns=as;c->regions=r;c->cap=nc;}c->providers[c->n]=strdup(a.provider_id);QrxStorageProviderState ps;if(qrx_storage_provider_get(c->db,a.provider_id,&ps)==0){c->operators[c->n]=strdup(ps.operator_id[0]?ps.operator_id:a.provider_id);c->asns[c->n]=strdup(ps.attested_asn);c->regions[c->n]=strdup(ps.attested_region);}else{c->operators[c->n]=strdup(a.provider_id);c->asns[c->n]=strdup("");c->regions[c->n]=strdup("");}if(!c->providers[c->n]||!c->operators[c->n]||!c->asns[c->n]||!c->regions[c->n])return -1;c->n++;return 0;}
static void exclusions_free(ExCtx*c){if(!c)return;for(size_t i=0;i<c->n;i++){free(c->providers[i]);free(c->operators[i]);free(c->asns[i]);free(c->regions[i]);}free(c->providers);free(c->operators);free(c->asns);free(c->regions);memset(c,0,sizeof(*c));}
static int deterministic_provider_seed(QrxDB*db,const char*cid,uint64_t bytes,uint64_t seed_height,char out[129]){CandCtx cc={0};cc.db=db;if(qrxdb_scan_prefix(db,PROVIDER_PREFIX,candidate_cb,&cc)||!cc.n){free(cc.v);return -1;}char pre[360];snprintf(pre,sizeof(pre),ASSIGN_PREFIX"%s/",cid);ExCtx ex={0};ex.cid=cid;ex.db=db;if(qrxdb_scan_prefix(db,pre,exclusions_cb,&ex)){free(cc.v);exclusions_free(&ex);return -1;}const char **pp=(const char**)ex.providers,**oo=(const char**)ex.operators,**aa=(const char**)ex.asns,**rr=(const char**)ex.regions;QrxStoragePlacementExclusions x={pp,ex.n,oo,ex.n,aa,ex.n,rr,ex.n};uint8_t rnd[64];if(block_hash_at(db,seed_height,rnd)){free(cc.v);exclusions_free(&ex);return -1;}size_t idx=0;int rc=qrx_storage_select_provider(cc.v,cc.n,&x,bytes,1,rnd,&idx);if(!rc)snprintf(out,129,"%s",cc.v[idx].provider_id);free(cc.v);exclusions_free(&ex);return rc;}

static int capacity_get(QrxDB*db,const char*pid,QrxCapacityCommitment*c,uint64_t*commit_h,int*verified){char k[300],v[1000];snprintf(k,sizeof(k),CAPACITY_PREFIX"%s",pid);if(qrxdb_get(db,k,v,sizeof(v)))return -1;char*t=strdup(v),*s=NULL,*a[8];int n=0;for(char*x=strtok_r(t,"|",&s);x&&n<8;x=strtok_r(NULL,"|",&s))a[n++]=x;if(n!=8||strcmp(a[0],"1")){free(t);return -1;}memset(c,0,sizeof(*c));c->version=1;snprintf(c->provider_id,sizeof(c->provider_id),"%s",pid);c->epoch=strtoull(a[1],NULL,10);c->slot_count=strtoull(a[2],NULL,10);c->slot_bytes=(uint32_t)strtoul(a[3],NULL,10);if(unhex(a[4],c->merkle_root,64)){free(t);return -1;}if(commit_h)*commit_h=strtoull(a[5],NULL,10);if(verified)*verified=atoi(a[6]);free(t);return 0;}
static int capacity_put(QrxDBBatch*b,const QrxCapacityCommitment*c,uint64_t h,int verified){char k[300],v[1000],rh[129];hex64(c->merkle_root,rh);snprintf(k,sizeof(k),CAPACITY_PREFIX"%s",c->provider_id);snprintf(v,sizeof(v),"1|%llu|%llu|%u|%s|%llu|%d|-",(unsigned long long)c->epoch,(unsigned long long)c->slot_count,c->slot_bytes,rh,(unsigned long long)h,verified);return qrxdb_batch_put(b,k,v);}

static int contract_shard_layout(const char*profile,uint64_t logical,uint64_t*shard_bytes,uint32_t*count){const QrxStorageRedundancyProfile*p=qrx_storage_profile_by_name(profile);if(!p||!logical||!shard_bytes||!count)return -1;if(p->full_replicas){*shard_bytes=logical;*count=p->full_replicas;return 0;}if(!p->data_shards||p->data_shards+p->parity_shards>UINT32_MAX)return -1;*shard_bytes=(logical+p->data_shards-1)/p->data_shards;*count=p->data_shards+p->parity_shards;return 0;}

static int verify_assignment_postor(QrxDB*db,const char*cid,uint32_t shard,const char*provider,const char*payload,uint64_t height,uint64_t*epoch_out){QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(db,cid,shard,&a)||strcmp(a.provider_id,provider)||(a.state!=QRX_ASSIGN_ACTIVE&&a.state!=QRX_ASSIGN_REPAIRING)||!a.accepted_height||!a.leaf_count)return -1;char*ep=field(payload,"epoch"),*ch=field(payload,"challenge_height"),*leafh=field(payload,"revealed_leaf_hex"),*sib=field(payload,"siblings_hex");uint64_t epoch=0,challenge_h=0;int rc=-1;uint64_t base_h=a.last_proof_height?a.last_proof_height:a.accepted_height;uint64_t expected_h=base_h+QRX_STORAGE_PROOF_WINDOW_BLOCKS;uint64_t expected_epoch=a.last_proof_epoch+1;if(parse_u64(ep,&epoch)||parse_u64(ch,&challenge_h)||epoch!=expected_epoch||challenge_h!=expected_h||challenge_h<=a.accepted_height||challenge_h>height||!leafh)goto done;size_t ln=strlen(leafh);if(ln%2||ln/2>1024*1024)goto done;uint8_t*leaf=malloc(ln/2?ln/2:1);if(!leaf)goto done;for(size_t i=0;i<ln/2;i++){int x=hexv(leafh[i*2]),y=hexv(leafh[i*2+1]);if(x<0||y<0){free(leaf);goto done;}leaf[i]=(uint8_t)((x<<4)|y);}uint8_t bh[64];if(block_hash_at(db,challenge_h,bh)){free(leaf);goto done;}QrxPoStorChallenge c;if(qrx_postor_derive_challenge(cid,provider,shard,epoch,a.leaf_count,bh,&c)){free(leaf);goto done;}QrxMerkleProof proof;if(parse_merkle_proof(sib,c.leaf_index,a.leaf_count,&proof)){free(leaf);goto done;}rc=qrx_postor_verify(&c,leaf,ln/2,&proof,a.merkle_root);free(leaf);if(!rc&&epoch_out)*epoch_out=epoch;done:free(ep);free(ch);free(leafh);free(sib);return rc;}

typedef struct { const char *pid; int found; } ProviderAssignmentFindCtx;
static int provider_assignment_find_cb(const char*k,const char*v,uint32_t l,void*x){(void)k;(void)l;ProviderAssignmentFindCtx*c=(ProviderAssignmentFindCtx*)x;QrxStorageAssignmentRecord a;if(!assign_decode(v,&a)&&!strcmp(a.provider_id,c->pid)&&a.state!=QRX_ASSIGN_REPLACED)c->found=1;return 0;}
static int provider_has_contract_assignment(QrxDB*db,const char*cid,const char*pid){char pre[360];snprintf(pre,sizeof(pre),ASSIGN_PREFIX"%s/",cid);ProviderAssignmentFindCtx c={pid,0};qrxdb_scan_prefix(db,pre,provider_assignment_find_cb,&c);return c.found;}

static int prepare_with_db(QrxDB*db,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,const char*txid,uint64_t h,QrxServiceEconomicEffect*e){(void)txid;memset(e,0,sizeof(*e));
    if(!strcmp(tx,"STORAGE_CAPACITY_COMMIT")){if(amount||strcmp(from,to))return -1;char*sc=field(p,"slot_count"),*sb=field(p,"slot_bytes"),*rh=field(p,"merkle_root_hex");uint64_t slots=0;uint32_t bytes=0;QrxCapacityCommitment old;int ok=capacity_get(db,from,&old,NULL,NULL)==0;int rc=parse_u64(sc,&slots)||parse_u32(sb,&bytes)||!slots||!bytes||bytes>1024*1024||!rh||strlen(rh)!=128||ok?-1:0;free(sc);free(sb);free(rh);return rc;}
    if(!strcmp(tx,"STORAGE_CAPACITY_PROVE")){if(amount||strcmp(from,to))return -1;QrxCapacityCommitment c;uint64_t commit_h=0;int verified=0;if(capacity_get(db,from,&c,&commit_h,&verified)||verified)return -1;char*ch=field(p,"challenge_height"),*leaf=field(p,"revealed_slot_hex"),*sib=field(p,"siblings_hex");uint64_t challenge_h=0;int rc=-1;if(parse_u64(ch,&challenge_h)||challenge_h<=commit_h||challenge_h>h||!leaf||strlen(leaf)!=(size_t)c.slot_bytes*2)goto capdone;uint8_t*slot=malloc(c.slot_bytes);if(!slot)goto capdone;for(uint32_t i=0;i<c.slot_bytes;i++){int x=hexv(leaf[i*2]),y=hexv(leaf[i*2+1]);if(x<0||y<0){free(slot);goto capdone;}slot[i]=(uint8_t)((x<<4)|y);}uint8_t bh[64];if(block_hash_at(db,challenge_h,bh)){free(slot);goto capdone;}uint64_t idx=qrx_capacity_challenge_index(&c,bh);QrxCapacityChallengeProof pr;memset(&pr,0,sizeof(pr));pr.slot_index=idx;if(parse_merkle_proof(sib,idx,c.slot_count,&pr.merkle_proof)){free(slot);goto capdone;}rc=qrx_capacity_verify_challenge(&c,bh,slot,c.slot_bytes,&pr);free(slot);capdone:free(ch);free(leaf);free(sib);return rc;}
    if(!strcmp(tx,"STORAGE_PROVIDER_BOND")){if(!amount||strcmp(from,to))return -1;QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps)==0)return -1;QrxCapacityCommitment c;int verified=0;if(capacity_get(db,from,&c,NULL,&verified)||!verified)return -1;if(c.slot_count>UINT64_MAX/c.slot_bytes)return -1;uint64_t cap=c.slot_count*c.slot_bytes;if(amount<qrx_storage_required_bond(cap))return -1;e->debit_atoms=amount;return 0;}
    if(!strcmp(tx,"STORAGE_PROVIDER_BIND_DISCOVERY_KEY")){if(amount||strcmp(from,to))return -1;QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps)||ps.status==QRX_PROVIDER_WITHDRAWN||ps.status==QRX_PROVIDER_SLASHED)return -1;char*kb=field(p,"public_key_pem_b64");EVP_PKEY*k=provider_key_from_b64(kb);int rc=-1;if(k){const char*n=EVP_PKEY_get0_type_name(k);if(n&&!strcmp(n,"ML-DSA-65"))rc=0;}EVP_PKEY_free(k);free(kb);return rc;}
    if(!strcmp(tx,"STORAGE_PROVIDER_ACTIVATE")){if(amount||strcmp(from,to))return -1;QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps)||ps.status!=QRX_PROVIDER_REGISTERED)return -1;return 0;}
    if(!strcmp(tx,"STORAGE_PROVIDER_EXIT")){if(amount||strcmp(from,to))return -1;QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps)||ps.status!=QRX_PROVIDER_ACTIVE)return -1;return 0;}
    if(!strcmp(tx,"STORAGE_PROVIDER_WITHDRAW")){if(amount||strcmp(from,to))return -1;QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps)||ps.status!=QRX_PROVIDER_EXITING||ps.allocated_bytes||h<ps.exit_height||h-ps.exit_height<QRX_STORAGE_EXIT_DELAY_BLOCKS)return -1;e->self_credit_atoms=ps.bond_atoms;return ps.bond_atoms?0:-1;}
    if(!strcmp(tx,"STORAGE_CONTRACT_CREATE")){if(!amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id"),*prof=field(p,"profile"),*lb=field(p,"logical_bytes"),*eh=field(p,"end_height"),*br=field(p,"base_atoms_per_gib_epoch"),*mh=field(p,"manifest_root_hex");uint64_t logical=0,end=0,rate=0,sb=0;uint32_t sc=0;QrxStorageContractState old;int rc=-1;if(!cid||!safe_token(cid,129)||qrx_storage_contract_get(db,cid,&old)==0||!prof||parse_u64(lb,&logical)||parse_u64(eh,&end)||parse_u64(br,&rate)||!rate||end<=h||!mh||strlen(mh)!=128||contract_shard_layout(prof,logical,&sb,&sc))goto cdone;e->debit_atoms=amount;{QrxStorageContractSplit sp;if(qrx_storage_split_contract_value(amount,QRX_STORAGE_DEV_SHARE_BPS,QRX_STORAGE_RESILIENCE_RESERVE_BPS,&sp))goto cdone;e->development_credit_atoms=sp.development_atoms;}rc=0;cdone:free(cid);free(prof);free(lb);free(eh);free(br);free(mh);return rc;}
    if(!strcmp(tx,"STORAGE_CONTRACT_COMPLETE")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id");QrxStorageContractState c;int rc=cid&&!qrx_storage_contract_get(db,cid,&c)&&!strcmp(c.owner,from)&&c.status==QRX_STORAGE_CONTRACT_ACTIVE&&h>=c.end_height?0:-1;free(cid);return rc;}
    if(!strcmp(tx,"STORAGE_CONTRACT_REFUND")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id");QrxStorageContractState c;int rc=-1;if(cid&&!qrx_storage_contract_get(db,cid,&c)&&!strcmp(c.owner,from)&&c.status==QRX_STORAGE_CONTRACT_COMPLETE){uint64_t pr=c.provider_escrow_atoms-c.provider_paid_atoms-c.egress_paid_atoms,rr=c.resilience_atoms-c.repair_paid_atoms;if(UINT64_MAX-pr>=rr){e->self_credit_atoms=pr+rr;rc=0;}}free(cid);return rc;}
    if(!strcmp(tx,"STORAGE_ASSIGN")){if(amount)return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index"),*oid=field(p,"object_id"),*rh=field(p,"merkle_root_hex"),*lc=field(p,"leaf_count");uint32_t shard=0;uint64_t leaves=0;QrxStorageContractState c;QrxStorageAssignmentRecord a;int rc=-1;if(!cid||qrx_storage_contract_get(db,cid,&c)||strcmp(c.owner,from)||c.status!=QRX_STORAGE_CONTRACT_ACTIVE||parse_u32(sh,&shard)||shard>=c.shard_count||qrx_storage_assignment_get(db,cid,shard,&a)==0||!oid||strlen(oid)!=64||!rh||strlen(rh)!=128||parse_u64(lc,&leaves)||!leaves)goto adone;char selected[129];if(deterministic_provider_seed(db,cid,c.shard_bytes,h?h-1:0,selected)||strcmp(to,selected))goto adone;rc=0;adone:free(cid);free(sh);free(oid);free(rh);free(lc);return rc;}
    if(!strcmp(tx,"STORAGE_ASSIGN_ACCEPT")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;QrxStorageAssignmentRecord a;int rc=cid&&!parse_u32(sh,&shard)&&!qrx_storage_assignment_get(db,cid,shard,&a)&&!strcmp(a.provider_id,from)&&a.state==QRX_ASSIGN_PENDING?0:-1;free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_POSTOR")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;int rc=cid&&!parse_u32(sh,&shard)?verify_assignment_postor(db,cid,shard,from,p,h,NULL):-1;free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_SETTLE_EPOCH")){if(amount)return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index"),*ep=field(p,"epoch");uint32_t shard=0;uint64_t epoch=0;QrxStorageContractState c;QrxStorageAssignmentRecord a;QrxStorageProviderState ps;int rc=-1;if(!cid||parse_u32(sh,&shard)||parse_u64(ep,&epoch)||qrx_storage_contract_get(db,cid,&c)||qrx_storage_assignment_get(db,cid,shard,&a)||qrx_storage_provider_get(db,a.provider_id,&ps)||strcmp(to,a.provider_id)||a.last_proof_epoch!=epoch||a.last_settled_epoch>=epoch)goto sdone;QrxStorageRewardInput ri={a.physical_bytes,1,c.base_atoms_per_gib_epoch,ps.availability_bps,10000,ps.performance_bps};uint64_t reward=qrx_storage_provider_reward(&ri),remain=c.provider_escrow_atoms-c.provider_paid_atoms-c.egress_paid_atoms;if(!reward||reward>remain)goto sdone;snprintf(e->recipient,sizeof(e->recipient),"%s",a.provider_id);e->recipient_credit_atoms=reward;rc=0;sdone:free(cid);free(sh);free(ep);return rc;}
    if(!strcmp(tx,"STORAGE_EGRESS_PAY")){if(amount)return -1;char*cid=field(p,"contract_id"),*pid=field(p,"provider_id"),*at=field(p,"egress_atoms"),*rid=field(p,"receipt_id");uint64_t atoms=0;QrxStorageContractState c;int rc=-1;if(!cid||!pid||!safe_token(pid,129)||!rid||!safe_token(rid,129)||parse_u64(at,&atoms)||!atoms||qrx_storage_contract_get(db,cid,&c)||strcmp(c.owner,from)||strcmp(to,pid)||!provider_has_contract_assignment(db,cid,pid))goto edone;char rk[500],tmp[8];snprintf(rk,sizeof(rk),"storage/egress-receipt/%s/%s",cid,rid);if(qrxdb_get(db,rk,tmp,sizeof(tmp))==0)goto edone;if(atoms>c.provider_escrow_atoms-c.provider_paid_atoms-c.egress_paid_atoms)goto edone;snprintf(e->recipient,sizeof(e->recipient),"%s",pid);e->recipient_credit_atoms=atoms;rc=0;edone:free(cid);free(pid);free(at);free(rid);return rc;}
    if(!strcmp(tx,"STORAGE_ATTEST")){if(amount||strcmp(from,to))return -1;char*target=field(p,"target_provider"),*asn=field(p,"asn"),*region=field(p,"region"),*ep=field(p,"epoch");uint64_t epoch=0;QrxStorageProviderState a,t;int rc=!target||!safe_token(target,129)||!asn||!safe_token(asn,64)||!region||!safe_token(region,96)||parse_u64(ep,&epoch)||epoch!=h/QRX_STORAGE_ATTEST_EPOCH_BLOCKS||!strcmp(target,from)||qrx_storage_provider_get(db,from,&a)||a.status!=QRX_PROVIDER_ACTIVE||qrx_storage_provider_get(db,target,&t)||t.status!=QRX_PROVIDER_ACTIVE?-1:0;free(target);free(asn);free(region);free(ep);return rc;}
    if(!strcmp(tx,"STORAGE_REPAIR_START")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;QrxStorageAssignmentRecord a;int rc=cid&&!parse_u32(sh,&shard)&&!qrx_storage_assignment_get(db,cid,shard,&a)&&a.state==QRX_ASSIGN_ACTIVE&&h>((a.last_proof_height?a.last_proof_height:a.accepted_height)+QRX_STORAGE_PROOF_WINDOW_BLOCKS)?0:-1;free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_REPAIR_ACCEPT")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;char rk[400],rv[900];int rc=-1;if(cid&&!parse_u32(sh,&shard)){snprintf(rk,sizeof(rk),REPAIR_PREFIX"%s/%010u",cid,shard);if(!qrxdb_get(db,rk,rv,sizeof(rv))){char*t=strdup(rv),*sv=NULL,*a[10];int n=0;for(char*x=strtok_r(t,"|",&sv);x&&n<10;x=strtok_r(NULL,"|",&sv))a[n++]=x;if(n==10&&!strcmp(a[0],"1")&&!strcmp(a[2],from)&&atoi(a[3])==QRX_ASSIGN_REPAIRING)rc=0;free(t);}}free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_REPAIR_COMPLETE")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;char rk[400],rv[900];int rc=-1;if(!cid||parse_u32(sh,&shard))goto rdone;snprintf(rk,sizeof(rk),REPAIR_PREFIX"%s/%010u",cid,shard);if(qrxdb_get(db,rk,rv,sizeof(rv)))goto rdone;char*t=strdup(rv),*sv=NULL,*a[10];int n=0;for(char*x=strtok_r(t,"|",&sv);x&&n<10;x=strtok_r(NULL,"|",&sv))a[n++]=x;if(n!=10||strcmp(a[0],"1")||strcmp(a[2],from)||atoi(a[3])!=QRX_ASSIGN_ACTIVE){free(t);goto rdone;}QrxStorageContractState c;if(qrx_storage_contract_get(db,cid,&c)){free(t);goto rdone;}QrxStorageAssignmentRecord tmp;memset(&tmp,0,sizeof(tmp));snprintf(tmp.provider_id,sizeof(tmp.provider_id),"%s",from);tmp.state=QRX_ASSIGN_REPAIRING;tmp.physical_bytes=strtoull(a[5],NULL,10);snprintf(tmp.object_id,sizeof(tmp.object_id),"%s",a[6]);if(unhex(a[7],tmp.merkle_root,64)){free(t);goto rdone;}tmp.leaf_count=strtoull(a[8],NULL,10);tmp.accepted_height=strtoull(a[9],NULL,10);char ak[360],av[1200];key_assign(cid,shard,ak);if(assign_encode(&tmp,av,sizeof(av))){free(t);goto rdone;}/* verification uses a temporary authoritative-like decode below */
        char*ep=field(p,"epoch"),*ch=field(p,"challenge_height"),*leafh=field(p,"revealed_leaf_hex"),*sib=field(p,"siblings_hex");uint64_t epoch=0,challenge_h=0;if(parse_u64(ep,&epoch)||parse_u64(ch,&challenge_h)||epoch!=1||tmp.accepted_height>UINT64_MAX-QRX_STORAGE_PROOF_WINDOW_BLOCKS||challenge_h!=tmp.accepted_height+QRX_STORAGE_PROOF_WINDOW_BLOCKS||challenge_h>h||!leafh){free(ep);free(ch);free(leafh);free(sib);free(t);goto rdone;}size_t ln=strlen(leafh);if(ln%2){free(ep);free(ch);free(leafh);free(sib);free(t);goto rdone;}uint8_t*leaf=malloc(ln/2?ln/2:1),bh[64];if(!leaf){free(ep);free(ch);free(leafh);free(sib);free(t);goto rdone;}int bad=0;for(size_t i=0;i<ln/2;i++){int x=hexv(leafh[i*2]),y=hexv(leafh[i*2+1]);if(x<0||y<0){bad=1;break;}leaf[i]=(uint8_t)((x<<4)|y);}QrxPoStorChallenge pc;QrxMerkleProof mp;if(bad||block_hash_at(db,challenge_h,bh)||qrx_postor_derive_challenge(cid,from,shard,epoch,tmp.leaf_count,bh,&pc)||parse_merkle_proof(sib,pc.leaf_index,tmp.leaf_count,&mp)||qrx_postor_verify(&pc,leaf,ln/2,&mp,tmp.merkle_root)){free(leaf);free(ep);free(ch);free(leafh);free(sib);free(t);goto rdone;}free(leaf);free(ep);free(ch);free(leafh);free(sib);uint64_t gib=(tmp.physical_bytes+(1024ULL*1024ULL*1024ULL-1))/(1024ULL*1024ULL*1024ULL);if(!gib)gib=1;uint64_t reward=gib*c.base_atoms_per_gib_epoch;if(reward>UINT64_MAX/2){free(t);goto rdone;}reward*=2;uint64_t rem=c.resilience_atoms-c.repair_paid_atoms;if(reward>rem)reward=rem;if(!reward){free(t);goto rdone;}snprintf(e->recipient,sizeof(e->recipient),"%s",from);e->recipient_credit_atoms=reward;free(t);rc=0;rdone:free(cid);free(sh);return rc;}
    return -1;
}

int qrx_storage_assignment_provider_for_height(QrxDB *db,const char *contract_id,uint64_t shard_bytes,uint64_t inclusion_height,char out[129]){
    if(!db||!contract_id||!*contract_id||!shard_bytes||!out||!inclusion_height)return -1;
    return deterministic_provider_seed(db,contract_id,shard_bytes,inclusion_height-1,out);
}

int qrx_storage_consensus_prepare(const char*chain,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,const char*txid,uint64_t h,QrxServiceEconomicEffect*e){if(!chain||!tx||!from||!to||!p||!e)return -1;QrxDB db;if(qrxdb_init(&db,chain))return -1;int rc=prepare_with_db(&db,tx,from,to,amount,p,txid,h,e);qrxdb_close(&db);return rc;}

typedef struct { const char *asn; const char *region; unsigned matches; } AttestCountCtx;
static int attest_count_cb(const char*kk,const char*vv,uint32_t vl,void*x){(void)kk;(void)vl;AttestCountCtx*c=(AttestCountCtx*)x;char*t=strdup(vv);if(!t)return -1;char*s=NULL,*a[4];int n=0;for(char*q=strtok_r(t,"|",&s);q&&n<4;q=strtok_r(NULL,"|",&s))a[n++]=q;if(n==4&&!strcmp(a[0],"1")&&!strcmp(a[1],c->asn)&&!strcmp(a[2],c->region))c->matches++;free(t);return 0;}
static int stage_attestation(QrxDB*db,QrxDBBatch*b,const char*from,const char*p,uint64_t h){char*target=field(p,"target_provider"),*asn=field(p,"asn"),*region=field(p,"region"),*ep=field(p,"epoch");uint64_t epoch=0;if(!target||!asn||!region||parse_u64(ep,&epoch)){free(target);free(asn);free(region);free(ep);return -1;}char k[600],v[300];snprintf(k,sizeof(k),ATTEST_PREFIX"%s/%020llu/%s",target,(unsigned long long)epoch,from);snprintf(v,sizeof(v),"1|%s|%s|%llu",asn,region,(unsigned long long)h);if(qrxdb_batch_put(b,k,v)){free(target);free(asn);free(region);free(ep);return -1;}AttestCountCtx c={asn,region,1};char pre[500];snprintf(pre,sizeof(pre),ATTEST_PREFIX"%s/%020llu/",target,(unsigned long long)epoch);qrxdb_scan_prefix(db,pre,attest_count_cb,&c);if(c.matches>=QRX_STORAGE_ATTEST_QUORUM){QrxStorageProviderState ps;if(qrx_storage_provider_get(db,target,&ps)==0){snprintf(ps.attested_asn,sizeof(ps.attested_asn),"%s",asn);snprintf(ps.attested_region,sizeof(ps.attested_region),"%s",region);ps.attestation_epoch=epoch;if(provider_put(b,target,&ps)){free(target);free(asn);free(region);free(ep);return -1;}}}free(target);free(asn);free(region);free(ep);return 0;}

int qrx_storage_consensus_stage(QrxDB*db,QrxDBBatch*b,const char*chain,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,const char*txid,uint64_t h){if(!db||!b||!chain||!tx||!from||!to||!p||!txid)return -1;QrxServiceEconomicEffect e;if(prepare_with_db(db,tx,from,to,amount,p,txid,h,&e))return -1;
    if(!strcmp(tx,"STORAGE_CAPACITY_COMMIT")){char*sc=field(p,"slot_count"),*sb=field(p,"slot_bytes"),*rh=field(p,"merkle_root_hex");QrxCapacityCommitment c;memset(&c,0,sizeof(c));c.version=1;snprintf(c.provider_id,sizeof(c.provider_id),"%s",from);c.epoch=h;parse_u64(sc,&c.slot_count);parse_u32(sb,&c.slot_bytes);int rc=unhex(rh,c.merkle_root,64)||capacity_put(b,&c,h,0);free(sc);free(sb);free(rh);return rc;}
    if(!strcmp(tx,"STORAGE_CAPACITY_PROVE")){QrxCapacityCommitment c;uint64_t ch=0;int v=0;if(capacity_get(db,from,&c,&ch,&v))return -1;return capacity_put(b,&c,ch,1);}
    if(!strcmp(tx,"STORAGE_PROVIDER_BOND")){QrxCapacityCommitment c;int v=0;if(capacity_get(db,from,&c,NULL,&v)||!v||c.slot_count>UINT64_MAX/c.slot_bytes)return -1;QrxStorageProviderState ps;memset(&ps,0,sizeof(ps));snprintf(ps.owner,sizeof(ps.owner),"%s",from);ps.status=QRX_PROVIDER_REGISTERED;ps.bond_atoms=amount;ps.proven_capacity_bytes=c.slot_count*c.slot_bytes;ps.availability_bps=QRX_STORAGE_REPUTATION_INITIAL_BPS;ps.proof_success_bps=QRX_STORAGE_REPUTATION_INITIAL_BPS;ps.performance_bps=10000;ps.reputation_bps=QRX_STORAGE_REPUTATION_INITIAL_BPS;char*op=field(p,"operator_id"),*asn=field(p,"asn"),*reg=field(p,"region");snprintf(ps.operator_id,sizeof(ps.operator_id),"%s",op&&*op?op:from);if(asn&&safe_token(asn,64))snprintf(ps.claimed_asn,sizeof(ps.claimed_asn),"%s",asn);if(reg&&safe_token(reg,96))snprintf(ps.claimed_region,sizeof(ps.claimed_region),"%s",reg);free(op);free(asn);free(reg);if(provider_put(b,from,&ps))return -1;return pool_adjust(db,b,"consensus:storage:provider_bonds",(int64_t)amount);}
    if(!strcmp(tx,"STORAGE_PROVIDER_BIND_DISCOVERY_KEY")){char*kb=field(p,"public_key_pem_b64");if(!kb)return -1;char key[320];snprintf(key,sizeof(key),"storage/provider-key/%s",from);int rc=qrxdb_batch_put(b,key,kb);free(kb);return rc;}
    if(!strcmp(tx,"STORAGE_PROVIDER_ACTIVATE")){QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps))return -1;ps.status=QRX_PROVIDER_ACTIVE;return provider_put(b,from,&ps);}
    if(!strcmp(tx,"STORAGE_PROVIDER_EXIT")){QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps))return -1;ps.status=QRX_PROVIDER_EXITING;ps.exit_height=h;return provider_put(b,from,&ps);}
    if(!strcmp(tx,"STORAGE_PROVIDER_WITHDRAW")){QrxStorageProviderState ps;if(qrx_storage_provider_get(db,from,&ps))return -1;uint64_t x=ps.bond_atoms;ps.bond_atoms=0;ps.status=QRX_PROVIDER_WITHDRAWN;if(provider_put(b,from,&ps))return -1;return pool_adjust(db,b,"consensus:storage:provider_bonds",-(int64_t)x);}
    if(!strcmp(tx,"STORAGE_CONTRACT_CREATE")){char*cid=field(p,"contract_id"),*prof=field(p,"profile"),*lb=field(p,"logical_bytes"),*eh=field(p,"end_height"),*br=field(p,"base_atoms_per_gib_epoch"),*mh=field(p,"manifest_root_hex");QrxStorageContractState c;memset(&c,0,sizeof(c));snprintf(c.owner,sizeof(c.owner),"%s",from);snprintf(c.profile,sizeof(c.profile),"%s",prof);parse_u64(lb,&c.logical_bytes);parse_u64(eh,&c.end_height);parse_u64(br,&c.base_atoms_per_gib_epoch);contract_shard_layout(c.profile,c.logical_bytes,&c.shard_bytes,&c.shard_count);c.start_height=h;c.original_atoms=amount;QrxStorageContractSplit sp;qrx_storage_split_contract_value(amount,QRX_STORAGE_DEV_SHARE_BPS,QRX_STORAGE_RESILIENCE_RESERVE_BPS,&sp);c.development_atoms=sp.development_atoms;c.resilience_atoms=sp.resilience_atoms;c.provider_escrow_atoms=sp.provider_budget_atoms;c.status=QRX_STORAGE_CONTRACT_ACTIVE;unhex(mh,c.manifest_root,64);int rc=contract_put(b,cid,&c)||pool_adjust(db,b,"consensus:storage:provider_escrow",(int64_t)c.provider_escrow_atoms)||pool_adjust(db,b,"consensus:storage:resilience",(int64_t)c.resilience_atoms);free(cid);free(prof);free(lb);free(eh);free(br);free(mh);return rc;}
    if(!strcmp(tx,"STORAGE_CONTRACT_COMPLETE")){char*cid=field(p,"contract_id");QrxStorageContractState c;if(qrx_storage_contract_get(db,cid,&c)){free(cid);return -1;}c.status=QRX_STORAGE_CONTRACT_COMPLETE;int rc=contract_put(b,cid,&c);free(cid);return rc;}
    if(!strcmp(tx,"STORAGE_CONTRACT_REFUND")){char*cid=field(p,"contract_id");QrxStorageContractState c;if(qrx_storage_contract_get(db,cid,&c)){free(cid);return -1;}uint64_t pr=c.provider_escrow_atoms-c.provider_paid_atoms-c.egress_paid_atoms,rr=c.resilience_atoms-c.repair_paid_atoms;c.provider_paid_atoms+=pr;c.repair_paid_atoms+=rr;c.status=QRX_STORAGE_CONTRACT_REFUNDED;int rc=contract_put(b,cid,&c)||pool_adjust(db,b,"consensus:storage:provider_escrow",-(int64_t)pr)||pool_adjust(db,b,"consensus:storage:resilience",-(int64_t)rr);free(cid);return rc;}
    if(!strcmp(tx,"STORAGE_ASSIGN")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index"),*oid=field(p,"object_id"),*rh=field(p,"merkle_root_hex"),*lc=field(p,"leaf_count");uint32_t shard=0;parse_u32(sh,&shard);QrxStorageContractState c;qrx_storage_contract_get(db,cid,&c);QrxStorageAssignmentRecord a;memset(&a,0,sizeof(a));snprintf(a.provider_id,sizeof(a.provider_id),"%s",to);a.state=QRX_ASSIGN_PENDING;a.physical_bytes=c.shard_bytes;snprintf(a.object_id,sizeof(a.object_id),"%s",oid);unhex(rh,a.merkle_root,64);parse_u64(lc,&a.leaf_count);QrxStorageProviderState ps;if(qrx_storage_provider_get(db,to,&ps)){free(cid);free(sh);free(oid);free(rh);free(lc);return -1;}if(UINT64_MAX-ps.allocated_bytes<c.shard_bytes){free(cid);free(sh);free(oid);free(rh);free(lc);return -1;}ps.allocated_bytes+=c.shard_bytes;int rc=assign_put(b,cid,shard,&a)||provider_put(b,to,&ps);free(cid);free(sh);free(oid);free(rh);free(lc);return rc;}
    if(!strcmp(tx,"STORAGE_ASSIGN_ACCEPT")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;parse_u32(sh,&shard);QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(db,cid,shard,&a)){free(cid);free(sh);return -1;}a.state=QRX_ASSIGN_ACTIVE;a.accepted_height=h;int rc=assign_put(b,cid,shard,&a);free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_POSTOR")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;parse_u32(sh,&shard);uint64_t epoch=0;if(verify_assignment_postor(db,cid,shard,from,p,h,&epoch)){free(cid);free(sh);return -1;}QrxStorageAssignmentRecord a;qrx_storage_assignment_get(db,cid,shard,&a);a.last_proof_epoch=epoch;a.last_proof_height=h;QrxStorageProviderState ps;qrx_storage_provider_get(db,from,&ps);QrxStorageProviderReputation r={ps.availability_bps,ps.proof_success_bps,ps.performance_bps,ps.reputation_bps,0,0,0,0};qrx_storage_reputation_record_proof(&r,1,10000);ps.availability_bps=r.availability_bps;ps.proof_success_bps=r.proof_success_bps;ps.performance_bps=r.performance_bps;ps.reputation_bps=r.reputation_bps;int rc=assign_put(b,cid,shard,&a)||provider_put(b,from,&ps);free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_SETTLE_EPOCH")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index"),*ep=field(p,"epoch");uint32_t shard=0;uint64_t epoch=0;parse_u32(sh,&shard);parse_u64(ep,&epoch);QrxStorageContractState c;QrxStorageAssignmentRecord a;qrx_storage_contract_get(db,cid,&c);qrx_storage_assignment_get(db,cid,shard,&a);uint64_t pay=e.recipient_credit_atoms;c.provider_paid_atoms+=pay;a.last_settled_epoch=epoch;int rc=contract_put(b,cid,&c)||assign_put(b,cid,shard,&a)||pool_adjust(db,b,"consensus:storage:provider_escrow",-(int64_t)pay);free(cid);free(sh);free(ep);return rc;}
    if(!strcmp(tx,"STORAGE_EGRESS_PAY")){char*cid=field(p,"contract_id"),*at=field(p,"egress_atoms"),*rid=field(p,"receipt_id");uint64_t atoms=0;parse_u64(at,&atoms);QrxStorageContractState c;qrx_storage_contract_get(db,cid,&c);c.egress_paid_atoms+=atoms;char rk[500];snprintf(rk,sizeof(rk),"storage/egress-receipt/%s/%s",cid,rid);int rc=contract_put(b,cid,&c)||qrxdb_batch_put(b,rk,txid)||pool_adjust(db,b,"consensus:storage:provider_escrow",-(int64_t)atoms);free(cid);free(at);free(rid);return rc;}
    if(!strcmp(tx,"STORAGE_ATTEST"))return stage_attestation(db,b,from,p,h);
    if(!strcmp(tx,"STORAGE_REPAIR_START")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;parse_u32(sh,&shard);QrxStorageAssignmentRecord a;qrx_storage_assignment_get(db,cid,shard,&a);char replacement[129];if(deterministic_provider_seed(db,cid,a.physical_bytes,h?h-1:0,replacement)){free(cid);free(sh);return -1;}QrxStorageProviderState oldp,newp;if(qrx_storage_provider_get(db,a.provider_id,&oldp)||qrx_storage_provider_get(db,replacement,&newp)){free(cid);free(sh);return -1;}if(oldp.allocated_bytes<a.physical_bytes||UINT64_MAX-newp.allocated_bytes<a.physical_bytes){free(cid);free(sh);return -1;}oldp.allocated_bytes-=a.physical_bytes;newp.allocated_bytes+=a.physical_bytes;a.state=QRX_ASSIGN_REPAIRING;char rh[129],rk[400],rv[900];hex64(a.merkle_root,rh);snprintf(rk,sizeof(rk),REPAIR_PREFIX"%s/%010u",cid,shard);snprintf(rv,sizeof(rv),"1|%s|%s|%u|%llu|%llu|%s|%s|%llu|0",a.provider_id,replacement,QRX_ASSIGN_REPAIRING,(unsigned long long)h,(unsigned long long)a.physical_bytes,a.object_id,rh,(unsigned long long)a.leaf_count);int rc=assign_put(b,cid,shard,&a)||provider_put(b,a.provider_id,&oldp)||provider_put(b,replacement,&newp)||qrxdb_batch_put(b,rk,rv);free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_REPAIR_ACCEPT")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index");uint32_t shard=0;parse_u32(sh,&shard);char rk[400],rv[900];snprintf(rk,sizeof(rk),REPAIR_PREFIX"%s/%010u",cid,shard);if(qrxdb_get(db,rk,rv,sizeof(rv))){free(cid);free(sh);return -1;}char*t=strdup(rv),*sv=NULL,*a[10];int n=0;for(char*x=strtok_r(t,"|",&sv);x&&n<10;x=strtok_r(NULL,"|",&sv))a[n++]=x;if(n!=10){free(t);free(cid);free(sh);return -1;}char nv[900];snprintf(nv,sizeof(nv),"1|%s|%s|%u|%s|%s|%s|%s|%s|%llu",a[1],a[2],QRX_ASSIGN_ACTIVE,a[4],a[5],a[6],a[7],a[8],(unsigned long long)h);int rc=qrxdb_batch_put(b,rk,nv);free(t);free(cid);free(sh);return rc;}
    if(!strcmp(tx,"STORAGE_REPAIR_COMPLETE")){char*cid=field(p,"contract_id"),*sh=field(p,"shard_index"),*ep=field(p,"epoch");uint32_t shard=0;uint64_t epoch=0;parse_u32(sh,&shard);parse_u64(ep,&epoch);char rk[400],rv[900];snprintf(rk,sizeof(rk),REPAIR_PREFIX"%s/%010u",cid,shard);if(qrxdb_get(db,rk,rv,sizeof(rv))){free(cid);free(sh);free(ep);return -1;}char*t=strdup(rv),*sv=NULL,*a[10];int n=0;for(char*x=strtok_r(t,"|",&sv);x&&n<10;x=strtok_r(NULL,"|",&sv))a[n++]=x;if(n!=10){free(t);free(cid);free(sh);free(ep);return -1;}QrxStorageAssignmentRecord as;memset(&as,0,sizeof(as));snprintf(as.provider_id,sizeof(as.provider_id),"%s",from);as.state=QRX_ASSIGN_ACTIVE;as.physical_bytes=strtoull(a[5],NULL,10);snprintf(as.object_id,sizeof(as.object_id),"%s",a[6]);unhex(a[7],as.merkle_root,64);as.leaf_count=strtoull(a[8],NULL,10);as.accepted_height=strtoull(a[9],NULL,10);as.last_proof_epoch=epoch;as.last_proof_height=h;QrxStorageContractState c;qrx_storage_contract_get(db,cid,&c);uint64_t pay=e.recipient_credit_atoms;c.repair_paid_atoms+=pay;char nv[900];snprintf(nv,sizeof(nv),"1|%s|%s|%u|%s|%s|%s|%s|%s|%s",a[1],a[2],QRX_ASSIGN_REPLACED,a[4],a[5],a[6],a[7],a[8],a[9]);int rc=assign_put(b,cid,shard,&as)||contract_put(b,cid,&c)||qrxdb_batch_put(b,rk,nv)||pool_adjust(db,b,"consensus:storage:resilience",-(int64_t)pay);free(t);free(cid);free(sh);free(ep);return rc;}
    return -1;
}
