#include "net/qrx_net_permissions.h"
#include <openssl/crypto.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static void hx(const uint8_t b[64],char o[129]){static const char h[]="0123456789abcdef";for(int i=0;i<64;i++){o[i*2]=h[b[i]>>4];o[i*2+1]=h[b[i]&15];}o[128]=0;}static int uh(const char*s,uint8_t b[64]){if(!s||strlen(s)!=128)return -1;for(int i=0;i<64;i++){char a=s[2*i],c=s[2*i+1];int x=a>='0'&&a<='9'?a-'0':a>='a'&&a<='f'?a-'a'+10:-1,y=c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:-1;if(x<0||y<0)return -1;b[i]=(uint8_t)(x*16+y);}return 0;}
int qrx_dapp_permission_create(const QrxDomainRecord *r,uint32_t scopes,uint64_t h,uint64_t exp,QrxDappPermissionGrant *o){if(!r||!o||!scopes||(scopes&~QRX_DAPP_SCOPE_ALLOWED_MASK)||exp<=h||!qrx_domain_is_active(r,h))return -1;memset(o,0,sizeof(*o));strcpy(o->domain,r->name);strcpy(o->owner,r->owner);memcpy(o->publishing_key_commitment,r->publishing_key_commitment,64);o->scopes=scopes;o->granted_height=h;o->expiry_height=exp<r->expiry_height?exp:r->expiry_height;return 0;}
int qrx_dapp_permission_valid(const QrxDappPermissionGrant *g,const QrxDomainRecord *r,uint64_t h,uint32_t scope){if(!g||!r||!scope||(scope&~QRX_DAPP_SCOPE_ALLOWED_MASK)||!(g->scopes&scope)||h>g->expiry_height||!qrx_domain_is_active(r,h)||strcmp(g->domain,r->name)||strcmp(g->owner,r->owner)||CRYPTO_memcmp(g->publishing_key_commitment,r->publishing_key_commitment,64))return 0;return 1;}
int qrx_dapp_permission_save(const char *path,const QrxDappPermissionGrant *g){if(!path||!g)return -1;char tmp[1024],ph[129];if(snprintf(tmp,sizeof(tmp),"%s.tmp",path)>=(int)sizeof(tmp))return -1;hx(g->publishing_key_commitment,ph);FILE *f=fopen(tmp,"wb");if(!f)return -1;int ok=fprintf(f,"1|%s|%s|%s|%u|%llu|%llu\n",g->domain,g->owner,ph,g->scopes,(unsigned long long)g->granted_height,(unsigned long long)g->expiry_height)>0&&fflush(f)==0&&fclose(f)==0;if(!ok){remove(tmp);return -1;}if(rename(tmp,path)!=0){remove(tmp);return -1;}return 0;}
int qrx_dapp_permission_load(const char *path,QrxDappPermissionGrant *g){if(!path||!g)return -1;FILE*f=fopen(path,"rb");if(!f)return -1;char line[1400];if(!fgets(line,sizeof(line),f)){fclose(f);return -1;}fclose(f);char domain[254],owner[160],ph[129];unsigned scopes=0;unsigned long long gh=0,eh=0;if(sscanf(line,"1|%253[^|]|%159[^|]|%128[^|]|%u|%llu|%llu",domain,owner,ph,&scopes,&gh,&eh)!=6)return -1;memset(g,0,sizeof(*g));strcpy(g->domain,domain);strcpy(g->owner,owner);if(uh(ph,g->publishing_key_commitment))return -1;g->scopes=scopes;g->granted_height=gh;g->expiry_height=eh;return (scopes&&!(scopes&~QRX_DAPP_SCOPE_ALLOWED_MASK))?0:-1;}
