#include "net/qrx_net_youth.h"
#include "net/qrx_net_name.h"
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int has_domain(char list[QRX_YOUTH_MAX_DOMAINS][254],uint32_t n,const char *domain){char norm[254];if(qrx_domain_normalize(domain,norm))return 0;for(uint32_t i=0;i<n;i++)if(strcmp(list[i],norm)==0)return 1;return 0;}
void qrx_youth_policy_default(uint32_t profile,QrxYouthPolicy*out){if(!out)return;memset(out,0,sizeof(*out));out->version=QRX_YOUTH_POLICY_VERSION;out->profile=profile;out->session_minutes=120;if(profile==QRX_YOUTH_PROFILE_CHILD){out->max_age_rating=12;out->blocked_categories=QRX_YOUTH_CAT_GAMBLING|QRX_YOUTH_CAT_ADULT|QRX_YOUTH_CAT_DRUGS;out->allowed_capabilities=0;out->payment_limit_atoms=0;out->unrated_blocked=1;out->ads_blocked=1;out->viewer_rewards_blocked=1;}else if(profile==QRX_YOUTH_PROFILE_TEEN){out->max_age_rating=16;out->blocked_categories=QRX_YOUTH_CAT_GAMBLING|QRX_YOUTH_CAT_ADULT;out->allowed_capabilities=QRX_YOUTH_CAP_DAPP;out->payment_limit_atoms=0;out->unrated_blocked=1;out->ads_blocked=1;out->viewer_rewards_blocked=1;}else{out->max_age_rating=18;out->blocked_categories=0;out->allowed_capabilities=0xffffffffu;out->payment_limit_atoms=UINT64_MAX;out->unrated_blocked=0;out->ads_blocked=0;out->viewer_rewards_blocked=0;}}
int qrx_youth_policy_validate(const QrxYouthPolicy*p){if(!p||p->version!=QRX_YOUTH_POLICY_VERSION||p->profile>QRX_YOUTH_PROFILE_CHILD||p->max_age_rating>21||p->allow_count>QRX_YOUTH_MAX_DOMAINS||p->block_count>QRX_YOUTH_MAX_DOMAINS||p->session_minutes>24u*60u)return -1;for(uint32_t i=0;i<p->allow_count;i++){char n[254];if(qrx_domain_normalize(p->allow_domains[i],n)||strcmp(n,p->allow_domains[i]))return -1;}for(uint32_t i=0;i<p->block_count;i++){char n[254];if(qrx_domain_normalize(p->block_domains[i],n)||strcmp(n,p->block_domains[i]))return -1;}return 0;}
static int add_domain(char list[QRX_YOUTH_MAX_DOMAINS][254],uint32_t*n,const char*d){char norm[254];if(!n||qrx_domain_normalize(d,norm)||*n>=QRX_YOUTH_MAX_DOMAINS)return -1;for(uint32_t i=0;i<*n;i++)if(!strcmp(list[i],norm))return 0;strcpy(list[*n],norm);(*n)++;return 0;}
int qrx_youth_policy_add_allow(QrxYouthPolicy*p,const char*d){return p?add_domain(p->allow_domains,&p->allow_count,d):-1;}
int qrx_youth_policy_add_block(QrxYouthPolicy*p,const char*d){return p?add_domain(p->block_domains,&p->block_count,d):-1;}
QrxYouthDecision qrx_youth_evaluate_navigation(const QrxYouthPolicy*p,const char*domain,const QrxYouthContentRating*r){if(!p||qrx_youth_policy_validate(p)||!domain)return QRX_YOUTH_BLOCK_DOMAIN;if(has_domain((char (*)[254])p->block_domains,p->block_count,domain))return QRX_YOUTH_BLOCK_DOMAIN;if(p->allow_count&&!has_domain((char (*)[254])p->allow_domains,p->allow_count,domain))return QRX_YOUTH_BLOCK_DOMAIN;if(!r||!r->rated){if(p->unrated_blocked)return QRX_YOUTH_BLOCK_UNRATED;return QRX_YOUTH_ALLOW;}if(r->min_age>p->max_age_rating)return QRX_YOUTH_BLOCK_AGE;if(r->categories&p->blocked_categories)return QRX_YOUTH_BLOCK_CATEGORY;return QRX_YOUTH_ALLOW;}
QrxYouthDecision qrx_youth_evaluate_capability(const QrxYouthPolicy*p,uint32_t cap,uint64_t atoms){if(!p||qrx_youth_policy_validate(p))return QRX_YOUTH_BLOCK_CAPABILITY;if(cap==QRX_YOUTH_CAP_SPONSORED_ADS&&p->ads_blocked)return QRX_YOUTH_BLOCK_ADS;if(cap==QRX_YOUTH_CAP_VIEWER_REWARD&&p->viewer_rewards_blocked)return QRX_YOUTH_BLOCK_VIEWER_REWARD;if(!(p->allowed_capabilities&cap))return QRX_YOUTH_BLOCK_CAPABILITY;if(cap==QRX_YOUTH_CAP_PAYMENT&&atoms>p->payment_limit_atoms)return QRX_YOUTH_BLOCK_PAYMENT_LIMIT;return QRX_YOUTH_ALLOW;}
static int encode(const QrxYouthPolicy*p,unsigned char**out,size_t*n){if(!p||qrx_youth_policy_validate(p)||!out||!n)return -1;*n=sizeof(*p);*out=malloc(*n);if(!*out)return -1;memcpy(*out,p,*n);return 0;}
static int derive(const char*pin,const unsigned char salt[16],unsigned char key[32]){if(!pin||strlen(pin)<4)return -1;return PKCS5_PBKDF2_HMAC(pin,(int)strlen(pin),salt,16,QRX_YOUTH_PBKDF2_ITERS,EVP_sha3_256(),32,key)==1?0:-1;}
int qrx_youth_policy_save_encrypted(const char*path,const QrxYouthPolicy*p,const char*pin){if(!path||!p||!pin)return -1;unsigned char *plain=NULL,*ct=NULL,key[32],salt[16],nonce[12],tag[16];size_t n=0;int rc=-1;if(encode(p,&plain,&n)||RAND_bytes(salt,16)!=1||RAND_bytes(nonce,12)!=1||derive(pin,salt,key))goto done;ct=malloc(n);if(!ct)goto done;EVP_CIPHER_CTX*c=EVP_CIPHER_CTX_new();int l=0,z=0;if(!c)goto done;if(EVP_EncryptInit_ex(c,EVP_aes_256_gcm(),NULL,NULL,NULL)!=1||EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_IVLEN,12,NULL)!=1||EVP_EncryptInit_ex(c,NULL,NULL,key,nonce)!=1||EVP_EncryptUpdate(c,ct,&l,plain,(int)n)!=1||EVP_EncryptFinal_ex(c,ct+l,&z)!=1||EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_GET_TAG,16,tag)!=1){EVP_CIPHER_CTX_free(c);goto done;}EVP_CIPHER_CTX_free(c);FILE*f=fopen(path,"wb");if(!f)goto done;uint32_t nn=(uint32_t)n;if(fwrite("QRXYFP1",1,7,f)!=7||fwrite(salt,1,16,f)!=16||fwrite(nonce,1,12,f)!=12||fwrite(tag,1,16,f)!=16||fwrite(&nn,1,4,f)!=4||fwrite(ct,1,n,f)!=n||fclose(f)!=0){remove(path);goto done;}rc=0;done:OPENSSL_cleanse(key,sizeof(key));if(plain){OPENSSL_cleanse(plain,n);free(plain);}free(ct);return rc;}
int qrx_youth_policy_load_encrypted(const char*path,QrxYouthPolicy*out,const char*pin){if(!path||!out||!pin)return -1;FILE*f=fopen(path,"rb");if(!f)return -1;char magic[7];unsigned char salt[16],nonce[12],tag[16],key[32],*ct=NULL,*pt=NULL;uint32_t n=0;int rc=-1;if(fread(magic,1,7,f)!=7||memcmp(magic,"QRXYFP1",7)||fread(salt,1,16,f)!=16||fread(nonce,1,12,f)!=12||fread(tag,1,16,f)!=16||fread(&n,1,4,f)!=4||n!=sizeof(QrxYouthPolicy)){fclose(f);return -1;}ct=malloc(n);pt=malloc(n);if(!ct||!pt||fread(ct,1,n,f)!=n||fgetc(f)!=EOF||derive(pin,salt,key)){fclose(f);goto done;}fclose(f);EVP_CIPHER_CTX*c=EVP_CIPHER_CTX_new();int l=0,z=0;if(!c)goto done;if(EVP_DecryptInit_ex(c,EVP_aes_256_gcm(),NULL,NULL,NULL)!=1||EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_IVLEN,12,NULL)!=1||EVP_DecryptInit_ex(c,NULL,NULL,key,nonce)!=1||EVP_DecryptUpdate(c,pt,&l,ct,(int)n)!=1||EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_TAG,16,tag)!=1||EVP_DecryptFinal_ex(c,pt+l,&z)!=1){EVP_CIPHER_CTX_free(c);goto done;}EVP_CIPHER_CTX_free(c);memcpy(out,pt,sizeof(*out));if(qrx_youth_policy_validate(out))goto done;rc=0;done:OPENSSL_cleanse(key,sizeof(key));if(pt){OPENSSL_cleanse(pt,n);free(pt);}free(ct);return rc;}
