#include "net/qrx_net_registry.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int safe_text(const char *s,size_t max){if(!s||!*s||strlen(s)>=max)return 0;for(const unsigned char *p=(const unsigned char*)s;*p;p++)if(*p=='|'||*p=='\n'||*p=='\r'||*p<32)return 0;return 1;}
static void hex64(const uint8_t b[64],char o[129]){static const char h[]="0123456789abcdef";for(int i=0;i<64;i++){o[i*2]=h[b[i]>>4];o[i*2+1]=h[b[i]&15];}o[128]=0;}
static int hv(char c){return c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:c>='A'&&c<='F'?c-'A'+10:-1;}
static int unhex64(const char *s,uint8_t o[64]){if(!s||strlen(s)!=128)return -1;for(int i=0;i<64;i++){int a=hv(s[i*2]),b=hv(s[i*2+1]);if(a<0||b<0)return -1;o[i]=(uint8_t)((a<<4)|b);}return 0;}
static int rec_encode(const QrxDomainRecord *r,char *out,size_t sz){char nh[129],wh[129],ph[129];hex64(r->name_hash,nh);hex64(r->web_manifest_root,wh);hex64(r->publishing_key_commitment,ph);int n=snprintf(out,sz,"1|%s|%s|%s|%s|%s|%s|%llu|%llu|%llu",r->name,nh,r->owner,r->qub_address[0]?r->qub_address:"-",wh,ph,(unsigned long long)r->created_height,(unsigned long long)r->expiry_height,(unsigned long long)r->sequence);return n>0&&(size_t)n<sz?0:-1;}
static int rec_decode(const char *v,QrxDomainRecord *r){if(!v||!r)return -1;char *tmp=strdup(v);if(!tmp)return -1;char *save=NULL,*parts[10];int n=0;for(char *p=strtok_r(tmp,"|",&save);p&&n<10;p=strtok_r(NULL,"|",&save))parts[n++]=p;if(n!=10||strcmp(parts[0],"1")){free(tmp);return -1;}memset(r,0,sizeof(*r));if(strlen(parts[1])>QRX_DOMAIN_MAX_NAME||strlen(parts[3])>=sizeof(r->owner)||strlen(parts[4])>=sizeof(r->qub_address)){free(tmp);return -1;}strcpy(r->name,parts[1]);if(unhex64(parts[2],r->name_hash)||unhex64(parts[5],r->web_manifest_root)||unhex64(parts[6],r->publishing_key_commitment)){free(tmp);return -1;}strcpy(r->owner,parts[3]);if(strcmp(parts[4],"-"))strcpy(r->qub_address,parts[4]);r->created_height=strtoull(parts[7],NULL,10);r->expiry_height=strtoull(parts[8],NULL,10);r->sequence=strtoull(parts[9],NULL,10);free(tmp);return r->sequence?0:-1;}
static void key_for(const uint8_t hash[64],char out[160]){char h[129];hex64(hash,h);snprintf(out,160,"qrxnet/domain/%s",h);}
static void hist_key(const uint8_t hash[64],uint64_t seq,char out[200]){char h[129];hex64(hash,h);snprintf(out,200,"qrxnet/history/%s/%020llu",h,(unsigned long long)seq);}

static int stage_transition(QrxDBBatch *b,const QrxDomainRecord *old,const QrxDomainRecord *now,int include_name_index){char value[1400],key[200],hvbuf[1400],hk[200],nk[320];if(!b||rec_encode(now,value,sizeof(value)))return -1;key_for(now->name_hash,key);if(old&&old->sequence){if(rec_encode(old,hvbuf,sizeof(hvbuf)))return -1;hist_key(old->name_hash,old->sequence,hk);if(qrxdb_batch_put(b,hk,hvbuf))return -1;}if(qrxdb_batch_put(b,key,value))return -1;if(include_name_index){char hh[129];hex64(now->name_hash,hh);snprintf(nk,sizeof(nk),"qrxnet/name/%s",now->name);if(qrxdb_batch_put(b,nk,hh))return -1;}return 0;}
static int commit_transition(QrxDB *db,const QrxDomainRecord *old,const QrxDomainRecord *now,int include_name_index){QrxDBBatch b;if(qrxdb_batch_begin(db,&b))return -1;if(stage_transition(&b,old,now,include_name_index)){qrxdb_batch_abort(&b);return -1;}return qrxdb_batch_commit(&b);}

int qrx_net_registry_get(QrxDB *db,const char *name,QrxDomainRecord *out){if(!db||!name||!out)return -1;char norm[254];uint8_t h[64];if(qrx_domain_normalize(name,norm)||qrx_domain_name_hash(norm,h))return -1;char key[160],v[1400];key_for(h,key);if(qrxdb_get(db,key,v,sizeof(v)))return -1;if(rec_decode(v,out))return -1;return strcmp(out->name,norm)?-1:0;}

typedef struct {const char *owner;QrxDomainRecordCallback cb;void *ctx;int count;int failed;} DomainScanCtx;
static int domain_list_cb(const char*k,const char*v,uint32_t vl,void*vp){(void)vl;DomainScanCtx*c=vp;QrxDomainRecord r;if(strncmp(k,"qrxnet/domain/",14)||rec_decode(v,&r))return 0;if(c->owner&&*c->owner&&strcmp(c->owner,r.owner))return 0;if(c->cb&&c->cb(&r,c->ctx)){c->failed=1;return -1;}c->count++;return 0;}
int qrx_net_registry_list(QrxDB *db,const char *owner,QrxDomainRecordCallback cb,void *ctx){if(!db)return -1;DomainScanCtx c={owner,cb,ctx,0,0};if(qrxdb_scan_prefix(db,"qrxnet/domain/",domain_list_cb,&c)||c.failed)return -1;return c.count;}
typedef struct {QrxDomainRecordCallback cb;void*ctx;int count;int failed;} HistScanCtx;
static int domain_hist_cb(const char*k,const char*v,uint32_t vl,void*vp){(void)k;(void)vl;HistScanCtx*c=vp;QrxDomainRecord r;if(rec_decode(v,&r))return 0;if(c->cb&&c->cb(&r,c->ctx)){c->failed=1;return -1;}c->count++;return 0;}
int qrx_net_registry_history(QrxDB *db,const char *name,QrxDomainRecordCallback cb,void *ctx){if(!db||!name)return -1;char norm[254],prefix[220],hh[129];uint8_t h[64];if(qrx_domain_normalize(name,norm)||qrx_domain_name_hash(norm,h))return -1;hex64(h,hh);snprintf(prefix,sizeof(prefix),"qrxnet/history/%s/",hh);HistScanCtx c={cb,ctx,0,0};if(qrxdb_scan_prefix(db,prefix,domain_hist_cb,&c)||c.failed)return -1;QrxDomainRecord cur;if(qrx_net_registry_get(db,norm,&cur)==0){if(cb&&cb(&cur,ctx))return -1;c.count++;}return c.count;}

static int build_register(QrxDB *db,const char *name,const char *owner,const char *qub,const uint8_t *web,const uint8_t *pub,uint64_t h,uint64_t exp,QrxDomainRecord *old,int *exists,QrxDomainRecord *r){if(!db||!safe_text(owner,160)||exp<=h||!r||!exists)return -1;char norm[254];if(qrx_domain_normalize(name,norm))return -1;*exists=qrx_net_registry_get(db,norm,old)==0;if(*exists&&(qrx_domain_is_active(old,h)||qrx_domain_in_grace(old,h)))return -1;memset(r,0,sizeof(*r));strcpy(r->name,norm);if(qrx_domain_name_hash(norm,r->name_hash))return -1;strcpy(r->owner,owner);if(qub&&*qub){if(!safe_text(qub,160))return -1;strcpy(r->qub_address,qub);}if(web)memcpy(r->web_manifest_root,web,64);if(pub)memcpy(r->publishing_key_commitment,pub,64);r->created_height=h;r->expiry_height=exp;r->sequence=*exists?old->sequence+1:1;return 0;}
static int build_renew(QrxDB *db,const char *name,const char *owner,uint64_t seq,uint64_t h,uint64_t exp,QrxDomainRecord *old,QrxDomainRecord *r){if(!db||!safe_text(owner,160)||qrx_net_registry_get(db,name,r)||strcmp(r->owner,owner)||r->sequence!=seq||!qrx_domain_is_active(r,h)||exp<=r->expiry_height)return -1;*old=*r;r->expiry_height=exp;r->sequence++;return 0;}
static int build_update(QrxDB *db,const char *name,const char *owner,uint64_t seq,uint64_t h,const QrxDomainUpdate *u,QrxDomainRecord *old,QrxDomainRecord *r){if(!db||!u||!safe_text(owner,160)||qrx_net_registry_get(db,name,r)||strcmp(r->owner,owner)||r->sequence!=seq||!qrx_domain_is_active(r,h))return -1;*old=*r;if(u->qub_mode==QRX_RECORD_CLEAR)r->qub_address[0]=0;else if(u->qub_mode==QRX_RECORD_SET){if(!safe_text(u->qub_address,160))return -1;strcpy(r->qub_address,u->qub_address);}if(u->web_mode==QRX_RECORD_CLEAR)memset(r->web_manifest_root,0,64);else if(u->web_mode==QRX_RECORD_SET){if(!u->web_manifest_root)return -1;memcpy(r->web_manifest_root,u->web_manifest_root,64);}if(u->publishing_mode==QRX_RECORD_CLEAR)memset(r->publishing_key_commitment,0,64);else if(u->publishing_mode==QRX_RECORD_SET){if(!u->publishing_key_commitment)return -1;memcpy(r->publishing_key_commitment,u->publishing_key_commitment,64);}r->sequence++;return 0;}
static int build_transfer(QrxDB *db,const char *name,const char *owner,uint64_t seq,uint64_t h,const char *new_owner,QrxDomainRecord *old,QrxDomainRecord *r){if(!db||!safe_text(owner,160)||!safe_text(new_owner,160)||qrx_net_registry_get(db,name,r)||strcmp(r->owner,owner)||r->sequence!=seq||!qrx_domain_is_active(r,h)||!strcmp(owner,new_owner))return -1;*old=*r;strcpy(r->owner,new_owner);r->qub_address[0]=0;memset(r->web_manifest_root,0,64);memset(r->publishing_key_commitment,0,64);r->sequence++;return 0;}

int qrx_net_registry_stage_register(QrxDB *db,QrxDBBatch *b,const char *name,const char *owner,const char *qub,const uint8_t *web,const uint8_t *pub,uint64_t h,uint64_t exp,QrxDomainRecord *out){QrxDomainRecord old,r;int exists=0;if(!b||build_register(db,name,owner,qub,web,pub,h,exp,&old,&exists,&r))return -1;if(stage_transition(b,exists?&old:NULL,&r,1))return -1;if(out)*out=r;return 0;}
int qrx_net_registry_stage_renew(QrxDB *db,QrxDBBatch *b,const char *name,const char *owner,uint64_t seq,uint64_t h,uint64_t exp,QrxDomainRecord *out){QrxDomainRecord old,r;if(!b||build_renew(db,name,owner,seq,h,exp,&old,&r)||stage_transition(b,&old,&r,0))return -1;if(out)*out=r;return 0;}
int qrx_net_registry_stage_update(QrxDB *db,QrxDBBatch *b,const char *name,const char *owner,uint64_t seq,uint64_t h,const QrxDomainUpdate *u,QrxDomainRecord *out){QrxDomainRecord old,r;if(!b||build_update(db,name,owner,seq,h,u,&old,&r)||stage_transition(b,&old,&r,0))return -1;if(out)*out=r;return 0;}
int qrx_net_registry_stage_transfer(QrxDB *db,QrxDBBatch *b,const char *name,const char *owner,uint64_t seq,uint64_t h,const char *new_owner,QrxDomainRecord *out){QrxDomainRecord old,r;if(!b||build_transfer(db,name,owner,seq,h,new_owner,&old,&r)||stage_transition(b,&old,&r,0))return -1;if(out)*out=r;return 0;}

int qrx_net_registry_register(QrxDB *db,const char *name,const char *owner,const char *qub,const uint8_t *web,const uint8_t *pub,uint64_t h,uint64_t exp,QrxDomainRecord *out){QrxDomainRecord old,r;int exists=0;if(build_register(db,name,owner,qub,web,pub,h,exp,&old,&exists,&r)||commit_transition(db,exists?&old:NULL,&r,1))return -1;if(out)*out=r;return 0;}
int qrx_net_registry_renew(QrxDB *db,const char *name,const char *owner,uint64_t seq,uint64_t h,uint64_t exp,QrxDomainRecord *out){QrxDomainRecord old,r;if(build_renew(db,name,owner,seq,h,exp,&old,&r)||commit_transition(db,&old,&r,0))return -1;if(out)*out=r;return 0;}
int qrx_net_registry_update(QrxDB *db,const char *name,const char *owner,uint64_t seq,uint64_t h,const QrxDomainUpdate *u,QrxDomainRecord *out){QrxDomainRecord old,r;if(build_update(db,name,owner,seq,h,u,&old,&r)||commit_transition(db,&old,&r,0))return -1;if(out)*out=r;return 0;}
int qrx_net_registry_transfer(QrxDB *db,const char *name,const char *owner,uint64_t seq,uint64_t h,const char *new_owner,QrxDomainRecord *out){QrxDomainRecord old,r;if(build_transfer(db,name,owner,seq,h,new_owner,&old,&r)||commit_transition(db,&old,&r,0))return -1;if(out)*out=r;return 0;}
