#include "net/qrx_net_consensus.h"
#include "net/qrx_net_name.h"
#include "net/qrx_net_registry.h"
#include "net/qrx_net_ads.h"
#include "resource/qrx_storage_consensus.h"
#include "resource/qrx_storage_market.h"
#include "resource/qrx_resource.h"
#include "chain_params.h"
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int safe_token(const char*s,size_t n){if(!s||!*s||strlen(s)>=n)return 0;for(const unsigned char*p=(const unsigned char*)s;*p;p++)if(*p=='|'||*p==';'||*p=='\n'||*p=='\r'||*p<32)return 0;return 1;}
static char *field(const char *payload,const char *key){if(!payload||!key)return NULL;size_t k=strlen(key);const char*p=payload;while(*p){while(*p==';')p++;const char*e=strchr(p,';');size_t n=e?(size_t)(e-p):strlen(p);if(n>k&&!memcmp(p,key,k)&&p[k]=='='){char*v=malloc(n-k);if(!v)return NULL;memcpy(v,p+k+1,n-k-1);v[n-k-1]=0;return v;}if(!e)break;p=e+1;}return NULL;}
static int parse_u64(const char*s,uint64_t*out){if(!s||!*s||!out)return -1;char*e=NULL;unsigned long long v=strtoull(s,&e,10);if(!e||*e)return -1;*out=v;return 0;}
static int hv(char c){return c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:c>='A'&&c<='F'?c-'A'+10:-1;}
static int unhex64(const char*s,uint8_t o[64]){if(!s||strlen(s)!=128)return -1;for(int i=0;i<64;i++){int a=hv(s[i*2]),b=hv(s[i*2+1]);if(a<0||b<0)return -1;o[i]=(uint8_t)((a<<4)|b);}return 0;}
static void hex64(const uint8_t b[64],char o[129]){static const char h[]="0123456789abcdef";for(int i=0;i<64;i++){o[i*2]=h[b[i]>>4];o[i*2+1]=h[b[i]&15];}o[128]=0;}
static int db_u64(QrxDB*db,const char*k,uint64_t d,uint64_t*out){char b[128];if(qrxdb_get(db,k,b,sizeof(b))){*out=d;return 0;}return parse_u64(b,out);}
static int batch_u64(QrxDBBatch*b,const char*k,uint64_t v){char s[64];snprintf(s,sizeof(s),"%llu",(unsigned long long)v);return qrxdb_batch_put(b,k,s);}
static int pool_adjust(QrxDB*db,QrxDBBatch*b,const char*k,int64_t d){uint64_t x=0;if(db_u64(db,k,0,&x))return -1;if(d<0){uint64_t z=(uint64_t)(-d);if(x<z)return -1;return batch_u64(b,k,x-z);}uint64_t z=(uint64_t)d;if(UINT64_MAX-x<z)return -1;return batch_u64(b,k,x+z);}
static void owner_count_key(const char*owner,char out[360]){snprintf(out,360,"qrxnet/owner_count/%s",owner);}
static int owner_count(QrxDB*db,const char*owner,uint64_t*out){char k[360];owner_count_key(owner,k);return db_u64(db,k,0,out);}
static int stage_owner_count(QrxDB*db,QrxDBBatch*b,const char*owner,int delta){char k[360];uint64_t n=0;owner_count_key(owner,k);if(db_u64(db,k,0,&n))return -1;if(delta<0){if(n<(uint64_t)(-delta))return -1;n-=(uint64_t)(-delta);}else{if(UINT64_MAX-n<(uint64_t)delta)return -1;n+=(uint64_t)delta;}return batch_u64(b,k,n);}
static void bond_key(const uint8_t hash[64],char out[220]){char h[129];hex64(hash,h);snprintf(out,220,"qrxnet/bond/%s",h);}
static uint64_t base_price(const char*chain,uint64_t h){long long x=qrx_chain_get_ll_at_height_or_default(chain,(long long)h,"qrxnet_domain_base_annual_atoms",(long long)QRX_DOMAIN_DEFAULT_BASE_ANNUAL_ATOMS);return x>0?(uint64_t)x:QRX_DOMAIN_DEFAULT_BASE_ANNUAL_ATOMS;}
static int addmul(uint64_t a,uint64_t b,uint64_t c,uint64_t*out){if(b&&a>UINT64_MAX/b)return -1;uint64_t x=a*b;if(UINT64_MAX-x<c)return -1;*out=x+c;return 0;}
static QrxRecordUpdateMode mode(const char*s){if(!s||!strcmp(s,"KEEP"))return QRX_RECORD_KEEP;if(!strcmp(s,"SET"))return QRX_RECORD_SET;if(!strcmp(s,"CLEAR"))return QRX_RECORD_CLEAR;return (QrxRecordUpdateMode)-1;}

static int ad_campaign_put(QrxDBBatch*b,const QrxAdCampaign*c){char k[300],v[1800],cr[129];hex64(c->creative_root,cr);snprintf(k,sizeof(k),"qrxnet/ad/campaign/%s",c->campaign_id);int n=snprintf(v,sizeof(v),"1|%s|%s|%s|%s|%llu|%llu|%llu|%llu|%llu|%llu|%u|0",c->advertiser,c->target_url,c->category,cr,(unsigned long long)c->start_height,(unsigned long long)c->end_height,(unsigned long long)c->cost_per_impression_atoms,(unsigned long long)c->total_budget_atoms,(unsigned long long)c->remaining_budget_atoms,(unsigned long long)c->settled_impressions,c->status);return n>0&&(size_t)n<sizeof(v)?qrxdb_batch_put(b,k,v):-1;}
static int ad_accrual_add(QrxDB*db,QrxDBBatch*b,const char*addr,uint64_t add){if(!safe_token(addr,160)||!add)return -1;char k[360];snprintf(k,sizeof(k),"qrxnet/ad/reward/%s",addr);uint64_t x=0;if(db_u64(db,k,0,&x)||UINT64_MAX-x<add)return -1;return batch_u64(b,k,x+add);}
typedef struct{QrxDB*db;char providers[8][129];size_t n;}AdReceiptScan;
static int ad_receipt_cb(const char*k,const char*v,uint32_t vl,void*vp){(void)v;(void)vl;AdReceiptScan*c=vp;const char*p=strrchr(k,'/');if(!p||!p[1]||c->n>=8)return 0;QrxStorageProviderState ps;if(qrx_storage_provider_get(c->db,p+1,&ps)||ps.status!=QRX_PROVIDER_ACTIVE)return 0;for(size_t i=0;i<c->n;i++)if(!strcmp(c->providers[i],p+1))return 0;snprintf(c->providers[c->n++],129,"%s",p+1);return 0;}
static int ad_receipts_diverse(QrxDB*db,const char*campaign,const char*imp,char out[3][129]){char pre[500];snprintf(pre,sizeof(pre),"qrxnet/ad/receipt/%s/%s/",campaign,imp);AdReceiptScan c={.db=db};if(qrxdb_scan_prefix(db,pre,ad_receipt_cb,&c)<0||c.n<QRX_AD_MIN_PROVIDER_RECEIPTS)return -1;for(size_t i=0;i<c.n;i++)for(size_t j=i+1;j<c.n;j++){QrxStorageProviderState a,b;if(qrx_storage_provider_get(db,c.providers[i],&a)||qrx_storage_provider_get(db,c.providers[j],&b))continue;const char*ao=a.operator_id[0]?a.operator_id:c.providers[i],*bo=b.operator_id[0]?b.operator_id:c.providers[j];if(!strcmp(ao,bo))continue;const char*aa=a.attested_asn[0]?a.attested_asn:a.claimed_asn,*ba=b.attested_asn[0]?b.attested_asn:b.claimed_asn;const char*ar=a.attested_region[0]?a.attested_region:a.claimed_region,*br=b.attested_region[0]?b.attested_region:b.claimed_region;if(*aa&&*ba&&!strcmp(aa,ba))continue;if(*ar&&*br&&!strcmp(ar,br))continue;for(size_t z=0;z<c.n;z++)if(z!=i&&z!=j){QrxStorageProviderState d;if(qrx_storage_provider_get(db,c.providers[z],&d))continue;const char*do_=d.operator_id[0]?d.operator_id:c.providers[z];const char*da=d.attested_asn[0]?d.attested_asn:d.claimed_asn,*dr=d.attested_region[0]?d.attested_region:d.claimed_region;if(!strcmp(do_,ao)||!strcmp(do_,bo))continue;if(*da&&((*aa&&!strcmp(da,aa))||(*ba&&!strcmp(da,ba))))continue;if(*dr&&((*ar&&!strcmp(dr,ar))||(*br&&!strcmp(dr,br))))continue;snprintf(out[0],129,"%s",c.providers[i]);snprintf(out[1],129,"%s",c.providers[j]);snprintf(out[2],129,"%s",c.providers[z]);return 0;}}return -1;}

static int prepare_db(QrxDB*db,const char*chain,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,uint64_t h,QrxServiceEconomicEffect*e){memset(e,0,sizeof(*e));
    /* Consensus-layer gate, not merely a CLI admission check. Domains/hosting
     * require QRX_NET_V1; advertising additionally requires ADVERTISING_V1. */
    if(!qrx_net_protocol_enabled_at_height(chain,(long long)h))return -1;
    if(!strncmp(tx,"AD_",3)&&!qrx_advertising_protocol_enabled_at_height(chain,(long long)h))return -1;
    if(!strcmp(tx,"DOMAIN_REGISTER")){if(strcmp(from,to))return -1;char*name=field(p,"name"),*ys=field(p,"years");uint64_t years=0,count=0;if(!name||parse_u64(ys,&years)||years<1||years>5||owner_count(db,from,&count)){free(name);free(ys);return -1;}QrxDomainPrice pr;if(qrx_domain_price(name,base_price(chain,h),count,&pr)||pr.mode!=QRX_DOMAIN_PRICE_FIXED){free(name);free(ys);return -1;}uint64_t rent=0,total=0;if(pr.annual_atoms>UINT64_MAX/years){free(name);free(ys);return -1;}rent=pr.annual_atoms*years;if(addmul(1,rent,pr.reservation_bond_atoms,&total)||amount!=total){free(name);free(ys);return -1;}QrxDomainRecord old;if(qrx_net_registry_get(db,name,&old)==0){char bk[220];bond_key(old.name_hash,bk);uint64_t oldbond=0;db_u64(db,bk,0,&oldbond);if(oldbond){free(name);free(ys);return -1;}}QrxDomainFeeSplit sp;if(qrx_domain_fee_split(rent,&sp)){free(name);free(ys);return -1;}e->debit_atoms=amount;e->development_credit_atoms=sp.development_atoms;e->protocol_fee_atoms=sp.registry_atoms;free(name);free(ys);return 0;}
    if(!strcmp(tx,"DOMAIN_RENEW")){if(strcmp(from,to))return -1;char*name=field(p,"name"),*seqs=field(p,"sequence"),*ys=field(p,"years");uint64_t seq=0,years=0,count=0;QrxDomainRecord r;if(!name||parse_u64(seqs,&seq)||parse_u64(ys,&years)||years<1||years>5||qrx_net_registry_get(db,name,&r)||strcmp(r.owner,from)||r.sequence!=seq||!qrx_domain_is_active(&r,h)||owner_count(db,from,&count)){free(name);free(seqs);free(ys);return -1;}QrxDomainPrice pr;if(qrx_domain_price(name,base_price(chain,h),count,&pr)||pr.mode!=QRX_DOMAIN_PRICE_FIXED||pr.annual_atoms>UINT64_MAX/years){free(name);free(seqs);free(ys);return -1;}uint64_t rent=pr.annual_atoms*years;if(amount!=rent){free(name);free(seqs);free(ys);return -1;}QrxDomainFeeSplit sp;qrx_domain_fee_split(rent,&sp);e->debit_atoms=rent;e->development_credit_atoms=sp.development_atoms;e->protocol_fee_atoms=sp.registry_atoms;free(name);free(seqs);free(ys);return 0;}
    if(!strcmp(tx,"DOMAIN_UPDATE")){if(amount||strcmp(from,to))return -1;char*name=field(p,"name"),*seqs=field(p,"sequence");uint64_t seq=0;QrxDomainRecord r;int rc=name&&!parse_u64(seqs,&seq)&&!qrx_net_registry_get(db,name,&r)&&!strcmp(r.owner,from)&&r.sequence==seq&&qrx_domain_is_active(&r,h)?0:-1;free(name);free(seqs);return rc;}
    if(!strcmp(tx,"DOMAIN_TRANSFER")){if(amount)return -1;char*name=field(p,"name"),*seqs=field(p,"sequence");uint64_t seq=0;QrxDomainRecord r;int rc=name&&safe_token(to,160)&&strcmp(from,to)&&!parse_u64(seqs,&seq)&&!qrx_net_registry_get(db,name,&r)&&!strcmp(r.owner,from)&&r.sequence==seq&&qrx_domain_is_active(&r,h)?0:-1;free(name);free(seqs);return rc;}
    if(!strcmp(tx,"DOMAIN_RELEASE")){if(amount||strcmp(from,to))return -1;char*name=field(p,"name"),*seqs=field(p,"sequence");uint64_t seq=0;QrxDomainRecord r;int rc=-1;if(name&&!parse_u64(seqs,&seq)&&!qrx_net_registry_get(db,name,&r)&&!strcmp(r.owner,from)&&r.sequence==seq&&!qrx_domain_is_active(&r,h)&&!qrx_domain_in_grace(&r,h)){char bk[220];bond_key(r.name_hash,bk);uint64_t bond=0;if(!db_u64(db,bk,0,&bond)&&bond){e->self_credit_atoms=bond;rc=0;}}free(name);free(seqs);return rc;}
    if(!strcmp(tx,"AD_CAMPAIGN_CREATE")){if(strcmp(from,to)||amount<QRX_AD_MIN_IMPRESSION_ATOMS)return -1;char*id=field(p,"campaign_id"),*url=field(p,"target_url"),*cat=field(p,"category"),*cr=field(p,"creative_root_hex"),*st=field(p,"start_height"),*en=field(p,"end_height"),*cp=field(p,"cost_per_impression_atoms");uint64_t sh=0,eh=0,cost=0;QrxAdCampaign old;int rc=id&&safe_token(id,129)&&url&&safe_token(url,512)&&cat&&safe_token(cat,48)&&cr&&strlen(cr)==128&&!parse_u64(st,&sh)&&!parse_u64(en,&eh)&&!parse_u64(cp,&cost)&&sh>=h&&eh>sh&&cost>=QRX_AD_MIN_IMPRESSION_ATOMS&&amount>=cost&&qrx_ad_campaign_get(db,id,&old)!=0?0:-1;if(!rc)e->debit_atoms=amount;free(id);free(url);free(cat);free(cr);free(st);free(en);free(cp);return rc;}
    if(!strcmp(tx,"AD_DELIVERY_RECEIPT")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"campaign_id"),*imp=field(p,"impression_id"),*pub=field(p,"publisher_domain"),*viewer=field(p,"viewer_reward_address"),*vh=field(p,"viewer_token_hash"),*cr=field(p,"creative_root_hex"),*ep=field(p,"epoch");uint64_t epoch=0;QrxAdCampaign c;QrxStorageProviderState ps;int rc=-1;if(cid&&imp&&pub&&viewer&&vh&&cr&&ep&&safe_token(imp,129)&&safe_token(viewer,160)&&safe_token(vh,129)&&!parse_u64(ep,&epoch)&&epoch==h/QRX_AD_FREQUENCY_EPOCH_BLOCKS&&!qrx_ad_campaign_get(db,cid,&c)&&h>=c.start_height&&h<=c.end_height&&c.remaining_budget_atoms>=c.cost_per_impression_atoms&&!qrx_storage_provider_get(db,from,&ps)&&ps.status==QRX_PROVIDER_ACTIVE){char ch[129];hex64(c.creative_root,ch);QrxDomainRecord dr;if(!strcmp(ch,cr)&&!qrx_net_registry_get(db,pub,&dr)&&qrx_domain_is_active(&dr,h))rc=0;}free(cid);free(imp);free(pub);free(viewer);free(vh);free(cr);free(ep);return rc;}
    if(!strcmp(tx,"AD_IMPRESSION_SETTLE")){if(amount)return -1;char*cid=field(p,"campaign_id"),*imp=field(p,"impression_id"),*pub=field(p,"publisher_domain"),*viewer=field(p,"viewer_reward_address"),*vh=field(p,"viewer_token_hash"),*ep=field(p,"epoch");uint64_t epoch=0;QrxAdCampaign c;QrxDomainRecord dr;char providers[3][129];int rc=-1;if(cid&&imp&&pub&&viewer&&vh&&ep&&safe_token(imp,129)&&safe_token(viewer,160)&&safe_token(vh,129)&&!parse_u64(ep,&epoch)&&epoch==h/QRX_AD_FREQUENCY_EPOCH_BLOCKS&&!qrx_ad_campaign_get(db,cid,&c)&&h>=c.start_height&&h<=c.end_height&&c.remaining_budget_atoms>=c.cost_per_impression_atoms&&!qrx_net_registry_get(db,pub,&dr)&&qrx_domain_is_active(&dr,h)&&!strcmp(dr.owner,from)&&!ad_receipts_diverse(db,cid,imp,providers)){char sk[600],vk[700],tmp[8];snprintf(sk,sizeof(sk),"qrxnet/ad/settled/%s/%s",cid,imp);snprintf(vk,sizeof(vk),"qrxnet/ad/viewer/%s/%s/%020llu",cid,vh,(unsigned long long)epoch);if(qrxdb_get(db,sk,tmp,sizeof(tmp))!=0&&qrxdb_get(db,vk,tmp,sizeof(tmp))!=0){QrxAdRewardSplit sp;if(!qrx_ad_reward_split(c.cost_per_impression_atoms,&sp)){e->development_credit_atoms=sp.development_atoms;e->protocol_fee_atoms=sp.protocol_atoms;rc=0;}}}free(cid);free(imp);free(pub);free(viewer);free(vh);free(ep);return rc;}
    if(!strcmp(tx,"AD_REWARD_CLAIM")){if(amount||strcmp(from,to))return -1;char k[360];snprintf(k,sizeof(k),"qrxnet/ad/reward/%s",from);uint64_t x=0;if(db_u64(db,k,0,&x)||!x)return -1;e->self_credit_atoms=x;return 0;}
    if(!strcmp(tx,"AD_CAMPAIGN_CLOSE")){if(amount||strcmp(from,to))return -1;char*cid=field(p,"campaign_id");QrxAdCampaign c;int rc=cid&&!qrx_ad_campaign_get(db,cid,&c)&&!strcmp(c.advertiser,from)&&h>c.end_height&&c.status==1?0:-1;if(!rc)e->self_credit_atoms=c.remaining_budget_atoms;free(cid);return rc;}
    return -1;
}

int qrx_net_consensus_prepare(const char*chain,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,const char*txid,uint64_t h,QrxServiceEconomicEffect*e){(void)txid;if(!chain||!tx||!from||!to||!p||!e)return -1;QrxDB db;if(qrxdb_init(&db,chain))return -1;int rc=prepare_db(&db,chain,tx,from,to,amount,p,h,e);qrxdb_close(&db);return rc;}

int qrx_net_consensus_stage(QrxDB*db,QrxDBBatch*b,const char*chain,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,const char*txid,uint64_t h){if(!db||!b||!chain||!tx||!from||!to||!p||!txid)return -1;QrxServiceEconomicEffect e;if(prepare_db(db,chain,tx,from,to,amount,p,h,&e))return -1;
    if(!strcmp(tx,"DOMAIN_REGISTER")){char*name=field(p,"name"),*ys=field(p,"years"),*qub=field(p,"qub_address"),*web=field(p,"web_manifest_root_hex"),*pub=field(p,"publishing_commitment_hex");uint64_t years=0,count=0;parse_u64(ys,&years);owner_count(db,from,&count);QrxDomainPrice pr;qrx_domain_price(name,base_price(chain,h),count,&pr);uint64_t rent=pr.annual_atoms*years,bond=amount-rent;uint8_t wr[64],pc[64];uint8_t *wp=NULL,*pp=NULL;if(web&&strcmp(web,"-")&&*web){if(unhex64(web,wr)){free(name);free(ys);free(qub);free(web);free(pub);return -1;}wp=wr;}if(pub&&strcmp(pub,"-")&&*pub){if(unhex64(pub,pc)){free(name);free(ys);free(qub);free(web);free(pub);return -1;}pp=pc;}QrxDomainRecord r;uint64_t expiry=h+years*QRX_DOMAIN_YEAR_BLOCKS;if(expiry<h||qrx_net_registry_stage_register(db,b,name,from,qub&&strcmp(qub,"-")?qub:NULL,wp,pp,h,expiry,&r)){free(name);free(ys);free(qub);free(web);free(pub);return -1;}char bk[220];bond_key(r.name_hash,bk);int rc=batch_u64(b,bk,bond)||pool_adjust(db,b,"consensus:qrxnet:domain_bonds",(int64_t)bond)||stage_owner_count(db,b,from,1);free(name);free(ys);free(qub);free(web);free(pub);return rc;}
    if(!strcmp(tx,"DOMAIN_RENEW")){char*name=field(p,"name"),*seqs=field(p,"sequence"),*ys=field(p,"years");uint64_t seq=0,years=0;parse_u64(seqs,&seq);parse_u64(ys,&years);QrxDomainRecord r;if(qrx_net_registry_get(db,name,&r)){free(name);free(seqs);free(ys);return -1;}uint64_t expiry=r.expiry_height+years*QRX_DOMAIN_YEAR_BLOCKS;if(expiry<r.expiry_height){free(name);free(seqs);free(ys);return -1;}int rc=qrx_net_registry_stage_renew(db,b,name,from,seq,h,expiry,NULL);free(name);free(seqs);free(ys);return rc;}
    if(!strcmp(tx,"DOMAIN_UPDATE")){char*name=field(p,"name"),*seqs=field(p,"sequence"),*qm=field(p,"qub_mode"),*q=field(p,"qub_address"),*wm=field(p,"web_mode"),*w=field(p,"web_manifest_root_hex"),*pm=field(p,"publishing_mode"),*pc=field(p,"publishing_commitment_hex");uint64_t seq=0;parse_u64(seqs,&seq);QrxDomainUpdate u;memset(&u,0,sizeof(u));u.qub_mode=mode(qm);u.web_mode=mode(wm);u.publishing_mode=mode(pm);uint8_t wr[64],pr[64];if((int)u.qub_mode<0||(int)u.web_mode<0||(int)u.publishing_mode<0){free(name);free(seqs);free(qm);free(q);free(wm);free(w);free(pm);free(pc);return -1;}if(u.qub_mode==QRX_RECORD_SET)u.qub_address=q;if(u.web_mode==QRX_RECORD_SET){if(unhex64(w,wr)){free(name);free(seqs);free(qm);free(q);free(wm);free(w);free(pm);free(pc);return -1;}u.web_manifest_root=wr;}if(u.publishing_mode==QRX_RECORD_SET){if(unhex64(pc,pr)){free(name);free(seqs);free(qm);free(q);free(wm);free(w);free(pm);free(pc);return -1;}u.publishing_key_commitment=pr;}int rc=qrx_net_registry_stage_update(db,b,name,from,seq,h,&u,NULL);free(name);free(seqs);free(qm);free(q);free(wm);free(w);free(pm);free(pc);return rc;}
    if(!strcmp(tx,"DOMAIN_TRANSFER")){char*name=field(p,"name"),*seqs=field(p,"sequence");uint64_t seq=0;parse_u64(seqs,&seq);int rc=qrx_net_registry_stage_transfer(db,b,name,from,seq,h,to,NULL);if(!rc)rc=stage_owner_count(db,b,from,-1)||stage_owner_count(db,b,to,1);free(name);free(seqs);return rc;}
    if(!strcmp(tx,"DOMAIN_RELEASE")){char*name=field(p,"name");QrxDomainRecord r;if(qrx_net_registry_get(db,name,&r)){free(name);return -1;}char bk[220],rk[260];bond_key(r.name_hash,bk);char hh[129];hex64(r.name_hash,hh);snprintf(rk,sizeof(rk),"qrxnet/released/%s/%020llu",hh,(unsigned long long)r.sequence);uint64_t bond=e.self_credit_atoms;int rc=batch_u64(b,bk,0)||pool_adjust(db,b,"consensus:qrxnet:domain_bonds",-(int64_t)bond)||qrxdb_batch_put(b,rk,txid)||stage_owner_count(db,b,from,-1);free(name);return rc;}
    if(!strcmp(tx,"AD_CAMPAIGN_CREATE")){char*id=field(p,"campaign_id"),*url=field(p,"target_url"),*cat=field(p,"category"),*cr=field(p,"creative_root_hex"),*st=field(p,"start_height"),*en=field(p,"end_height"),*cp=field(p,"cost_per_impression_atoms");QrxAdCampaign c;memset(&c,0,sizeof(c));snprintf(c.campaign_id,sizeof(c.campaign_id),"%s",id);snprintf(c.advertiser,sizeof(c.advertiser),"%s",from);snprintf(c.target_url,sizeof(c.target_url),"%s",url);snprintf(c.category,sizeof(c.category),"%s",cat);unhex64(cr,c.creative_root);parse_u64(st,&c.start_height);parse_u64(en,&c.end_height);parse_u64(cp,&c.cost_per_impression_atoms);c.total_budget_atoms=c.remaining_budget_atoms=amount;c.status=1;int rc=ad_campaign_put(b,&c)||pool_adjust(db,b,"consensus:qrxnet:ad_escrow",(int64_t)amount);free(id);free(url);free(cat);free(cr);free(st);free(en);free(cp);return rc;}
    if(!strcmp(tx,"AD_DELIVERY_RECEIPT")){char*cid=field(p,"campaign_id"),*imp=field(p,"impression_id");char k[700];snprintf(k,sizeof(k),"qrxnet/ad/receipt/%s/%s/%s",cid,imp,from);char tmp[8];int rc=qrxdb_get(db,k,tmp,sizeof(tmp))==0?-1:qrxdb_batch_put(b,k,txid);free(cid);free(imp);return rc;}
    if(!strcmp(tx,"AD_IMPRESSION_SETTLE")){char*cid=field(p,"campaign_id"),*imp=field(p,"impression_id"),*pub=field(p,"publisher_domain"),*viewer=field(p,"viewer_reward_address"),*vh=field(p,"viewer_token_hash"),*ep=field(p,"epoch");uint64_t epoch=0;parse_u64(ep,&epoch);QrxAdCampaign c;qrx_ad_campaign_get(db,cid,&c);QrxAdRewardSplit sp;qrx_ad_reward_split(c.cost_per_impression_atoms,&sp);char providers[3][129];if(ad_receipts_diverse(db,cid,imp,providers)){free(cid);free(imp);free(pub);free(viewer);free(vh);free(ep);return -1;}uint64_t each=sp.delivery_atoms/3,rem=sp.delivery_atoms-each*3;QrxDomainRecord dr;if(qrx_net_registry_get(db,pub,&dr)){free(cid);free(imp);free(pub);free(viewer);free(vh);free(ep);return -1;}int rc=0;for(int i=0;i<3;i++)rc|=ad_accrual_add(db,b,providers[i],each+(i==0?rem:0));rc|=ad_accrual_add(db,b,dr.owner,sp.publisher_atoms);rc|=ad_accrual_add(db,b,viewer,sp.viewer_atoms);c.remaining_budget_atoms-=c.cost_per_impression_atoms;c.settled_impressions++;rc|=ad_campaign_put(b,&c);char sk[600],vk[700];snprintf(sk,sizeof(sk),"qrxnet/ad/settled/%s/%s",cid,imp);snprintf(vk,sizeof(vk),"qrxnet/ad/viewer/%s/%s/%020llu",cid,vh,(unsigned long long)epoch);rc|=qrxdb_batch_put(b,sk,txid)||qrxdb_batch_put(b,vk,txid);uint64_t immediate=sp.protocol_atoms+sp.development_atoms;rc|=pool_adjust(db,b,"consensus:qrxnet:ad_escrow",-(int64_t)immediate);free(cid);free(imp);free(pub);free(viewer);free(vh);free(ep);return rc;}
    if(!strcmp(tx,"AD_REWARD_CLAIM")){char k[360];snprintf(k,sizeof(k),"qrxnet/ad/reward/%s",from);uint64_t x=e.self_credit_atoms;return batch_u64(b,k,0)||pool_adjust(db,b,"consensus:qrxnet:ad_escrow",-(int64_t)x);}
    if(!strcmp(tx,"AD_CAMPAIGN_CLOSE")){char*cid=field(p,"campaign_id");QrxAdCampaign c;if(qrx_ad_campaign_get(db,cid,&c)){free(cid);return -1;}uint64_t refund=e.self_credit_atoms;c.remaining_budget_atoms=0;c.status=2;int rc=ad_campaign_put(b,&c)||pool_adjust(db,b,"consensus:qrxnet:ad_escrow",-(int64_t)refund);free(cid);return rc;}
    return -1;
}
