#include "net/qrx_net_site.h"
#include "storage/qrx_merkle.h"
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
static int safe_path(const char *p){if(!p||!*p||strlen(p)>QRX_NET_SITE_PATH_MAX||p[0]=='/'||strstr(p,".."))return 0;for(const unsigned char *s=(const unsigned char*)p;*s;s++)if(*s<32||*s=='\\')return 0;return 1;}
static void p64(uint8_t o[8],uint64_t v){for(int i=7;i>=0;i--){o[i]=(uint8_t)v;v>>=8;}}
static int sha3(const void *d,size_t n,uint8_t out[64]){EVP_MD_CTX *c=EVP_MD_CTX_new();unsigned int z=0;int rc=-1;if(c&&EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)==1&&EVP_DigestUpdate(c,"QRX-NET-CONTENT-V1",18)==1&&EVP_DigestUpdate(c,d,n)==1&&EVP_DigestFinal_ex(c,out,&z)==1&&z==64)rc=0;EVP_MD_CTX_free(c);return rc;}
static int cmp_entry(const void *a,const void *b){return strcmp(((const QrxNetSiteFileEntry*)a)->path,((const QrxNetSiteFileEntry*)b)->path);}
static int bundle_root(QrxNetSiteFileEntry *e,size_t n,uint8_t out[64]){if(!e||!n||n>QRX_NET_SITE_MAX_FILES)return -1;qsort(e,n,sizeof(*e),cmp_entry);uint8_t *leaves=malloc(n*64);if(!leaves)return -1;for(size_t i=0;i<n;i++){if(i&&strcmp(e[i-1].path,e[i].path)==0){free(leaves);return -1;}uint8_t buf[QRX_NET_SITE_PATH_MAX+1+65+8+64+64];size_t o=0,l=strlen(e[i].path);memcpy(buf+o,e[i].path,l);o+=l;buf[o++]=0;memcpy(buf+o,e[i].object_id,64);o+=64;uint8_t sz[8];p64(sz,e[i].size);memcpy(buf+o,sz,8);o+=8;memcpy(buf+o,e[i].content_hash,64);o+=64;memcpy(buf+o,e[i].merkle_root,64);o+=64;if(qrx_merkle_leaf_hash(i,buf,o,leaves+i*64)){free(leaves);return -1;}}int rc=qrx_merkle_root_from_leaves(leaves,n,out);free(leaves);return rc;}
int qrx_net_site_manifest_hash(const QrxNetSiteManifest *m,uint8_t out[64]){if(!m||!out||m->version!=1||!m->domain[0]||!m->file_count)return -1;EVP_MD_CTX *c=EVP_MD_CTX_new();unsigned int z=0;uint8_t seq[8],h[8],fc[8];p64(seq,m->sequence);p64(h,m->published_height);p64(fc,m->file_count);int rc=-1;if(c&&EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)==1&&EVP_DigestUpdate(c,"QRX-NET-SITE-MANIFEST-V1",24)==1&&EVP_DigestUpdate(c,m->domain,strlen(m->domain))==1&&EVP_DigestUpdate(c,seq,8)==1&&EVP_DigestUpdate(c,h,8)==1&&EVP_DigestUpdate(c,fc,8)==1&&EVP_DigestUpdate(c,m->bundle_root,64)==1&&EVP_DigestFinal_ex(c,out,&z)==1&&z==64)rc=0;EVP_MD_CTX_free(c);return rc;}

static int capture_public_der(EVP_PKEY *key,QrxNetPublishedSite *out){
    if(!key||!out)return -1;int n=i2d_PUBKEY(key,NULL);if(n<=0||n>65536)return -1;
    out->publishing_public_der=malloc((size_t)n);if(!out->publishing_public_der)return -1;
    unsigned char *p=out->publishing_public_der;if(i2d_PUBKEY(key,&p)!=n){free(out->publishing_public_der);out->publishing_public_der=NULL;return -1;}
    out->publishing_public_der_len=(size_t)n;return 0;
}
static EVP_PKEY *embedded_public(const QrxNetPublishedSite *s){
    if(!s||!s->publishing_public_der||!s->publishing_public_der_len)return NULL;
    const unsigned char *p=s->publishing_public_der;return d2i_PUBKEY(NULL,&p,(long)s->publishing_public_der_len);
}
static int sign_hash(EVP_PKEY *k,const uint8_t h[64],uint8_t **sig,size_t *len){EVP_MD_CTX *c=EVP_MD_CTX_new();if(!c)return -1;size_t n=0;uint8_t *s=NULL;int rc=-1;if(EVP_DigestSignInit_ex(c,NULL,NULL,NULL,NULL,k,NULL)!=1||EVP_DigestSign(c,NULL,&n,h,64)!=1||!n)goto done;s=malloc(n);if(!s)goto done;if(EVP_DigestSign(c,s,&n,h,64)!=1)goto done;*sig=s;*len=n;s=NULL;rc=0;done:free(s);EVP_MD_CTX_free(c);return rc;}
int qrx_net_site_publish_entries(const char *domain,uint64_t seq,uint64_t height,const QrxNetSiteFileEntry *entries,size_t n,EVP_PKEY *key,QrxNetPublishedSite *out){
    if(!domain||!seq||!entries||!n||n>QRX_NET_SITE_MAX_FILES||!key||!out)return -1;
    char norm[254];if(qrx_domain_normalize(domain,norm))return -1;
    memset(out,0,sizeof(*out));out->files=calloc(n,sizeof(*out->files));if(!out->files)return -1;
    for(size_t i=0;i<n;i++){if(!safe_path(entries[i].path)||strlen(entries[i].object_id)!=64){qrx_net_published_site_free(out);return -1;}out->files[i]=entries[i];}
    out->manifest.version=1;strcpy(out->manifest.domain,norm);out->manifest.sequence=seq;out->manifest.published_height=height;out->manifest.file_count=(uint32_t)n;
    if(bundle_root(out->files,n,out->manifest.bundle_root)){qrx_net_published_site_free(out);return -1;}
    uint8_t mh[64];if(capture_public_der(key,out)||qrx_net_site_manifest_hash(&out->manifest,mh)||sign_hash(key,mh,&out->signature,&out->signature_len)){qrx_net_published_site_free(out);return -1;}
    return 0;
}
int qrx_net_site_publish(QrxStorageFs *fs,const char *domain,uint64_t seq,uint64_t height,const QrxNetSiteFileInput *f,size_t n,EVP_PKEY *key,QrxNetPublishedSite *out){if(!fs||!domain||!seq||!f||!n||n>QRX_NET_SITE_MAX_FILES||!key||!out)return -1;char norm[254];if(qrx_domain_normalize(domain,norm))return -1;memset(out,0,sizeof(*out));out->files=calloc(n,sizeof(*out->files));if(!out->files)return -1;for(size_t i=0;i<n;i++){if(!safe_path(f[i].path)||(!f[i].data&&f[i].data_len)){qrx_net_published_site_free(out);return -1;}QrxNetSiteFileEntry *e=&out->files[i];strcpy(e->path,f[i].path);e->size=f[i].data_len;if(qrx_storage_fs_put(fs,f[i].data,f[i].data_len,e->object_id)||sha3(f[i].data,f[i].data_len,e->content_hash)||qrx_merkle_root_from_chunks(f[i].data,f[i].data_len,64*1024,e->merkle_root,NULL)){qrx_net_published_site_free(out);return -1;}}
    out->manifest.version=1;strcpy(out->manifest.domain,norm);out->manifest.sequence=seq;out->manifest.published_height=height;out->manifest.file_count=(uint32_t)n;if(bundle_root(out->files,n,out->manifest.bundle_root)){qrx_net_published_site_free(out);return -1;}uint8_t mh[64];if(capture_public_der(key,out)||qrx_net_site_manifest_hash(&out->manifest,mh)||sign_hash(key,mh,&out->signature,&out->signature_len)){qrx_net_published_site_free(out);return -1;}return 0;}
int qrx_net_site_verify_file(const QrxNetSiteFileEntry *e,const uint8_t *d,size_t n){if(!e||(!d&&n)||n!=e->size)return -1;uint8_t h[64],r[64];if(sha3(d,n,h)||qrx_merkle_root_from_chunks(d,n,64*1024,r,NULL))return -1;return CRYPTO_memcmp(h,e->content_hash,64)||CRYPTO_memcmp(r,e->merkle_root,64)?-1:0;}
int qrx_net_site_verify(const QrxNetPublishedSite *s,const QrxDomainRecord *r,EVP_PKEY *pub,uint64_t height){
    EVP_PKEY *owned=NULL;if(!pub){owned=embedded_public(s);pub=owned;}
    if(!s||!r||!pub||strcmp(s->manifest.domain,r->name)||!qrx_domain_is_active(r,height)||!s->signature||!s->signature_len||!s->files||s->manifest.file_count==0||s->manifest.file_count>QRX_NET_SITE_MAX_FILES){EVP_PKEY_free(owned);return -1;}
    uint8_t pk[64],mh[64],br[64];QrxNetSiteFileEntry *tmp=malloc((size_t)s->manifest.file_count*sizeof(*tmp));if(!tmp){EVP_PKEY_free(owned);return -1;}
    memcpy(tmp,s->files,(size_t)s->manifest.file_count*sizeof(*tmp));int bad=bundle_root(tmp,s->manifest.file_count,br)||CRYPTO_memcmp(br,s->manifest.bundle_root,64);free(tmp);
    if(bad||qrx_domain_pubkey_commitment(pub,pk)||CRYPTO_memcmp(pk,r->publishing_key_commitment,64)||qrx_net_site_manifest_hash(&s->manifest,mh)||CRYPTO_memcmp(mh,r->web_manifest_root,64)){EVP_PKEY_free(owned);return -1;}
    EVP_MD_CTX *c=EVP_MD_CTX_new();if(!c){EVP_PKEY_free(owned);return -1;}int ok=EVP_DigestVerifyInit_ex(c,NULL,NULL,NULL,NULL,pub,NULL)==1&&EVP_DigestVerify(c,s->signature,s->signature_len,mh,64)==1;EVP_MD_CTX_free(c);EVP_PKEY_free(owned);return ok?0:-1;
}
void qrx_net_published_site_free(QrxNetPublishedSite *s){if(!s)return;free(s->files);free(s->signature);free(s->publishing_public_der);memset(s,0,sizeof(*s));}


static int w32(FILE*f,uint32_t v){unsigned char b[4]={(unsigned char)(v>>24),(unsigned char)(v>>16),(unsigned char)(v>>8),(unsigned char)v};return fwrite(b,1,4,f)==4?0:-1;}
static int w64(FILE*f,uint64_t v){unsigned char b[8];p64(b,v);return fwrite(b,1,8,f)==8?0:-1;}
static int r32(FILE*f,uint32_t*v){unsigned char b[4];if(fread(b,1,4,f)!=4)return -1;*v=((uint32_t)b[0]<<24)|((uint32_t)b[1]<<16)|((uint32_t)b[2]<<8)|b[3];return 0;}
static int r64(FILE*f,uint64_t*v){unsigned char b[8];if(fread(b,1,8,f)!=8)return -1;*v=0;for(int i=0;i<8;i++)*v=(*v<<8)|b[i];return 0;}
int qrx_net_site_package_save(const QrxNetPublishedSite*s,const char*path){if(!s||!path||!s->files||!s->signature||!s->signature_len||s->signature_len>65536||!s->publishing_public_der||!s->publishing_public_der_len||s->publishing_public_der_len>65536||s->manifest.file_count==0||s->manifest.file_count>QRX_NET_SITE_MAX_FILES)return -1;FILE*f=fopen(path,"wb");if(!f)return -1;uint32_t dl=(uint32_t)strlen(s->manifest.domain);int rc=fwrite("QRXNS02",1,7,f)==7?0:-1;if(!rc)rc=w32(f,s->manifest.version);if(!rc)rc=w32(f,dl);if(!rc&&fwrite(s->manifest.domain,1,dl,f)!=dl)rc=-1;if(!rc)rc=w64(f,s->manifest.sequence);if(!rc)rc=w64(f,s->manifest.published_height);if(!rc)rc=w32(f,s->manifest.file_count);if(!rc&&fwrite(s->manifest.bundle_root,1,64,f)!=64)rc=-1;for(uint32_t i=0;!rc&&i<s->manifest.file_count;i++){const QrxNetSiteFileEntry*e=&s->files[i];uint32_t pl=(uint32_t)strlen(e->path);if(!safe_path(e->path)||pl>QRX_NET_SITE_PATH_MAX||strlen(e->object_id)!=64){rc=-1;break;}rc=w32(f,pl);if(!rc&&fwrite(e->path,1,pl,f)!=pl)rc=-1;if(!rc&&fwrite(e->object_id,1,64,f)!=64)rc=-1;if(!rc)rc=w64(f,e->size);if(!rc&&fwrite(e->content_hash,1,64,f)!=64)rc=-1;if(!rc&&fwrite(e->merkle_root,1,64,f)!=64)rc=-1;}if(!rc)rc=w32(f,(uint32_t)s->signature_len);if(!rc&&fwrite(s->signature,1,s->signature_len,f)!=s->signature_len)rc=-1;if(!rc)rc=w32(f,(uint32_t)s->publishing_public_der_len);if(!rc&&fwrite(s->publishing_public_der,1,s->publishing_public_der_len,f)!=s->publishing_public_der_len)rc=-1;if(fclose(f)!=0)rc=-1;if(rc)remove(path);return rc;}
int qrx_net_site_package_load(const char*path,QrxNetPublishedSite*out){if(!path||!out)return -1;memset(out,0,sizeof(*out));FILE*f=fopen(path,"rb");if(!f)return -1;char magic[7];uint32_t dl=0,fc=0,sl=0,kl=0;int fmt=0;int rc=fread(magic,1,7,f)==7?0:-1;if(!rc){if(!memcmp(magic,"QRXNS02",7))fmt=2;else if(!memcmp(magic,"QRXNS01",7))fmt=1;else rc=-1;}if(!rc)rc=r32(f,&out->manifest.version);if(!rc)rc=r32(f,&dl);if(!rc&&(dl==0||dl>=sizeof(out->manifest.domain)))rc=-1;if(!rc&&fread(out->manifest.domain,1,dl,f)!=dl)rc=-1;out->manifest.domain[dl]=0;if(!rc)rc=r64(f,&out->manifest.sequence);if(!rc)rc=r64(f,&out->manifest.published_height);if(!rc)rc=r32(f,&fc);if(!rc&&(fc==0||fc>QRX_NET_SITE_MAX_FILES))rc=-1;out->manifest.file_count=fc;if(!rc&&fread(out->manifest.bundle_root,1,64,f)!=64)rc=-1;if(!rc){out->files=calloc(fc,sizeof(*out->files));if(!out->files)rc=-1;}for(uint32_t i=0;!rc&&i<fc;i++){uint32_t pl=0;QrxNetSiteFileEntry*e=&out->files[i];rc=r32(f,&pl);if(!rc&&(pl==0||pl>QRX_NET_SITE_PATH_MAX))rc=-1;if(!rc&&fread(e->path,1,pl,f)!=pl)rc=-1;e->path[pl]=0;if(!rc&&!safe_path(e->path))rc=-1;if(!rc&&fread(e->object_id,1,64,f)!=64)rc=-1;e->object_id[64]=0;if(!rc)rc=r64(f,&e->size);if(!rc&&fread(e->content_hash,1,64,f)!=64)rc=-1;if(!rc&&fread(e->merkle_root,1,64,f)!=64)rc=-1;}if(!rc)rc=r32(f,&sl);if(!rc&&(sl==0||sl>65536))rc=-1;if(!rc){out->signature=malloc(sl);if(!out->signature)rc=-1;else if(fread(out->signature,1,sl,f)!=sl)rc=-1;else out->signature_len=sl;}if(!rc&&fmt==2){rc=r32(f,&kl);if(!rc&&(kl==0||kl>65536))rc=-1;if(!rc){out->publishing_public_der=malloc(kl);if(!out->publishing_public_der)rc=-1;else if(fread(out->publishing_public_der,1,kl,f)!=kl)rc=-1;else out->publishing_public_der_len=kl;}}if(!rc&&fgetc(f)!=EOF)rc=-1;fclose(f);if(rc)qrx_net_published_site_free(out);return rc;}
int qrx_net_site_verify_storage(QrxStorageFs*fs,const QrxNetPublishedSite*s,const QrxDomainRecord*r,EVP_PKEY*pub,uint64_t h){if(!fs||qrx_net_site_verify(s,r,pub,h))return -1;for(uint32_t i=0;i<s->manifest.file_count;i++){unsigned char*d=NULL;size_t n=0;if(qrx_storage_fs_read(fs,s->files[i].object_id,&d,&n)){free(d);return -1;}int rc=qrx_net_site_verify_file(&s->files[i],d,n);free(d);if(rc)return -1;}return 0;}
