#include "net/qrx_net_publisher.h"
#include "net/qrx_net_name.h"
#include "storage/qrx_drive_contract.h"
#include "resource/qrx_storage_repair.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#ifdef _WIN32
#define PUB_FSEEK64(f,o,w) _fseeki64((f),(__int64)(o),(w))
#define PUB_FTELL64(f) ((int64_t)_ftelli64((f)))
#else
#define PUB_FSEEK64(f,o,w) fseeko((f),(off_t)(o),(w))
#define PUB_FTELL64(f) ((int64_t)ftello((f)))
#endif
#ifdef _WIN32
#include <direct.h>
#define mkdir_one(p) _mkdir(p)
#else
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#define mkdir_one(p) mkdir((p),0700)
#endif
static int mk(const char*p){if(mkdir_one(p)==0||errno==EEXIST)return 0;return -1;}
static int paths(const char*root,const char*domain,uint64_t seq,char*dd,size_t dsz,char*vp,size_t vsz){char norm[254];if(!root||qrx_domain_normalize(domain,norm))return -1;if(snprintf(dd,dsz,"%s/%s",root,norm)>=(int)dsz)return -1;if(snprintf(vp,vsz,"%s/%llu.qrxsite",dd,(unsigned long long)seq)>=(int)vsz)return -1;return 0;}
int qrx_net_publisher_archive(const char*root,const QrxNetPublishedSite*s,QrxNetSiteVersion*out){if(!root||!s||!s->manifest.sequence)return -1;char dd[1024],vp[1024];if(paths(root,s->manifest.domain,s->manifest.sequence,dd,sizeof(dd),vp,sizeof(vp))||mk(root)||mk(dd))return -1;FILE*e=fopen(vp,"rb");if(e){fclose(e);return -1;}if(qrx_net_site_package_save(s,vp))return -1;if(out){memset(out,0,sizeof(*out));strcpy(out->domain,s->manifest.domain);out->sequence=s->manifest.sequence;if(qrx_net_site_manifest_hash(&s->manifest,out->manifest_root)){remove(vp);return -1;}strcpy(out->package_path,vp);}return 0;}
int qrx_net_publisher_load_version(const char*root,const char*domain,uint64_t seq,QrxNetPublishedSite*out){char dd[1024],vp[1024];if(!seq||paths(root,domain,seq,dd,sizeof(dd),vp,sizeof(vp)))return -1;return qrx_net_site_package_load(vp,out);}
#ifndef _WIN32
int qrx_net_publisher_list_versions(const char*root,const char*domain,QrxNetSiteVersionCallback cb,void*ctx){if(!cb)return -1;char dd[1024],dummy[1024],norm[254];if(qrx_domain_normalize(domain,norm)||paths(root,norm,1,dd,sizeof(dd),dummy,sizeof(dummy)))return -1;DIR*d=opendir(dd);if(!d)return -1;struct dirent*de;int rc=0;while((de=readdir(d))){char*end=NULL;unsigned long long seq=strtoull(de->d_name,&end,10);if(!seq||!end||strcmp(end,".qrxsite"))continue;QrxNetPublishedSite s;if(qrx_net_publisher_load_version(root,norm,(uint64_t)seq,&s))continue;QrxNetSiteVersion v;memset(&v,0,sizeof(v));strcpy(v.domain,norm);v.sequence=(uint64_t)seq;qrx_net_site_manifest_hash(&s.manifest,v.manifest_root);paths(root,norm,v.sequence,dd,sizeof(dd),v.package_path,sizeof(v.package_path));qrx_net_published_site_free(&s);if(cb(&v,ctx)){rc=-1;break;}}closedir(d);return rc;}
#else
int qrx_net_publisher_list_versions(const char*root,const char*domain,QrxNetSiteVersionCallback cb,void*ctx){(void)root;(void)domain;(void)cb;(void)ctx;return -1;}
#endif
int qrx_net_publisher_prepare_rollback(const char*root,const char*domain,uint64_t seq,QrxNetSiteVersion*out){if(!out)return -1;QrxNetPublishedSite s;if(qrx_net_publisher_load_version(root,domain,seq,&s))return -1;memset(out,0,sizeof(*out));strcpy(out->domain,s.manifest.domain);out->sequence=s.manifest.sequence;int rc=qrx_net_site_manifest_hash(&s.manifest,out->manifest_root);char dd[1024];if(!rc)rc=paths(root,out->domain,out->sequence,dd,sizeof(dd),out->package_path,sizeof(out->package_path));qrx_net_published_site_free(&s);return rc;}

/* 0.0.8.76 secure directory publisher */
#include "storage/qrx_merkle.h"
#include <openssl/evp.h>
#include <openssl/crypto.h>
#include <ctype.h>
#ifndef _WIN32
#include <unistd.h>
#include <limits.h>
#else
#include <windows.h>
#endif

typedef struct { QrxNetSiteFileEntry e[QRX_NET_SITE_MAX_FILES]; size_t n; QrxStorageFs *fs; const char *root; size_t root_len; } PubWalk;
static int pub_hex_eq_ci(const char*a,const char*b){for(;*a&&*b;a++,b++)if(tolower((unsigned char)*a)!=tolower((unsigned char)*b))return 0;return *a==0&&*b==0;}
static int pub_rel_safe(const char*p){if(!p||!*p||strlen(p)>QRX_NET_SITE_PATH_MAX||p[0]=='/'||p[0]=='\\'||strstr(p,".."))return 0;for(const unsigned char*s=(const unsigned char*)p;*s;s++)if(*s<32||*s=='\\')return 0;return 1;}
static int pub_content_hash_file(const char*path,uint8_t out[64]){FILE*f=fopen(path,"rb");if(!f)return -1;EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned z=0;uint8_t b[128*1024];int rc=-1;if(!c||EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)!=1||EVP_DigestUpdate(c,"QRX-NET-CONTENT-V1",18)!=1)goto done;for(;;){size_t n=fread(b,1,sizeof(b),f);if(n&&EVP_DigestUpdate(c,b,n)!=1)goto done;if(n<sizeof(b)){if(ferror(f))goto done;break;}}if(EVP_DigestFinal_ex(c,out,&z)==1&&z==64)rc=0;done:EVP_MD_CTX_free(c);fclose(f);return rc;}
static int pub_merkle_file(const char*path,uint8_t out[64],uint64_t*size_out){FILE*f=fopen(path,"rb");if(!f)return -1;uint8_t *leaves=NULL;size_t n=0,cap=0;uint64_t total=0;uint8_t b[64*1024];int rc=-1;for(;;){size_t got=fread(b,1,sizeof(b),f);if(got){if(n==cap){size_t nc=cap?cap*2:16;if(nc>SIZE_MAX/64)goto done;uint8_t*x=realloc(leaves,nc*64);if(!x)goto done;leaves=x;cap=nc;}if(qrx_merkle_leaf_hash((uint64_t)n,b,got,leaves+n*64))goto done;n++;total+=got;}if(got<sizeof(b)){if(ferror(f))goto done;break;}}if(!n){leaves=malloc(64);if(!leaves)goto done;if(qrx_merkle_leaf_hash(0,NULL,0,leaves))goto done;n=1;}if(qrx_merkle_root_from_leaves(leaves,n,out)==0){if(size_out)*size_out=total;rc=0;}done:free(leaves);fclose(f);return rc;}
static int pub_add_file(PubWalk*w,const char*full,const char*rel){if(!w||w->n>=QRX_NET_SITE_MAX_FILES||!pub_rel_safe(rel))return -1;for(size_t i=0;i<w->n;i++)if(pub_hex_eq_ci(w->e[i].path,rel))return -1;QrxNetSiteFileEntry*e=&w->e[w->n];memset(e,0,sizeof(*e));snprintf(e->path,sizeof(e->path),"%s",rel);uint64_t sz=0;if(qrx_storage_fs_put_file(w->fs,full,e->object_id)||pub_content_hash_file(full,e->content_hash)||pub_merkle_file(full,e->merkle_root,&sz))return -1;e->size=sz;w->n++;return 0;}
#ifndef _WIN32
static int pub_walk_dir(PubWalk*w,const char*dir,const char*prefix){DIR*d=opendir(dir);if(!d)return -1;struct dirent*de;int rc=0;while(!rc&&(de=readdir(d))){if(!strcmp(de->d_name,".")||!strcmp(de->d_name,".."))continue;char full[2048],rel[512];if(snprintf(full,sizeof(full),"%s/%s",dir,de->d_name)>=(int)sizeof(full)||snprintf(rel,sizeof(rel),"%s%s%s",prefix&&*prefix?prefix:"",prefix&&*prefix?"/":"",de->d_name)>=(int)sizeof(rel)){rc=-1;break;}struct stat st;if(lstat(full,&st)){rc=-1;break;}if(S_ISLNK(st.st_mode)){rc=-1;break;}if(S_ISDIR(st.st_mode)){rc=pub_walk_dir(w,full,rel);continue;}if(!S_ISREG(st.st_mode)){rc=-1;break;}rc=pub_add_file(w,full,rel);}closedir(d);return rc;}
#else
static int pub_walk_dir(PubWalk*w,const char*dir,const char*prefix){char pat[2048];if(snprintf(pat,sizeof(pat),"%s\\*",dir)>=(int)sizeof(pat))return -1;WIN32_FIND_DATAA fd;HANDLE h=FindFirstFileA(pat,&fd);if(h==INVALID_HANDLE_VALUE)return -1;int rc=0;do{if(!strcmp(fd.cFileName,".")||!strcmp(fd.cFileName,".."))continue;if(fd.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT){rc=-1;break;}char full[2048],rel[512];if(snprintf(full,sizeof(full),"%s\\%s",dir,fd.cFileName)>=(int)sizeof(full)||snprintf(rel,sizeof(rel),"%s%s%s",prefix&&*prefix?prefix:"",prefix&&*prefix?"/":"",fd.cFileName)>=(int)sizeof(rel)){rc=-1;break;}if(fd.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)rc=pub_walk_dir(w,full,rel);else rc=pub_add_file(w,full,rel);}while(!rc&&FindNextFileA(h,&fd));FindClose(h);return rc;}
#endif
static void pub_hex64(const uint8_t*d,char out[129]){static const char*h="0123456789abcdef";for(size_t i=0;i<64;i++){out[i*2]=h[d[i]>>4];out[i*2+1]=h[d[i]&15];}out[128]=0;}
static int pub_unhex64(const char*s,uint8_t out[64]){if(!s||strlen(s)!=128)return -1;for(size_t i=0;i<64;i++){int a=isdigit((unsigned char)s[i*2])?s[i*2]-'0':tolower((unsigned char)s[i*2])-'a'+10,b=isdigit((unsigned char)s[i*2+1])?s[i*2+1]-'0':tolower((unsigned char)s[i*2+1])-'a'+10;if(a<0||a>15||b<0||b>15)return -1;out[i]=(uint8_t)((a<<4)|b);}return 0;}
int qrx_net_publisher_job_save(const QrxNetPublishJob*j){if(!j||!j->journal_path[0])return -1;char tmp[QRX_NET_SITE_CATALOG_PATH_MAX+8],mh[129];snprintf(tmp,sizeof(tmp),"%s.tmp",j->journal_path);pub_hex64(j->manifest_root,mh);FILE*f=fopen(tmp,"wb");if(!f)return -1;fprintf(f,"format=qrx-net-publish-job-v2\ndomain=%s\nsequence=%llu\npublished_height=%llu\nmanifest_root=%s\npackage_path=%s\ndistribution_path=%s\nprepare_dir=%s\nstorage_contract_id=%s\ntransfer_id=%s\nactivation_txid=%s\nactivation_height=%llu\nstorage_step_txid=%s\nstorage_step_height=%llu\nstorage_step_kind=%u\nstorage_step_shard=%u\nrequired_active_shards=%u\nactive_shards=%u\ntotal_shards=%u\nstatus=%u\n",j->domain,(unsigned long long)j->sequence,(unsigned long long)j->published_height,mh,j->package_path,j->distribution_path,j->prepare_dir,j->storage_contract_id[0]?j->storage_contract_id:"-",j->transfer_id[0]?j->transfer_id:"-",j->activation_txid[0]?j->activation_txid:"-",(unsigned long long)j->activation_height,j->storage_step_txid[0]?j->storage_step_txid:"-",(unsigned long long)j->storage_step_height,j->storage_step_kind,j->storage_step_shard,j->required_active_shards,j->active_shards,j->total_shards,j->status);if(fflush(f)||fclose(f)||rename(tmp,j->journal_path)){remove(tmp);return -1;}return 0;}
static int pub_meta(const char*txt,const char*k,char*out,size_t cap){char p[96];snprintf(p,sizeof(p),"%s=",k);const char*s=strstr(txt,p);if(!s)return -1;s+=strlen(p);const char*e=strchr(s,'\n');size_t n=e?(size_t)(e-s):strlen(s);if(!n||n>=cap)return -1;memcpy(out,s,n);out[n]=0;return 0;}
int qrx_net_publisher_job_load(const char*path,QrxNetPublishJob*out){if(!path||!out)return -1;FILE*f=fopen(path,"rb");if(!f)return -1;if(fseek(f,0,SEEK_END)){fclose(f);return -1;}long z=ftell(f);if(z<=0||z>65536||fseek(f,0,SEEK_SET)){fclose(f);return -1;}char*t=malloc((size_t)z+1);if(!t){fclose(f);return -1;}if(fread(t,1,(size_t)z,f)!=(size_t)z){free(t);fclose(f);return -1;}fclose(f);t[z]=0;char fmt[64],seq[32],ph[32],mh[129],req[16],act[16],tot[16],st[16],cid[129],tid[129],atid[129],ah[32],sctx[129],sch[32],sck[16],scs[16];memset(out,0,sizeof(*out));int rc=pub_meta(t,"format",fmt,sizeof(fmt))||strcmp(fmt,"qrx-net-publish-job-v2")||pub_meta(t,"domain",out->domain,sizeof(out->domain))||pub_meta(t,"sequence",seq,sizeof(seq))||pub_meta(t,"published_height",ph,sizeof(ph))||pub_meta(t,"manifest_root",mh,sizeof(mh))||pub_meta(t,"package_path",out->package_path,sizeof(out->package_path))||pub_meta(t,"distribution_path",out->distribution_path,sizeof(out->distribution_path))||pub_meta(t,"prepare_dir",out->prepare_dir,sizeof(out->prepare_dir))||pub_meta(t,"storage_contract_id",cid,sizeof(cid))||pub_meta(t,"transfer_id",tid,sizeof(tid))||pub_meta(t,"activation_txid",atid,sizeof(atid))||pub_meta(t,"activation_height",ah,sizeof(ah))||pub_meta(t,"storage_step_txid",sctx,sizeof(sctx))||pub_meta(t,"storage_step_height",sch,sizeof(sch))||pub_meta(t,"storage_step_kind",sck,sizeof(sck))||pub_meta(t,"storage_step_shard",scs,sizeof(scs))||pub_meta(t,"required_active_shards",req,sizeof(req))||pub_meta(t,"active_shards",act,sizeof(act))||pub_meta(t,"total_shards",tot,sizeof(tot))||pub_meta(t,"status",st,sizeof(st));if(!rc){out->sequence=strtoull(seq,NULL,10);out->published_height=strtoull(ph,NULL,10);out->required_active_shards=(uint32_t)strtoul(req,NULL,10);out->active_shards=(uint32_t)strtoul(act,NULL,10);out->total_shards=(uint32_t)strtoul(tot,NULL,10);out->status=(uint32_t)strtoul(st,NULL,10);if(strcmp(cid,"-"))snprintf(out->storage_contract_id,sizeof(out->storage_contract_id),"%s",cid);if(strcmp(tid,"-"))snprintf(out->transfer_id,sizeof(out->transfer_id),"%s",tid);if(strcmp(atid,"-"))snprintf(out->activation_txid,sizeof(out->activation_txid),"%s",atid);out->activation_height=strtoull(ah,NULL,10);if(strcmp(sctx,"-"))snprintf(out->storage_step_txid,sizeof(out->storage_step_txid),"%s",sctx);out->storage_step_height=strtoull(sch,NULL,10);out->storage_step_kind=(uint32_t)strtoul(sck,NULL,10);out->storage_step_shard=(uint32_t)strtoul(scs,NULL,10);snprintf(out->journal_path,sizeof(out->journal_path),"%s",path);rc=pub_unhex64(mh,out->manifest_root);if(!out->required_active_shards||out->required_active_shards>out->total_shards||out->total_shards>QRX_DRIVE_PREPARE_MAX_SHARDS)rc=-1;}free(t);return rc?-1:0;}
int qrx_net_publisher_job_set_active_shards(QrxNetPublishJob*j,uint32_t n){if(!j||j->required_active_shards==0||j->required_active_shards>14||n>14)return -1;j->active_shards=n;if(j->status<QRX_NET_PUBLISH_STATUS_ACTIVATION_SUBMITTED)j->status=n>=j->required_active_shards?QRX_NET_PUBLISH_STATUS_READY_TO_ACTIVATE:QRX_NET_PUBLISH_STATUS_WAITING_STORAGE;return qrx_net_publisher_job_save(j);}
int qrx_net_publisher_publish_directory(const char*catalog,QrxStorageFs*fs,const char*webroot,const char*domain,uint64_t seq,uint64_t height,EVP_PKEY*key,QrxNetPublishJob*out){if(!catalog||!fs||!webroot||!domain||!seq||!key||!out)return -1;uint8_t pc[64];if(qrx_domain_pubkey_commitment(key,pc))return -1;PubWalk w;memset(&w,0,sizeof(w));w.fs=fs;w.root=webroot;w.root_len=strlen(webroot);if(pub_walk_dir(&w,webroot,NULL)||!w.n)return -1;QrxNetPublishedSite site;if(qrx_net_site_publish_entries(domain,seq,height,w.e,w.n,key,&site))return -1;QrxNetSiteVersion v;if(qrx_net_publisher_archive(catalog,&site,&v)){qrx_net_published_site_free(&site);return -1;}memset(out,0,sizeof(*out));snprintf(out->domain,sizeof(out->domain),"%s",site.manifest.domain);out->sequence=seq;out->published_height=height;memcpy(out->manifest_root,v.manifest_root,64);snprintf(out->package_path,sizeof(out->package_path),"%s",v.package_path);out->required_active_shards=QRX_NET_SITE_STANDARD_ACTIVE_MIN;out->total_shards=QRX_NET_SITE_STANDARD_DATA_SHARDS+QRX_NET_SITE_STANDARD_PARITY_SHARDS;out->status=QRX_NET_PUBLISH_STATUS_PREPARED;char dd[1024],dummy[1024];if(paths(catalog,out->domain,seq,dd,sizeof(dd),dummy,sizeof(dummy))||snprintf(out->distribution_path,sizeof(out->distribution_path),"%s/%llu.qrxweb",dd,(unsigned long long)seq)>=(int)sizeof(out->distribution_path)||snprintf(out->journal_path,sizeof(out->journal_path),"%s/%llu.publish",dd,(unsigned long long)seq)>=(int)sizeof(out->journal_path)){qrx_net_published_site_free(&site);return -1;}if(qrx_net_publisher_export_distribution(fs,&site,v.package_path,out->distribution_path)){qrx_net_published_site_free(&site);return -1;}char prep_root[1200];if(snprintf(prep_root,sizeof(prep_root),"%s/prepared",dd)>=(int)sizeof(prep_root)){qrx_net_published_site_free(&site);return -1;}QrxDrivePreparedUpload prep;if(qrx_drive_prepare_public_signed_upload(prep_root,out->distribution_path,"STANDARD",QRX_NET_SITE_STANDARD_DATA_SHARDS,QRX_NET_SITE_STANDARD_PARITY_SHARDS,key,&prep)){qrx_net_published_site_free(&site);return -1;}snprintf(out->prepare_dir,sizeof(out->prepare_dir),"%s",prep.package_dir);qrx_drive_prepared_upload_free(&prep);int rc=qrx_net_publisher_job_save(out);qrx_net_published_site_free(&site);return rc;}

static int pub_w32(FILE*f,uint32_t v){unsigned char b[4]={(unsigned char)(v>>24),(unsigned char)(v>>16),(unsigned char)(v>>8),(unsigned char)v};return fwrite(b,1,4,f)==4?0:-1;}
static int pub_w64(FILE*f,uint64_t v){unsigned char b[8];for(int i=7;i>=0;i--){b[i]=(unsigned char)v;v>>=8;}return fwrite(b,1,8,f)==8?0:-1;}
static int pub_r32(FILE*f,uint32_t*v){unsigned char b[4];if(fread(b,1,4,f)!=4)return-1;*v=((uint32_t)b[0]<<24)|((uint32_t)b[1]<<16)|((uint32_t)b[2]<<8)|b[3];return 0;}
static int pub_r64(FILE*f,uint64_t*v){unsigned char b[8];if(fread(b,1,8,f)!=8)return-1;*v=0;for(int i=0;i<8;i++)*v=(*v<<8)|b[i];return 0;}
static int pub_copy_file(FILE*out,const char*path,uint64_t*len_out){FILE*in=fopen(path,"rb");if(!in)return-1;unsigned char b[128*1024];uint64_t z=0;int rc=0;for(;;){size_t n=fread(b,1,sizeof(b),in);if(n){if(fwrite(b,1,n,out)!=n){rc=-1;break;}z+=n;}if(n<sizeof(b)){if(ferror(in))rc=-1;break;}}fclose(in);if(!rc&&len_out)*len_out=z;return rc;}
int qrx_net_publisher_export_distribution(QrxStorageFs*fs,const QrxNetPublishedSite*site,const char*pkg,const char*outp){if(!fs||!site||!pkg||!outp||!site->files||!site->manifest.file_count)return-1;FILE*pf=fopen(pkg,"rb");if(!pf)return-1;if(PUB_FSEEK64(pf,0,SEEK_END)){fclose(pf);return-1;}int64_t pl=PUB_FTELL64(pf);if(pl<=0||PUB_FSEEK64(pf,0,SEEK_SET)){fclose(pf);return-1;}FILE*out=fopen(outp,"wb");if(!out){fclose(pf);return-1;}int rc=fwrite("QRXWEB1",1,7,out)==7?0:-1;if(!rc)rc=pub_w32(out,1);if(!rc)rc=pub_w64(out,(uint64_t)pl);unsigned char b[128*1024];while(!rc){size_t n=fread(b,1,sizeof(b),pf);if(n&&fwrite(b,1,n,out)!=n)rc=-1;if(n<sizeof(b)){if(ferror(pf))rc=-1;break;}}fclose(pf);if(!rc)rc=pub_w32(out,site->manifest.file_count);for(uint32_t i=0;!rc&&i<site->manifest.file_count;i++){const QrxNetSiteFileEntry*e=&site->files[i];if(strlen(e->object_id)!=64){rc=-1;break;}if(fwrite(e->object_id,1,64,out)!=64||pub_w64(out,e->size)){rc=-1;break;}uint64_t off=0;while(off<e->size){size_t want=(size_t)((e->size-off)>sizeof(b)?sizeof(b):(e->size-off));unsigned char*d=NULL;size_t dn=0;if(qrx_storage_fs_read_range(fs,e->object_id,off,want,&d,&dn)||dn!=want){free(d);rc=-1;break;}if(fwrite(d,1,dn,out)!=dn)rc=-1;free(d);if(rc)break;off+=dn;}}
 if(fflush(out)||fclose(out))rc=-1;if(rc)remove(outp);return rc;}

#ifndef _WIN32
static int pub_tmp_package(const unsigned char*d,size_t n,char path[1024]){snprintf(path,1024,"/tmp/qrxsitepkg-XXXXXX");int fd=mkstemp(path);if(fd<0)return-1;FILE*f=fdopen(fd,"wb");if(!f){close(fd);remove(path);return-1;}int rc=fwrite(d,1,n,f)==n&&fflush(f)==0&&fclose(f)==0?0:-1;if(rc)remove(path);return rc;}
#else
static int pub_tmp_package(const unsigned char*d,size_t n,char path[1024]){char td[MAX_PATH],tp[MAX_PATH];if(!GetTempPathA(MAX_PATH,td)||!GetTempFileNameA(td,"qrx",0,tp))return-1;snprintf(path,1024,"%s",tp);FILE*f=fopen(path,"wb");if(!f){DeleteFileA(tp);return-1;}int rc=fwrite(d,1,n,f)==n&&fflush(f)==0&&fclose(f)==0?0:-1;if(rc)DeleteFileA(tp);return rc;}
#endif
int qrx_net_publisher_extract_file(const char*dist,const char*req,QrxNetPublishedSite*site_out,unsigned char**data_out,size_t*len_out){if(!dist||!req||!site_out||!data_out||!len_out||!pub_rel_safe(req))return-1;*data_out=NULL;*len_out=0;memset(site_out,0,sizeof(*site_out));FILE*f=fopen(dist,"rb");if(!f)return-1;char magic[7];uint32_t ver=0,fc=0;uint64_t pl=0;int rc=fread(magic,1,7,f)==7&&!memcmp(magic,"QRXWEB1",7)?0:-1;if(!rc)rc=pub_r32(f,&ver);if(!rc&&(ver!=1||pub_r64(f,&pl)||!pl||pl>16*1024*1024ULL))rc=-1;unsigned char*pb=NULL;if(!rc){pb=malloc((size_t)pl);if(!pb||fread(pb,1,(size_t)pl,f)!=(size_t)pl)rc=-1;}char tmp[1024]={0};if(!rc&&pub_tmp_package(pb,(size_t)pl,tmp))rc=-1;free(pb);if(!rc&&qrx_net_site_package_load(tmp,site_out))rc=-1;if(tmp[0])remove(tmp);if(!rc)rc=pub_r32(f,&fc);if(!rc&&fc!=site_out->manifest.file_count)rc=-1;const QrxNetSiteFileEntry*target=NULL;if(!rc)for(uint32_t i=0;i<site_out->manifest.file_count;i++)if(!strcmp(site_out->files[i].path,req)){target=&site_out->files[i];break;}if(!rc&&!target)rc=-1;for(uint32_t i=0;!rc&&i<fc;i++){char oid[65];uint64_t sz=0;if(fread(oid,1,64,f)!=64||pub_r64(f,&sz)){rc=-1;break;}oid[64]=0;const QrxNetSiteFileEntry*entry=NULL;for(uint32_t j=0;j<site_out->manifest.file_count;j++)if(!strcmp(site_out->files[j].object_id,oid)){entry=&site_out->files[j];break;}if(!entry||entry->size!=sz){rc=-1;break;}if(entry==target){if(sz>SIZE_MAX){rc=-1;break;}unsigned char*d=malloc(sz?((size_t)sz):1);if(!d){rc=-1;break;}if(sz&&fread(d,1,(size_t)sz,f)!=(size_t)sz){free(d);rc=-1;break;}if(qrx_net_site_verify_file(entry,d,(size_t)sz)){free(d);rc=-1;break;}*data_out=d;*len_out=(size_t)sz;}else{if(PUB_FSEEK64(f,sz,SEEK_CUR)){rc=-1;break;}}}
 if(!rc&&fgetc(f)!=EOF)rc=-1;fclose(f);if(rc||!*data_out){free(*data_out);*data_out=NULL;*len_out=0;qrx_net_published_site_free(site_out);return-1;}return 0;}

int qrx_net_publisher_load_prepared(const QrxNetPublishJob*j,EVP_PKEY*pub,QrxDrivePreparedUpload*out){if(!j||!pub||!out||!j->prepare_dir[0]||qrx_drive_prepared_upload_load(j->prepare_dir,pub,out))return-1;if(strcmp(out->manifest.crypto_suite,QRX_DRIVE_SUITE_PUBLIC_SIGNED)||out->data_shards!=QRX_NET_SITE_STANDARD_DATA_SHARDS||out->parity_shards!=QRX_NET_SITE_STANDARD_PARITY_SHARDS){qrx_drive_prepared_upload_free(out);return-1;}return 0;}
static int pub_contract_id(const char*owner,const QrxNetPublishJob*j,char out[129]){if(!owner||!*owner||!j||!j->domain[0]||!out)return-1;EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned char h[32];unsigned z=0;static const char d[]="QRX-NET-HOST-CONTRACT-V1";int ok=c&&EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(c,d,sizeof(d)-1)==1&&EVP_DigestUpdate(c,owner,strlen(owner))==1&&EVP_DigestUpdate(c,j->domain,strlen(j->domain))==1&&EVP_DigestUpdate(c,j->manifest_root,64)==1&&EVP_DigestFinal_ex(c,h,&z)==1&&z==32;EVP_MD_CTX_free(c);if(!ok)return-1;static const char*x="0123456789abcdef";char hx[65];for(int i=0;i<32;i++){hx[i*2]=x[h[i]>>4];hx[i*2+1]=x[h[i]&15];}hx[64]=0;snprintf(out,129,"web-%s",hx);return 0;}
static int pub_contract_matches(const QrxStorageContractState*c,const char*owner,const QrxNetPublishJob*j,const QrxDrivePreparedUpload*p,uint64_t rate){return !c||strcmp(c->owner,owner)||strcmp(c->profile,"STANDARD")||c->logical_bytes!=p->ciphertext_bytes||c->shard_bytes!=p->shard_bytes||c->shard_count!=p->total_shards||c->base_atoms_per_gib_epoch!=rate||CRYPTO_memcmp(c->manifest_root,j->manifest_root,64)?-1:0;}
int qrx_net_publisher_host_next_step(QrxDB*db,const char*owner,const QrxNetPublishJob*j,const QrxDrivePreparedUpload*p,uint64_t h,uint64_t epochs,uint64_t rate,QrxNetHostStep*out){if(!db||!owner||!*owner||!j||!p||!out||!h||strcmp(p->manifest.crypto_suite,QRX_DRIVE_SUITE_PUBLIC_SIGNED)||qrx_drive_prepared_upload_verify_files(p))return-1;if(!epochs)epochs=30;if(!rate)rate=10000;memset(out,0,sizeof(*out));out->required_active_shards=QRX_NET_SITE_STANDARD_ACTIVE_MIN;out->base_atoms_per_gib_epoch=rate;if(pub_contract_id(owner,j,out->contract_id))return-1;QrxStorageContractState c;if(qrx_storage_contract_get(db,out->contract_id,&c)){uint64_t atoms=0;if(qrx_drive_contract_quote(p,epochs,rate,&atoms)||epochs>UINT64_MAX/QRX_STORAGE_PROOF_WINDOW_BLOCKS)return-1;out->end_height=h+epochs*QRX_STORAGE_PROOF_WINDOW_BLOCKS;if(out->end_height<h)return-1;char mh[129];pub_hex64(j->manifest_root,mh);out->kind=QRX_NET_HOST_STEP_CREATE;snprintf(out->tx_type,sizeof(out->tx_type),"STORAGE_CONTRACT_CREATE");snprintf(out->to,sizeof(out->to),"%s",owner);out->amount_atoms=atoms;snprintf(out->payload,sizeof(out->payload),"contract_id=%s;profile=STANDARD;logical_bytes=%llu;end_height=%llu;base_atoms_per_gib_epoch=%llu;manifest_root_hex=%s",out->contract_id,(unsigned long long)p->ciphertext_bytes,(unsigned long long)out->end_height,(unsigned long long)rate,mh);return 0;}if(pub_contract_matches(&c,owner,j,p,rate))return-1;out->end_height=c.end_height;for(unsigned i=0;i<p->total_shards;i++){QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(db,out->contract_id,i,&a)==0){if(strcmp(a.object_id,p->shard_object_ids[i])||CRYPTO_memcmp(a.merkle_root,p->shard_merkle_roots[i],64)||a.leaf_count!=p->shard_leaf_counts[i])return-1;out->assignments_present++;if(a.state==QRX_ASSIGN_ACTIVE)out->active_shards++;continue;}char provider[129],mr[129];if(qrx_storage_assignment_provider_for_height(db,out->contract_id,p->shard_bytes,h+1,provider))return-1;pub_hex64(p->shard_merkle_roots[i],mr);out->kind=QRX_NET_HOST_STEP_ASSIGN;out->shard_index=i;snprintf(out->tx_type,sizeof(out->tx_type),"STORAGE_ASSIGN");snprintf(out->to,sizeof(out->to),"%s",provider);snprintf(out->payload,sizeof(out->payload),"contract_id=%s;shard_index=%u;object_id=%s;merkle_root_hex=%s;leaf_count=%llu",out->contract_id,i,p->shard_object_ids[i],mr,(unsigned long long)p->shard_leaf_counts[i]);return 0;}if(out->active_shards>=QRX_NET_SITE_STANDARD_ACTIVE_MIN){out->kind=QRX_NET_HOST_STEP_READY_ACTIVATE;snprintf(out->tx_type,sizeof(out->tx_type),"-");return 0;}out->kind=j->transfer_id[0]?QRX_NET_HOST_STEP_WAIT_ACTIVE:QRX_NET_HOST_STEP_READY_UPLOAD;snprintf(out->tx_type,sizeof(out->tx_type),"-");return 0;}
int qrx_net_publisher_refresh_storage(QrxDB*db,QrxNetPublishJob*j,const QrxDrivePreparedUpload*p){if(!db||!j||!p)return-1;char owner[160]={0};QrxStorageContractState c;if(!j->storage_contract_id[0]||qrx_storage_contract_get(db,j->storage_contract_id,&c))return-1;snprintf(owner,sizeof(owner),"%s",c.owner);if(pub_contract_matches(&c,owner,j,p,c.base_atoms_per_gib_epoch))return-1;uint32_t active=0;for(unsigned i=0;i<p->total_shards;i++){QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(db,j->storage_contract_id,i,&a))continue;if(strcmp(a.object_id,p->shard_object_ids[i])||CRYPTO_memcmp(a.merkle_root,p->shard_merkle_roots[i],64)||a.leaf_count!=p->shard_leaf_counts[i])return-1;if(a.state==QRX_ASSIGN_ACTIVE)active++;}j->active_shards=active;j->status=active>=j->required_active_shards?QRX_NET_PUBLISH_STATUS_READY_TO_ACTIVATE:QRX_NET_PUBLISH_STATUS_WAITING_STORAGE;return qrx_net_publisher_job_save(j);}

/* 0.0.8.77 verified distribution cache gate. */
static int pub_node_hash77(const uint8_t left[64],const uint8_t right[64],uint8_t out[64]){
    static const char dom[]="QRX-MERKLE-NODE-V1";EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned int n=0;int rc=-1;
    if(c&&EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)==1&&EVP_DigestUpdate(c,dom,sizeof(dom)-1)==1&&EVP_DigestUpdate(c,left,64)==1&&EVP_DigestUpdate(c,right,64)==1&&EVP_DigestFinal_ex(c,out,&n)==1&&n==64)rc=0;EVP_MD_CTX_free(c);return rc;
}
typedef struct{uint8_t h[64][64];uint8_t used[64];uint64_t count;} PubMerkleAcc77;
static int pub_merkle_add77(PubMerkleAcc77*a,const uint8_t leaf[64]){uint8_t cur[64];memcpy(cur,leaf,64);unsigned l=0;while(l<64&&a->used[l]){uint8_t x[64];if(pub_node_hash77(a->h[l],cur,x))return -1;a->used[l]=0;memcpy(cur,x,64);l++;}if(l>=64)return -1;memcpy(a->h[l],cur,64);a->used[l]=1;a->count++;return 0;}
static uint64_t pub_next_pow2_77(uint64_t n){uint64_t p=1;if(!n)return 0;while(p<n){if(p>UINT64_MAX/2)return 0;p<<=1;}return p;}
static int pub_merkle_finish77(PubMerkleAcc77*a,const uint8_t last[64],uint8_t out[64]){if(!a||!a->count)return -1;uint64_t width=pub_next_pow2_77(a->count);if(!width)return -1;while(a->count<width)if(pub_merkle_add77(a,last))return -1;for(unsigned i=0;i<64;i++)if(a->used[i]){memcpy(out,a->h[i],64);for(unsigned j=i+1;j<64;j++)if(a->used[j])return -1;return 0;}return -1;}
static int pub_verify_stream_file77(FILE*f,const QrxNetSiteFileEntry*e){
    if(!f||!e)return -1;EVP_MD_CTX*c=EVP_MD_CTX_new();if(!c)return -1;static const char dom[]="QRX-NET-CONTENT-V1";int rc=-1;unsigned int hn=0;uint8_t content[64],buf[64*1024],last[64];PubMerkleAcc77 a;memset(&a,0,sizeof(a));
    if(EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)!=1||EVP_DigestUpdate(c,dom,sizeof(dom)-1)!=1)goto done;uint64_t rem=e->size,idx=0;
    if(!rem){if(qrx_merkle_leaf_hash(0,NULL,0,last)||pub_merkle_add77(&a,last))goto done;}
    while(rem){size_t want=(size_t)(rem>sizeof(buf)?sizeof(buf):rem);if(fread(buf,1,want,f)!=want)goto done;if(EVP_DigestUpdate(c,buf,want)!=1||qrx_merkle_leaf_hash(idx++,buf,want,last)||pub_merkle_add77(&a,last))goto done;rem-=want;}
    if(EVP_DigestFinal_ex(c,content,&hn)!=1||hn!=64||CRYPTO_memcmp(content,e->content_hash,64))goto done;uint8_t mr[64];if(pub_merkle_finish77(&a,last,mr)||CRYPTO_memcmp(mr,e->merkle_root,64))goto done;rc=0;
done:EVP_MD_CTX_free(c);return rc;
}
int qrx_net_publisher_verify_distribution(const char*dist,const QrxDomainRecord*r,uint64_t h,QrxNetPublishedSite*out){
    if(!dist||!r)return -1;if(out)memset(out,0,sizeof(*out));FILE*f=fopen(dist,"rb");if(!f)return -1;char magic[7];uint32_t ver=0,fc=0;uint64_t pl=0;int rc=fread(magic,1,7,f)==7&&!memcmp(magic,"QRXWEB1",7)?0:-1;if(!rc)rc=pub_r32(f,&ver);if(!rc&&(ver!=1||pub_r64(f,&pl)||!pl||pl>64*1024*1024ULL))rc=-1;
    char tmp[1024]={0};FILE*pf=NULL;if(!rc){char t[]="/tmp/qrxweb-pkg-XXXXXX";
#ifdef _WIN32
        char tp[MAX_PATH];if(!GetTempPathA(MAX_PATH,tp)||!GetTempFileNameA(tp,"qwp",0,tmp))rc=-1;else pf=fopen(tmp,"wb");
#else
        int fd=mkstemp(t);if(fd<0)rc=-1;else{snprintf(tmp,sizeof(tmp),"%s",t);pf=fdopen(fd,"wb");}
#endif
    }
    unsigned char b[128*1024];uint64_t left=pl;while(!rc&&left){size_t want=(size_t)(left>sizeof(b)?sizeof(b):left);if(fread(b,1,want,f)!=want||fwrite(b,1,want,pf)!=want)rc=-1;left-=want;}if(pf&&fclose(pf)!=0)rc=-1;
    QrxNetPublishedSite site;memset(&site,0,sizeof(site));if(!rc&&qrx_net_site_package_load(tmp,&site))rc=-1;if(tmp[0])remove(tmp);if(!rc&&qrx_net_site_verify(&site,r,NULL,h))rc=-1;if(!rc)rc=pub_r32(f,&fc);if(!rc&&fc!=site.manifest.file_count)rc=-1;
    for(uint32_t i=0;!rc&&i<fc;i++){char oid[65];uint64_t sz=0;if(fread(oid,1,64,f)!=64||pub_r64(f,&sz)){rc=-1;break;}oid[64]=0;const QrxNetSiteFileEntry*e=NULL;for(uint32_t j=0;j<site.manifest.file_count;j++)if(!strcmp(site.files[j].object_id,oid)){e=&site.files[j];break;}if(!e||e->size!=sz||pub_verify_stream_file77(f,e)){rc=-1;break;}}
    if(!rc&&fgetc(f)!=EOF)rc=-1;fclose(f);if(rc){qrx_net_published_site_free(&site);return -1;}if(out)*out=site;else qrx_net_published_site_free(&site);return 0;
}
