#include "storage/qrx_storage_postor_runtime.h"
#include "resource/qrx_storage_consensus.h"
#include "resource/qrx_storage_repair.h"
#include "storage/qrx_drive_prepare.h"
#include "storage/qrx_postor.h"
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

static size_t pow2_ceil_u64(uint64_t n){size_t p=1;if(!n||n>SIZE_MAX)return 0;while(p<(size_t)n){if(p>SIZE_MAX/2)return 0;p<<=1;}return p;}
static int read_leaf(QrxStorageFs*fs,const char*oid,uint64_t bytes,uint64_t idx,unsigned char**out,size_t*len){
    if(!fs||!oid||!out||!len)return -1;*out=NULL;*len=0;uint64_t off=idx*(uint64_t)QRX_DRIVE_POSTOR_LEAF_BYTES;if(off>=bytes)return -1;uint64_t rem=bytes-off;size_t want=(size_t)(rem>QRX_DRIVE_POSTOR_LEAF_BYTES?QRX_DRIVE_POSTOR_LEAF_BYTES:rem);return qrx_storage_fs_read_range(fs,oid,off,want,out,len)||*len!=want?-1:0;
}
static int subtree_root(QrxStorageFs*fs,const char*oid,uint64_t bytes,uint64_t leaf_count,size_t start,size_t width,uint8_t out[64]){
    if(!width||!leaf_count)return -1;if(width==1){uint64_t idx=start<(size_t)leaf_count?(uint64_t)start:leaf_count-1;unsigned char*b=NULL;size_t n=0;if(read_leaf(fs,oid,bytes,idx,&b,&n))return -1;int rc=qrx_merkle_leaf_hash(idx,b,n,out);OPENSSL_cleanse(b,n);free(b);return rc;}
    uint8_t*l=malloc(64),*r=malloc(64);if(!l||!r){free(l);free(r);return -1;}int rc=subtree_root(fs,oid,bytes,leaf_count,start,width/2,l)||subtree_root(fs,oid,bytes,leaf_count,start+width/2,width/2,r);if(!rc){uint8_t pair[128];memcpy(pair,l,64);memcpy(pair+64,r,64);static const char d[]="QRX-MERKLE-NODE-V1";EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned int n=0;if(!c||EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)!=1||EVP_DigestUpdate(c,d,sizeof(d)-1)!=1||EVP_DigestUpdate(c,pair,sizeof(pair))!=1||EVP_DigestFinal_ex(c,out,&n)!=1||n!=64)rc=-1;EVP_MD_CTX_free(c);}OPENSSL_cleanse(l,64);OPENSSL_cleanse(r,64);free(l);free(r);return rc;
}

const char*qrx_storage_postor_health_name(QrxPoStorHealth h){switch(h){case QRX_POSTOR_HEALTH_ACTIVE:return"ACTIVE";case QRX_POSTOR_HEALTH_PROOF_DUE:return"PROOF_DUE";case QRX_POSTOR_HEALTH_DEGRADED:return"DEGRADED";case QRX_POSTOR_HEALTH_REPAIRING:return"REPAIRING";default:return"UNKNOWN";}}

typedef struct{QrxDB*db;const char*provider;uint64_t h;QrxPoStorDueAssignment*out;size_t cap,n;} Scan;
static int scan_cb(const char*k,const char*v,uint32_t vl,void*x){(void)v;(void)vl;Scan*c=x;if(c->n>=c->cap)return 1;const char*p="storage/assignment/";size_t pn=strlen(p);if(strncmp(k,p,pn))return 0;const char*s=k+pn,*slash=strrchr(s,'/');if(!slash||slash==s)return 0;size_t cn=(size_t)(slash-s);if(cn>=129)return 0;char cid[129];memcpy(cid,s,cn);cid[cn]=0;char*e=NULL;unsigned long sh=strtoul(slash+1,&e,10);if(!e||*e||sh>UINT32_MAX)return 0;QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(c->db,cid,(uint32_t)sh,&a)||strcmp(a.provider_id,c->provider)||(a.state!=QRX_ASSIGN_ACTIVE&&a.state!=QRX_ASSIGN_REPAIRING)||!a.accepted_height||!a.leaf_count)return 0;uint64_t base=a.last_proof_height?a.last_proof_height:a.accepted_height;if(UINT64_MAX-base<QRX_STORAGE_PROOF_WINDOW_BLOCKS)return 0;uint64_t dueh=base+QRX_STORAGE_PROOF_WINDOW_BLOCKS;QrxPoStorDueAssignment*d=&c->out[c->n];memset(d,0,sizeof(*d));snprintf(d->contract_id,sizeof(d->contract_id),"%s",cid);d->shard_index=(uint32_t)sh;snprintf(d->object_id,sizeof(d->object_id),"%s",a.object_id);d->physical_bytes=a.physical_bytes;d->leaf_count=a.leaf_count;d->epoch=a.last_proof_epoch+1;d->challenge_height=dueh;if(a.state==QRX_ASSIGN_REPAIRING)d->health=QRX_POSTOR_HEALTH_REPAIRING;else if(c->h<dueh)d->health=QRX_POSTOR_HEALTH_ACTIVE;else if(c->h==dueh)d->health=QRX_POSTOR_HEALTH_PROOF_DUE;else {d->health=QRX_POSTOR_HEALTH_DEGRADED;d->repair_ready=1;}if(c->h>=dueh){char bh[160];uint8_t b[64];if(qrxdb_chain_get_block_hash_by_height(c->db,dueh,bh,sizeof(bh))==0&&strlen(bh)==128){for(int i=0;i<64;i++){char q[3]={bh[i*2],bh[i*2+1],0};b[i]=(uint8_t)strtoul(q,NULL,16);}QrxPoStorChallenge pc;if(!qrx_postor_derive_challenge(cid,a.provider_id,(uint32_t)sh,d->epoch,a.leaf_count,b,&pc))d->leaf_index=pc.leaf_index;else return 0;}else return 0;}c->n++;return 0;}
int qrx_storage_postor_collect(QrxDB*db,const char*provider,uint64_t h,QrxPoStorDueAssignment*out,size_t cap,size_t*count){if(!db||!provider||!*provider||!out||!cap||!count)return-1;Scan c={db,provider,h,out,cap,0};int rc=qrxdb_scan_prefix(db,"storage/assignment/",scan_cb,&c);*count=c.n;return rc<0?-1:0;}

int qrx_storage_postor_build_local(QrxDB*db,QrxStorageFs*fs,const char*provider,const QrxPoStorDueAssignment*d,unsigned char**leaf,size_t*leafn,QrxMerkleProof*proof){
    if(!db||!fs||!provider||!d||!leaf||!leafn||!proof||d->health==QRX_POSTOR_HEALTH_ACTIVE)return-1;QrxStorageAssignmentRecord a;if(qrx_storage_assignment_get(db,d->contract_id,d->shard_index,&a)||strcmp(a.provider_id,provider)||strcmp(a.object_id,d->object_id)||a.physical_bytes!=d->physical_bytes||a.leaf_count!=d->leaf_count||d->leaf_index>=d->leaf_count)return-1;unsigned char*b=NULL;size_t n=0;if(read_leaf(fs,d->object_id,d->physical_bytes,d->leaf_index,&b,&n))return-1;size_t width=pow2_ceil_u64(d->leaf_count);if(!width){free(b);return-1;}memset(proof,0,sizeof(*proof));proof->leaf_index=d->leaf_index;proof->leaf_count=d->leaf_count;size_t idx=(size_t)d->leaf_index,block=1;while(block<width){if(proof->depth>=QRX_MERKLE_MAX_DEPTH){free(b);return-1;}size_t group=idx/block,sibling_group=group^1u,start=sibling_group*block;if(subtree_root(fs,d->object_id,d->physical_bytes,d->leaf_count,start,block,proof->siblings[proof->depth])){OPENSSL_cleanse(b,n);free(b);return-1;}proof->depth++;block<<=1;}
    uint8_t lh[64];if(qrx_merkle_leaf_hash(d->leaf_index,b,n,lh)||qrx_merkle_verify_proof(lh,proof,a.merkle_root)){OPENSSL_cleanse(b,n);free(b);return-1;}*leaf=b;*leafn=n;return 0;
}
static void hx(const unsigned char*in,size_t n,char*out){static const char*x="0123456789abcdef";for(size_t i=0;i<n;i++){out[i*2]=x[in[i]>>4];out[i*2+1]=x[in[i]&15];}out[n*2]=0;}
int qrx_storage_postor_payload(const QrxPoStorDueAssignment*d,const unsigned char*leaf,size_t leafn,const QrxMerkleProof*p,char**out){if(!d||(!leaf&&leafn)||!p||!out||p->leaf_index!=d->leaf_index)return-1;*out=NULL;size_t lh=leafn*2,sh=(size_t)p->depth*128,cap=lh+sh+512;char*z=malloc(cap),*lhex=malloc(lh+1),*shex=malloc(sh+1);if(!z||!lhex||!shex){free(z);free(lhex);free(shex);return-1;}hx(leaf,leafn,lhex);for(uint32_t i=0;i<p->depth;i++)hx(p->siblings[i],64,shex+(size_t)i*128);shex[sh]=0;snprintf(z,cap,"contract_id=%s;shard_index=%u;epoch=%llu;challenge_height=%llu;revealed_leaf_hex=%s;siblings_hex=%s",d->contract_id,d->shard_index,(unsigned long long)d->epoch,(unsigned long long)d->challenge_height,lhex,sh?shex:"-");OPENSSL_cleanse(lhex,lh);free(lhex);free(shex);*out=z;return 0;}
