#include "storage/qrx_drive_manifest.h"
#include "storage/qrx_drive_crypto.h"
#include <openssl/evp.h>
#include <stdlib.h>
#include <string.h>

static void p32(uint8_t *o,uint32_t v){o[0]=v>>24;o[1]=v>>16;o[2]=v>>8;o[3]=v;}
static void p64(uint8_t *o,uint64_t v){for(int i=7;i>=0;i--){o[i]=(uint8_t)v;v>>=8;}}
int qrx_drive_manifest_canonical(const QrxDriveManifest *m,uint8_t **out,size_t *olen){if(!m||!out||!olen||m->version!=QRX_DRIVE_MANIFEST_VERSION||!m->crypto_suite[0]||!m->profile[0]||m->data_shards+m->parity_shards>QRX_DRIVE_MANIFEST_MAX_SHARDS)return -1;size_t n=4+32+16+8+8+4+4+64+(size_t)(m->data_shards+m->parity_shards)*64;uint8_t *b=calloc(n,1);if(!b)return -1;size_t o=0;p32(b+o,m->version);o+=4;memcpy(b+o,m->crypto_suite,strnlen(m->crypto_suite,31));o+=32;memcpy(b+o,m->profile,strnlen(m->profile,15));o+=16;p64(b+o,m->plaintext_bytes);o+=8;p64(b+o,m->ciphertext_bytes);o+=8;p32(b+o,m->data_shards);o+=4;p32(b+o,m->parity_shards);o+=4;memcpy(b+o,m->ciphertext_root,64);o+=64;unsigned total=m->data_shards+m->parity_shards;for(unsigned i=0;i<total;i++){memcpy(b+o,m->shard_roots[i],64);o+=64;}*out=b;*olen=n;return 0;}
int qrx_drive_manifest_hash(const QrxDriveManifest *m,uint8_t out[64]){uint8_t *b=NULL;size_t n=0;if(!out||qrx_drive_manifest_canonical(m,&b,&n)!=0)return -1;EVP_MD_CTX *c=EVP_MD_CTX_new();unsigned int z=0;int rc=-1;if(c&&EVP_DigestInit_ex(c,EVP_sha3_512(),NULL)==1&&EVP_DigestUpdate(c,"QRX-DRIVE-MANIFEST-V1",21)==1&&EVP_DigestUpdate(c,b,n)==1&&EVP_DigestFinal_ex(c,out,&z)==1&&z==64)rc=0;EVP_MD_CTX_free(c);free(b);return rc;}
int qrx_drive_manifest_generate_signing_key(EVP_PKEY **out){if(!out)return -1;*out=NULL;EVP_PKEY_CTX *c=EVP_PKEY_CTX_new_from_name(NULL,"ML-DSA-65",NULL);if(!c)return -1;int rc=EVP_PKEY_keygen_init(c)==1&&EVP_PKEY_generate(c,out)==1?0:-1;EVP_PKEY_CTX_free(c);if(rc){EVP_PKEY_free(*out);*out=NULL;}return rc;}
int qrx_drive_manifest_sign(EVP_PKEY *k,const QrxDriveManifest *m,uint8_t **sig,size_t *slen){if(!k||!m||!sig||!slen)return -1;uint8_t h[64];if(qrx_drive_manifest_hash(m,h)!=0)return -1;EVP_MD_CTX *c=EVP_MD_CTX_new();if(!c)return -1;int rc=-1;size_t n=0;uint8_t *s=NULL;if(EVP_DigestSignInit_ex(c,NULL,NULL,NULL,NULL,k,NULL)!=1)goto done;if(EVP_DigestSign(c,NULL,&n,h,64)!=1||!n)goto done;s=malloc(n);if(!s)goto done;if(EVP_DigestSign(c,s,&n,h,64)!=1)goto done;*sig=s;*slen=n;s=NULL;rc=0;done:free(s);EVP_MD_CTX_free(c);return rc;}
int qrx_drive_manifest_verify(EVP_PKEY *k,const QrxDriveManifest *m,const uint8_t *sig,size_t slen){if(!k||!m||!sig||!slen)return -1;uint8_t h[64];if(qrx_drive_manifest_hash(m,h)!=0)return -1;EVP_MD_CTX *c=EVP_MD_CTX_new();if(!c)return -1;int rc=-1;if(EVP_DigestVerifyInit_ex(c,NULL,NULL,NULL,NULL,k,NULL)==1&&EVP_DigestVerify(c,sig,slen,h,64)==1)rc=0;EVP_MD_CTX_free(c);return rc;}
