#include "compute/qrx_aura_provider_supervisor.h"
#include <limits.h>
#include <string.h>
#include <stdio.h>
static uint64_t cooldown_blocks(uint32_t failures){if(failures<3)return 0;uint32_t shift=failures-3;if(shift>6)shift=6;return 1ull<<shift;}
static uint64_t relay_score(const QrxAuraRelayHealth*r,uint64_t h){if(!r||!r->enabled||r->cooldown_until_height>h)return 0;uint64_t reliability=(uint64_t)(r->successes+1)*100000u/(uint64_t)(r->successes+r->failures+1);uint64_t latency=r->last_latency_ms<10000u?10000u-r->last_latency_ms:0;return reliability*100u+latency;}
int qrx_aura_provider_supervisor_init(QrxAuraProviderSupervisor*s,const QrxAuraProviderHostConfig*h){if(!s||!h||qrx_aura_provider_host_config_validate(h))return-1;memset(s,0,sizeof(*s));s->version=1;s->active_relay=-1;s->relay_required=h->relay_required;s->runtime_healthy=1;s->keep_committed_jobs=128;s->keep_prepared_jobs=32;s->relay_count=h->relay_count;for(uint32_t i=0;i<h->relay_count;i++){snprintf(s->relays[i].endpoint,sizeof(s->relays[i].endpoint),"%s",h->relay_endpoints[i]);s->relays[i].enabled=1;}s->revision=1;return 0;}
int qrx_aura_provider_supervisor_record_relay(QrxAuraProviderSupervisor*s,uint32_t i,int ok,uint32_t latency,uint64_t h){if(!s||s->version!=1||i>=s->relay_count)return-1;QrxAuraRelayHealth*r=&s->relays[i];r->last_latency_ms=latency;if(ok){r->successes++;r->consecutive_failures=0;r->cooldown_until_height=0;r->last_success_height=h;}else{r->failures++;if(r->consecutive_failures<UINT32_MAX)r->consecutive_failures++;uint64_t cd=cooldown_blocks(r->consecutive_failures);r->cooldown_until_height=UINT64_MAX-h<cd?UINT64_MAX:h+cd;if(s->active_relay==(int32_t)i)s->active_relay=-1;}s->revision++;return 0;}
int qrx_aura_provider_supervisor_select_relay(QrxAuraProviderSupervisor*s,uint64_t h){if(!s||s->version!=1)return-1;int best=-1;uint64_t bs=0;for(uint32_t i=0;i<s->relay_count;i++){uint64_t sc=relay_score(&s->relays[i],h);if(!sc)continue;if(best<0||sc>bs||(sc==bs&&strcmp(s->relays[i].endpoint,s->relays[best].endpoint)<0)){best=(int)i;bs=sc;}}if(s->active_relay!=best){s->active_relay=best;s->revision++;}return best;}
int qrx_aura_provider_supervisor_record_runtime(QrxAuraProviderSupervisor*s,int healthy,uint64_t h){if(!s||s->version!=1)return-1;s->last_runtime_probe_height=h;if(healthy){s->runtime_healthy=1;s->runtime_consecutive_failures=0;}else{s->runtime_healthy=0;if(s->runtime_consecutive_failures<UINT32_MAX)s->runtime_consecutive_failures++;}s->revision++;return 0;}
int qrx_aura_provider_supervisor_restart_recommended(const QrxAuraProviderSupervisor*s,uint64_t h){if(!s||s->version!=1)return 1;if(!s->runtime_healthy&&s->runtime_consecutive_failures>=3)return 1;if(s->relay_required){int any=0;for(uint32_t i=0;i<s->relay_count;i++)if(relay_score(&s->relays[i],h)){any=1;break;}if(!any)return 1;}return 0;}
int qrx_aura_provider_supervisor_maintenance(QrxAuraProviderSupervisor*s,QrxAuraJobJournal*j,const char*path,size_t*removed){if(removed)*removed=0;if(!s||s->version!=1||!j)return-1;size_t n=qrx_aura_job_journal_compact(j,s->keep_committed_jobs,s->keep_prepared_jobs);if(n&&path&&path[0]&&qrx_aura_job_journal_save(path,j))return-2;if(removed)*removed=n;if(n)s->revision++;return 0;}
int qrx_aura_provider_supervisor_status(const QrxAuraProviderSupervisor*s,uint64_t h,QrxAuraProviderSupervisorStatus*out){if(!s||!out||s->version!=1)return-1;memset(out,0,sizeof(*out));out->relay_count=s->relay_count;out->active_relay=s->active_relay;for(uint32_t i=0;i<s->relay_count;i++)if(relay_score(&s->relays[i],h))out->available_relays++;out->runtime_healthy=s->runtime_healthy;out->runtime_consecutive_failures=s->runtime_consecutive_failures;out->restart_recommended=qrx_aura_provider_supervisor_restart_recommended(s,h)?1:0;out->revision=s->revision;return 0;}
