#include "compute/qrx_pouc_pipeline.h"
#include "compute/qrx_pouc_consensus.h"
#include <openssl/evp.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <limits.h>

#define POOL_KEY "consensus:compute:escrow_pool"
#define FUND_PREFIX "consensus:compute:funding:"
#define ASSIGN_PREFIX "consensus:compute:assignment:"
#define RECEIPT_PREFIX "consensus:compute:receipt:"
#define RECEIPT_GRAPH_PREFIX "consensus:compute:receipt_by_graph:"
#define VERIFY_PREFIX "consensus:compute:verify:"
#define VERIFY_AGG_PREFIX "consensus:compute:verification_aggregate:"
#define CHALLENGE_VOTE_PREFIX "consensus:compute:challenge_vote:"
#define CHALLENGE_AGG_PREFIX "consensus:compute:challenge_aggregate:"

static int hex64(const char*s){if(!s||strlen(s)!=64)return 0;for(size_t i=0;i<64;i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return 0;}return 1;}
static int safe(const char*s){return s&&s[0]&&!strchr(s,';')&&!strchr(s,'|')&&!strchr(s,'\n')&&!strchr(s,'\r');}
static int u64s(const char*s,uint64_t*out){if(!s||!*s||!out||*s=='-')return -1;errno=0;char*e=NULL;unsigned long long v=strtoull(s,&e,10);if(errno||!e||*e)return -1;*out=(uint64_t)v;return 0;}
static int u32s(const char*s,uint32_t*out){uint64_t v=0;if(u64s(s,&v)||v>UINT32_MAX)return -1;*out=(uint32_t)v;return 0;}
static char* fld(const char*p,const char*k){if(!p||!k)return NULL;size_t kl=strlen(k);const char*s=p;while(*s){const char*e=strchr(s,';');size_t n=e?(size_t)(e-s):strlen(s);if(n>kl+1&&!strncmp(s,k,kl)&&s[kl]=='='){size_t z=n-kl-1;char*r=malloc(z+1);if(!r)return NULL;memcpy(r,s+kl+1,z);r[z]=0;return r;}if(!e)break;s=e+1;}return NULL;}
static int dbu64(QrxDB*d,const char*k,uint64_t*out){char b[128];if(qrxdb_get(d,k,b,sizeof(b)))return -1;return u64s(b,out);}
static int putu64(QrxDBBatch*b,const char*k,uint64_t v){char x[64];snprintf(x,sizeof(x),"%llu",(unsigned long long)v);return qrxdb_batch_put(b,k,x);}
static int exists(QrxDB*d,const char*k){char b[8];return qrxdb_get(d,k,b,sizeof(b))==0;}
static int sha_field(EVP_MD_CTX*c,const void*p,size_t n){uint64_t z=(uint64_t)n;return EVP_DigestUpdate(c,&z,sizeof(z))==1&&(!n||EVP_DigestUpdate(c,p,n)==1)?0:-1;}
static int finish(EVP_MD_CTX*c,char out[65]){unsigned char h[32];unsigned int n=0;if(EVP_DigestFinal_ex(c,h,&n)!=1||n!=32)return -1;static const char x[]="0123456789abcdef";for(int i=0;i<32;i++){out[i*2]=x[h[i]>>4];out[i*2+1]=x[h[i]&15];}out[64]=0;return 0;}

uint32_t qrx_pouc_pipeline_target_verifiers(uint32_t mode){switch(mode){case QRX_POUC_VERIFY_SPOT:return 1;case QRX_POUC_VERIFY_RANDOM:return 2;case QRX_POUC_VERIFY_REDUNDANT_2_OF_3:return 3;default:return 0;}}

static int assignment_commit(const QrxPoucAssignment*a,char out[65]){if(!a||a->version!=1||!hex64(a->graph_commitment)||!safe(a->owner)||!safe(a->provider)||!safe(a->quote_id)||!safe(a->runtime_id)||!hex64(a->model_commitment)||!a->node_id||!a->quote_price_atoms||!a->quote_expiry_height||!qrx_pouc_pipeline_target_verifiers(a->verification_mode)||!a->assignment_nonce||!a->assigned_height)return -1;EVP_MD_CTX*c=EVP_MD_CTX_new();if(!c)return -1;int ok=EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1;const char dom[]="QRX/POUC/ASSIGNMENT/V1";
#define F(p,n) do{if(ok&&sha_field(c,(p),(n)))ok=0;}while(0)
F(dom,sizeof(dom)-1);F(a->graph_commitment,64);F(a->owner,strlen(a->owner));F(a->provider,strlen(a->provider));F(a->quote_id,strlen(a->quote_id));F(a->runtime_id,strlen(a->runtime_id));F(a->model_commitment,64);F(&a->node_id,sizeof(a->node_id));F(&a->quote_price_atoms,sizeof(a->quote_price_atoms));F(&a->quote_expiry_height,sizeof(a->quote_expiry_height));F(&a->verification_mode,sizeof(a->verification_mode));F(&a->assignment_nonce,sizeof(a->assignment_nonce));F(&a->assigned_height,sizeof(a->assigned_height));
#undef F
int rc=ok?finish(c,out):-1;EVP_MD_CTX_free(c);return rc;}

static int assignment_encode(const QrxPoucAssignment*a,char*out,size_t n){if(!a||!out||assignment_commit(a,(char[65]){0})||!hex64(a->assignment_commitment))return -1;int z=snprintf(out,n,"%u|%s|%s|%s|%s|%s|%s|%u|%llu|%llu|%u|%llu|%llu|%s",a->version,a->graph_commitment,a->owner,a->provider,a->quote_id,a->runtime_id,a->model_commitment,a->node_id,(unsigned long long)a->quote_price_atoms,(unsigned long long)a->quote_expiry_height,a->verification_mode,(unsigned long long)a->assignment_nonce,(unsigned long long)a->assigned_height,a->assignment_commitment);return z>0&&(size_t)z<n?0:-1;}
static int assignment_decode(const char*s,QrxPoucAssignment*a){if(!s||!a)return -1;memset(a,0,sizeof(*a));unsigned v=0,node=0,mode=0;unsigned long long p=0,qe=0,nn=0,ah=0;char gc[65]={0},o[160]={0},pr[160]={0},q[129]={0},rt[96]={0},mc[65]={0},ac[65]={0};if(sscanf(s,"%u|%64[^|]|%159[^|]|%159[^|]|%128[^|]|%95[^|]|%64[^|]|%u|%llu|%llu|%u|%llu|%llu|%64s",&v,gc,o,pr,q,rt,mc,&node,&p,&qe,&mode,&nn,&ah,ac)!=14)return -1;a->version=v;a->node_id=node;a->quote_price_atoms=p;a->quote_expiry_height=qe;a->verification_mode=mode;a->assignment_nonce=nn;a->assigned_height=ah;snprintf(a->graph_commitment,65,"%s",gc);snprintf(a->owner,sizeof(a->owner),"%s",o);snprintf(a->provider,sizeof(a->provider),"%s",pr);snprintf(a->quote_id,sizeof(a->quote_id),"%s",q);snprintf(a->runtime_id,sizeof(a->runtime_id),"%s",rt);snprintf(a->model_commitment,65,"%s",mc);snprintf(a->assignment_commitment,65,"%s",ac);char chk[65];return assignment_commit(a,chk)||strcmp(chk,a->assignment_commitment)?-1:0;}
int qrx_pouc_pipeline_get_assignment(QrxDB*d,const char gc[65],QrxPoucAssignment*out){if(!d||!hex64(gc)||!out)return -1;char k[180],v[1024];snprintf(k,sizeof(k),"%s%s",ASSIGN_PREFIX,gc);if(qrxdb_get(d,k,v,sizeof(v)))return -2;return assignment_decode(v,out);}

static int receipt_encode(const QrxPoucReceipt*r,char*out,size_t n){char rc[65];if(qrx_pouc_receipt_commitment(r,rc))return -1;int z=snprintf(out,n,"%u|%u|%s|%s|%s|%s|%s|%s|%s|%llu|%llu|%llu|%u",r->version,r->node_id,r->provider_id,r->runtime_id,r->graph_commitment,r->input_commitment,r->model_commitment,r->execution_params_commitment,r->result_commitment,(unsigned long long)r->verified_compute_atoms,(unsigned long long)r->started_height,(unsigned long long)r->completed_height,r->verification_mode);return z>0&&(size_t)z<n?0:-1;}
static int receipt_decode(const char*s,QrxPoucReceipt*r){if(!s||!r)return -1;memset(r,0,sizeof(*r));unsigned v=0,node=0,mode=0;unsigned long long atoms=0,st=0,co=0;char pr[160]={0},rt[96]={0},gc[65]={0},ic[65]={0},mc[65]={0},pc[65]={0},oc[65]={0};if(sscanf(s,"%u|%u|%159[^|]|%95[^|]|%64[^|]|%64[^|]|%64[^|]|%64[^|]|%64[^|]|%llu|%llu|%llu|%u",&v,&node,pr,rt,gc,ic,mc,pc,oc,&atoms,&st,&co,&mode)!=13)return -1;r->version=v;r->node_id=node;r->verified_compute_atoms=atoms;r->started_height=st;r->completed_height=co;r->verification_mode=mode;snprintf(r->provider_id,sizeof(r->provider_id),"%s",pr);snprintf(r->runtime_id,sizeof(r->runtime_id),"%s",rt);snprintf(r->graph_commitment,65,"%s",gc);snprintf(r->input_commitment,65,"%s",ic);snprintf(r->model_commitment,65,"%s",mc);snprintf(r->execution_params_commitment,65,"%s",pc);snprintf(r->result_commitment,65,"%s",oc);return qrx_pouc_receipt_validate(r);}
int qrx_pouc_pipeline_get_receipt(QrxDB*d,const char rc[65],QrxPoucReceipt*out){if(!d||!hex64(rc)||!out)return -1;char k[180],v[1024];snprintf(k,sizeof(k),"%s%s",RECEIPT_PREFIX,rc);if(qrxdb_get(d,k,v,sizeof(v)))return -2;return receipt_decode(v,out);}
int qrx_pouc_pipeline_get_receipt_for_graph(QrxDB*d,const char gc[65],char rc[65]){if(!d||!hex64(gc)||!rc)return -1;char k[180],v[96];snprintf(k,sizeof(k),"%s%s",RECEIPT_GRAPH_PREFIX,gc);if(qrxdb_get(d,k,v,sizeof(v))||!hex64(v))return -2;snprintf(rc,65,"%s",v);return 0;}

static int agg_encode(const QrxPoucVerificationAggregate*a,char*out,size_t n){if(!a||a->version!=1||a->matching_verifiers+a->mismatching_verifiers!=a->verifier_count||a->verifier_count>a->target_verifiers||!a->target_verifiers)return -1;int z=snprintf(out,n,"%u|%u|%u|%u|%u|%u",a->version,a->verifier_count,a->matching_verifiers,a->mismatching_verifiers,a->target_verifiers,(unsigned)a->finalized);return z>0&&(size_t)z<n?0:-1;}
static int agg_decode(const char*s,QrxPoucVerificationAggregate*a){if(!s||!a)return -1;memset(a,0,sizeof(*a));unsigned v=0,c=0,m=0,mm=0,t=0,f=0;if(sscanf(s,"%u|%u|%u|%u|%u|%u",&v,&c,&m,&mm,&t,&f)!=6)return -1;a->version=v;a->verifier_count=c;a->matching_verifiers=m;a->mismatching_verifiers=mm;a->target_verifiers=t;a->finalized=(uint8_t)f;char x[128];return agg_encode(a,x,sizeof(x));}
int qrx_pouc_pipeline_get_verification(QrxDB*d,const char rc[65],QrxPoucVerificationAggregate*out){if(!d||!hex64(rc)||!out)return -1;char k[180],v[128];snprintf(k,sizeof(k),"%s%s",VERIFY_AGG_PREFIX,rc);if(qrxdb_get(d,k,v,sizeof(v)))return -2;return agg_decode(v,out);}

static uint64_t verifier_power(QrxDB*d,const char*a){uint64_t total=0,x=0;char k[512];snprintf(k,sizeof(k),"staking:self:%s",a);if(!dbu64(d,k,&x)&&UINT64_MAX-total>=x)total+=x;snprintf(k,sizeof(k),"staking:delegated_total:%s",a);if(!dbu64(d,k,&x)&&UINT64_MAX-total>=x)total+=x;snprintf(k,sizeof(k),"genesis:validator:%s:amount_atoms",a);if(!dbu64(d,k,&x)&&UINT64_MAX-total>=x)total+=x;return total;}

static int receipt_payload(const char*p,const QrxPoucAssignment*a,QrxPoucReceipt*r){char*gc=fld(p,"graph_commitment"),*node=fld(p,"node_id"),*provider=fld(p,"provider_id"),*runtime=fld(p,"runtime_id"),*input=fld(p,"input_commitment"),*model=fld(p,"model_commitment"),*params=fld(p,"execution_params_commitment"),*result=fld(p,"result_commitment"),*atoms=fld(p,"verified_compute_atoms"),*started=fld(p,"started_height"),*completed=fld(p,"completed_height"),*mode=fld(p,"verification_mode");int ok=gc&&node&&provider&&runtime&&input&&model&&params&&result&&atoms&&started&&completed&&mode;uint32_t nd=0,md=0;memset(r,0,sizeof(*r));r->version=1;if(ok)ok=hex64(gc)&&hex64(input)&&hex64(model)&&hex64(params)&&hex64(result)&&safe(provider)&&safe(runtime)&&!u32s(node,&nd)&&!u64s(atoms,&r->verified_compute_atoms)&&!u64s(started,&r->started_height)&&!u64s(completed,&r->completed_height)&&!u32s(mode,&md);if(ok){r->node_id=nd;r->verification_mode=md;snprintf(r->graph_commitment,65,"%s",gc);snprintf(r->provider_id,sizeof(r->provider_id),"%s",provider);snprintf(r->runtime_id,sizeof(r->runtime_id),"%s",runtime);snprintf(r->input_commitment,65,"%s",input);snprintf(r->model_commitment,65,"%s",model);snprintf(r->execution_params_commitment,65,"%s",params);snprintf(r->result_commitment,65,"%s",result);ok=!qrx_pouc_receipt_validate(r)&&!strcmp(r->graph_commitment,a->graph_commitment)&&r->node_id==a->node_id&&!strcmp(r->provider_id,a->provider)&&!strcmp(r->runtime_id,a->runtime_id)&&!strcmp(r->model_commitment,a->model_commitment)&&r->verification_mode==a->verification_mode&&r->verified_compute_atoms<=a->quote_price_atoms&&r->started_height>=a->assigned_height&&r->completed_height>=r->started_height;}
free(gc);free(node);free(provider);free(runtime);free(input);free(model);free(params);free(result);free(atoms);free(started);free(completed);free(mode);return ok?0:-1;}

static int adversarial_result(const QrxPoucReceipt*r,const char observed[65],uint32_t vc,uint32_t mc,QrxComputeAdversarialVerdict*v){QrxComputeAdversarialEvidence e;memset(&e,0,sizeof(e));e.version=1;snprintf(e.scenario_id,sizeof(e.scenario_id),"receipt-%.*s",32,r->result_commitment);e.attack=QRX_ADV_RESULT_MISMATCH;snprintf(e.provider_id,sizeof(e.provider_id),"%s",r->provider_id);snprintf(e.expected_result_commitment,65,"%s",r->result_commitment);snprintf(e.observed_result_commitment,65,"%s",observed);e.verifier_count=vc;e.matching_verifiers=mc;return qrx_compute_adversarial_evaluate(&e,v);}
typedef struct { const char *expected; char observed[65]; } MismatchScan;
static int mismatch_scan_cb(const char*k,const char*v,uint32_t n,void*opaque){(void)k;MismatchScan*c=(MismatchScan*)opaque;if(c->observed[0]||!v||n<73)return 0;const char*p=strstr(v,"observed=");if(!p)return 0;p+=9;if(strlen(p)<64)return 0;char x[65];memcpy(x,p,64);x[64]=0;if(hex64(x)&&strcmp(x,c->expected))snprintf(c->observed,65,"%s",x);return 0;}
static int find_prior_mismatch(QrxDB*d,const char rc[65],const char expected[65],char out[65]){char pre[256];snprintf(pre,sizeof(pre),"%s%s:",VERIFY_PREFIX,rc);MismatchScan c={expected,{0}};if(qrxdb_scan_prefix(d,pre,mismatch_scan_cb,&c)||!c.observed[0])return -1;snprintf(out,65,"%s",c.observed);return 0;}

int qrx_pouc_pipeline_prepare(QrxDB*d,const char*tt,const char*from,const char*to,uint64_t amount,const char*p,uint64_t h,QrxPoucPipelineEffect*out){
    if(!d||!tt||!from||!to||!p||!out||amount||!h||!safe(from)||!safe(to))return -1;memset(out,0,sizeof(*out));out->version=1;
    if(!strcmp(tt,"COMPUTE_ESCROW_LOCK")){
        out->op=QRX_POUC_PIPELINE_ESCROW_LOCK;if(strcmp(from,to))return -2;char*gc=fld(p,"graph_commitment"),*ma=fld(p,"max_compute_atoms"),*fa=fld(p,"fasttrack_fee_atoms"),*vr=fld(p,"verification_reward_atoms"),*ex=fld(p,"expiry_height");uint64_t max=0,fast=0,verify_reward=0,expiry=0;int ok=gc&&ma&&fa&&ex&&hex64(gc)&&!u64s(ma,&max)&&max&&!u64s(fa,&fast)&&(!vr||!u64s(vr,&verify_reward))&&!u64s(ex,&expiry)&&expiry>h&&UINT64_MAX-max>=fast&&UINT64_MAX-(max+fast)>=verify_reward;free(ma);free(fa);if(vr)free(vr);free(ex);if(!ok){free(gc);return -3;}QrxComputeEscrow old;if(!qrx_pouc_journal_get_escrow(d,gc,&old)){free(gc);return -4;}QrxComputeEscrow*e=&out->escrow_after;memset(e,0,sizeof(*e));e->market_version=QRX_COMPUTE_MARKET_VERSION;snprintf(e->graph_commitment,65,"%s",gc);snprintf(e->owner,sizeof(e->owner),"%s",from);e->max_compute_atoms=max;e->fasttrack_fee_atoms=fast;e->verification_reward_atoms=verify_reward;e->verification_reward_spent_atoms=0;e->locked_atoms=max+fast+verify_reward;e->expiry_height=expiry;e->state=QRX_COMPUTE_ESCROW_LOCKED;out->debit_atoms=e->locked_atoms;free(gc);return out->debit_atoms<=LLONG_MAX?0:-5;
    }
    if(!strcmp(tt,"COMPUTE_ASSIGN")){
        out->op=QRX_POUC_PIPELINE_ASSIGN;char*gc=fld(p,"graph_commitment"),*node=fld(p,"node_id"),*qid=fld(p,"quote_id"),*price=fld(p,"quote_price_atoms"),*qe=fld(p,"quote_expiry_height"),*mode=fld(p,"verification_mode"),*an=fld(p,"assignment_nonce"),*rt=fld(p,"runtime_id"),*mc=fld(p,"model_commitment");uint32_t nd=0,md=0;uint64_t pr=0,qexp=0,nonce=0;int ok=gc&&node&&qid&&price&&qe&&mode&&an&&rt&&mc&&hex64(gc)&&safe(qid)&&safe(rt)&&hex64(mc)&&!u32s(node,&nd)&&nd&&!u64s(price,&pr)&&pr&&!u64s(qe,&qexp)&&qexp>=h&&!u32s(mode,&md)&&qrx_pouc_pipeline_target_verifiers(md)&&!u64s(an,&nonce)&&nonce;QrxComputeEscrow e;if(ok)ok=!qrx_pouc_journal_get_escrow(d,gc,&e)&&e.state==QRX_COMPUTE_ESCROW_LOCKED&&!strcmp(e.owner,from)&&e.expiry_height>=qexp&&pr<=e.max_compute_atoms&&strcmp(from,to)&&safe(to);QrxPoucAssignment prev;if(ok&&qrx_pouc_pipeline_get_assignment(d,gc,&prev)==0)ok=0;if(ok){QrxPoucAssignment*a=&out->assignment;a->version=1;snprintf(a->graph_commitment,65,"%s",gc);snprintf(a->owner,sizeof(a->owner),"%s",from);snprintf(a->provider,sizeof(a->provider),"%s",to);snprintf(a->quote_id,sizeof(a->quote_id),"%s",qid);snprintf(a->runtime_id,sizeof(a->runtime_id),"%s",rt);snprintf(a->model_commitment,65,"%s",mc);a->node_id=nd;a->quote_price_atoms=pr;a->quote_expiry_height=qexp;a->verification_mode=md;a->assignment_nonce=nonce;a->assigned_height=h;if(assignment_commit(a,a->assignment_commitment))ok=0;out->escrow_before=e;out->escrow_after=e;if(ok&&qrx_compute_escrow_mark_assigned(&out->escrow_after))ok=0;}free(gc);free(node);free(qid);free(price);free(qe);free(mode);free(an);free(rt);free(mc);return ok?0:-6;
    }
    if(!strcmp(tt,"COMPUTE_RECEIPT")){
        out->op=QRX_POUC_PIPELINE_RECEIPT;char*gc=fld(p,"graph_commitment");QrxPoucAssignment a;int ok=gc&&hex64(gc)&&!qrx_pouc_pipeline_get_assignment(d,gc,&a)&&!strcmp(from,a.provider)&&!strcmp(to,a.owner);QrxComputeEscrow e;if(ok)ok=!qrx_pouc_journal_get_escrow(d,gc,&e)&&e.state==QRX_COMPUTE_ESCROW_ASSIGNED&&h<=e.expiry_height;if(ok)ok=!receipt_payload(p,&a,&out->receipt)&&out->receipt.completed_height<=h;char existing[65];if(ok&&qrx_pouc_pipeline_get_receipt_for_graph(d,gc,existing)==0)ok=0;if(ok)ok=!qrx_pouc_receipt_commitment(&out->receipt,out->receipt_commitment);if(ok){QrxComputeEscrow esc;if(qrx_pouc_journal_get_escrow(d,gc,&esc))ok=0;else if(h<2||qrx_pouc_verifier_selection_build(d,out->receipt_commitment,a.owner,a.provider,a.verification_mode,h-1,h,esc.verification_reward_atoms,&out->selection))ok=0;}free(gc);return ok?0:-7;
    }
    if(!strcmp(tt,"COMPUTE_VERIFY")){
        out->op=QRX_POUC_PIPELINE_VERIFY;char*rc=fld(p,"receipt_commitment"),*obs=fld(p,"observed_result_commitment");int ok=rc&&obs&&hex64(rc)&&hex64(obs)&&verifier_power(d,from)>0;QrxPoucReceipt r;QrxPoucAssignment a;QrxPoucVerifierSelection sel;if(ok)ok=!qrx_pouc_pipeline_get_receipt(d,rc,&r)&&!qrx_pouc_pipeline_get_assignment(d,r.graph_commitment,&a)&&!qrx_pouc_verifier_selection_get(d,rc,&sel)&&qrx_pouc_verifier_is_primary(&sel,from)&&h<=sel.verification_deadline_height&&!strcmp(to,r.provider_id)&&strcmp(from,r.provider_id)&&strcmp(from,a.owner);char vk[512];if(ok){snprintf(vk,sizeof(vk),"%s%s:%s",VERIFY_PREFIX,rc,from);if(exists(d,vk))ok=0;}QrxPoucVerificationAggregate ag={0};if(ok){if(qrx_pouc_pipeline_get_verification(d,rc,&ag)){ag.version=1;ag.target_verifiers=qrx_pouc_pipeline_target_verifiers(r.verification_mode);}if(!ag.target_verifiers||ag.finalized||ag.verifier_count>=ag.target_verifiers)ok=0;}if(ok){QrxComputeEscrow esc;if(qrx_pouc_journal_get_escrow(d,r.graph_commitment,&esc))ok=0;else if(esc.verification_reward_spent_atoms>esc.verification_reward_atoms||sel.primary_reward_atoms>esc.verification_reward_atoms-esc.verification_reward_spent_atoms)ok=0;else{out->escrow_before=esc;out->escrow_after=esc;out->escrow_after.verification_reward_spent_atoms+=sel.primary_reward_atoms;out->reward_credit_atoms=sel.primary_reward_atoms;out->reward_role=1;out->selection=sel;}}if(ok){ag.verifier_count++;if(!strcmp(obs,r.result_commitment))ag.matching_verifiers++;else ag.mismatching_verifiers++;ag.finalized=ag.verifier_count==ag.target_verifiers;out->verification=ag;snprintf(out->receipt_commitment,65,"%s",rc);snprintf(out->verifier,sizeof(out->verifier),"%s",from);snprintf(out->observed_result_commitment,65,"%s",obs);out->receipt=r;if(ag.finalized){QrxPoucVerification v;if(qrx_pouc_verify_result(&r,ag.verifier_count,ag.matching_verifiers,&v))ok=0;else if(!v.accepted){out->challenge_status=QRX_POUC_CHALLENGE_FAILED;if(ag.mismatching_verifiers>=2){char bad[65];snprintf(bad,65,"%s",obs);if(!strcmp(bad,r.result_commitment))find_prior_mismatch(d,rc,r.result_commitment,bad);if(hex64(bad)&&strcmp(bad,r.result_commitment)&&!adversarial_result(&r,bad,ag.verifier_count,ag.matching_verifiers,&out->adversarial)&&out->adversarial.detected)out->has_adversarial_verdict=1;}}else if(v.challenge_required)out->challenge_status=QRX_POUC_CHALLENGE_PENDING;}}free(rc);free(obs);return ok?0:-8;
    }
    if(!strcmp(tt,"COMPUTE_CHALLENGE")){
        out->op=QRX_POUC_PIPELINE_CHALLENGE;char*rc=fld(p,"receipt_commitment"),*obs=fld(p,"observed_result_commitment");int ok=rc&&obs&&hex64(rc)&&hex64(obs)&&verifier_power(d,from)>0;QrxPoucReceipt r;QrxPoucAssignment a;QrxPoucVerificationAggregate ag;QrxPoucVerifierSelection sel;if(ok)ok=!qrx_pouc_pipeline_get_receipt(d,rc,&r)&&!qrx_pouc_pipeline_get_assignment(d,r.graph_commitment,&a)&&!qrx_pouc_pipeline_get_verification(d,rc,&ag)&&!qrx_pouc_verifier_selection_get(d,rc,&sel)&&qrx_pouc_verifier_is_challenger(&sel,from)&&h<=sel.challenge_deadline_height&&ag.finalized&&!strcmp(to,r.provider_id)&&strcmp(from,r.provider_id)&&strcmp(from,a.owner);char ck[180],cv[32];if(ok){snprintf(ck,sizeof(ck),"consensus:compute:challenge:%s",rc);if(qrxdb_get(d,ck,cv,sizeof(cv))||strcmp(cv,"PENDING"))ok=0;}char vk[512];if(ok){snprintf(vk,sizeof(vk),"%s%s:%s",CHALLENGE_VOTE_PREFIX,rc,from);if(exists(d,vk))ok=0;snprintf(vk,sizeof(vk),"%s%s:%s",VERIFY_PREFIX,rc,from);if(exists(d,vk))ok=0;}uint64_t votes=0,pass=0,fail=0;char ak[180],av[128];if(ok){snprintf(ak,sizeof(ak),"%s%s",CHALLENGE_AGG_PREFIX,rc);if(qrxdb_get(d,ak,av,sizeof(av))==0){unsigned long long x=0,y=0,z=0;if(sscanf(av,"%llu|%llu|%llu",&x,&y,&z)!=3)ok=0;votes=x;pass=y;fail=z;}if(votes>=QRX_POUC_CHALLENGE_QUORUM)ok=0;}if(ok){QrxComputeEscrow esc;if(qrx_pouc_journal_get_escrow(d,r.graph_commitment,&esc))ok=0;else if(esc.verification_reward_spent_atoms>esc.verification_reward_atoms||sel.challenge_reward_atoms>esc.verification_reward_atoms-esc.verification_reward_spent_atoms)ok=0;else{out->escrow_before=esc;out->escrow_after=esc;out->escrow_after.verification_reward_spent_atoms+=sel.challenge_reward_atoms;out->reward_credit_atoms=sel.challenge_reward_atoms;out->reward_role=2;out->selection=sel;}}if(ok){votes++;if(!strcmp(obs,r.result_commitment))pass++;else fail++;out->challenge_votes=(uint32_t)votes;out->challenge_pass_votes=(uint32_t)pass;out->challenge_fail_votes=(uint32_t)fail;out->challenge_status=(pass>=2)?QRX_POUC_CHALLENGE_PASSED:(fail>=2)?QRX_POUC_CHALLENGE_FAILED:QRX_POUC_CHALLENGE_PENDING;snprintf(out->receipt_commitment,65,"%s",rc);snprintf(out->verifier,sizeof(out->verifier),"%s",from);snprintf(out->observed_result_commitment,65,"%s",obs);out->receipt=r;if(out->challenge_status==QRX_POUC_CHALLENGE_FAILED&&!adversarial_result(&r,obs,ag.verifier_count,ag.matching_verifiers,&out->adversarial)&&out->adversarial.detected)out->has_adversarial_verdict=1;}free(rc);free(obs);return ok?0:-9;
    }
    if(!strcmp(tt,"COMPUTE_RESELECT")){
        out->op=QRX_POUC_PIPELINE_RESELECT;char*rc=fld(p,"receipt_commitment");int ok=rc&&hex64(rc);QrxPoucReceipt r;if(ok)ok=!qrx_pouc_pipeline_get_receipt(d,rc,&r)&&!strcmp(to,r.provider_id)&&strcmp(from,r.provider_id);if(ok)ok=!qrx_pouc_reselection_prepare(d,rc,h,&out->reselection);if(ok)snprintf(out->receipt_commitment,65,"%s",rc);free(rc);return ok?0:-10;
    }
    return -11;
}

int qrx_pouc_pipeline_stage(QrxDB*d,QrxDBBatch*b,const QrxPoucPipelineEffect*e,const char*txid,uint64_t h){if(!d||!b||!e||e->version!=1||!txid||!*txid||!h)return -1;char k[512],v[1536];
    if(e->op==QRX_POUC_PIPELINE_ESCROW_LOCK){uint64_t pool=0;char x[128];if(qrxdb_get(d,POOL_KEY,x,sizeof(x))==0&&u64s(x,&pool))return -2;if(UINT64_MAX-pool<e->debit_atoms)return -2;if(qrx_pouc_journal_stage_escrow(b,&e->escrow_after)||putu64(b,POOL_KEY,pool+e->debit_atoms))return -3;snprintf(k,sizeof(k),"%s%s",FUND_PREFIX,e->escrow_after.graph_commitment);snprintf(v,sizeof(v),"height=%llu|owner=%s|locked=%llu|max_compute=%llu|fasttrack=%llu|verification_reward=%llu|expiry=%llu|txid=%s",(unsigned long long)h,e->escrow_after.owner,(unsigned long long)e->escrow_after.locked_atoms,(unsigned long long)e->escrow_after.max_compute_atoms,(unsigned long long)e->escrow_after.fasttrack_fee_atoms,(unsigned long long)e->escrow_after.verification_reward_atoms,(unsigned long long)e->escrow_after.expiry_height,txid);return qrxdb_batch_put(b,k,v);}
    if(e->op==QRX_POUC_PIPELINE_ASSIGN){char av[1024];if(assignment_encode(&e->assignment,av,sizeof(av))||qrx_pouc_journal_stage_escrow(b,&e->escrow_after))return -4;snprintf(k,sizeof(k),"%s%s",ASSIGN_PREFIX,e->assignment.graph_commitment);if(qrxdb_batch_put(b,k,av))return -4;snprintf(k,sizeof(k),"consensus:compute:assignment_tx:%s",e->assignment.graph_commitment);return qrxdb_batch_put(b,k,txid);}
    if(e->op==QRX_POUC_PIPELINE_RECEIPT){char rv[1024];if(receipt_encode(&e->receipt,rv,sizeof(rv))||qrx_pouc_verifier_selection_stage(b,&e->selection))return -5;snprintf(k,sizeof(k),"%s%s",RECEIPT_PREFIX,e->receipt_commitment);if(qrxdb_batch_put(b,k,rv))return -5;snprintf(k,sizeof(k),"%s%s",RECEIPT_GRAPH_PREFIX,e->receipt.graph_commitment);if(qrxdb_batch_put(b,k,e->receipt_commitment))return -5;snprintf(k,sizeof(k),"consensus:compute:receipt_tx:%s",e->receipt_commitment);return qrxdb_batch_put(b,k,txid);}
    if(e->op==QRX_POUC_PIPELINE_VERIFY){if(e->reward_credit_atoms){uint64_t pool=0;if(dbu64(d,POOL_KEY,&pool)||pool<e->reward_credit_atoms||qrx_pouc_journal_stage_escrow(b,&e->escrow_after)||putu64(b,POOL_KEY,pool-e->reward_credit_atoms))return -6;}snprintf(k,sizeof(k),"%s%s:%s",VERIFY_PREFIX,e->receipt_commitment,e->verifier);snprintf(v,sizeof(v),"height=%llu|observed=%s|match=%u|reward=%llu|txid=%s",(unsigned long long)h,e->observed_result_commitment,(unsigned)!strcmp(e->observed_result_commitment,e->receipt.result_commitment),(unsigned long long)e->reward_credit_atoms,txid);if(qrxdb_batch_put(b,k,v))return -6;char ag[128];if(agg_encode(&e->verification,ag,sizeof(ag)))return -6;snprintf(k,sizeof(k),"%s%s",VERIFY_AGG_PREFIX,e->receipt_commitment);if(qrxdb_batch_put(b,k,ag))return -6;if(e->challenge_status&&qrx_pouc_consensus_stage_challenge(b,e->receipt_commitment,e->challenge_status))return -6;if(e->has_adversarial_verdict&&qrx_pouc_consensus_stage_adversarial(b,e->receipt_commitment,&e->adversarial))return -6;return 0;}
    if(e->op==QRX_POUC_PIPELINE_CHALLENGE){if(e->reward_credit_atoms){uint64_t pool=0;if(dbu64(d,POOL_KEY,&pool)||pool<e->reward_credit_atoms||qrx_pouc_journal_stage_escrow(b,&e->escrow_after)||putu64(b,POOL_KEY,pool-e->reward_credit_atoms))return -7;}snprintf(k,sizeof(k),"%s%s:%s",CHALLENGE_VOTE_PREFIX,e->receipt_commitment,e->verifier);snprintf(v,sizeof(v),"height=%llu|observed=%s|pass=%u|reward=%llu|txid=%s",(unsigned long long)h,e->observed_result_commitment,(unsigned)!strcmp(e->observed_result_commitment,e->receipt.result_commitment),(unsigned long long)e->reward_credit_atoms,txid);if(qrxdb_batch_put(b,k,v))return -7;snprintf(k,sizeof(k),"%s%s",CHALLENGE_AGG_PREFIX,e->receipt_commitment);snprintf(v,sizeof(v),"%u|%u|%u",e->challenge_votes,e->challenge_pass_votes,e->challenge_fail_votes);if(qrxdb_batch_put(b,k,v)||qrx_pouc_consensus_stage_challenge(b,e->receipt_commitment,e->challenge_status))return -7;if(e->has_adversarial_verdict&&qrx_pouc_consensus_stage_adversarial(b,e->receipt_commitment,&e->adversarial))return -7;return 0;}
    if(e->op==QRX_POUC_PIPELINE_RESELECT)return qrx_pouc_reselection_stage(d,b,&e->reselection,txid);
    return -8;
}

const char*qrx_pouc_pipeline_op_name(QrxPoucPipelineOp o){switch(o){case QRX_POUC_PIPELINE_ESCROW_LOCK:return "ESCROW_LOCK";case QRX_POUC_PIPELINE_ASSIGN:return "ASSIGN";case QRX_POUC_PIPELINE_RECEIPT:return "RECEIPT";case QRX_POUC_PIPELINE_VERIFY:return "VERIFY";case QRX_POUC_PIPELINE_CHALLENGE:return "CHALLENGE";case QRX_POUC_PIPELINE_RESELECT:return "RESELECT";default:return "NONE";}}
