#include "compute/qrx_compute_provider_identity.h"
#include <openssl/pem.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int safe(const char*s,size_t max){if(!s||!*s||strlen(s)>=max)return 0;for(const unsigned char*p=(const unsigned char*)s;*p;p++)if(*p<0x21||*p=='|'||*p==';'||*p=='\n'||*p=='\r')return 0;return 1;}
static char*field(const char*p,const char*k){if(!p||!k)return NULL;size_t kn=strlen(k);while(*p){while(*p==';')p++;const char*e=strchr(p,';');size_t n=e?(size_t)(e-p):strlen(p);if(n>kn&&p[kn]=='='&&!memcmp(p,k,kn)){char*v=malloc(n-kn);if(!v)return NULL;memcpy(v,p+kn+1,n-kn-1);v[n-kn-1]=0;return v;}if(!e)break;p=e+1;}return NULL;}
static int u64s(const char*s,uint64_t*out){if(!s||!*s||!out)return -1;char*e=NULL;unsigned long long v=strtoull(s,&e,10);if(!e||*e)return -1;*out=(uint64_t)v;return 0;}
static EVP_PKEY*key_from_b64(const char*b64){if(!b64||!*b64||strlen(b64)>=QRX_COMPUTE_PROVIDER_KEY_B64_MAX)return NULL;size_t n=strlen(b64);unsigned char*buf=malloc(n+4);if(!buf)return NULL;int z=EVP_DecodeBlock(buf,(const unsigned char*)b64,(int)n);if(z<=0){free(buf);return NULL;}while(n&&b64[n-1]=='='){z--;n--;}BIO*bio=BIO_new_mem_buf(buf,z);EVP_PKEY*k=bio?PEM_read_bio_PUBKEY(bio,NULL,NULL,NULL):NULL;BIO_free(bio);free(buf);return k;}
static int key_ok_b64(const char*b64){EVP_PKEY*k=key_from_b64(b64);if(!k)return 0;const char*n=EVP_PKEY_get0_type_name(k);int ok=n&&!strcmp(n,QRX_COMPUTE_PROVIDER_KEY_SCHEME);EVP_PKEY_free(k);return ok;}
static int encode(const QrxComputeProviderIdentity*i,char*out,size_t n){int z=snprintf(out,n,"%u|%s|%s|%s|%s|%llu|%llu",i->version,i->provider_id,i->owner,i->key_scheme,i->public_key_pem_b64,(unsigned long long)i->sequence,(unsigned long long)i->bound_height);return z>0&&(size_t)z<n?0:-1;}
static int decode(const char*v,QrxComputeProviderIdentity*i){if(!v||!i)return -1;char*t=strdup(v);if(!t)return -1;char*sv=NULL,*a[7];int n=0;for(char*x=strtok_r(t,"|",&sv);x&&n<7;x=strtok_r(NULL,"|",&sv))a[n++]=x;if(n!=7){free(t);return -1;}memset(i,0,sizeof(*i));i->version=(uint32_t)strtoul(a[0],NULL,10);snprintf(i->provider_id,sizeof(i->provider_id),"%s",a[1]);snprintf(i->owner,sizeof(i->owner),"%s",a[2]);snprintf(i->key_scheme,sizeof(i->key_scheme),"%s",a[3]);snprintf(i->public_key_pem_b64,sizeof(i->public_key_pem_b64),"%s",a[4]);i->sequence=strtoull(a[5],NULL,10);i->bound_height=strtoull(a[6],NULL,10);free(t);return qrx_compute_provider_identity_validate(i);}
int qrx_compute_provider_identity_validate(const QrxComputeProviderIdentity*i){if(!i||i->version!=QRX_COMPUTE_PROVIDER_IDENTITY_VERSION||!safe(i->provider_id,sizeof(i->provider_id))||!safe(i->owner,sizeof(i->owner))||strcmp(i->provider_id,i->owner)||strcmp(i->key_scheme,QRX_COMPUTE_PROVIDER_KEY_SCHEME)||!i->sequence||!i->bound_height||!key_ok_b64(i->public_key_pem_b64))return -1;return 0;}
int qrx_compute_provider_identity_get(QrxDB*d,const char*id,QrxComputeProviderIdentity*out){if(!d||!out||!safe(id,QRX_COMPUTE_PROVIDER_ID_MAX+1))return -1;char k[320],v[QRX_COMPUTE_PROVIDER_KEY_B64_MAX+512];snprintf(k,sizeof(k),QRX_COMPUTE_PROVIDER_IDENTITY_PREFIX"%s",id);if(qrxdb_get(d,k,v,sizeof(v)))return -2;return decode(v,out);}
int qrx_compute_provider_identity_key_lookup(void*ctx,const char*id,EVP_PKEY**out){if(!ctx||!id||!out)return -1;*out=NULL;QrxComputeProviderIdentity i;if(qrx_compute_provider_identity_get((QrxDB*)ctx,id,&i))return -1;EVP_PKEY*k=key_from_b64(i.public_key_pem_b64);if(!k)return -1;const char*n=EVP_PKEY_get0_type_name(k);if(!n||strcmp(n,QRX_COMPUTE_PROVIDER_KEY_SCHEME)){EVP_PKEY_free(k);return -1;}*out=k;return 0;}
static int parse_payload(const char*from,const char*p,uint64_t h,QrxComputeProviderIdentity*out){char*kb=field(p,"public_key_pem_b64"),*sq=field(p,"sequence");uint64_t seq=0;int ok=from&&kb&&sq&&!u64s(sq,&seq)&&seq&&key_ok_b64(kb);if(ok){memset(out,0,sizeof(*out));out->version=QRX_COMPUTE_PROVIDER_IDENTITY_VERSION;snprintf(out->provider_id,sizeof(out->provider_id),"%s",from);snprintf(out->owner,sizeof(out->owner),"%s",from);snprintf(out->key_scheme,sizeof(out->key_scheme),"%s",QRX_COMPUTE_PROVIDER_KEY_SCHEME);snprintf(out->public_key_pem_b64,sizeof(out->public_key_pem_b64),"%s",kb);out->sequence=seq;out->bound_height=h;ok=!qrx_compute_provider_identity_validate(out);}free(kb);free(sq);return ok?0:-1;}
int qrx_compute_provider_identity_prepare(QrxDB*d,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,uint64_t h,QrxServiceEconomicEffect*e){if(!d||!tx||strcmp(tx,QRX_COMPUTE_PROVIDER_BIND_TX)||!from||!to||strcmp(from,to)||amount||!h||!e)return -1;memset(e,0,sizeof(*e));QrxComputeProviderIdentity next;if(parse_payload(from,p,h,&next))return -2;QrxComputeProviderIdentity old;if(!qrx_compute_provider_identity_get(d,from,&old)&&next.sequence<=old.sequence)return -3;return 0;}
int qrx_compute_provider_identity_stage(QrxDB*d,QrxDBBatch*b,const char*tx,const char*from,const char*to,uint64_t amount,const char*p,uint64_t h){if(!d||!b||!b->active||b->db!=d||strcmp(tx,QRX_COMPUTE_PROVIDER_BIND_TX)||strcmp(from,to)||amount)return -1;QrxComputeProviderIdentity i;if(parse_payload(from,p,h,&i))return -2;QrxComputeProviderIdentity old;if(!qrx_compute_provider_identity_get(d,from,&old)&&i.sequence<=old.sequence)return -3;char k[320],v[QRX_COMPUTE_PROVIDER_KEY_B64_MAX+512];snprintf(k,sizeof(k),QRX_COMPUTE_PROVIDER_IDENTITY_PREFIX"%s",from);if(encode(&i,v,sizeof(v)))return -4;return qrxdb_batch_put(b,k,v);}
static int fld(EVP_MD_CTX*x,const void*p,size_t n){uint8_t z[8];uint64_t v=n;for(int i=7;i>=0;i--){z[i]=(uint8_t)v;v>>=8;}return EVP_DigestUpdate(x,z,8)==1&&(!n||EVP_DigestUpdate(x,p,n)==1)?0:-1;}
static int u64be(EVP_MD_CTX*x,uint64_t v){uint8_t z[8];for(int i=7;i>=0;i--){z[i]=(uint8_t)v;v>>=8;}return EVP_DigestUpdate(x,z,8)==1?0:-1;}
int qrx_compute_provider_identity_commitment(const QrxComputeProviderIdentity*i,char out[65]){if(qrx_compute_provider_identity_validate(i)||!out)return -1;const char dom[]="QRX/COMPUTE/PROVIDER-IDENTITY/V1";EVP_MD_CTX*x=EVP_MD_CTX_new();uint8_t h[32];unsigned hn=0;int ok=x&&EVP_DigestInit_ex(x,EVP_sha3_256(),NULL)==1;if(ok&&fld(x,dom,sizeof(dom)-1))ok=0;if(ok&&fld(x,i->provider_id,strlen(i->provider_id)))ok=0;if(ok&&fld(x,i->owner,strlen(i->owner)))ok=0;if(ok&&fld(x,i->key_scheme,strlen(i->key_scheme)))ok=0;if(ok&&fld(x,i->public_key_pem_b64,strlen(i->public_key_pem_b64)))ok=0;if(ok&&u64be(x,i->sequence))ok=0;if(ok&&u64be(x,i->bound_height))ok=0;if(ok&&EVP_DigestFinal_ex(x,h,&hn)!=1)ok=0;EVP_MD_CTX_free(x);if(!ok||hn!=32)return -2;static const char hx[]="0123456789abcdef";for(int j=0;j<32;j++){out[j*2]=hx[h[j]>>4];out[j*2+1]=hx[h[j]&15];}out[64]=0;return 0;}
