#include "compute/qrx_aura_model_distribution.h"
#include <limits.h>
#include <openssl/crypto.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MANIFEST_DOMAIN "QRX/AURA/MODEL-MANIFEST/V1"
#define CATALOG_DOMAIN "QRX/AURA/MODEL-CATALOG/V1"
#define AVAIL_DOMAIN "QRX/AURA/MODEL-AVAILABILITY/V1"

typedef struct { uint8_t *p; size_t n,cap; } Buf;
static int grow(Buf*b,size_t add){if(!b||SIZE_MAX-b->n<add)return-1;size_t need=b->n+add;if(need<=b->cap)return 0;size_t c=b->cap?b->cap:512;while(c<need){if(c>SIZE_MAX/2){c=need;break;}c*=2;}uint8_t*q=realloc(b->p,c);if(!q)return-1;b->p=q;b->cap=c;return 0;}
static int bp(Buf*b,const void*p,size_t n){if(grow(b,n))return-1;if(n)memcpy(b->p+b->n,p,n);b->n+=n;return 0;}
static int b32(Buf*b,uint32_t v){uint8_t x[4]={(uint8_t)(v>>24),(uint8_t)(v>>16),(uint8_t)(v>>8),(uint8_t)v};return bp(b,x,4);}
static int b64(Buf*b,uint64_t v){uint8_t x[8];for(int i=7;i>=0;i--){x[i]=(uint8_t)v;v>>=8;}return bp(b,x,8);}
static int bs(Buf*b,const char*s,size_t cap){if(!s||!memchr(s,0,cap))return-1;size_t n=strlen(s);if(n>UINT32_MAX)return-1;return b32(b,(uint32_t)n)||bp(b,s,n)?-1:0;}
static int hex64(const char*s){if(!s||strlen(s)!=64)return 0;for(size_t i=0;i<64;i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return 0;}return 1;}
static void hex32(const uint8_t h[32],char out[65]){static const char*x="0123456789abcdef";for(int i=0;i<32;i++){out[i*2]=x[h[i]>>4];out[i*2+1]=x[h[i]&15];}out[64]=0;}
static int hash_domain(const char*d,const void*p,size_t n,uint8_t out[32]){EVP_MD_CTX*m=EVP_MD_CTX_new();unsigned hn=0;if(!m)return-1;int ok=EVP_DigestInit_ex(m,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(m,d,strlen(d))==1&&(!n||EVP_DigestUpdate(m,p,n)==1)&&EVP_DigestFinal_ex(m,out,&hn)==1&&hn==32;EVP_MD_CTX_free(m);return ok?0:-1;}
static int sign_hash(EVP_PKEY*k,const uint8_t h[32],uint8_t**sig,size_t*sn){if(!k||!sig||!sn)return-1;*sig=NULL;*sn=0;EVP_MD_CTX*m=EVP_MD_CTX_new();size_t n=0;uint8_t*p=NULL;int rc=-1;if(!m||EVP_DigestSignInit_ex(m,NULL,NULL,NULL,NULL,k,NULL)!=1||EVP_DigestSign(m,NULL,&n,h,32)!=1||!n||n>QRX_AURA_MODEL_SIGNATURE_MAX)goto done;p=malloc(n);if(!p)goto done;if(EVP_DigestSign(m,p,&n,h,32)!=1)goto done;*sig=p;*sn=n;p=NULL;rc=0;done:free(p);EVP_MD_CTX_free(m);return rc;}
static int verify_hash(EVP_PKEY*k,const uint8_t h[32],const uint8_t*sig,size_t sn){if(!k||!sig||!sn||sn>QRX_AURA_MODEL_SIGNATURE_MAX)return-1;EVP_MD_CTX*m=EVP_MD_CTX_new();int ok=m&&EVP_DigestVerifyInit_ex(m,NULL,NULL,NULL,NULL,k,NULL)==1&&EVP_DigestVerify(m,sig,sn,h,32)==1;EVP_MD_CTX_free(m);return ok?0:-1;}
static int bps(uint32_t v){return v<=10000u;}

int qrx_aura_model_manifest_validate(const QrxAuraModelManifest*m){
    if(!m||m->version!=QRX_AURA_MODEL_DIST_VERSION||!m->model_id[0]||!m->model_version[0]||!m->family[0]||!m->architecture[0]||!m->format[0]||!m->quantization[0])return-1;
    if(!memchr(m->model_id,0,sizeof(m->model_id))||!memchr(m->model_version,0,sizeof(m->model_version))||!memchr(m->family,0,sizeof(m->family))||!memchr(m->architecture,0,sizeof(m->architecture))||!memchr(m->format,0,sizeof(m->format))||!memchr(m->quantization,0,sizeof(m->quantization))||!memchr(m->license_id,0,sizeof(m->license_id))||!memchr(m->origin_uri,0,sizeof(m->origin_uri)))return-1;
    if(!m->asset_count||m->asset_count>QRX_AURA_MODEL_MANIFEST_MAX_ASSETS)return-1;
    uint64_t total=0;
    for(uint32_t i=0;i<m->asset_count;i++){const QrxAuraModelAsset*a=&m->assets[i];if(a->index!=i||a->kind<QRX_AURA_ASSET_CONFIG||a->kind>QRX_AURA_ASSET_ADAPTER||!hex64(a->content_root)||!a->bytes)return-1;if(UINT64_MAX-total<a->bytes)return-1;total+=a->bytes;}
    return total==m->total_bytes?0:-1;
}
static int manifest_payload(const QrxAuraModelManifest*m,Buf*b){if(qrx_aura_model_manifest_validate(m))return-1;if(b32(b,m->version)||bs(b,m->model_id,sizeof(m->model_id))||bs(b,m->model_version,sizeof(m->model_version))||bs(b,m->family,sizeof(m->family))||bs(b,m->architecture,sizeof(m->architecture))||bs(b,m->format,sizeof(m->format))||bs(b,m->quantization,sizeof(m->quantization))||bs(b,m->license_id,sizeof(m->license_id))||bs(b,m->origin_uri,sizeof(m->origin_uri))||b32(b,m->max_context_tokens)||b32(b,m->asset_count)||b64(b,m->total_bytes))return-1;for(uint32_t i=0;i<m->asset_count;i++){const QrxAuraModelAsset*a=&m->assets[i];if(b32(b,a->index)||b32(b,(uint32_t)a->kind)||bs(b,a->content_root,65)||b64(b,a->bytes)||b32(b,a->layer_first)||b32(b,a->layer_count)||b32(b,a->expert_first)||b32(b,a->expert_count)||b32(b,a->required_for_boot?1u:0u))return-1;}return 0;}
int qrx_aura_model_manifest_commitment(const QrxAuraModelManifest*m,char out[65]){if(!out)return-1;Buf b={0};uint8_t h[32];if(manifest_payload(m,&b)||hash_domain(MANIFEST_DOMAIN,b.p,b.n,h)){free(b.p);return-1;}hex32(h,out);OPENSSL_cleanse(h,sizeof(h));free(b.p);return 0;}
static int catalog_payload(const QrxAuraModelCatalogAnnouncement*a,Buf*b){char root[65];if(!a||a->version!=1||!a->publisher_id[0]||!memchr(a->publisher_id,0,sizeof(a->publisher_id))||!a->sequence||a->valid_until_height<a->valid_from_height||!bps(a->popularity_bps)||!bps(a->priority_bps)||qrx_aura_model_profile_validate(&a->capability)||qrx_aura_model_manifest_commitment(&a->manifest,root)||strcmp(root,a->manifest_root)||strcmp(a->manifest.model_id,a->capability.model_id)||strcmp(a->manifest.model_version,a->capability.model_version))return-1;if(b32(b,a->version)||bs(b,a->publisher_id,sizeof(a->publisher_id))||b64(b,a->sequence)||b64(b,a->valid_from_height)||b64(b,a->valid_until_height)||bs(b,a->manifest_root,65)||manifest_payload(&a->manifest,b)||bs(b,a->capability.runtime_id,sizeof(a->capability.runtime_id))||b32(b,(uint32_t)a->capability.tier)||b64(b,a->capability.min_memory_bytes)||b64(b,a->capability.recommended_memory_bytes)||b64(b,a->capability.min_storage_bytes)||b64(b,a->capability.min_aggregate_milli_tokens_per_second)||b32(b,a->capability.min_pods)||b32(b,a->capability.min_network_mbps)||b32(b,a->capability.max_latency_ms)||b32(b,a->capability.min_reliability_bps)||b32(b,a->capability.min_cache_hit_bps)||b32(b,a->capability.min_expert_locality_bps)||b32(b,a->capability.max_context_tokens)||b32(b,a->capability.quality_bps)||b32(b,a->capability.coding_bps)||b32(b,a->capability.reasoning_bps)||b32(b,a->capability.rag_bps)||b32(b,a->capability.tool_use_bps)||b32(b,a->capability.required_accelerator_features)||b32(b,a->capability.is_moe)||b32(b,a->capability.supports_single_device)||b32(b,a->popularity_bps)||b32(b,a->priority_bps)||b32(b,a->recommended))return-1;return 0;}
int qrx_aura_model_catalog_announcement_hash(const QrxAuraModelCatalogAnnouncement*a,uint8_t out[32]){Buf b={0};if(!out||catalog_payload(a,&b)){free(b.p);return-1;}int rc=hash_domain(CATALOG_DOMAIN,b.p,b.n,out);free(b.p);return rc;}
int qrx_aura_model_catalog_announcement_sign(EVP_PKEY*k,const QrxAuraModelCatalogAnnouncement*a,uint8_t**sig,size_t*sn){uint8_t h[32];return qrx_aura_model_catalog_announcement_hash(a,h)||sign_hash(k,h,sig,sn);}
int qrx_aura_model_catalog_announcement_verify(EVP_PKEY*k,const QrxAuraModelCatalogAnnouncement*a,const uint8_t*sig,size_t sn){uint8_t h[32];return qrx_aura_model_catalog_announcement_hash(a,h)||verify_hash(k,h,sig,sn);}
void qrx_aura_model_catalog_init(QrxAuraModelCatalog*c){if(c)memset(c,0,sizeof(*c));}
void qrx_aura_model_catalog_free(QrxAuraModelCatalog*c){if(!c)return;for(uint32_t i=0;i<c->count;i++)free(c->entries[i].signature);memset(c,0,sizeof(*c));}
static QrxAuraModelCatalogEntry*catalog_slot(QrxAuraModelCatalog*c,const char*id,const char*v){for(uint32_t i=0;i<c->count;i++)if(!strcmp(c->entries[i].announcement.manifest.model_id,id)&&!strcmp(c->entries[i].announcement.manifest.model_version,v))return &c->entries[i];return NULL;}
int qrx_aura_model_catalog_ingest(QrxAuraModelCatalog*c,const QrxAuraModelCatalogAnnouncement*a,const uint8_t*sig,size_t sn,uint64_t h,QrxAuraModelDistKeyLookupFn lookup,void*kctx,QrxAuraModelCatalogAuthorizeFn auth,void*actx){if(!c||!a||!sig||!sn||!lookup||!auth||h<a->valid_from_height||h>a->valid_until_height||auth(actx,a->publisher_id))return-1;uint8_t hh[32];if(qrx_aura_model_catalog_announcement_hash(a,hh))return-1;EVP_PKEY*pk=NULL;if(lookup(kctx,a->publisher_id,&pk)||!pk||verify_hash(pk,hh,sig,sn)){EVP_PKEY_free(pk);return-2;}EVP_PKEY_free(pk);QrxAuraModelCatalogEntry*e=catalog_slot(c,a->manifest.model_id,a->manifest.model_version);if(e&&a->sequence<=e->announcement.sequence)return-3;if(!e){if(c->count>=QRX_AURA_MODEL_CATALOG_MAX)return-4;e=&c->entries[c->count++];memset(e,0,sizeof(*e));}uint8_t*copy=malloc(sn);if(!copy)return-5;memcpy(copy,sig,sn);free(e->signature);e->announcement=*a;e->signature=copy;e->signature_len=sn;c->revision++;return 0;}
const QrxAuraModelCatalogAnnouncement*qrx_aura_model_catalog_find(const QrxAuraModelCatalog*c,const char*id,const char*v){if(!c||!id||!v)return NULL;for(uint32_t i=0;i<c->count;i++)if(!strcmp(c->entries[i].announcement.manifest.model_id,id)&&!strcmp(c->entries[i].announcement.manifest.model_version,v))return &c->entries[i].announcement;return NULL;}
size_t qrx_aura_model_catalog_profiles(const QrxAuraModelCatalog*c,uint64_t h,QrxAuraModelCapabilityProfile*out,size_t cap){if(!c||(!out&&cap))return 0;size_t n=0;for(uint32_t i=0;i<c->count&&n<cap;i++){const QrxAuraModelCatalogAnnouncement*a=&c->entries[i].announcement;if(h<a->valid_from_height||h>a->valid_until_height)continue;out[n++]=a->capability;}return n;}

int qrx_aura_model_availability_set_asset(QrxAuraModelAvailabilityAnnouncement*a,uint32_t idx,int present){if(!a||idx>=QRX_AURA_MODEL_MANIFEST_MAX_ASSETS)return-1;uint8_t m=(uint8_t)(1u<<(idx&7u));if(present)a->asset_bitmap[idx>>3]|=m;else a->asset_bitmap[idx>>3]&=(uint8_t)~m;return 0;}
int qrx_aura_model_availability_has_asset(const QrxAuraModelAvailabilityAnnouncement*a,uint32_t idx){if(!a||idx>=QRX_AURA_MODEL_MANIFEST_MAX_ASSETS)return 0;return a->full_model?1:((a->asset_bitmap[idx>>3]>>(idx&7u))&1u);}
int qrx_aura_model_availability_validate(const QrxAuraModelAvailabilityAnnouncement*a,uint64_t h){if(!a||a->version!=1||!a->provider_id[0]||!a->pod_id[0]||!a->region[0]||!a->endpoint[0]||!a->model_id[0]||!a->model_version[0]||!hex64(a->manifest_root)||!a->sequence||a->valid_until_height<a->valid_from_height||h<a->valid_from_height||h>a->valid_until_height||!bps(a->reliability_bps))return-1;if(!memchr(a->provider_id,0,sizeof(a->provider_id))||!memchr(a->pod_id,0,sizeof(a->pod_id))||!memchr(a->region,0,sizeof(a->region))||!memchr(a->endpoint,0,sizeof(a->endpoint)))return-1;return 0;}
static int availability_payload(const QrxAuraModelAvailabilityAnnouncement*a,Buf*b){if(!a)return-1;if(b32(b,a->version)||bs(b,a->provider_id,sizeof(a->provider_id))||bs(b,a->pod_id,sizeof(a->pod_id))||bs(b,a->region,sizeof(a->region))||bs(b,a->endpoint,sizeof(a->endpoint))||bs(b,a->model_id,sizeof(a->model_id))||bs(b,a->model_version,sizeof(a->model_version))||bs(b,a->manifest_root,65)||b64(b,a->sequence)||b64(b,a->valid_from_height)||b64(b,a->valid_until_height)||b32(b,a->bandwidth_mbps)||b32(b,a->latency_ms)||b32(b,a->reliability_bps)||b32(b,a->full_model)||bp(b,a->asset_bitmap,sizeof(a->asset_bitmap)))return-1;return 0;}
int qrx_aura_model_availability_hash(const QrxAuraModelAvailabilityAnnouncement*a,uint8_t out[32]){if(!a||!out||a->version!=1||!hex64(a->manifest_root)||!a->sequence||a->valid_until_height<a->valid_from_height||!bps(a->reliability_bps))return-1;Buf b={0};if(availability_payload(a,&b)){free(b.p);return-1;}int rc=hash_domain(AVAIL_DOMAIN,b.p,b.n,out);free(b.p);return rc;}
int qrx_aura_model_availability_sign(EVP_PKEY*k,const QrxAuraModelAvailabilityAnnouncement*a,uint8_t**sig,size_t*sn){uint8_t h[32];return qrx_aura_model_availability_hash(a,h)||sign_hash(k,h,sig,sn);}
int qrx_aura_model_availability_verify(EVP_PKEY*k,const QrxAuraModelAvailabilityAnnouncement*a,const uint8_t*sig,size_t sn){uint8_t h[32];return qrx_aura_model_availability_hash(a,h)||verify_hash(k,h,sig,sn);}
void qrx_aura_model_provider_index_init(QrxAuraModelProviderIndex*i){if(i)memset(i,0,sizeof(*i));}
void qrx_aura_model_provider_index_free(QrxAuraModelProviderIndex*i){if(!i)return;for(uint32_t x=0;x<i->count;x++)free(i->entries[x].signature);memset(i,0,sizeof(*i));}
static QrxAuraModelAvailabilityEntry*avail_slot(QrxAuraModelProviderIndex*i,const QrxAuraModelAvailabilityAnnouncement*a){for(uint32_t x=0;x<i->count;x++){QrxAuraModelAvailabilityAnnouncement*b=&i->entries[x].announcement;if(!strcmp(b->provider_id,a->provider_id)&&!strcmp(b->pod_id,a->pod_id)&&!strcmp(b->model_id,a->model_id)&&!strcmp(b->model_version,a->model_version))return&i->entries[x];}return NULL;}
int qrx_aura_model_provider_index_ingest(QrxAuraModelProviderIndex*i,const QrxAuraModelAvailabilityAnnouncement*a,const uint8_t*sig,size_t sn,uint64_t h,QrxAuraModelDistKeyLookupFn lookup,void*kctx){if(!i||!a||!sig||!sn||!lookup||qrx_aura_model_availability_validate(a,h))return-1;EVP_PKEY*pk=NULL;if(lookup(kctx,a->provider_id,&pk)||!pk||qrx_aura_model_availability_verify(pk,a,sig,sn)){EVP_PKEY_free(pk);return-2;}EVP_PKEY_free(pk);QrxAuraModelAvailabilityEntry*e=avail_slot(i,a);if(e&&a->sequence<=e->announcement.sequence)return-3;if(!e){if(i->count>=QRX_AURA_MODEL_PROVIDER_MAX)return-4;e=&i->entries[i->count++];memset(e,0,sizeof(*e));}uint8_t*copy=malloc(sn);if(!copy)return-5;memcpy(copy,sig,sn);free(e->signature);e->announcement=*a;e->signature=copy;e->signature_len=sn;i->revision++;return 0;}
size_t qrx_aura_model_provider_index_prune(QrxAuraModelProviderIndex*i,uint64_t h){if(!i)return 0;uint32_t w=0;size_t n=0;for(uint32_t x=0;x<i->count;x++){if(i->entries[x].announcement.valid_until_height<h){free(i->entries[x].signature);n++;continue;}if(w!=x)i->entries[w]=i->entries[x];w++;}i->count=w;if(n)i->revision++;return n;}
static int same_model(const QrxAuraModelAvailabilityAnnouncement*a,const QrxAuraModelManifest*m,const char*root,uint64_t h){return a&&m&&a->valid_from_height<=h&&a->valid_until_height>=h&&!strcmp(a->model_id,m->model_id)&&!strcmp(a->model_version,m->model_version)&&!strcmp(a->manifest_root,root);}
uint32_t qrx_aura_model_target_replicas(const QrxAuraModelCatalogAnnouncement*c,const QrxAuraModelAsset*a,uint32_t demand){uint32_t v=QRX_AURA_MODEL_MIN_GLOBAL_REPLICAS;if(c){v+=c->popularity_bps/250u;v+=c->priority_bps/250u;}v+=demand/125u;if(a&&(a->required_for_boot||a->kind==QRX_AURA_ASSET_CONFIG||a->kind==QRX_AURA_ASSET_TOKENIZER))v+=16u;if(a&&a->kind==QRX_AURA_ASSET_EXPERT_PACK)v+=8u;if(v>256u)v=256u;return v;}
int qrx_aura_model_asset_health(const QrxAuraModelManifest *m, const QrxAuraModelProviderIndex *i,
                                uint64_t h, uint32_t ai, uint32_t demand,
                                const QrxAuraModelCatalogAnnouncement *c, QrxAuraModelAssetHealth *out) {
    if (!m || !i || !out || ai >= m->asset_count) return -1;
    char root[65];
    if (qrx_aura_model_manifest_commitment(m, root)) return -1;

    uint32_t pn = 0, rn = 0;
    for (uint32_t x = 0; x < i->count; x++) {
        const QrxAuraModelAvailabilityAnnouncement *a = &i->entries[x].announcement;
        if (!same_model(a, m, root, h) || !qrx_aura_model_availability_has_asset(a, ai)) continue;

        int provider_seen = 0, region_seen = 0;
        for (uint32_t y = 0; y < x && (!provider_seen || !region_seen); y++) {
            const QrxAuraModelAvailabilityAnnouncement *prev = &i->entries[y].announcement;
            if (!same_model(prev, m, root, h) || !qrx_aura_model_availability_has_asset(prev, ai)) continue;
            if (!strcmp(prev->provider_id, a->provider_id)) provider_seen = 1;
            if (!strcmp(prev->region, a->region)) region_seen = 1;
        }
        if (!provider_seen) pn++;
        if (!region_seen) rn++;
    }

    memset(out, 0, sizeof(*out));
    out->asset_index = ai;
    out->provider_replicas = pn;
    out->region_replicas = rn;
    out->target_replicas = qrx_aura_model_target_replicas(c, &m->assets[ai], demand);
    out->deficit = pn < out->target_replicas ? out->target_replicas - pn : 0;
    out->demand_bps = demand;
    uint64_t score = (uint64_t)out->deficit * 1000u + demand
        + (m->assets[ai].required_for_boot ? 50000u : 0u)
        + (rn < QRX_AURA_MODEL_MIN_REGIONS ? 20000u : 0u);
    out->priority_score = score > UINT32_MAX ? UINT32_MAX : (uint32_t)score;
    return 0;
}
int qrx_aura_model_zero_config_profile(uint64_t free_disk,QrxAuraPowerProfile power,QrxAuraZeroConfigProfile*out){if(!out||power<QRX_AURA_POWER_ECO||power>QRX_AURA_POWER_PERFORMANCE)return-1;memset(out,0,sizeof(*out));out->version=1;out->power_profile=power;out->automatic_models=1;out->predictive_prefetch=power!=QRX_AURA_POWER_ECO;out->allow_external_origin=1;uint64_t cap=power==QRX_AURA_POWER_ECO?10ull<<30:power==QRX_AURA_POWER_BALANCED?50ull<<30:200ull<<30;uint64_t reserve=free_disk/5;uint64_t usable=free_disk>reserve?free_disk-reserve:0;out->disk_budget_bytes=usable<cap?usable:cap;return 0;}
static int local_has(const uint8_t*b,uint32_t i){return b?((b[i>>3]>>(i&7u))&1u):0;}
typedef struct{uint32_t idx,score;uint64_t bytes;uint8_t boot;}Cand;
static int cand_cmp(const void*A,const void*B){const Cand*a=A,*b=B;if(a->score!=b->score)return a->score>b->score?-1:1;if(a->boot!=b->boot)return a->boot?-1:1;return a->idx<b->idx?-1:a->idx>b->idx;}
int qrx_aura_model_placement_plan(const QrxAuraModelCatalogAnnouncement*c,const QrxAuraModelProviderIndex*i,uint64_t h,const QrxAuraPodCapacity*p,const QrxAuraZeroConfigProfile*z,const uint8_t local[QRX_AURA_MODEL_AVAILABILITY_BITS],QrxAuraModelPlacementPlan*out){if(!c||!i||!p||!z||!out||z->version!=1||qrx_aura_model_manifest_validate(&c->manifest)||qrx_aura_pod_capacity_validate(p)||!z->automatic_models)return-1;if(!(p->role_mask&(QRX_AURA_POD_ROLE_MODEL_CACHE|QRX_AURA_POD_ROLE_INFERENCE)))return-2;uint64_t budget=z->disk_budget_bytes<p->model_cache_free_bytes?z->disk_budget_bytes:p->model_cache_free_bytes;Cand cand[QRX_AURA_MODEL_MANIFEST_MAX_ASSETS];uint32_t cn=0;uint32_t demand=c->popularity_bps;for(uint32_t a=0;a<c->manifest.asset_count;a++){if(local_has(local,a))continue;QrxAuraModelAssetHealth ah;if(qrx_aura_model_asset_health(&c->manifest,i,h,a,demand,c,&ah))continue;if(!ah.deficit&&!c->manifest.assets[a].required_for_boot)continue;cand[cn].idx=a;cand[cn].score=ah.priority_score;cand[cn].bytes=c->manifest.assets[a].bytes;cand[cn].boot=c->manifest.assets[a].required_for_boot;cn++;}qsort(cand,cn,sizeof(cand[0]),cand_cmp);memset(out,0,sizeof(*out));out->version=1;snprintf(out->model_id,sizeof(out->model_id),"%s",c->manifest.model_id);snprintf(out->model_version,sizeof(out->model_version),"%s",c->manifest.model_version);snprintf(out->manifest_root,65,"%s",c->manifest_root);for(uint32_t x=0;x<cn;x++){if(cand[x].bytes>budget-out->total_bytes)continue;QrxAuraModelPlacementItem*it=&out->items[out->item_count++];it->asset_index=cand[x].idx;it->bytes=cand[x].bytes;it->priority_score=cand[x].score;it->boot_required=cand[x].boot;out->total_bytes+=cand[x].bytes;if(out->item_count>=QRX_AURA_MODEL_MANIFEST_MAX_ASSETS)break;}return 0;}
static uint32_t source_score(QrxAuraModelSourceTier t,uint32_t lat,uint32_t bw,uint32_t rel){uint64_t base=(uint64_t)(7u-(uint32_t)t)*100000u;uint64_t s=base+(uint64_t)bw*10u+rel;if(lat<10000u)s+=10000u-lat;return s>UINT32_MAX?UINT32_MAX:(uint32_t)s;}
static int source_cmp(const void*A,const void*B){const QrxAuraModelSource*a=A,*b=B;if(a->score!=b->score)return a->score>b->score?-1:1;return strcmp(a->provider_id,b->provider_id);}
int qrx_aura_model_download_plan(const QrxAuraModelManifest*m,const QrxAuraModelProviderIndex*i,uint64_t h,uint32_t ai,const char*region,uint32_t lan_ceiling,uint8_t allow_origin,QrxAuraModelDownloadPlan*out){if(!m||!i||!out||ai>=m->asset_count||qrx_aura_model_manifest_validate(m))return-1;char root[65];if(qrx_aura_model_manifest_commitment(m,root))return-1;memset(out,0,sizeof(*out));out->version=1;out->asset_index=ai;for(uint32_t x=0;x<i->count&&out->source_count<30;x++){const QrxAuraModelAvailabilityAnnouncement*a=&i->entries[x].announcement;if(!same_model(a,m,root,h)||!qrx_aura_model_availability_has_asset(a,ai))continue;QrxAuraModelSource*s=&out->sources[out->source_count++];if(a->latency_ms<=lan_ceiling)s->tier=QRX_AURA_SOURCE_LAN_PEER;else if(region&&region[0]&&!strcmp(region,a->region)&&a->latency_ms<=20)s->tier=QRX_AURA_SOURCE_POD_PEER;else s->tier=QRX_AURA_SOURCE_NEARBY_PROVIDER;snprintf(s->provider_id,sizeof(s->provider_id),"%s",a->provider_id);snprintf(s->endpoint,sizeof(s->endpoint),"%s",a->endpoint);s->latency_ms=a->latency_ms;s->bandwidth_mbps=a->bandwidth_mbps;s->reliability_bps=a->reliability_bps;s->score=source_score(s->tier,s->latency_ms,s->bandwidth_mbps,s->reliability_bps);}QrxAuraModelSource*d=&out->sources[out->source_count++];d->tier=QRX_AURA_SOURCE_QRX_DRIVE;snprintf(d->provider_id,sizeof(d->provider_id),"QRX_DRIVE");snprintf(d->endpoint,sizeof(d->endpoint),"qrxdrive://model/%s/%s/%u",m->model_id,m->model_version,ai);d->reliability_bps=9000;d->score=source_score(d->tier,100,100,9000);if(allow_origin&&m->origin_uri[0]&&out->source_count<32){QrxAuraModelSource*o=&out->sources[out->source_count++];o->tier=QRX_AURA_SOURCE_EXTERNAL_ORIGIN;snprintf(o->provider_id,sizeof(o->provider_id),"EXTERNAL_ORIGIN");if (strlen(m->origin_uri) >= sizeof(o->endpoint)) { out->source_count--; } else { memcpy(o->endpoint,m->origin_uri,strlen(m->origin_uri)+1); o->reliability_bps=8000; o->score=source_score(o->tier,250,50,8000); }}qsort(out->sources,out->source_count,sizeof(out->sources[0]),source_cmp);return 0;}
