#include "compute/qrx_aura_model_origin.h"
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#ifdef _WIN32
#include <direct.h>
#define MKDIR(p) _mkdir(p)
#else
#include <unistd.h>
#define MKDIR(p) mkdir((p),0700)
#endif
#ifdef QRX_HAVE_CURL
#include <curl/curl.h>
#endif

#define SOURCE_MAGIC "QRXHFM1\0"
#define SOURCE_MAGIC_N 8u

typedef struct { unsigned char *p; size_t n,cap; } Mem;
static int memgrow(Mem*m,size_t add){if(!m||SIZE_MAX-m->n<add)return-1;size_t need=m->n+add;if(need<=m->cap)return 0;size_t c=m->cap?m->cap:4096;while(c<need)c=c>SIZE_MAX/2?need:c*2;void*q=realloc(m->p,c+1);if(!q)return-1;m->p=q;m->cap=c;return 0;}
#ifdef QRX_HAVE_CURL
static size_t wrmem(char*p,size_t s,size_t n,void*v){Mem*m=v;size_t z=s*n;if(memgrow(m,z))return 0;memcpy(m->p+m->n,p,z);m->n+=z;m->p[m->n]=0;return z;}
static size_t wrfile(char*p,size_t s,size_t n,void*v){return fwrite(p,s,n,(FILE*)v);}
/* ---------------------------------------------------------------------------
 * Genesis hardening (Finding 4): AURA model-origin transport policy.
 *
 * Previously this set CURLOPT_FOLLOWLOCATION without restricting the redirect
 * protocol, so a compromised or hostile origin could redirect an HTTPS model
 * fetch down to plain HTTP. Redirects were also unbounded, and TLS peer/host
 * verification relied on libcurl defaults instead of being stated explicitly.
 *
 * The credential handling was the more serious problem. The Hugging Face token
 * was attached with CURLOPT_HTTPHEADER. libcurl forwards custom headers across
 * redirects to *any* host, so a redirect to an attacker-controlled origin
 * leaked the bearer token. Credentials supplied through libcurl's own auth
 * options are instead governed by CURLOPT_UNRESTRICTED_AUTH, which defaults to
 * off and therefore stops the token at a host change.
 * ------------------------------------------------------------------------- */
static int curl_common(CURL*c,const QrxAuraOriginConfig*cfg,const char*url){
    if(!c||!cfg||!url)return -1;
    /* Origin must be HTTPS to begin with. */
    if(strncmp(url,"https://",8)!=0)return -1;
    curl_easy_setopt(c,CURLOPT_URL,url);

    /* Only HTTPS, for the request and for every redirect hop. */
#if defined(CURLOPT_PROTOCOLS_STR)
    curl_easy_setopt(c,CURLOPT_PROTOCOLS_STR,"https");
    curl_easy_setopt(c,CURLOPT_REDIR_PROTOCOLS_STR,"https");
#else
    curl_easy_setopt(c,CURLOPT_PROTOCOLS,(long)CURLPROTO_HTTPS);
    curl_easy_setopt(c,CURLOPT_REDIR_PROTOCOLS,(long)CURLPROTO_HTTPS);
#endif
    curl_easy_setopt(c,CURLOPT_FOLLOWLOCATION,1L);
    curl_easy_setopt(c,CURLOPT_MAXREDIRS,5L);

    /* Explicit TLS policy; never inherit a relaxed build default. */
    curl_easy_setopt(c,CURLOPT_SSL_VERIFYPEER,1L);
    curl_easy_setopt(c,CURLOPT_SSL_VERIFYHOST,2L);
    curl_easy_setopt(c,CURLOPT_SSLVERSION,(long)CURL_SSLVERSION_TLSv1_2);
    if(cfg->tls_ca_bundle[0])curl_easy_setopt(c,CURLOPT_CAINFO,cfg->tls_ca_bundle);

    curl_easy_setopt(c,CURLOPT_FAILONERROR,1L);
    curl_easy_setopt(c,CURLOPT_USERAGENT,"QRX-AURA/0.0.9-genesis");
    curl_easy_setopt(c,CURLOPT_CONNECTTIMEOUT,(long)(cfg->connect_timeout_seconds?cfg->connect_timeout_seconds:20));
    if(cfg->transfer_timeout_seconds)curl_easy_setopt(c,CURLOPT_TIMEOUT,(long)cfg->transfer_timeout_seconds);

    if(cfg->hf_token[0]){
        /* Bearer credential that libcurl drops on a cross-origin redirect. */
        curl_easy_setopt(c,CURLOPT_UNRESTRICTED_AUTH,0L);
#if defined(CURLAUTH_BEARER)
        curl_easy_setopt(c,CURLOPT_HTTPAUTH,(long)CURLAUTH_BEARER);
        curl_easy_setopt(c,CURLOPT_XOAUTH2_BEARER,cfg->hf_token);
#else
        /* Very old libcurl: no bearer auth type. Do not risk leaking the token
         * through a forwarded custom header; refuse the gated fetch instead. */
        return -1;
#endif
    }
    return 0;
}
static void curl_headers_free(CURL*c){void*p=NULL;if(c&&curl_easy_getinfo(c,CURLINFO_PRIVATE,&p)==CURLE_OK&&p)curl_slist_free_all((struct curl_slist*)p);}
static int http_mem(const QrxAuraOriginConfig*cfg,const char*url,size_t max,Mem*out){if(!cfg||!url||!out)return-1;memset(out,0,sizeof(*out));CURL*c=curl_easy_init();if(!c)return-1;if(curl_common(c,cfg,url)){curl_easy_cleanup(c);return-3;}curl_easy_setopt(c,CURLOPT_WRITEFUNCTION,wrmem);curl_easy_setopt(c,CURLOPT_WRITEDATA,out);CURLcode rc=curl_easy_perform(c);long code=0;curl_easy_getinfo(c,CURLINFO_RESPONSE_CODE,&code);curl_headers_free(c);curl_easy_cleanup(c);if(rc!=CURLE_OK||(code&&code>=400)||(max&&out->n>max)){free(out->p);memset(out,0,sizeof(*out));return-2;}return 0;}
static int http_size(const QrxAuraOriginConfig*cfg,const char*url,uint64_t*out){if(!cfg||!url||!out)return-1;CURL*c=curl_easy_init();if(!c)return-1;if(curl_common(c,cfg,url)){curl_easy_cleanup(c);return-3;}curl_easy_setopt(c,CURLOPT_NOBODY,1L);CURLcode rc=curl_easy_perform(c);curl_off_t z=-1;if(rc==CURLE_OK)curl_easy_getinfo(c,CURLINFO_CONTENT_LENGTH_DOWNLOAD_T,&z);curl_headers_free(c);curl_easy_cleanup(c);if(rc!=CURLE_OK||z<0)return-2;*out=(uint64_t)z;return 0;}
static int http_file_resume(const QrxAuraOriginConfig*cfg,const char*url,const char*path,uint64_t total,QrxAuraOriginProgressFn cb,void*ctx){FILE*f=fopen(path,"ab+");if(!f)return-1;if(fseek(f,0,SEEK_END)){fclose(f);return-1;}long pos=ftell(f);if(pos<0){fclose(f);return-1;}uint64_t have=(uint64_t)pos;if(have>total){fclose(f);remove(path);return-1;}if(have==total){fclose(f);return 0;}CURL*c=curl_easy_init();if(!c){fclose(f);return-1;}if(curl_common(c,cfg,url)){curl_easy_cleanup(c);fclose(f);return-3;}curl_easy_setopt(c,CURLOPT_WRITEFUNCTION,wrfile);curl_easy_setopt(c,CURLOPT_WRITEDATA,f);if(have)curl_easy_setopt(c,CURLOPT_RESUME_FROM_LARGE,(curl_off_t)have);CURLcode rc=curl_easy_perform(c);fflush(f);fclose(f);curl_headers_free(c);curl_easy_cleanup(c);if(rc!=CURLE_OK)return-2;FILE*q=fopen(path,"rb");if(!q)return-2;fseek(q,0,SEEK_END);long fin=ftell(q);fclose(q);if(fin<0||(uint64_t)fin!=total)return-2;if(cb)cb(ctx,"download",url,total,total);return 0;}
#else
static int http_mem(const QrxAuraOriginConfig*a,const char*b,size_t c,Mem*d){(void)a;(void)b;(void)c;(void)d;return-90;}
static int http_size(const QrxAuraOriginConfig*a,const char*b,uint64_t*c){(void)a;(void)b;(void)c;return-90;}
static int http_file_resume(const QrxAuraOriginConfig*a,const char*b,const char*c,uint64_t d,QrxAuraOriginProgressFn e,void*f){(void)a;(void)b;(void)c;(void)d;(void)e;(void)f;return-90;}
#endif

static void trim(char*s){if(!s)return;char*p=s;while(isspace((unsigned char)*p))p++;if(p!=s)memmove(s,p,strlen(p)+1);size_t n=strlen(s);while(n&&isspace((unsigned char)s[n-1]))s[--n]=0;}
static int textcpy(char*d,size_t cap,const char*s){if(!d||!cap||!s||strlen(s)>=cap)return-1;memcpy(d,s,strlen(s)+1);return 0;}
static const char*json_key(const char*j,const char*k){char pat[128];snprintf(pat,sizeof(pat),"\"%s\"",k);return strstr(j,pat);}
static int json_string(const char*j,const char*k,char*out,size_t cap){const char*p=json_key(j,k);if(!p)return-1;p=strchr(p,':');if(!p)return-1;p++;while(isspace((unsigned char)*p))p++;if(*p!='\"')return-1;p++;size_t n=0;while(*p&&*p!='\"'){if(*p=='\\'&&p[1])p++;if(n+1>=cap)return-1;out[n++]=*p++;}if(*p!='\"')return-1;out[n]=0;return 0;}
static int json_u32(const char*j,const char*k,uint32_t*out){const char*p=json_key(j,k);if(!p)return-1;p=strchr(p,':');if(!p)return-1;p++;while(isspace((unsigned char)*p))p++;char*e=NULL;unsigned long v=strtoul(p,&e,10);if(e==p||v>0xffffffffUL)return-1;*out=(uint32_t)v;return 0;}
static int json_bool(const char*j,const char*k,uint8_t*out){const char*p=json_key(j,k);if(!p)return-1;p=strchr(p,':');if(!p)return-1;p++;while(isspace((unsigned char)*p))p++;if(!strncmp(p,"true",4)){*out=1;return 0;}if(!strncmp(p,"false",5)){*out=0;return 0;}return-1;}
static uint32_t first_u32(const char*j,const char*const*keys,size_t n,uint32_t def){uint32_t v;for(size_t i=0;i<n;i++)if(!json_u32(j,keys[i],&v))return v;return def;}
static int weight_path(const char*p){size_t n=strlen(p);if(n>=12&&!strcmp(p+n-12,".safetensors"))return 1;if(n>=5&&!strcmp(p+n-5,".gguf"))return 1;return 0;}
static int selected_path(const char*p,const QrxAuraOriginModelSpec*s){size_t n=strlen(p);int weight=weight_path(p);if(weight&&s&&s->file_filter[0]&&strcmp(s->file_filter,"*")&&strcmp(p,s->file_filter))return 0;if(!strcmp(p,"LICENSE")||!strcmp(p,"THIRD_PARTY_NOTICES.md")||!strcmp(p,"config.json")||!strcmp(p,"generation_config.json")||!strcmp(p,"model.safetensors.index.json")||!strcmp(p,"params")||!strcmp(p,"params.json"))return 1;if(strstr(p,"tokenizer")||strstr(p,"processor")||strstr(p,"configuration_")||strstr(p,"modeling_")||strstr(p,"encoding_")||strstr(p,"vision_processing")||strstr(p,"media_utils"))return 1;if(weight)return 1;if(n>=6&&!strcmp(p+n-6,".model"))return 1;if(!strcmp(p,"vocab.json")||!strcmp(p,"merges.txt")||!strcmp(p,"chat_template.jinja"))return 1;return 0;}
static QrxAuraModelAssetKind kind_for(const char*p){size_t n=strlen(p);if(weight_path(p))return QRX_AURA_ASSET_WEIGHT_CHUNK;if(strstr(p,"token")||!strcmp(p,"vocab.json")||!strcmp(p,"merges.txt")||(n>=6&&!strcmp(p+n-6,".model"))||strstr(p,"chat_template"))return QRX_AURA_ASSET_TOKENIZER;if(n>=3&&!strcmp(p+n-3,".py"))return QRX_AURA_ASSET_ADAPTER;return QRX_AURA_ASSET_CONFIG;}
static int make_url(char*out,size_t cap,const char*base,const char*repo,const char*rev,const char*path){int n=snprintf(out,cap,"%s/%s/resolve/%s/%s",base,repo,rev,path);return n<0||(size_t)n>=cap?-1:0;}
static int make_api(char*out,size_t cap,const char*base,const char*repo,const char*rev){int n;if(!strcmp(rev,"main"))n=snprintf(out,cap,"%s/models/%s",base,repo);else n=snprintf(out,cap,"%s/models/%s/revision/%s",base,repo,rev);return n<0||(size_t)n>=cap?-1:0;}
static int sha3_text(const char*s,char out[65]){EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned char h[32];unsigned n=0;if(!c)return-1;int ok=EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(c,s,strlen(s))==1&&EVP_DigestFinal_ex(c,h,&n)==1&&n==32;EVP_MD_CTX_free(c);if(!ok)return-1;static const char*x="0123456789abcdef";for(int i=0;i<32;i++){out[i*2]=x[h[i]>>4];out[i*2+1]=x[h[i]&15];}out[64]=0;return 0;}
static int ensure_dir(const char*p){if(!p||!p[0])return-1;if(!MKDIR(p)||errno==EEXIST)return 0;return-1;}
static void zero_root(char x[65]){memset(x,'0',64);x[64]=0;}

int qrx_aura_origin_config_defaults(QrxAuraOriginConfig*o){if(!o)return-1;memset(o,0,sizeof(*o));o->version=QRX_AURA_ORIGIN_VERSION;snprintf(o->hf_base_url,sizeof(o->hf_base_url),"https://huggingface.co");snprintf(o->hf_api_base_url,sizeof(o->hf_api_base_url),"https://huggingface.co/api");snprintf(o->work_dir,sizeof(o->work_dir),"./qrx-aura-origin-cache");o->connect_timeout_seconds=20;return 0;}

static uint32_t parse_bps(const char*s,uint32_t def){unsigned long v=s&&*s?strtoul(s,NULL,10):def;return v>10000?10000:(uint32_t)v;}
static uint64_t mib_bytes(const char*s){unsigned long long v=s&&*s?strtoull(s,NULL,10):0;return v>UINT64_MAX/(1024ull*1024ull)?0:v*1024ull*1024ull;}
int qrx_aura_origin_catalog_load(const char*path,QrxAuraOriginModelSpec*out,size_t cap,size_t*count){if(!path||!out||!cap||!count)return-1;*count=0;FILE*f=fopen(path,"rb");if(!f)return-2;char line[4096];int hdr=0,ver=0;while(fgets(line,sizeof(line),f)){trim(line);if(!line[0]||line[0]=='#')continue;if(!hdr){if(!strcmp(line,"QRXAURA-ORIGIN-CATALOG-1"))ver=1;else if(!strcmp(line,"QRXAURA-ORIGIN-CATALOG-2"))ver=2;else{fclose(f);return-3;}hdr=1;continue;}if(*count>=cap){fclose(f);return-4;}char*fld[24]={0};size_t n=0;char*save=NULL;for(char*q=strtok_r(line,"|",&save);q&&n<24;q=strtok_r(NULL,"|",&save))fld[n++]=q;if((ver==1&&n!=11)||(ver==2&&n!=22)){fclose(f);return-5;}QrxAuraOriginModelSpec*x=&out[(*count)++];memset(x,0,sizeof(*x));x->version=(uint32_t)ver;textcpy(x->model_id,sizeof(x->model_id),fld[0]);textcpy(x->family,sizeof(x->family),fld[1]);textcpy(x->repo_id,sizeof(x->repo_id),fld[2]);textcpy(x->revision,sizeof(x->revision),fld[3]);textcpy(x->expected_license,sizeof(x->expected_license),fld[4]);textcpy(x->architecture_hint,sizeof(x->architecture_hint),fld[5]);textcpy(x->runtime_id,sizeof(x->runtime_id),fld[6]);textcpy(x->quantization,sizeof(x->quantization),fld[7]);x->tier=(QrxAuraModelTier)strtoul(fld[8],NULL,10);x->recommended=(uint8_t)strtoul(fld[9],NULL,10);x->moe_hint=(uint8_t)strtoul(fld[10],NULL,10);if(ver==1){x->quality_bps=x->coding_bps=x->reasoning_bps=9000;x->rag_bps=8500;x->tool_use_bps=9000;x->auto_default=x->recommended;textcpy(x->file_filter,sizeof(x->file_filter),"*");}else{x->min_memory_bytes=mib_bytes(fld[11]);x->recommended_memory_bytes=mib_bytes(fld[12]);x->min_milli_tokens_per_second=strtoull(fld[13],NULL,10);x->quality_bps=parse_bps(fld[14],9000);x->coding_bps=parse_bps(fld[15],x->quality_bps);x->reasoning_bps=parse_bps(fld[16],x->quality_bps);x->rag_bps=parse_bps(fld[17],x->quality_bps);x->tool_use_bps=parse_bps(fld[18],x->quality_bps);x->auto_default=(uint8_t)strtoul(fld[19],NULL,10);x->gated_optional=(uint8_t)strtoul(fld[20],NULL,10);textcpy(x->file_filter,sizeof(x->file_filter),fld[21]);if(!x->file_filter[0])textcpy(x->file_filter,sizeof(x->file_filter),"*");if(x->recommended_memory_bytes&&x->min_memory_bytes&&x->recommended_memory_bytes<x->min_memory_bytes){fclose(f);return-6;}}}fclose(f);return hdr?0:-3;}

int qrx_aura_origin_spec_profile(const QrxAuraOriginModelSpec*s,QrxAuraModelCapabilityProfile*p){if(!s||!p||s->tier<QRX_AURA_TIER_NANO||s->tier>QRX_AURA_TIER_K3_CLASS)return-1;memset(p,0,sizeof(*p));p->version=QRX_AURA_FABRIC_VERSION;textcpy(p->model_id,sizeof(p->model_id),s->model_id);textcpy(p->model_version,sizeof(p->model_version),"bootstrap");textcpy(p->family,sizeof(p->family),s->family);textcpy(p->runtime_id,sizeof(p->runtime_id),s->runtime_id);textcpy(p->quantization,sizeof(p->quantization),s->quantization);p->tier=s->tier;p->min_memory_bytes=s->min_memory_bytes?s->min_memory_bytes:(s->tier==QRX_AURA_TIER_NANO?2ull<<30:s->tier==QRX_AURA_TIER_EDGE?4ull<<30:s->tier==QRX_AURA_TIER_LOCAL?8ull<<30:s->tier==QRX_AURA_TIER_CLUSTER?16ull<<30:s->tier==QRX_AURA_TIER_K2_CLASS?32ull<<30:64ull<<30);p->recommended_memory_bytes=s->recommended_memory_bytes?s->recommended_memory_bytes:p->min_memory_bytes*2;p->min_storage_bytes=1;p->min_aggregate_milli_tokens_per_second=s->min_milli_tokens_per_second?s->min_milli_tokens_per_second:1;p->min_pods=s->tier>=QRX_AURA_TIER_K2_CLASS?2:1;p->min_network_mbps=s->tier>=QRX_AURA_TIER_K2_CLASS?100:0;p->max_latency_ms=1000;p->min_reliability_bps=0;p->min_cache_hit_bps=0;p->min_expert_locality_bps=0;p->max_context_tokens=2048;p->quality_bps=s->quality_bps?s->quality_bps:9000;p->coding_bps=s->coding_bps?s->coding_bps:p->quality_bps;p->reasoning_bps=s->reasoning_bps?s->reasoning_bps:p->quality_bps;p->rag_bps=s->rag_bps?s->rag_bps:p->quality_bps;p->tool_use_bps=s->tool_use_bps?s->tool_use_bps:p->quality_bps;p->is_moe=s->moe_hint;p->supports_single_device=s->tier<QRX_AURA_TIER_K2_CLASS;return qrx_aura_model_profile_validate(p);}
static uint32_t spec_task_score(const QrxAuraOriginModelSpec*s,QrxAuraTaskClass t){switch(t){case QRX_AURA_TASK_CODING:return s->coding_bps;case QRX_AURA_TASK_REASONING:return s->reasoning_bps;case QRX_AURA_TASK_RAG:return s->rag_bps;case QRX_AURA_TASK_TOOL_USE:return s->tool_use_bps;default:return s->quality_bps;}}
int qrx_aura_origin_auto_select(const QrxAuraOriginModelSpec*specs,size_t count,const QrxAuraPodCapacity*pod,QrxAuraTaskClass task,uint32_t complexity,uint8_t allow_gated,QrxAuraOriginAutoSelection*out){if(!specs||!count||!pod||!out||qrx_aura_pod_capacity_validate(pod)||task<QRX_AURA_TASK_CHAT||task>QRX_AURA_TASK_TOOL_USE)return-1;if(complexity>10000)complexity=10000;QrxAuraModelTier max_tier=complexity<=3000?QRX_AURA_TIER_NANO:complexity<=7000?QRX_AURA_TIER_EDGE:complexity<=9000?QRX_AURA_TIER_LOCAL:QRX_AURA_TIER_K3_CLASS;int found=-1;uint64_t best=0;QrxAuraModelCapabilityProfile bestp;memset(&bestp,0,sizeof(bestp));for(size_t i=0;i<count;i++){const QrxAuraOriginModelSpec*s=&specs[i];if(!s->auto_default||(s->gated_optional&&!allow_gated)||s->tier>max_tier)continue;QrxAuraModelCapabilityProfile p;if(qrx_aura_origin_spec_profile(s,&p))continue;if(pod->free_memory_bytes<p.min_memory_bytes||pod->measured_milli_tokens_per_second<p.min_aggregate_milli_tokens_per_second)continue;uint64_t score=(uint64_t)spec_task_score(s,task)*1000ull+(uint64_t)p.quality_bps*100ull+(uint64_t)s->recommended*250000ull;score+=(uint64_t)s->tier*25000ull;uint64_t spare=pod->free_memory_bytes-p.min_memory_bytes;score+=spare>(8ull<<30)?8000ull:(spare>>20);if(found<0||score>best||(score==best&&strcmp(s->model_id,specs[found].model_id)<0)){found=(int)i;best=score;bestp=p;}}if(found<0){/* graceful degradation: allow any smaller AUTO model that fits */for(size_t i=0;i<count;i++){const QrxAuraOriginModelSpec*s=&specs[i];if(!s->auto_default||(s->gated_optional&&!allow_gated))continue;QrxAuraModelCapabilityProfile p;if(qrx_aura_origin_spec_profile(s,&p))continue;if(pod->free_memory_bytes<p.min_memory_bytes||pod->measured_milli_tokens_per_second<p.min_aggregate_milli_tokens_per_second)continue;uint64_t score=(uint64_t)spec_task_score(s,task)*1000ull;if(found<0||score>best){found=(int)i;best=score;bestp=p;}}}if(found<0)return-2;memset(out,0,sizeof(*out));out->version=1;out->spec_index=(uint32_t)found;out->spec=specs[found];out->profile=bestp;out->degraded=(uint8_t)(out->spec.tier>max_tier?1:0);return 0;}

static int immutable_revision(const char *s){size_t n=s?strlen(s):0;if(n!=40&&n!=64)return 0;for(size_t i=0;i<n;i++)if(!isxdigit((unsigned char)s[i]))return 0;return 1;}

int qrx_aura_hf_repo_resolve(const QrxAuraOriginConfig*cfg,const QrxAuraOriginModelSpec*spec,QrxAuraOriginRepoMetadata*out){if(!cfg||!spec||!out||cfg->version!=1||(spec->version!=1&&spec->version!=2))return-1;const char *requested=spec->revision[0]?spec->revision:"main";char url[QRX_AURA_ORIGIN_URL_MAX*2];if(make_api(url,sizeof(url),cfg->hf_api_base_url,spec->repo_id,requested))return-1;Mem m={0};int hrc=http_mem(cfg,url,8u*1024u*1024u,&m);/* Some HF-compatible origins do not expose /revision/<sha>.  A pinned SHA may safely fall back to base metadata only if the returned SHA is exactly the requested immutable revision. */if(hrc&&immutable_revision(requested)){if(make_api(url,sizeof(url),cfg->hf_api_base_url,spec->repo_id,"main")||http_mem(cfg,url,8u*1024u*1024u,&m))return-2;}else if(hrc)return-2;memset(out,0,sizeof(*out));out->version=1;textcpy(out->repo_id,sizeof(out->repo_id),spec->repo_id);textcpy(out->requested_revision,sizeof(out->requested_revision),requested);if(json_string((char*)m.p,"sha",out->resolved_revision,sizeof(out->resolved_revision))){free(m.p);return-3;}if(immutable_revision(requested)&&strcmp(requested,out->resolved_revision)){free(m.p);return-8;}if(json_string((char*)m.p,"license_name",out->license_id,sizeof(out->license_id))&&json_string((char*)m.p,"license",out->license_id,sizeof(out->license_id)))textcpy(out->license_id,sizeof(out->license_id),spec->expected_license);json_bool((char*)m.p,"gated",&out->gated);if(out->gated&&!cfg->allow_gated){free(m.p);return-4;}if(spec->expected_license[0]&&out->license_id[0]&&strcmp(spec->expected_license,out->license_id)){/* HF often exposes cardData license=other + license_name=modified-mit. Accept if raw metadata names expected license. */if(!strstr((char*)m.p,spec->expected_license)){free(m.p);return-5;}textcpy(out->license_id,sizeof(out->license_id),spec->expected_license);}const char*p=(char*)m.p;while((p=strstr(p,"\"rfilename\""))){p=strchr(p,':');if(!p)break;p++;while(*p&&*p!='\"')p++;if(*p!='\"')break;p++;char fn[QRX_AURA_ORIGIN_PATH_MAX];size_t z=0;while(*p&&*p!='\"'&&z+1<sizeof(fn)){if(*p=='\\'&&p[1])p++;fn[z++]=*p++;}fn[z]=0;if(selected_path(fn,spec)){if(out->file_count>=QRX_AURA_ORIGIN_MAX_FILES){free(m.p);return-6;}textcpy(out->files[out->file_count++].path,sizeof(out->files[0].path),fn);}if(*p)p++;}free(m.p);return out->file_count?0:-7;}

static int w32(Mem*b,uint32_t v){unsigned char x[4]={(unsigned char)(v>>24),(unsigned char)(v>>16),(unsigned char)(v>>8),(unsigned char)v};if(memgrow(b,4))return-1;memcpy(b->p+b->n,x,4);b->n+=4;return 0;}
static int w64(Mem*b,uint64_t v){unsigned char x[8];for(int i=7;i>=0;i--){x[i]=(unsigned char)v;v>>=8;}if(memgrow(b,8))return-1;memcpy(b->p+b->n,x,8);b->n+=8;return 0;}
static int ws(Mem*b,const char*s,size_t cap){if(!s||!memchr(s,0,cap)||strlen(s)>0xffffffffu)return-1;uint32_t n=(uint32_t)strlen(s);if(w32(b,n)||memgrow(b,n))return-1;memcpy(b->p+b->n,s,n);b->n+=n;return 0;}
int qrx_aura_origin_source_map_encode(const QrxAuraOriginSourceMap*m,uint8_t**out,size_t*outn){if(!m||!out||!outn||m->version!=1||!m->file_count||m->file_count>QRX_AURA_ORIGIN_MAX_FILES)return-1;Mem b={0};if(memgrow(&b,SOURCE_MAGIC_N)){return-1;}memcpy(b.p,SOURCE_MAGIC,SOURCE_MAGIC_N);b.n=SOURCE_MAGIC_N;if(w32(&b,m->version)||ws(&b,m->repo_id,sizeof(m->repo_id))||ws(&b,m->revision,sizeof(m->revision))||w32(&b,m->file_count)){free(b.p);return-1;}for(uint32_t i=0;i<m->file_count;i++){const QrxAuraOriginSeededFile*f=&m->files[i];if(!f->path[0]||strlen(f->content_root)!=64||!f->bytes){free(b.p);return-1;}if(ws(&b,f->path,sizeof(f->path))||ws(&b,f->content_root,65)||w64(&b,f->bytes)||w32(&b,(uint32_t)f->kind)||w32(&b,f->layer_first)||w32(&b,f->layer_count)||w32(&b,f->expert_first)||w32(&b,f->expert_count)){free(b.p);return-1;}}*out=b.p;*outn=b.n;return 0;}
typedef struct{const uint8_t*p;size_t n,o;}Rd;static int r32(Rd*r,uint32_t*v){if(r->n-r->o<4)return-1;const uint8_t*p=r->p+r->o;*v=((uint32_t)p[0]<<24)|((uint32_t)p[1]<<16)|((uint32_t)p[2]<<8)|p[3];r->o+=4;return 0;}static int r64(Rd*r,uint64_t*v){if(r->n-r->o<8)return-1;uint64_t x=0;for(int i=0;i<8;i++)x=(x<<8)|r->p[r->o+i];r->o+=8;*v=x;return 0;}static int rs(Rd*r,char*d,size_t cap){uint32_t n;if(r32(r,&n)||n>=cap||r->n-r->o<n)return-1;memcpy(d,r->p+r->o,n);d[n]=0;r->o+=n;return 0;}
int qrx_aura_origin_source_map_decode(const uint8_t*in,size_t n,QrxAuraOriginSourceMap*m){if(!in||!m||n<SOURCE_MAGIC_N||memcmp(in,SOURCE_MAGIC,SOURCE_MAGIC_N))return-1;memset(m,0,sizeof(*m));Rd r={in+SOURCE_MAGIC_N,n-SOURCE_MAGIC_N,0};if(r32(&r,&m->version)||rs(&r,m->repo_id,sizeof(m->repo_id))||rs(&r,m->revision,sizeof(m->revision))||r32(&r,&m->file_count)||m->version!=1||!m->file_count||m->file_count>QRX_AURA_ORIGIN_MAX_FILES)return-1;for(uint32_t i=0;i<m->file_count;i++){QrxAuraOriginSeededFile*f=&m->files[i];uint32_t k;if(rs(&r,f->path,sizeof(f->path))||rs(&r,f->content_root,65)||r64(&r,&f->bytes)||r32(&r,&k)||r32(&r,&f->layer_first)||r32(&r,&f->layer_count)||r32(&r,&f->expert_first)||r32(&r,&f->expert_count))return-1;f->kind=(QrxAuraModelAssetKind)k;}return r.o==r.n?0:-1;}

static QrxAuraOriginSeededFile*map_find(QrxAuraOriginSourceMap*m,const char*path){for(uint32_t i=0;i<m->file_count;i++)if(!strcmp(m->files[i].path,path))return &m->files[i];return NULL;}
static void map_index_ranges(QrxAuraOriginSourceMap*m,const char*j){if(!m||!j)return;const char*p=j;while((p=strstr(p,".layers."))){const char*q=p+8;unsigned long layer=strtoul(q,(char**)&q,10);const char*e=strstr(q,".experts.");if(!e){p=q;continue;}e+=9;char*ee=NULL;unsigned long ex=strtoul(e,&ee,10);if(ee==e){p=e;continue;}const char*colon=strchr(ee,':');if(!colon)break;const char*v=strchr(colon,'\"');if(!v)break;v++;char fn[QRX_AURA_ORIGIN_PATH_MAX];size_t z=0;while(*v&&*v!='\"'&&z+1<sizeof(fn))fn[z++]=*v++;fn[z]=0;QrxAuraOriginSeededFile*f=map_find(m,fn);if(f){if(!f->layer_count){f->layer_first=(uint32_t)layer;f->layer_count=1;}else{uint32_t lo=f->layer_first,hi=lo+f->layer_count-1;if(layer<lo)lo=(uint32_t)layer;if(layer>hi)hi=(uint32_t)layer;f->layer_first=lo;f->layer_count=hi-lo+1;}if(!f->expert_count){f->expert_first=(uint32_t)ex;f->expert_count=1;}else{uint32_t lo=f->expert_first,hi=lo+f->expert_count-1;if(ex<lo)lo=(uint32_t)ex;if(ex>hi)hi=(uint32_t)ex;f->expert_first=lo;f->expert_count=hi-lo+1;}}p=ee;}}
static int get_small(const QrxAuraOriginConfig*c,const QrxAuraOriginRepoMetadata*md,const char*path,Mem*out){char u[2048];if(make_url(u,sizeof(u),c->hf_base_url,md->repo_id,md->resolved_revision,path))return-1;return http_mem(c,u,64u*1024u*1024u,out);}
static int seed_bytes(QrxStorageFs*fs,const void*p,size_t n,char root[65]){return qrx_storage_fs_put(fs,p,n,root);}
static int seed_remote_file(const QrxAuraOriginConfig*c,const QrxAuraOriginRepoMetadata*md,QrxStorageFs*fs,const char*path,QrxAuraOriginProgressFn cb,void*ctx,char root[65],uint64_t*bytes){char u[2048];if(make_url(u,sizeof(u),c->hf_base_url,md->repo_id,md->resolved_revision,path))return-1;uint64_t z=0;if(http_size(c,u,&z)||!z||(c->max_asset_bytes&&z>c->max_asset_bytes))return-2;ensure_dir(c->work_dir);char h[65],tmp[1400];sha3_text(u,h);snprintf(tmp,sizeof(tmp),"%s/%s.part",c->work_dir,h);if(cb)cb(ctx,"asset",path,0,z);if(http_file_resume(c,u,tmp,z,cb,ctx))return-3;if(qrx_storage_fs_put_file(fs,tmp,root)){return-4;}remove(tmp);*bytes=z;return 0;}
static int add_bundle(QrxAuraModelBundleManifest*b,uint32_t kind,uint64_t bytes,const char*root){if(b->object_count>=QRX_AURA_REMOTE_MAX_BUNDLE_OBJECTS)return-1;QrxAuraModelBundleObject*o=&b->objects[b->object_count++];o->kind=kind;o->bytes=bytes;textcpy(o->object_root,sizeof(o->object_root),root);if(UINT64_MAX-b->total_bytes<bytes)return-1;b->total_bytes+=bytes;return 0;}
static uint32_t bundle_kind(QrxAuraModelAssetKind k){if(k==QRX_AURA_ASSET_TOKENIZER)return QRX_AURA_MODEL_OBJECT_TOKENIZER;if(k==QRX_AURA_ASSET_WEIGHT_CHUNK||k==QRX_AURA_ASSET_SHARED_WEIGHTS)return QRX_AURA_MODEL_OBJECT_WEIGHTS;return QRX_AURA_MODEL_OBJECT_CONFIG;}
static int choose_tokenizer(const QrxAuraOriginSourceMap*m,char out[65]){const char*best[] = {"tokenizer.json","tokenizer.model","tiktoken.model","tokenizer_config.json","vocab.json"};for(size_t b=0;b<sizeof(best)/sizeof(best[0]);b++)for(uint32_t i=0;i<m->file_count;i++)if(!strcmp(m->files[i].path,best[b])){textcpy(out,65,m->files[i].content_root);return 0;}for(uint32_t i=0;i<m->file_count;i++)if(m->files[i].kind==QRX_AURA_ASSET_TOKENIZER){textcpy(out,65,m->files[i].content_root);return 0;}for(uint32_t i=0;i<m->file_count;i++){size_t n=strlen(m->files[i].path);if(n>=5&&!strcmp(m->files[i].path+n-5,".gguf")){textcpy(out,65,m->files[i].content_root);return 0;}}return-1;}
static uint64_t memory_floor(const QrxAuraOriginModelSpec*s,uint64_t total){if(s->min_memory_bytes)return s->min_memory_bytes;uint64_t floor=s->tier==QRX_AURA_TIER_NANO?2ull<<30:s->tier==QRX_AURA_TIER_EDGE?4ull<<30:s->tier==QRX_AURA_TIER_LOCAL?8ull<<30:s->tier==QRX_AURA_TIER_CLUSTER?16ull<<30:s->tier==QRX_AURA_TIER_K2_CLASS?32ull<<30:64ull<<30;if(total&&s->tier<=QRX_AURA_TIER_LOCAL){uint64_t with_overhead=total>UINT64_MAX/5?UINT64_MAX:total+total/5;if(with_overhead>floor)floor=with_overhead;}return floor;}

int qrx_aura_hf_seed_to_qrx_drive(const QrxAuraOriginConfig*c,const QrxAuraOriginModelSpec*s,QrxStorageFs*fs,QrxAuraOriginProgressFn cb,void*ctx,QrxAuraOriginSeedResult*out){if(!c||!s||!fs||!out)return-1;memset(out,0,sizeof(*out));if(qrx_aura_hf_repo_resolve(c,s,&out->upstream))return-2;QrxAuraOriginSourceMap*map=&out->source_map;map->version=1;textcpy(map->repo_id,sizeof(map->repo_id),out->upstream.repo_id);textcpy(map->revision,sizeof(map->revision),out->upstream.resolved_revision);
    /* Deterministic lexicographic file order makes the QRX manifest stable even if upstream API order changes. */
    char paths[QRX_AURA_ORIGIN_MAX_FILES][QRX_AURA_ORIGIN_PATH_MAX];uint32_t pc=out->upstream.file_count;for(uint32_t i=0;i<pc;i++)textcpy(paths[i],sizeof(paths[i]),out->upstream.files[i].path);for(uint32_t i=0;i<pc;i++)for(uint32_t j=i+1;j<pc;j++)if(strcmp(paths[i],paths[j])>0){char t[QRX_AURA_ORIGIN_PATH_MAX];memcpy(t,paths[i],sizeof(t));memcpy(paths[i],paths[j],sizeof(t));memcpy(paths[j],t,sizeof(t));}
    Mem cfg={0},idx={0};get_small(c,&out->upstream,"config.json",&cfg);get_small(c,&out->upstream,"model.safetensors.index.json",&idx);
    for(uint32_t i=0;i<pc;i++){if(map->file_count>=QRX_AURA_ORIGIN_MAX_FILES)return-3;QrxAuraOriginSeededFile*f=&map->files[map->file_count++];textcpy(f->path,sizeof(f->path),paths[i]);f->kind=kind_for(f->path);Mem sm={0};int small=(f->kind!=QRX_AURA_ASSET_WEIGHT_CHUNK);if(small&&!get_small(c,&out->upstream,f->path,&sm)){if(!sm.n||seed_bytes(fs,sm.p,sm.n,f->content_root)){free(sm.p);return-4;}f->bytes=sm.n;free(sm.p);}else{if(seed_remote_file(c,&out->upstream,fs,f->path,cb,ctx,f->content_root,&f->bytes))return-5;}}
    if(idx.p)map_index_ranges(map,(char*)idx.p);
    uint32_t layers=0,experts=0,topk=0,context=0;char arch[QRX_MODEL_MAX_ARCH]={0};if(cfg.p){const char*lk[]={"num_hidden_layers","num_layers","n_layer"};const char*ek[]={"n_routed_experts","num_local_experts","num_experts","moe_num_experts"};const char*tk[]={"num_experts_per_tok","num_experts_per_token","num_selected_experts","moe_top_k"};const char*ck[]={"max_position_embeddings","max_sequence_length","seq_length"};layers=first_u32((char*)cfg.p,lk,3,1);experts=first_u32((char*)cfg.p,ek,4,0);topk=first_u32((char*)cfg.p,tk,4,experts?1:0);context=first_u32((char*)cfg.p,ck,3,131072);json_string((char*)cfg.p,"model_type",arch,sizeof(arch));}if(!arch[0])textcpy(arch,sizeof(arch),s->architecture_hint[0]?s->architecture_hint:"transformer");free(cfg.p);free(idx.p);
    QrxAuraModelBundleManifest*b=&out->drive_bundle;memset(b,0,sizeof(*b));b->version=QRX_AURA_MODEL_BUNDLE_VERSION;textcpy(b->model_id,sizeof(b->model_id),s->model_id);textcpy(b->model_version,sizeof(b->model_version),out->upstream.resolved_revision);for(uint32_t i=0;i<map->file_count;i++)if(add_bundle(b,bundle_kind(map->files[i].kind),map->files[i].bytes,map->files[i].content_root))return-6;
    uint8_t*mb=NULL;size_t mn=0;if(qrx_aura_origin_source_map_encode(map,&mb,&mn)||seed_bytes(fs,mb,mn,out->source_map_root)){free(mb);return-7;}free(mb);if(add_bundle(b,QRX_AURA_MODEL_OBJECT_SOURCE_MAP,mn,out->source_map_root))return-7;
    if((experts&&topk)||s->moe_hint){QrxAuraExpertManifest*em=&out->expert_manifest;memset(em,0,sizeof(*em));em->version=QRX_AURA_EXPERT_MANIFEST_VERSION;textcpy(em->model_id,sizeof(em->model_id),s->model_id);textcpy(em->model_version,sizeof(em->model_version),out->upstream.resolved_revision);textcpy(em->architecture,sizeof(em->architecture),arch);em->layer_count=layers?layers:1;em->expert_count=experts?experts:1;em->experts_per_token=topk?topk:1;uint8_t*eb=NULL;size_t en=0;char er[65];if(qrx_aura_expert_manifest_encode(em,&eb,&en)||seed_bytes(fs,eb,en,er)){free(eb);return-8;}free(eb);out->has_expert_manifest=1;if(add_bundle(b,QRX_AURA_MODEL_OBJECT_EXPERT_MANIFEST,en,er))return-8;}
    uint8_t*bb=NULL;size_t bn=0;if(qrx_aura_model_bundle_encode(b,&bb,&bn)||seed_bytes(fs,bb,bn,out->drive_bundle_root)){free(bb);return-9;}free(bb);char br[65];if(qrx_aura_model_bundle_root(b,br)||strcmp(br,out->drive_bundle_root))return-9;
    QrxAuraModelManifest*dm=&out->distribution_manifest;memset(dm,0,sizeof(*dm));dm->version=QRX_AURA_MODEL_DIST_VERSION;textcpy(dm->model_id,sizeof(dm->model_id),s->model_id);textcpy(dm->model_version,sizeof(dm->model_version),out->upstream.resolved_revision);textcpy(dm->family,sizeof(dm->family),s->family);textcpy(dm->architecture,sizeof(dm->architecture),arch);int has_gguf=0;for(uint32_t gi=0;gi<map->file_count;gi++){size_t gn=strlen(map->files[gi].path);if(gn>=5&&!strcmp(map->files[gi].path+gn-5,".gguf")){has_gguf=1;break;}}textcpy(dm->format,sizeof(dm->format),has_gguf?"gguf":"safetensors");textcpy(dm->quantization,sizeof(dm->quantization),s->quantization[0]?s->quantization:"upstream");textcpy(dm->license_id,sizeof(dm->license_id),out->upstream.license_id[0]?out->upstream.license_id:s->expected_license);if(s->file_filter[0]&&strcmp(s->file_filter,"*"))snprintf(dm->origin_uri,sizeof(dm->origin_uri),"hf://%s@%s#%s",out->upstream.repo_id,out->upstream.resolved_revision,s->file_filter);else snprintf(dm->origin_uri,sizeof(dm->origin_uri),"hf://%s@%s",out->upstream.repo_id,out->upstream.resolved_revision);dm->max_context_tokens=context;
    for(uint32_t i=0;i<map->file_count;i++){if(dm->asset_count>=QRX_AURA_MODEL_MANIFEST_MAX_ASSETS)return-10;QrxAuraModelAsset*a=&dm->assets[dm->asset_count];a->index=dm->asset_count++;a->kind=map->files[i].kind;textcpy(a->content_root,sizeof(a->content_root),map->files[i].content_root);a->bytes=map->files[i].bytes;a->layer_first=map->files[i].layer_first;a->layer_count=map->files[i].layer_count;a->expert_first=map->files[i].expert_first;a->expert_count=map->files[i].expert_count;a->required_for_boot=(a->kind==QRX_AURA_ASSET_CONFIG||a->kind==QRX_AURA_ASSET_TOKENIZER);dm->total_bytes+=a->bytes;}
    if(qrx_aura_model_manifest_validate(dm)||qrx_aura_model_manifest_commitment(dm,out->distribution_manifest_root))return-11;
    QrxAiModelRecord*r=&out->registry_record;memset(r,0,sizeof(*r));r->registry_version=QRX_MODEL_REGISTRY_VERSION;textcpy(r->model_id,sizeof(r->model_id),s->model_id);textcpy(r->model_version,sizeof(r->model_version),out->upstream.resolved_revision);textcpy(r->architecture,sizeof(r->architecture),arch);textcpy(r->runtime_id,sizeof(r->runtime_id),s->runtime_id);textcpy(r->manifest_root,sizeof(r->manifest_root),out->drive_bundle_root);if(choose_tokenizer(map,r->tokenizer_root))return-12;if(out->has_expert_manifest){uint8_t*eb=NULL;size_t en=0;if(qrx_aura_expert_manifest_encode(&out->expert_manifest,&eb,&en))return-12;char er[65];if(seed_bytes(fs,eb,en,er)){free(eb);return-12;}free(eb);textcpy(r->expert_manifest_root,sizeof(r->expert_manifest_root),er);r->is_moe=1;}else zero_root(r->expert_manifest_root);r->min_memory_bytes=memory_floor(s,dm->total_bytes);r->min_storage_bytes=dm->total_bytes;r->verification_profile=QRX_MODEL_VERIFY_HIGH;textcpy(r->license_id,sizeof(r->license_id),dm->license_id);if(qrx_ai_model_validate(r))return-13;if(cb)cb(ctx,"ready",s->model_id,dm->total_bytes,dm->total_bytes);return 0;}

static int mkdirs_for_file(const char*base,const char*rel,char out[1400]){if(snprintf(out,1400,"%s/%s",base,rel)>=1400)return-1;char tmp[1400];snprintf(tmp,sizeof(tmp),"%s",out);for(char*p=tmp+strlen(base)+1;*p;p++)if(*p=='/'){*p=0;MKDIR(tmp);*p='/';}return 0;}
int qrx_aura_origin_materialize(const QrxAuraOriginSourceMap*m,QrxStorageFs*fs,const char*dir){if(!m||!fs||!dir||!dir[0])return-1;MKDIR(dir);for(uint32_t i=0;i<m->file_count;i++){uint8_t*b=NULL;size_t n=0;if(qrx_storage_fs_read(fs,m->files[i].content_root,&b,&n)||n!=m->files[i].bytes){free(b);return-2;}char p[1400];if(mkdirs_for_file(dir,m->files[i].path,p)){free(b);return-3;}FILE*f=fopen(p,"wb");if(!f){free(b);return-4;}size_t wrote=fwrite(b,1,n,f);int close_rc=fclose(f);if(wrote!=n||close_rc){free(b);return-4;}free(b);}return 0;}

int qrx_aura_origin_catalog_announcement(const QrxAuraOriginSeedResult*seed,const QrxAuraOriginModelSpec*spec,const char*publisher,uint64_t seq,uint64_t from,uint64_t until,QrxAuraModelCatalogAnnouncement*out){
    if(!seed||!spec||!publisher||!publisher[0]||!seq||until<from||!out)return-1;memset(out,0,sizeof(*out));out->version=1;if(textcpy(out->publisher_id,sizeof(out->publisher_id),publisher))return-1;out->sequence=seq;out->valid_from_height=from;out->valid_until_height=until;out->manifest=seed->distribution_manifest;if(textcpy(out->manifest_root,sizeof(out->manifest_root),seed->distribution_manifest_root))return-1;QrxAuraModelCapabilityProfile*p=&out->capability;memset(p,0,sizeof(*p));p->version=1;textcpy(p->model_id,sizeof(p->model_id),seed->registry_record.model_id);textcpy(p->model_version,sizeof(p->model_version),seed->registry_record.model_version);textcpy(p->family,sizeof(p->family),spec->family);textcpy(p->runtime_id,sizeof(p->runtime_id),spec->runtime_id);textcpy(p->quantization,sizeof(p->quantization),spec->quantization);p->tier=spec->tier;p->min_memory_bytes=seed->registry_record.min_memory_bytes;p->recommended_memory_bytes=spec->recommended_memory_bytes?spec->recommended_memory_bytes:(p->min_memory_bytes>UINT64_MAX/2?p->min_memory_bytes:p->min_memory_bytes*2);p->min_storage_bytes=seed->distribution_manifest.total_bytes;p->min_aggregate_milli_tokens_per_second=spec->min_milli_tokens_per_second?spec->min_milli_tokens_per_second:1;p->min_pods=spec->tier>=QRX_AURA_TIER_K2_CLASS?2:1;p->min_network_mbps=spec->tier>=QRX_AURA_TIER_K2_CLASS?100:20;p->max_latency_ms=1000;p->min_reliability_bps=7000;p->max_context_tokens=seed->distribution_manifest.max_context_tokens;p->quality_bps=spec->quality_bps?spec->quality_bps:9000;p->coding_bps=spec->coding_bps?spec->coding_bps:p->quality_bps;p->reasoning_bps=spec->reasoning_bps?spec->reasoning_bps:p->quality_bps;p->rag_bps=spec->rag_bps?spec->rag_bps:p->quality_bps;p->tool_use_bps=spec->tool_use_bps?spec->tool_use_bps:p->quality_bps;p->is_moe=seed->registry_record.is_moe;p->supports_single_device=spec->tier<QRX_AURA_TIER_K2_CLASS?1:0;out->popularity_bps=spec->recommended?8000:5000;out->priority_bps=spec->recommended?8500:5000;out->recommended=spec->recommended;return qrx_aura_model_manifest_validate(&out->manifest)||qrx_aura_model_profile_validate(p)?-2:0;
}
int qrx_aura_origin_availability_announcement(const QrxAuraOriginSeedResult*seed,const char*provider,const char*pod,const char*region,const char*endpoint,uint64_t seq,uint64_t from,uint64_t until,uint32_t bandwidth,uint32_t latency,uint32_t reliability,QrxAuraModelAvailabilityAnnouncement*out){
    if(!seed||!provider||!pod||!region||!endpoint||!seq||until<from||!out)return-1;memset(out,0,sizeof(*out));out->version=1;textcpy(out->provider_id,sizeof(out->provider_id),provider);textcpy(out->pod_id,sizeof(out->pod_id),pod);textcpy(out->region,sizeof(out->region),region);textcpy(out->endpoint,sizeof(out->endpoint),endpoint);textcpy(out->model_id,sizeof(out->model_id),seed->distribution_manifest.model_id);textcpy(out->model_version,sizeof(out->model_version),seed->distribution_manifest.model_version);textcpy(out->manifest_root,sizeof(out->manifest_root),seed->distribution_manifest_root);out->sequence=seq;out->valid_from_height=from;out->valid_until_height=until;out->bandwidth_mbps=bandwidth;out->latency_ms=latency;out->reliability_bps=reliability>10000?10000:reliability;out->full_model=1;return qrx_aura_model_availability_validate(out,from);
}

static int parse_hf_origin(const char*u,char repo[QRX_AURA_ORIGIN_REPO_MAX],char rev[QRX_AURA_ORIGIN_REV_MAX],char filter[QRX_AURA_ORIGIN_FILTER_MAX]){if(!u||strncmp(u,"hf://",5))return-1;const char*p=u+5,*at=strrchr(p,'@');if(!at||at==p||!at[1])return-1;size_t rn=(size_t)(at-p);if(rn>=QRX_AURA_ORIGIN_REPO_MAX)return-1;memcpy(repo,p,rn);repo[rn]=0;const char*hash=strchr(at+1,'#');size_t vn=hash?(size_t)(hash-(at+1)):strlen(at+1);if(!vn||vn>=QRX_AURA_ORIGIN_REV_MAX)return-1;memcpy(rev,at+1,vn);rev[vn]=0;if(filter){filter[0]=0;if(hash&&hash[1]){if(strlen(hash+1)>=QRX_AURA_ORIGIN_FILTER_MAX)return-1;strcpy(filter,hash+1);}else strcpy(filter,"*");}return 0;}
static int asset_fetch_known(const QrxAuraOriginConfig*c,const char*repo,const char*rev,const char*path,uint64_t declared,QrxStorageFs*fs,const char*expect){if(qrx_storage_fs_has(fs,expect)==1)return 0;char u[2048];if(make_url(u,sizeof(u),c->hf_base_url,repo,rev,path))return-1;if(declared<=64u*1024u*1024u){Mem b={0};if(http_mem(c,u,(size_t)declared+1,&b)||b.n!=declared)return-2;char got[65];int rc=seed_bytes(fs,b.p,b.n,got);free(b.p);return rc||strcmp(got,expect)?-3:0;}ensure_dir(c->work_dir);char h[65],tmp[1400],got[65];sha3_text(u,h);snprintf(tmp,sizeof(tmp),"%s/%s.part",c->work_dir,h);if(http_file_resume(c,u,tmp,declared,NULL,NULL))return-4;if(qrx_storage_fs_put_file(fs,tmp,got)){return-5;}remove(tmp);return strcmp(got,expect)?-6:0;}
static int rebuild_origin_map(const QrxAuraOriginConfig*c,const QrxAuraModelManifest*m,QrxAuraOriginSourceMap*map,Mem*cfgmem){char repo[QRX_AURA_ORIGIN_REPO_MAX],rev[QRX_AURA_ORIGIN_REV_MAX],filter[QRX_AURA_ORIGIN_FILTER_MAX];if(parse_hf_origin(m->origin_uri,repo,rev,filter))return-1;QrxAuraOriginModelSpec s={0};s.version=2;textcpy(s.model_id,sizeof(s.model_id),m->model_id);textcpy(s.family,sizeof(s.family),m->family);textcpy(s.repo_id,sizeof(s.repo_id),repo);textcpy(s.revision,sizeof(s.revision),rev);textcpy(s.expected_license,sizeof(s.expected_license),m->license_id);textcpy(s.file_filter,sizeof(s.file_filter),filter);QrxAuraOriginRepoMetadata md;if(qrx_aura_hf_repo_resolve(c,&s,&md)||strcmp(md.resolved_revision,rev)||md.file_count!=m->asset_count)return-2;char paths[QRX_AURA_ORIGIN_MAX_FILES][QRX_AURA_ORIGIN_PATH_MAX];for(uint32_t i=0;i<md.file_count;i++)textcpy(paths[i],sizeof(paths[i]),md.files[i].path);for(uint32_t i=0;i<md.file_count;i++)for(uint32_t j=i+1;j<md.file_count;j++)if(strcmp(paths[i],paths[j])>0){char t[QRX_AURA_ORIGIN_PATH_MAX];memcpy(t,paths[i],sizeof(t));memcpy(paths[i],paths[j],sizeof(t));memcpy(paths[j],t,sizeof(t));}memset(map,0,sizeof(*map));map->version=1;textcpy(map->repo_id,sizeof(map->repo_id),repo);textcpy(map->revision,sizeof(map->revision),rev);map->file_count=md.file_count;for(uint32_t i=0;i<md.file_count;i++){QrxAuraOriginSeededFile*f=&map->files[i];textcpy(f->path,sizeof(f->path),paths[i]);textcpy(f->content_root,sizeof(f->content_root),m->assets[i].content_root);f->bytes=m->assets[i].bytes;f->kind=m->assets[i].kind;f->layer_first=m->assets[i].layer_first;f->layer_count=m->assets[i].layer_count;f->expert_first=m->assets[i].expert_first;f->expert_count=m->assets[i].expert_count;}if(cfgmem){memset(cfgmem,0,sizeof(*cfgmem));get_small(c,&md,"config.json",cfgmem);}return 0;}
static int origin_fetch_selected(QrxAuraOriginFallbackFetchContext*c,const QrxAiModelRecord*model,const QrxAuraModelCachePlacement*p,const QrxAuraModelCatalogAnnouncement*a,char out[65]){QrxAuraOriginSourceMap map;Mem cfg={0};if(rebuild_origin_map(&c->origin,&a->manifest,&map,&cfg))return-1;char mc[65];if(qrx_ai_model_commitment(model,mc)){free(cfg.p);return-1;}uint64_t fetched=0;
    for(uint32_t i=0;i<a->manifest.asset_count;i++){const QrxAuraModelAsset*x=&a->manifest.assets[i];if(!x->required_for_boot)continue;if(asset_fetch_known(&c->origin,map.repo_id,map.revision,map.files[i].path,x->bytes,c->local_cache,x->content_root)){free(cfg.p);return-2;}fetched+=x->bytes;}
    uint32_t cand[QRX_AURA_MODEL_MANIFEST_MAX_ASSETS],cn=0;for(uint32_t i=0;i<a->manifest.asset_count;i++)if(a->manifest.assets[i].kind==QRX_AURA_ASSET_WEIGHT_CHUNK||a->manifest.assets[i].kind==QRX_AURA_ASSET_SHARED_WEIGHTS||a->manifest.assets[i].kind==QRX_AURA_ASSET_EXPERT_PACK)cand[cn++]=i;if(!cn){free(cfg.p);return-3;}EVP_MD_CTX*h=EVP_MD_CTX_new();unsigned char d[32];unsigned dn=0;if(!h||EVP_DigestInit_ex(h,EVP_sha3_256(),NULL)!=1||EVP_DigestUpdate(h,p->pod_id,strlen(p->pod_id))!=1||EVP_DigestUpdate(h,mc,64)!=1||EVP_DigestFinal_ex(h,d,&dn)!=1||dn!=32){if(h)EVP_MD_CTX_free(h);free(cfg.p);return-3;}EVP_MD_CTX_free(h);uint32_t start=((uint32_t)d[0]<<24|((uint32_t)d[1]<<16)|((uint32_t)d[2]<<8)|d[3])%cn;uint32_t compute=0;for(uint32_t k=0;k<cn&&(fetched<p->bytes_to_place||!compute);k++){uint32_t i=cand[(start+k)%cn];const QrxAuraModelAsset*x=&a->manifest.assets[i];if(asset_fetch_known(&c->origin,map.repo_id,map.revision,map.files[i].path,x->bytes,c->local_cache,x->content_root)){free(cfg.p);return-4;}fetched+=x->bytes;compute++;}
    uint8_t*smb=NULL;size_t smn=0;char smroot[65];if(qrx_aura_origin_source_map_encode(&map,&smb,&smn)||qrx_storage_fs_put(c->local_cache,smb,smn,smroot)){free(smb);free(cfg.p);return-5;}free(smb);QrxAuraModelBundleManifest b={0};b.version=QRX_AURA_MODEL_BUNDLE_VERSION;textcpy(b.model_id,sizeof(b.model_id),model->model_id);textcpy(b.model_version,sizeof(b.model_version),model->model_version);for(uint32_t i=0;i<map.file_count;i++)if(add_bundle(&b,bundle_kind(map.files[i].kind),map.files[i].bytes,map.files[i].content_root)){free(cfg.p);return-5;}if(add_bundle(&b,QRX_AURA_MODEL_OBJECT_SOURCE_MAP,smn,smroot)){free(cfg.p);return-5;}
    if(model->is_moe){if(!cfg.p){free(cfg.p);return-6;}const char*lk[]={"num_hidden_layers","num_layers","n_layer"};const char*ek[]={"n_routed_experts","num_local_experts","num_experts","moe_num_experts"};const char*tk[]={"num_experts_per_tok","num_experts_per_token","num_selected_experts","moe_top_k"};QrxAuraExpertManifest em={0};em.version=1;textcpy(em.model_id,sizeof(em.model_id),model->model_id);textcpy(em.model_version,sizeof(em.model_version),model->model_version);textcpy(em.architecture,sizeof(em.architecture),model->architecture);em.layer_count=first_u32((char*)cfg.p,lk,3,1);em.expert_count=first_u32((char*)cfg.p,ek,4,0);em.experts_per_token=first_u32((char*)cfg.p,tk,4,0);if(!em.expert_count||!em.experts_per_token){free(cfg.p);return-6;}uint8_t*eb=NULL;size_t en=0;char er[65];if(qrx_aura_expert_manifest_encode(&em,&eb,&en)||qrx_storage_fs_put(c->local_cache,eb,en,er)){free(eb);free(cfg.p);return-6;}free(eb);if(strcmp(er,model->expert_manifest_root)||add_bundle(&b,QRX_AURA_MODEL_OBJECT_EXPERT_MANIFEST,en,er)){free(cfg.p);return-6;}}
    free(cfg.p);uint8_t*bb=NULL;size_t bn=0;char br[65];if(qrx_aura_model_bundle_encode(&b,&bb,&bn)||qrx_storage_fs_put(c->local_cache,bb,bn,br)){free(bb);return-7;}free(bb);if(strcmp(br,model->manifest_root))return-8;if(fetched<p->bytes_to_place)return-9;textcpy(out,65,mc);return 0;}
int qrx_aura_model_fetch_drive_then_origin(void*v,const QrxAiModelRecord*m,const QrxAuraModelCachePlacement*p,char out[65]){QrxAuraOriginFallbackFetchContext*c=v;if(!c||!m||!p||!out||!c->local_cache||!c->catalog)return-1;if(c->drive){int rc=qrx_aura_drive_model_fetch(c->drive,m,p,out);if(!rc)return 0;}if(!c->allow_origin_fallback)return-2;const QrxAuraModelCatalogAnnouncement*a=qrx_aura_model_catalog_find(c->catalog,m->model_id,m->model_version);if(!a||!a->manifest.origin_uri[0])return-3;return origin_fetch_selected(c,m,p,a,out);}
