#include "compute/qrx_aura_moe_aggregate.h"
#include <openssl/evp.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static uint32_t be32(const uint8_t*p){return ((uint32_t)p[0]<<24)|((uint32_t)p[1]<<16)|((uint32_t)p[2]<<8)|p[3];}
static uint64_t be64(const uint8_t*p){uint64_t v=0;for(int i=0;i<8;i++)v=(v<<8)|p[i];return v;}
static void put32(uint8_t*p,uint32_t v){p[0]=(uint8_t)(v>>24);p[1]=(uint8_t)(v>>16);p[2]=(uint8_t)(v>>8);p[3]=(uint8_t)v;}
static void put64(uint8_t*p,uint64_t v){for(int i=7;i>=0;i--){p[i]=(uint8_t)v;v>>=8;}}
static int hex64(const char*s){if(!s||strlen(s)!=64)return 0;for(int i=0;i<64;i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return 0;}return 1;}
static void hex32(const uint8_t h[32],char out[65]){static const char*x="0123456789abcdef";for(int i=0;i<32;i++){out[i*2]=x[h[i]>>4];out[i*2+1]=x[h[i]&15];}out[64]=0;}
static int sha3(const char*domain,const void*p,size_t n,char out[65]){EVP_MD_CTX*c=EVP_MD_CTX_new();uint8_t h[32];unsigned hn=0;int ok=c&&EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(c,domain,strlen(domain))==1&&(!n||EVP_DigestUpdate(c,p,n)==1)&&EVP_DigestFinal_ex(c,h,&hn)==1&&hn==32;if(c)EVP_MD_CTX_free(c);if(!ok)return-1;hex32(h,out);return 0;}
static int contrib_valid(const QrxAuraMoeContribution*c){return c&&c->version==QRX_AURA_MOE_AGG_VERSION&&hex64(c->plan_commitment)&&c->fragment_count&&c->fragment_index<c->fragment_count&&c->vector_length&&c->vector_length<=QRX_AURA_MOE_MAX_VECTOR_ELEMENTS&&c->q_fraction_bits<=30&&c->values;}
static int result_valid(const QrxAuraMoeAggregateResult*r){return r&&r->version==QRX_AURA_MOE_AGG_VERSION&&hex64(r->plan_commitment)&&r->fragment_count&&r->vector_length&&r->vector_length<=QRX_AURA_MOE_MAX_VECTOR_ELEMENTS&&r->q_fraction_bits<=30&&r->values;}
int qrx_aura_moe_contribution_encode(const QrxAuraMoeContribution*c,uint8_t**out,size_t*outn){if(!contrib_valid(c)||!out||!outn)return-1;size_t n=8+4+64+5*4+(size_t)c->vector_length*4;if(n>QRX_AURA_REMOTE_MAX_PAYLOAD)return-2;uint8_t*b=malloc(n);if(!b)return-2;size_t o=0;memcpy(b+o,QRX_AURA_MOE_CONTRIB_MAGIC,8);o+=8;put32(b+o,c->version);o+=4;memcpy(b+o,c->plan_commitment,64);o+=64;put32(b+o,c->fragment_index);o+=4;put32(b+o,c->fragment_count);o+=4;put32(b+o,c->token_index);o+=4;put32(b+o,c->vector_length);o+=4;put32(b+o,c->q_fraction_bits);o+=4;for(uint32_t i=0;i<c->vector_length;i++){put32(b+o,(uint32_t)c->values[i]);o+=4;}*out=b;*outn=o;return 0;}
int qrx_aura_moe_contribution_decode(const uint8_t*in,size_t n,QrxAuraMoeContribution*out){if(!in||!out||n<8+4+64+20||memcmp(in,QRX_AURA_MOE_CONTRIB_MAGIC,8))return-1;memset(out,0,sizeof(*out));size_t o=8;out->version=be32(in+o);o+=4;memcpy(out->plan_commitment,in+o,64);out->plan_commitment[64]=0;o+=64;out->fragment_index=be32(in+o);o+=4;out->fragment_count=be32(in+o);o+=4;out->token_index=be32(in+o);o+=4;out->vector_length=be32(in+o);o+=4;out->q_fraction_bits=be32(in+o);o+=4;if(!out->vector_length||out->vector_length>QRX_AURA_MOE_MAX_VECTOR_ELEMENTS||n-o!=(size_t)out->vector_length*4){memset(out,0,sizeof(*out));return-1;}out->values=malloc((size_t)out->vector_length*sizeof(*out->values));if(!out->values){memset(out,0,sizeof(*out));return-2;}for(uint32_t i=0;i<out->vector_length;i++){out->values[i]=(int32_t)be32(in+o);o+=4;}if(!contrib_valid(out)){qrx_aura_moe_contribution_free(out);return-1;}return 0;}
void qrx_aura_moe_contribution_free(QrxAuraMoeContribution*c){if(!c)return;free(c->values);memset(c,0,sizeof(*c));}
int qrx_aura_moe_contribution_commitment(const QrxAuraMoeContribution*c,char out[65]){uint8_t*b=NULL;size_t n=0;if(qrx_aura_moe_contribution_encode(c,&b,&n))return-1;int rc=sha3("QRX/AURA/MOE-CONTRIBUTION/V1",b,n,out);free(b);return rc;}
int qrx_aura_moe_aggregate_result_encode(const QrxAuraMoeAggregateResult*r,uint8_t**out,size_t*outn){if(!result_valid(r)||!out||!outn)return-1;size_t n=8+4+64+4*4+(size_t)r->vector_length*8;if(n>QRX_AURA_REMOTE_MAX_PAYLOAD)return-2;uint8_t*b=malloc(n);if(!b)return-2;size_t o=0;memcpy(b+o,QRX_AURA_MOE_RESULT_MAGIC,8);o+=8;put32(b+o,r->version);o+=4;memcpy(b+o,r->plan_commitment,64);o+=64;put32(b+o,r->fragment_count);o+=4;put32(b+o,r->token_index);o+=4;put32(b+o,r->vector_length);o+=4;put32(b+o,r->q_fraction_bits);o+=4;for(uint32_t i=0;i<r->vector_length;i++){put64(b+o,(uint64_t)r->values[i]);o+=8;}*out=b;*outn=o;return 0;}
int qrx_aura_moe_aggregate_result_decode(const uint8_t*in,size_t n,QrxAuraMoeAggregateResult*out){if(!in||!out||n<8+4+64+16||memcmp(in,QRX_AURA_MOE_RESULT_MAGIC,8))return-1;memset(out,0,sizeof(*out));size_t o=8;out->version=be32(in+o);o+=4;memcpy(out->plan_commitment,in+o,64);out->plan_commitment[64]=0;o+=64;out->fragment_count=be32(in+o);o+=4;out->token_index=be32(in+o);o+=4;out->vector_length=be32(in+o);o+=4;out->q_fraction_bits=be32(in+o);o+=4;if(!out->vector_length||out->vector_length>QRX_AURA_MOE_MAX_VECTOR_ELEMENTS||n-o!=(size_t)out->vector_length*8)return-1;out->values=malloc((size_t)out->vector_length*sizeof(*out->values));if(!out->values){memset(out,0,sizeof(*out));return-2;}for(uint32_t i=0;i<out->vector_length;i++){out->values[i]=(int64_t)be64(in+o);o+=8;}if(!result_valid(out)){qrx_aura_moe_aggregate_result_free(out);return-1;}if(qrx_aura_moe_aggregate_result_commitment(out,out->result_commitment)){qrx_aura_moe_aggregate_result_free(out);return-1;}return 0;}
void qrx_aura_moe_aggregate_result_free(QrxAuraMoeAggregateResult*r){if(!r)return;free(r->values);memset(r,0,sizeof(*r));}
int qrx_aura_moe_aggregate_result_commitment(const QrxAuraMoeAggregateResult*r,char out[65]){uint8_t*b=NULL;size_t n=0;if(qrx_aura_moe_aggregate_result_encode(r,&b,&n))return-1;int rc=sha3("QRX/AURA/MOE-AGGREGATE/V1",b,n,out);free(b);return rc;}
int qrx_aura_moe_fixedpoint_aggregate(const uint8_t*const*parts,const size_t*sizes,uint32_t count,QrxAuraMoeAggregateResult*out){if(!parts||!sizes||!count||count>QRX_AURA_ADMISSION_MAX_PODS||!out)return-1;QrxAuraMoeContribution c[QRX_AURA_ADMISSION_MAX_PODS];memset(c,0,sizeof(c));uint8_t seen[QRX_AURA_ADMISSION_MAX_PODS]={0};int rc=-2;for(uint32_t i=0;i<count;i++){if(qrx_aura_moe_contribution_decode(parts[i],sizes[i],&c[i]))goto done;if(c[i].fragment_count!=count||c[i].fragment_index>=count||seen[c[i].fragment_index])goto done;seen[c[i].fragment_index]=1;if(i&& (strcmp(c[i].plan_commitment,c[0].plan_commitment)||c[i].token_index!=c[0].token_index||c[i].vector_length!=c[0].vector_length||c[i].q_fraction_bits!=c[0].q_fraction_bits))goto done;}
    memset(out,0,sizeof(*out));out->version=QRX_AURA_MOE_AGG_VERSION;snprintf(out->plan_commitment,sizeof(out->plan_commitment),"%s",c[0].plan_commitment);out->fragment_count=count;out->token_index=c[0].token_index;out->vector_length=c[0].vector_length;out->q_fraction_bits=c[0].q_fraction_bits;out->values=calloc(out->vector_length,sizeof(*out->values));if(!out->values){rc=-3;goto done;}for(uint32_t i=0;i<count;i++)for(uint32_t j=0;j<out->vector_length;j++){int64_t v=(int64_t)c[i].values[j];if((v>0&&out->values[j]>INT64_MAX-v)||(v<0&&out->values[j]<INT64_MIN-v)){qrx_aura_moe_aggregate_result_free(out);rc=-4;goto done;}out->values[j]+=v;}if(qrx_aura_moe_aggregate_result_commitment(out,out->result_commitment)){qrx_aura_moe_aggregate_result_free(out);rc=-4;goto done;}rc=0;
done:for(uint32_t i=0;i<count;i++)qrx_aura_moe_contribution_free(&c[i]);return rc;}
int qrx_aura_moe_fixedpoint_aggregate_adapter(void*ctx,const uint8_t*const*parts,const size_t*sizes,uint32_t count,void*output,size_t cap,size_t*out_n){(void)ctx;if(!output||!out_n)return-1;QrxAuraMoeAggregateResult r;if(qrx_aura_moe_fixedpoint_aggregate(parts,sizes,count,&r))return-2;uint8_t*b=NULL;size_t n=0;int rc=qrx_aura_moe_aggregate_result_encode(&r,&b,&n);if(!rc){if(n>cap)rc=-3;else{memcpy(output,b,n);*out_n=n;}}free(b);qrx_aura_moe_aggregate_result_free(&r);return rc;}
