#include "compute/qrx_pouc_verifier.h"
#include <openssl/evp.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <limits.h>

typedef struct {
    char address[QRX_POUC_VERIFIER_ADDRESS_MAX];
    uint64_t power;
    uint8_t selected;
} Candidate;
typedef struct { Candidate v[QRX_POUC_VERIFIER_MAX_CANDIDATES]; uint32_t n; int error; } CandidateSet;

static int safe(const char*s){return s&&s[0]&&!strchr(s,'|')&&!strchr(s,';')&&!strchr(s,'\n')&&!strchr(s,'\r');}
static int hexn(const char*s,size_t n){if(!s||strlen(s)!=n)return 0;for(size_t i=0;i<n;i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return 0;}return 1;}
static int hashhex(const char*s){return hexn(s,64)||hexn(s,128);}
static int u64parse(const char*s,uint64_t*out){if(!s||!*s||!out||*s=='-')return -1;errno=0;char*e=NULL;unsigned long long v=strtoull(s,&e,10);if(errno||!e||*e)return -1;*out=(uint64_t)v;return 0;}
static int dbu64(QrxDB*d,const char*k,uint64_t*out){char b[128];if(qrxdb_get(d,k,b,sizeof(b)))return -1;return u64parse(b,out);}
static int batchu64(QrxDBBatch*b,const char*k,uint64_t v){char x[64];snprintf(x,sizeof(x),"%llu",(unsigned long long)v);return qrxdb_batch_put(b,k,x);}
static int field(EVP_MD_CTX*c,const void*p,size_t n){unsigned char z[8];uint64_t v=(uint64_t)n;for(int i=0;i<8;i++)z[i]=(unsigned char)(v>>(56-8*i));if(EVP_DigestUpdate(c,z,sizeof(z))!=1)return -1;return n&&EVP_DigestUpdate(c,p,n)!=1?-1:0;}
static int field_u32(EVP_MD_CTX*c,uint32_t v){unsigned char b[4]={(unsigned char)(v>>24),(unsigned char)(v>>16),(unsigned char)(v>>8),(unsigned char)v};return field(c,b,sizeof(b));}
static int field_u64(EVP_MD_CTX*c,uint64_t v){unsigned char b[8];for(int i=0;i<8;i++)b[i]=(unsigned char)(v>>(56-8*i));return field(c,b,sizeof(b));}
static uint64_t mul_bps(uint64_t v,uint64_t bps){if(bps>10000u)return UINT64_MAX;return (v/10000u)*bps+((v%10000u)*bps)/10000u;}
static int digest_hex(EVP_MD_CTX*c,char out[65]){unsigned char h[32];unsigned int n=0;if(EVP_DigestFinal_ex(c,h,&n)!=1||n!=32)return -1;static const char hx[]="0123456789abcdef";for(int i=0;i<32;i++){out[i*2]=hx[h[i]>>4];out[i*2+1]=hx[h[i]&15];}out[64]=0;return 0;}
static int add_candidate(CandidateSet*s,const char*a,uint64_t p){if(!s||!safe(a)||!p)return 0;for(uint32_t i=0;i<s->n;i++)if(!strcmp(s->v[i].address,a)){if(UINT64_MAX-s->v[i].power<p){s->error=1;return -1;}s->v[i].power+=p;return 0;}if(s->n>=QRX_POUC_VERIFIER_MAX_CANDIDATES){s->error=1;return -1;}snprintf(s->v[s->n].address,sizeof(s->v[s->n].address),"%s",a);s->v[s->n].power=p;s->n++;return 0;}
static int scan_stake(const char*k,const char*v,uint32_t vl,void*ctx){(void)vl;CandidateSet*s=(CandidateSet*)ctx;uint64_t p=0;if(u64parse(v,&p)||!p)return 0;const char*a=NULL;char tmp[QRX_POUC_VERIFIER_ADDRESS_MAX]={0};if(!strncmp(k,"staking:self:",13))a=k+13;else if(!strncmp(k,"staking:delegated_total:",24))a=k+24;else return 0;if(!safe(a))return -1;snprintf(tmp,sizeof(tmp),"%s",a);return add_candidate(s,tmp,p);}
static int scan_genesis(const char*k,const char*v,uint32_t vl,void*ctx){(void)vl;CandidateSet*s=(CandidateSet*)ctx;const char*pfx="genesis:validator:",*suf=":amount_atoms";size_t pl=strlen(pfx),sl=strlen(suf),kl=strlen(k);if(kl<=pl+sl||strncmp(k,pfx,pl)||strcmp(k+kl-sl,suf))return 0;uint64_t p=0;if(u64parse(v,&p)||!p)return 0;size_t al=kl-pl-sl;if(al>=QRX_POUC_VERIFIER_ADDRESS_MAX)return -1;char a[QRX_POUC_VERIFIER_ADDRESS_MAX];memcpy(a,k+pl,al);a[al]=0;return add_candidate(s,a,p);}
static int cmpcand(const void*a,const void*b){return strcmp(((const Candidate*)a)->address,((const Candidate*)b)->address);}
int qrx_pouc_verifier_is_compute_jailed(QrxDB*d,const char*v,uint64_t h){if(!d||!safe(v))return 1;char k[512];uint64_t until=0;snprintf(k,sizeof(k),"%s%s",QRX_POUC_COMPUTE_JAIL_PREFIX,v);if(!dbu64(d,k,&until)&&until>=h)return 1;snprintf(k,sizeof(k),"staking:validator_paused:%s",v);uint64_t paused=0;if(!dbu64(d,k,&paused)&&paused)return 1;return 0;}
static int collect(QrxDB*d,const char*owner,const char*provider,uint64_t h,CandidateSet*out){memset(out,0,sizeof(*out));if(qrxdb_scan_prefix(d,"staking:self:",scan_stake,out)||qrxdb_scan_prefix(d,"staking:delegated_total:",scan_stake,out)||qrxdb_scan_prefix(d,"genesis:validator:",scan_genesis,out)||out->error)return -1;uint32_t w=0;for(uint32_t i=0;i<out->n;i++){Candidate*c=&out->v[i];if(!strcmp(c->address,owner)||!strcmp(c->address,provider)||qrx_pouc_verifier_is_compute_jailed(d,c->address,h))continue;if(w!=i)out->v[w]=*c;w++;}out->n=w;qsort(out->v,out->n,sizeof(out->v[0]),cmpcand);return 0;}
static int random64(const char*block,const char*receipt,const char*role,uint32_t slot,uint64_t*out){EVP_MD_CTX*c=EVP_MD_CTX_new();if(!c)return -1;const char dom[]="QRX/POUC/VERIFIER-SELECTION/RANDOM/V1";int ok=EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1;unsigned char h[32];unsigned int n=0;if(ok&&field(c,dom,sizeof(dom)-1))ok=0;if(ok&&field(c,block,strlen(block)))ok=0;if(ok&&field(c,receipt,64))ok=0;if(ok&&field(c,role,strlen(role)))ok=0;if(ok&&field_u32(c,slot))ok=0;if(ok&&EVP_DigestFinal_ex(c,h,&n)!=1)ok=0;EVP_MD_CTX_free(c);if(!ok||n!=32)return -1;uint64_t x=0;for(int i=0;i<8;i++)x=(x<<8)|h[i];*out=x;return 0;}
static int pick(CandidateSet*s,const char*block,const char*receipt,const char*role,uint32_t slot,char out[QRX_POUC_VERIFIER_ADDRESS_MAX]){uint64_t total=0;for(uint32_t i=0;i<s->n;i++)if(!s->v[i].selected){if(UINT64_MAX-total<s->v[i].power)return -1;total+=s->v[i].power;}if(!total)return -1;uint64_t r=0;if(random64(block,receipt,role,slot,&r))return -1;uint64_t target=r%total,acc=0;for(uint32_t i=0;i<s->n;i++)if(!s->v[i].selected){if(UINT64_MAX-acc<s->v[i].power)return -1;acc+=s->v[i].power;if(target<acc){s->v[i].selected=1;snprintf(out,QRX_POUC_VERIFIER_ADDRESS_MAX,"%s",s->v[i].address);return 0;}}return -1;}

int qrx_pouc_verifier_selection_commitment(const QrxPoucVerifierSelection*s,char out[65]){if(!s||!out||s->version!=QRX_POUC_VERIFIER_SELECTION_VERSION||!hexn(s->receipt_commitment,64)||!hashhex(s->entropy_block_hash)||!s->entropy_height||!s->target_verifiers||s->primary_count!=s->target_verifiers||s->primary_count>QRX_POUC_VERIFIER_MAX_PRIMARY||s->challenge_count>QRX_POUC_VERIFIER_MAX_CHALLENGE)return -1;EVP_MD_CTX*c=EVP_MD_CTX_new();if(!c)return -1;const char dom[]="QRX/POUC/VERIFIER-SELECTION/V1";int ok=EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1;
#define F(p,n) do{if(ok&&field(c,(p),(n)))ok=0;}while(0)
 F(dom,sizeof(dom)-1);F(s->receipt_commitment,64);if(ok&&field_u64(c,s->entropy_height))ok=0;F(s->entropy_block_hash,strlen(s->entropy_block_hash));if(ok&&field_u32(c,s->verification_mode))ok=0;if(ok&&field_u32(c,s->target_verifiers))ok=0;if(ok&&field_u32(c,s->primary_count))ok=0;if(ok&&field_u32(c,s->challenge_count))ok=0;for(uint32_t i=0;i<s->primary_count;i++)F(s->primary[i],strlen(s->primary[i]));for(uint32_t i=0;i<s->challenge_count;i++)F(s->challenger[i],strlen(s->challenger[i]));if(ok&&field_u64(c,s->primary_reward_atoms))ok=0;if(ok&&field_u64(c,s->challenge_reward_atoms))ok=0;if(ok&&field_u64(c,s->verification_deadline_height))ok=0;if(ok&&field_u64(c,s->challenge_deadline_height))ok=0;
#undef F
 int rc=ok?digest_hex(c,out):-1;EVP_MD_CTX_free(c);return rc;}

int qrx_pouc_verifier_selection_build(QrxDB*d,const char rc[65],const char*owner,const char*provider,uint32_t mode,uint64_t eh,uint64_t rh,uint64_t budget,QrxPoucVerifierSelection*out){if(!d||!hexn(rc,64)||!safe(owner)||!safe(provider)||!out||!eh||!rh||rh<=eh)return -1;uint32_t target=mode==QRX_POUC_VERIFY_SPOT?1:mode==QRX_POUC_VERIFY_RANDOM?2:mode==QRX_POUC_VERIFY_REDUNDANT_2_OF_3?3:0;if(!target)return -2;char block[129];if(qrxdb_chain_get_block_hash_by_height(d,eh,block,sizeof(block))||!hashhex(block))return -3;CandidateSet set;if(collect(d,owner,provider,eh,&set))return -4;uint32_t chall=(mode==QRX_POUC_VERIFY_REDUNDANT_2_OF_3)?0:QRX_POUC_VERIFIER_MAX_CHALLENGE;if(set.n<target+chall)return -5;memset(out,0,sizeof(*out));out->version=QRX_POUC_VERIFIER_SELECTION_VERSION;snprintf(out->receipt_commitment,65,"%s",rc);out->entropy_height=eh;snprintf(out->entropy_block_hash,sizeof(out->entropy_block_hash),"%s",block);out->verification_mode=mode;out->target_verifiers=target;out->primary_count=target;out->challenge_count=chall;for(uint32_t i=0;i<target;i++)if(pick(&set,block,rc,"PRIMARY",i,out->primary[i]))return -6;for(uint32_t i=0;i<chall;i++)if(pick(&set,block,rc,"CHALLENGE",i,out->challenger[i]))return -7;uint64_t weights=(uint64_t)target*QRX_POUC_PRIMARY_REWARD_WEIGHT+(uint64_t)chall*QRX_POUC_CHALLENGE_REWARD_WEIGHT;if(budget&&weights){uint64_t unit=budget/weights;out->primary_reward_atoms=unit*QRX_POUC_PRIMARY_REWARD_WEIGHT;out->challenge_reward_atoms=unit*QRX_POUC_CHALLENGE_REWARD_WEIGHT;}out->verification_deadline_height=rh+QRX_POUC_VERIFY_WINDOW_BLOCKS;out->challenge_deadline_height=out->verification_deadline_height+QRX_POUC_CHALLENGE_WINDOW_BLOCKS;if(qrx_pouc_verifier_selection_commitment(out,out->selection_commitment))return -8;return 0;}

static const char* slot_or_dash(const char*s){return (s&&s[0])?s:"-";}
static void dash_to_empty(char*s){if(s&&!strcmp(s,"-"))s[0]=0;}
static int encode(const QrxPoucVerifierSelection*s,char*out,size_t n){char chk[65];if(qrx_pouc_verifier_selection_commitment(s,chk)||strcmp(chk,s->selection_commitment))return -1;int z=snprintf(out,n,"%u|%s|%llu|%s|%u|%u|%u|%u|%llu|%llu|%llu|%llu|%s|%s|%s|%s|%s|%s|%s",s->version,s->receipt_commitment,(unsigned long long)s->entropy_height,s->entropy_block_hash,s->verification_mode,s->target_verifiers,s->primary_count,s->challenge_count,(unsigned long long)s->primary_reward_atoms,(unsigned long long)s->challenge_reward_atoms,(unsigned long long)s->verification_deadline_height,(unsigned long long)s->challenge_deadline_height,slot_or_dash(s->primary[0]),slot_or_dash(s->primary[1]),slot_or_dash(s->primary[2]),slot_or_dash(s->challenger[0]),slot_or_dash(s->challenger[1]),slot_or_dash(s->challenger[2]),s->selection_commitment);return z>0&&(size_t)z<n?0:-1;}
static int decode(const char*s,QrxPoucVerifierSelection*out){if(!s||!out)return -1;memset(out,0,sizeof(*out));unsigned v=0,mode=0,t=0,pc=0,cc=0;unsigned long long eh=0,pr=0,cr=0,vd=0,cd=0;char rc[65]={0},bh[129]={0},p0[160]={0},p1[160]={0},p2[160]={0},c0[160]={0},c1[160]={0},c2[160]={0},sc[65]={0};if(sscanf(s,"%u|%64[^|]|%llu|%128[^|]|%u|%u|%u|%u|%llu|%llu|%llu|%llu|%159[^|]|%159[^|]|%159[^|]|%159[^|]|%159[^|]|%159[^|]|%64s",&v,rc,&eh,bh,&mode,&t,&pc,&cc,&pr,&cr,&vd,&cd,p0,p1,p2,c0,c1,c2,sc)!=19)return -1;dash_to_empty(p0);dash_to_empty(p1);dash_to_empty(p2);dash_to_empty(c0);dash_to_empty(c1);dash_to_empty(c2);out->version=v;snprintf(out->receipt_commitment,65,"%s",rc);out->entropy_height=eh;snprintf(out->entropy_block_hash,129,"%s",bh);out->verification_mode=mode;out->target_verifiers=t;out->primary_count=pc;out->challenge_count=cc;out->primary_reward_atoms=pr;out->challenge_reward_atoms=cr;out->verification_deadline_height=vd;out->challenge_deadline_height=cd;snprintf(out->primary[0],160,"%s",p0);snprintf(out->primary[1],160,"%s",p1);snprintf(out->primary[2],160,"%s",p2);snprintf(out->challenger[0],160,"%s",c0);snprintf(out->challenger[1],160,"%s",c1);snprintf(out->challenger[2],160,"%s",c2);snprintf(out->selection_commitment,65,"%s",sc);if(pc>QRX_POUC_VERIFIER_MAX_PRIMARY||cc>QRX_POUC_VERIFIER_MAX_CHALLENGE)return -1;for(uint32_t i=0;i<pc;i++)if(!safe(out->primary[i]))return -1;for(uint32_t i=0;i<cc;i++)if(!safe(out->challenger[i]))return -1;char chk[65];return qrx_pouc_verifier_selection_commitment(out,chk)||strcmp(chk,out->selection_commitment)?-1:0;}
int qrx_pouc_verifier_selection_stage(QrxDBBatch*b,const QrxPoucVerifierSelection*s){if(!b||!s)return -1;char k[200],v[2048];if(encode(s,v,sizeof(v)))return -2;snprintf(k,sizeof(k),"%s%s",QRX_POUC_VERIFIER_SELECTION_PREFIX,s->receipt_commitment);return qrxdb_batch_put(b,k,v);}
int qrx_pouc_verifier_selection_get(QrxDB*d,const char rc[65],QrxPoucVerifierSelection*out){if(!d||!hexn(rc,64)||!out)return -1;char k[200],v[2048];snprintf(k,sizeof(k),"%s%s",QRX_POUC_VERIFIER_SELECTION_PREFIX,rc);if(qrxdb_get(d,k,v,sizeof(v)))return -2;return decode(v,out);}
int qrx_pouc_verifier_is_primary(const QrxPoucVerifierSelection*s,const char*v){if(!s||!safe(v))return 0;for(uint32_t i=0;i<s->primary_count;i++)if(!strcmp(s->primary[i],v))return 1;return 0;}
int qrx_pouc_verifier_is_challenger(const QrxPoucVerifierSelection*s,const char*v){if(!s||!safe(v))return 0;for(uint32_t i=0;i<s->challenge_count;i++)if(!strcmp(s->challenger[i],v))return 1;return 0;}

/* --- authoritative stake penalty ------------------------------------------------ */
typedef struct {char key[512];uint64_t value;} Deleg;
typedef struct {const char*validator;Deleg d[4096];uint32_t n;int error;} DelegSet;
static int collect_deleg(const char*k,const char*v,uint32_t vl,void*ctxp){(void)vl;DelegSet*c=(DelegSet*)ctxp;const char*pfx="staking:delegation:";size_t pl=strlen(pfx),kl=strlen(k),vlr=strlen(c->validator);if(kl<=pl+vlr+1||strncmp(k,pfx,pl)||k[kl-vlr-1]!=':'||strcmp(k+kl-vlr,c->validator))return 0;uint64_t x=0;if(u64parse(v,&x)||!x)return 0;if(c->n>=4096){c->error=1;return -1;}snprintf(c->d[c->n].key,sizeof(c->d[c->n].key),"%s",k);c->d[c->n].value=x;c->n++;return 0;}
static int penalty_snapshot_stage(QrxDB*d,QrxDBBatch*b,const char*pid,uint32_t idx,const char*k){char old[1024]={0},sk[256],sv[1600];int ex=qrxdb_get(d,k,old,sizeof(old))==0;snprintf(sk,sizeof(sk),"%s%s:snapshot:%04u",QRX_POUC_PENALTY_JOURNAL_PREFIX,pid,idx);snprintf(sv,sizeof(sv),"%s|%u|%s",k,(unsigned)ex,ex?old:"-");return qrxdb_batch_put(b,sk,sv);}
int qrx_pouc_stage_consensus_penalty_custom(QrxDB*d,QrxDBBatch*b,const char*validator,const char pid[65],const char rc[65],uint64_t h,uint64_t slash_bps,uint64_t jail_blocks,uint64_t*out_slash,uint64_t*out_jail){
 if(out_slash)*out_slash=0;
 if(out_jail)*out_jail=0;
 if(!d||!b||!safe(validator)||!hexn(pid,64)||!hexn(rc,64)||!h||(!slash_bps&&!jail_blocks)||slash_bps>10000)return -1;
 char once[256],buf[1024];snprintf(once,sizeof(once),"consensus:compute:penalty_applied:%s",pid);if(qrxdb_get(d,once,buf,sizeof(buf))==0&&strcmp(buf,"REVERTED"))return -5;
 uint64_t self=0,deleg=0;char ks[512],kd[512],jk[512];snprintf(ks,sizeof(ks),"staking:self:%s",validator);(void)dbu64(d,ks,&self);snprintf(kd,sizeof(kd),"staking:delegated_total:%s",validator);(void)dbu64(d,kd,&deleg);snprintf(jk,sizeof(jk),"%s%s",QRX_POUC_COMPUTE_JAIL_PREFIX,validator);
 uint64_t total=self;if(UINT64_MAX-total<deleg)return -6;total+=deleg;uint64_t slash_amt=0,self_cut=0,deleg_cut=0;DelegSet ds;memset(&ds,0,sizeof(ds));ds.validator=validator;
 if(slash_bps&&total){slash_amt=mul_bps(total,slash_bps);if(slash_amt==UINT64_MAX)return -6;if(!slash_amt)slash_amt=1;if(slash_amt>total)slash_amt=total;self_cut=mul_bps(self,slash_bps);deleg_cut=mul_bps(deleg,slash_bps);if(self_cut>self||deleg_cut>deleg)return -6;uint64_t component=self_cut+deleg_cut;if(component>slash_amt)return -6;uint64_t extra=slash_amt-component;if(extra&&self_cut<self){self_cut++;extra--;}if(extra&&deleg_cut<deleg){deleg_cut++;extra--;}if(extra)return -6;if(deleg_cut&&qrxdb_scan_prefix(d,"staking:delegation:",collect_deleg,&ds))return -8;if(ds.error)return -8;}
 uint32_t snaps=0;if(penalty_snapshot_stage(d,b,pid,snaps++,once)||penalty_snapshot_stage(d,b,pid,snaps++,ks)||penalty_snapshot_stage(d,b,pid,snaps++,kd))return -7;if(slash_bps&&penalty_snapshot_stage(d,b,pid,snaps++,QRX_POUC_COMPUTE_SLASH_POOL_KEY))return -7;if(jail_blocks&&penalty_snapshot_stage(d,b,pid,snaps++,jk))return -7;for(uint32_t i=0;i<ds.n;i++)if(penalty_snapshot_stage(d,b,pid,snaps++,ds.d[i].key))return -7;
 if(slash_amt){if(batchu64(b,ks,self-self_cut))return -7;uint64_t removed=0;if(deleg_cut&&deleg){for(uint32_t i=0;i<ds.n;i++){uint64_t part=mul_bps(ds.d[i].value,slash_bps);if(part>ds.d[i].value)return -9;ds.d[i].value-=part;if(UINT64_MAX-removed<part)return -9;removed+=part;}uint64_t rem=deleg_cut-removed;for(uint32_t i=0;i<ds.n&&rem;i++){uint64_t take=ds.d[i].value<rem?ds.d[i].value:rem;ds.d[i].value-=take;removed+=take;rem-=take;}if(rem)return -9;for(uint32_t i=0;i<ds.n;i++)if(batchu64(b,ds.d[i].key,ds.d[i].value))return -10;}if(batchu64(b,kd,deleg-removed))return -11;uint64_t pool=0;(void)dbu64(d,QRX_POUC_COMPUTE_SLASH_POOL_KEY,&pool);if(UINT64_MAX-pool<slash_amt||batchu64(b,QRX_POUC_COMPUTE_SLASH_POOL_KEY,pool+slash_amt))return -12;}
 uint64_t until=0;if(jail_blocks){if(UINT64_MAX-h<jail_blocks)return -13;until=h+jail_blocks;uint64_t old=0;(void)dbu64(d,jk,&old);if(old>until)until=old;if(batchu64(b,jk,until))return -14;}
 char ev[768],jkey[256],jval[1024];snprintf(ev,sizeof(ev),"height=%llu|validator=%s|receipt=%s|slash_atoms=%llu|slash_bps=%llu|jail_until=%llu",(unsigned long long)h,validator,rc,(unsigned long long)slash_amt,(unsigned long long)slash_bps,(unsigned long long)until);if(qrxdb_batch_put(b,once,ev))return -15;snprintf(jkey,sizeof(jkey),"%s%s",QRX_POUC_PENALTY_JOURNAL_PREFIX,pid);snprintf(jval,sizeof(jval),"APPLIED|%llu|%s|%s|%u|%llu|%llu",(unsigned long long)h,validator,rc,snaps,(unsigned long long)slash_amt,(unsigned long long)until);if(qrxdb_batch_put(b,jkey,jval))return -16;if(out_slash)*out_slash=slash_amt;if(out_jail)*out_jail=until;return 0;
}
int qrx_pouc_stage_consensus_penalty(QrxDB*d,QrxDBBatch*b,const char*validator,const char rc[65],uint64_t h,uint8_t slash,uint8_t jail,uint64_t*out_slash,uint64_t*out_jail){uint64_t sb=0,jb=0;if(slash&&dbu64(d,QRX_POUC_FRAUD_SLASH_BPS_KEY,&sb))return -2;if(jail&&dbu64(d,QRX_POUC_FRAUD_JAIL_BLOCKS_KEY,&jb))return -3;return qrx_pouc_stage_consensus_penalty_custom(d,b,validator,rc,rc,h,slash?sb:0,jail?jb:0,out_slash,out_jail);}
typedef struct{char id[65];uint64_t h;uint32_t snaps;} PenRev;typedef struct{PenRev a[512];uint32_t n;} PenRevSet;
static int collect_pen_journal(const char*k,const char*v,uint32_t vl,void*ctxp){(void)vl;PenRevSet*s=(PenRevSet*)ctxp;const char*p=QRX_POUC_PENALTY_JOURNAL_PREFIX;size_t pl=strlen(p);if(strstr(k,":snapshot:"))return 0;if(strncmp(k,p,pl)||s->n>=512)return 0;char st[16],val[160],rc[65];unsigned long long h=0,sa=0,ju=0;unsigned snaps=0;if(sscanf(v,"%15[^|]|%llu|%159[^|]|%64[^|]|%u|%llu|%llu",st,&h,val,rc,&snaps,&sa,&ju)!=7||strcmp(st,"APPLIED"))return 0;snprintf(s->a[s->n].id,65,"%s",k+pl);s->a[s->n].h=h;s->a[s->n].snaps=snaps;s->n++;return 0;}
static int cmp_rev(const void*a,const void*b){const PenRev*x=a,*y=b;return x->h<y->h?1:x->h>y->h?-1:strcmp(x->id,y->id);}
int qrx_pouc_penalty_journal_revert_above_height(QrxDB*d,uint64_t canon,uint32_t*out){if(!d)return -1;PenRevSet s;memset(&s,0,sizeof(s));if(qrxdb_scan_prefix(d,QRX_POUC_PENALTY_JOURNAL_PREFIX,collect_pen_journal,&s))return -2;qsort(s.a,s.n,sizeof(s.a[0]),cmp_rev);uint32_t pending=0;for(uint32_t i=0;i<s.n;i++)if(s.a[i].h>canon)pending++;if(!pending){if(out)*out=0;return 0;}uint32_t n=0;QrxDBBatch b;if(qrxdb_batch_begin(d,&b))return -3;for(uint32_t i=0;i<s.n;i++){PenRev*r=&s.a[i];if(r->h<=canon)continue;for(uint32_t j=0;j<r->snaps;j++){char sk[256],sv[1600],keyv[1600],old[1600];unsigned ex=0;snprintf(sk,sizeof(sk),"%s%s:snapshot:%04u",QRX_POUC_PENALTY_JOURNAL_PREFIX,r->id,j);if(qrxdb_get(d,sk,sv,sizeof(sv))) {qrxdb_batch_abort(&b);return -4;}char*bar1=strchr(sv,'|');if(!bar1){qrxdb_batch_abort(&b);return -5;}*bar1=0;snprintf(keyv,sizeof(keyv),"%s",sv);char*bar2=strchr(bar1+1,'|');if(!bar2){qrxdb_batch_abort(&b);return -5;}*bar2=0;ex=(unsigned)strtoul(bar1+1,NULL,10);snprintf(old,sizeof(old),"%s",bar2+1);const char*restore=ex?old:(!strncmp(keyv,"consensus:compute:penalty_applied:",34)?"REVERTED":"0");if(qrxdb_batch_put(&b,keyv,restore)){qrxdb_batch_abort(&b);return -6;}}
 char jk[256],jv[256];snprintf(jk,sizeof(jk),"%s%s",QRX_POUC_PENALTY_JOURNAL_PREFIX,r->id);snprintf(jv,sizeof(jv),"REVERTED|%llu",(unsigned long long)r->h);if(qrxdb_batch_put(&b,jk,jv)){qrxdb_batch_abort(&b);return -7;}n++;}if(qrxdb_batch_commit(&b)){qrxdb_batch_abort(&b);return -8;}if(out)*out=n;return 0;}
