#include "compute/qrx_aura_model_governance.h"
#include <openssl/crypto.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define GOV_DOMAIN "QRX/AURA/MODEL-GOVERNANCE/V1"

typedef struct { uint8_t *p; size_t n,cap; } Buf;
static int grow(Buf*b,size_t add){if(!b||SIZE_MAX-b->n<add)return-1;size_t need=b->n+add;if(need<=b->cap)return 0;size_t cap=b->cap?b->cap:512;while(cap<need){if(cap>SIZE_MAX/2)return-1;cap*=2;}uint8_t*p=realloc(b->p,cap);if(!p)return-1;b->p=p;b->cap=cap;return 0;}
static int put(Buf*b,const void*p,size_t n){if(grow(b,n))return-1;if(n)memcpy(b->p+b->n,p,n);b->n+=n;return 0;}
static int u32(Buf*b,uint32_t v){uint8_t x[4]={(uint8_t)(v>>24),(uint8_t)(v>>16),(uint8_t)(v>>8),(uint8_t)v};return put(b,x,4);}
static int u64(Buf*b,uint64_t v){uint8_t x[8];for(int i=7;i>=0;i--){x[i]=(uint8_t)v;v>>=8;}return put(b,x,8);}
static int str(Buf*b,const char*s,size_t cap){if(!s||!memchr(s,0,cap))return-1;size_t n=strlen(s);return n>UINT32_MAX||u32(b,(uint32_t)n)||put(b,s,n)?-1:0;}
static int hex64(const char*s){if(!s||strlen(s)!=64)return 0;for(size_t i=0;i<64;i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return 0;}return 1;}
static int hash_domain(const char*d,const void*p,size_t n,uint8_t out[32]){EVP_MD_CTX*m=EVP_MD_CTX_new();unsigned hn=0;if(!m)return-1;int ok=EVP_DigestInit_ex(m,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(m,d,strlen(d))==1&&(!n||EVP_DigestUpdate(m,p,n)==1)&&EVP_DigestFinal_ex(m,out,&hn)==1&&hn==32;EVP_MD_CTX_free(m);return ok?0:-1;}
static int sign_hash(EVP_PKEY*k,const uint8_t h[32],uint8_t**sig,size_t*sn){if(!k||!sig||!sn)return-1;*sig=NULL;*sn=0;EVP_MD_CTX*m=EVP_MD_CTX_new();size_t n=0;uint8_t*p=NULL;int rc=-1;if(!m||EVP_DigestSignInit_ex(m,NULL,NULL,NULL,NULL,k,NULL)!=1||EVP_DigestSign(m,NULL,&n,h,32)!=1||!n||n>QRX_AURA_MODEL_SIGNATURE_MAX)goto done;p=malloc(n);if(!p)goto done;if(EVP_DigestSign(m,p,&n,h,32)!=1)goto done;*sig=p;*sn=n;p=NULL;rc=0;done:free(p);EVP_MD_CTX_free(m);return rc;}
static int verify_hash(EVP_PKEY*k,const uint8_t h[32],const uint8_t*sig,size_t sn){if(!k||!sig||!sn||sn>QRX_AURA_MODEL_SIGNATURE_MAX)return-1;EVP_MD_CTX*m=EVP_MD_CTX_new();int ok=m&&EVP_DigestVerifyInit_ex(m,NULL,NULL,NULL,NULL,k,NULL)==1&&EVP_DigestVerify(m,sig,sn,h,32)==1;EVP_MD_CTX_free(m);return ok?0:-1;}

void qrx_aura_model_license_policy_init(QrxAuraModelLicensePolicy*p){if(p){memset(p,0,sizeof(*p));p->version=1;p->require_provenance=1;p->allow_external_origin=1;}}
int qrx_aura_model_license_policy_add(QrxAuraModelLicensePolicy*p,const char*id,QrxAuraModelLicenseAction a){if(!p||p->version!=1||!id||!id[0]||strlen(id)>=QRX_AURA_MODEL_LICENSE_MAX||(a!=QRX_AURA_LICENSE_ALLOW&&a!=QRX_AURA_LICENSE_DENY))return-1;for(uint32_t i=0;i<p->rule_count;i++)if(!strcmp(p->rules[i].license_id,id)){p->rules[i].action=a;return 0;}if(p->rule_count>=QRX_AURA_MODEL_LICENSE_RULE_MAX)return-2;QrxAuraModelLicenseRule*r=&p->rules[p->rule_count++];snprintf(r->license_id,sizeof(r->license_id),"%s",id);r->action=a;return 0;}
int qrx_aura_model_license_policy_allows(const QrxAuraModelLicensePolicy*p,const char*id){if(!p||p->version!=1||!id||!id[0])return 0;for(uint32_t i=0;i<p->rule_count;i++)if(!strcmp(p->rules[i].license_id,id))return p->rules[i].action==QRX_AURA_LICENSE_ALLOW;return p->default_allow?1:0;}
int qrx_aura_model_provenance_validate(const QrxAuraModelProvenance*p,const QrxAuraModelCatalogAnnouncement*a){if(!p||!a||p->version!=1||!p->model_id[0]||!p->model_version[0]||!hex64(p->manifest_root)||!p->publisher_id[0]||!p->license_id[0]||!p->source_uri[0]||!hex64(p->source_commit)||!p->recorded_at_height)return-1;if(p->parent_manifest_root[0]&&!hex64(p->parent_manifest_root))return-1;if(strcmp(p->model_id,a->manifest.model_id)||strcmp(p->model_version,a->manifest.model_version)||strcmp(p->manifest_root,a->manifest_root)||strcmp(p->publisher_id,a->publisher_id)||strcmp(p->license_id,a->manifest.license_id))return-2;return 0;}
static int decision_valid(const QrxAuraModelGovernanceDecision*d){if(!d||d->version!=1||!d->governor_id[0]||!d->sequence||!d->effective_height||!d->model_id[0]||!d->model_version[0]||!hex64(d->manifest_root)||d->action<QRX_AURA_MODEL_GOV_APPROVE||d->action>QRX_AURA_MODEL_GOV_ROLLBACK||!memchr(d->reason,0,sizeof(d->reason)))return 0;if(d->action==QRX_AURA_MODEL_GOV_ROLLBACK&&!hex64(d->rollback_manifest_root))return 0;if(d->action!=QRX_AURA_MODEL_GOV_ROLLBACK&&d->rollback_manifest_root[0])return 0;return 1;}
static int decision_payload(const QrxAuraModelGovernanceDecision*d,Buf*b){if(!decision_valid(d))return-1;return u32(b,d->version)||str(b,d->governor_id,sizeof(d->governor_id))||u64(b,d->sequence)||u64(b,d->effective_height)||str(b,d->model_id,sizeof(d->model_id))||str(b,d->model_version,sizeof(d->model_version))||str(b,d->manifest_root,sizeof(d->manifest_root))||str(b,d->rollback_manifest_root,sizeof(d->rollback_manifest_root))||u32(b,(uint32_t)d->action)||str(b,d->reason,sizeof(d->reason))?-1:0;}
int qrx_aura_model_governance_decision_hash(const QrxAuraModelGovernanceDecision*d,uint8_t out[32]){if(!out)return-1;Buf b={0};if(decision_payload(d,&b)){free(b.p);return-1;}int rc=hash_domain(GOV_DOMAIN,b.p,b.n,out);free(b.p);return rc;}
int qrx_aura_model_governance_decision_sign(EVP_PKEY*k,const QrxAuraModelGovernanceDecision*d,uint8_t**sig,size_t*sn){uint8_t h[32];if(qrx_aura_model_governance_decision_hash(d,h))return-1;int rc=sign_hash(k,h,sig,sn);OPENSSL_cleanse(h,sizeof(h));return rc;}
int qrx_aura_model_governance_decision_verify(EVP_PKEY*k,const QrxAuraModelGovernanceDecision*d,const uint8_t*sig,size_t sn){uint8_t h[32];if(qrx_aura_model_governance_decision_hash(d,h))return-1;int rc=verify_hash(k,h,sig,sn);OPENSSL_cleanse(h,sizeof(h));return rc;}
void qrx_aura_model_governance_state_init(QrxAuraModelGovernanceState*s){if(s){memset(s,0,sizeof(*s));s->version=1;}}
void qrx_aura_model_governance_state_free(QrxAuraModelGovernanceState*s){if(!s)return;for(uint32_t i=0;i<s->count;i++)free(s->entries[i].signature);memset(s,0,sizeof(*s));}
static QrxAuraModelGovernanceEntry*gov_slot(QrxAuraModelGovernanceState*s,const char*id,const char*v){for(uint32_t i=0;i<s->count;i++)if(!strcmp(s->entries[i].decision.model_id,id)&&!strcmp(s->entries[i].decision.model_version,v))return&s->entries[i];return NULL;}
int qrx_aura_model_governance_ingest(QrxAuraModelGovernanceState*s,const QrxAuraModelGovernanceDecision*d,const uint8_t*sig,size_t sn,uint64_t h,QrxAuraModelDistKeyLookupFn lookup,void*kctx,QrxAuraModelGovernorAuthorizeFn auth,void*actx){if(!s||s->version!=1||!decision_valid(d)||!sig||!sn||!lookup||!auth||h<d->effective_height||auth(actx,d->governor_id))return-1;EVP_PKEY*pk=NULL;if(lookup(kctx,d->governor_id,&pk)||!pk||qrx_aura_model_governance_decision_verify(pk,d,sig,sn)){EVP_PKEY_free(pk);return-2;}EVP_PKEY_free(pk);QrxAuraModelGovernanceEntry*e=gov_slot(s,d->model_id,d->model_version);if(e&&d->sequence<=e->decision.sequence)return-3;if(!e){if(s->count>=QRX_AURA_MODEL_GOV_MAX_ENTRIES)return-4;e=&s->entries[s->count++];memset(e,0,sizeof(*e));}uint8_t*copy=malloc(sn);if(!copy)return-5;memcpy(copy,sig,sn);free(e->signature);e->decision=*d;e->signature=copy;e->signature_len=sn;s->revision++;return 0;}
const QrxAuraModelGovernanceDecision*qrx_aura_model_governance_find(const QrxAuraModelGovernanceState*s,const char*id,const char*v){if(!s||s->version!=1||!id||!v)return NULL;for(uint32_t i=0;i<s->count;i++)if(!strcmp(s->entries[i].decision.model_id,id)&&!strcmp(s->entries[i].decision.model_version,v))return&s->entries[i].decision;return NULL;}
static void why(char out[QRX_AURA_MODEL_GOV_REASON_MAX],const char*s){if(out)snprintf(out,QRX_AURA_MODEL_GOV_REASON_MAX,"%s",s?s:"");}
int qrx_aura_model_governance_evaluate(const QrxAuraModelGovernanceState*s,const QrxAuraModelLicensePolicy*p,const QrxAuraModelCatalogAnnouncement*a,const QrxAuraModelProvenance*prov,uint64_t h,char reason[QRX_AURA_MODEL_GOV_REASON_MAX]){if(!s||!p||!a||s->version!=1||p->version!=1){why(reason,"invalid governance state/policy");return-1;}if(!qrx_aura_model_license_policy_allows(p,a->manifest.license_id)){why(reason,"license policy rejected model");return-2;}if(!p->allow_external_origin&&a->manifest.origin_uri[0]){why(reason,"external origin disabled by policy");return-3;}if(p->require_provenance){if(!prov||qrx_aura_model_provenance_validate(prov,a)){why(reason,"missing or mismatched provenance");return-4;}if(prov->recorded_at_height>h){why(reason,"provenance is from the future");return-4;}}
    const QrxAuraModelGovernanceDecision*d=qrx_aura_model_governance_find(s,a->manifest.model_id,a->manifest.model_version);if(!d||h<d->effective_height){why(reason,"no effective governance decision");return-5;}if(d->action==QRX_AURA_MODEL_GOV_BLOCK){why(reason,d->reason[0]?d->reason:"model blocked");return-6;}if(d->action==QRX_AURA_MODEL_GOV_APPROVE){if(strcmp(d->manifest_root,a->manifest_root)){why(reason,"manifest not approved");return-7;}}else if(d->action==QRX_AURA_MODEL_GOV_ROLLBACK){if(strcmp(d->rollback_manifest_root,a->manifest_root)){why(reason,"rollback requires previous manifest");return-8;}}
    why(reason,d->action==QRX_AURA_MODEL_GOV_ROLLBACK?"rollback approved":"approved");return 0;}
int qrx_aura_model_catalog_ingest_governed(QrxAuraModelCatalog*c,const QrxAuraModelCatalogAnnouncement*a,const uint8_t*sig,size_t sn,uint64_t h,QrxAuraModelDistKeyLookupFn lookup,void*kctx,QrxAuraModelCatalogAuthorizeFn auth,void*actx,const QrxAuraModelGovernanceState*s,const QrxAuraModelLicensePolicy*p,const QrxAuraModelProvenance*prov){char reason[QRX_AURA_MODEL_GOV_REASON_MAX];if(qrx_aura_model_governance_evaluate(s,p,a,prov,h,reason))return-10;return qrx_aura_model_catalog_ingest(c,a,sig,sn,h,lookup,kctx,auth,actx);}
