#include "compute/qrx_aura_release.h"
#include <openssl/evp.h>
#include <stdio.h>
#include <string.h>

#define RELEASE_DOMAIN "QRX/AURA/RELEASE-READINESS/V1"
static int joinp(const char*d,const char*f,char*out,size_t cap){if(!d||!d[0]||!f||!out)return-1;size_t n=strlen(d);int sep=n&&d[n-1]!='/'&&d[n-1]!='\\';int rc=snprintf(out,cap,"%s%s%s",d,sep?"/":"",f);return rc<0||(size_t)rc>=cap?-1:0;}
static const QrxAuraModelProvenance*find_evidence(const QrxAuraReleaseModelEvidence*e,size_t n,const QrxAuraModelCatalogAnnouncement*a){if(!e||!a)return NULL;for(size_t i=0;i<n;i++){const QrxAuraModelProvenance*p=&e[i].provenance;if(!strcmp(p->model_id,a->manifest.model_id)&&!strcmp(p->model_version,a->manifest.model_version)&&!strcmp(p->manifest_root,a->manifest_root))return p;}return NULL;}
static uint32_t model_provider_count(const QrxAuraModelProviderIndex*i,const QrxAuraModelCatalogAnnouncement*a,uint64_t h){if(!i||!a)return 0;uint32_t n=0;for(uint32_t x=0;x<i->count;x++){const QrxAuraModelAvailabilityAnnouncement*p=&i->entries[x].announcement;if(p->valid_from_height<=h&&p->valid_until_height>=h&&!strcmp(p->model_id,a->manifest.model_id)&&!strcmp(p->model_version,a->manifest.model_version)&&!strcmp(p->manifest_root,a->manifest_root))n++;}return n;}
int qrx_aura_release_migrate_host_config(QrxAuraProviderHostConfig*c,const char*state,QrxAuraReleaseMigrationReport*r){if(!c||!r||!state||!state[0])return-1;memset(r,0,sizeof(*r));r->version=1;if(c->version==0){c->version=QRX_AURA_PROVIDER_HOST_CONFIG_VERSION;r->changed=1;}if(c->version!=QRX_AURA_PROVIDER_HOST_CONFIG_VERSION)return-2;if(c->runtime_adapter.version==0){c->runtime_adapter.version=QRX_AURA_RUNTIME_ADAPTER_VERSION;c->runtime_adapter.kind=QRX_AURA_ADAPTER_AUTO;r->runtime_auto_initialized=1;r->changed=1;}if(!c->require_wallet_approval||!c->require_secure_dispatch||!c->enable_pq_hybrid_sessions){c->require_wallet_approval=1;c->require_secure_dispatch=1;c->enable_pq_hybrid_sessions=1;r->security_hardened=1;r->changed=1;}if(c->enabled&&!c->lease_journal_path[0]){if(joinp(state,"aura-provider.leases",c->lease_journal_path,sizeof(c->lease_journal_path)))return-3;r->lease_journal_derived=1;r->changed=1;}if(c->enabled&&!c->job_journal_path[0]){if(c->lease_journal_path[0]){int n=snprintf(c->job_journal_path,sizeof(c->job_journal_path),"%s.jobs",c->lease_journal_path);if(n<0||(size_t)n>=sizeof(c->job_journal_path))return-3;}else if(joinp(state,"aura-provider.jobs",c->job_journal_path,sizeof(c->job_journal_path)))return-3;r->job_journal_derived=1;r->changed=1;}if(c->enabled&&!c->model_cache_bytes){c->model_cache_bytes=50ull<<30;r->cache_budget_defaulted=1;r->changed=1;}return qrx_aura_provider_host_config_validate(c);}
int qrx_aura_release_readiness_commitment(const QrxAuraReleaseReadiness*r,char out[65]){if(!r||r->version!=1||!out)return-1;QrxAuraReleaseReadiness c=*r;c.readiness_commitment[0]=0;EVP_MD_CTX*m=EVP_MD_CTX_new();unsigned char h[32];unsigned hn=0;int ok=m&&EVP_DigestInit_ex(m,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(m,RELEASE_DOMAIN,strlen(RELEASE_DOMAIN))==1&&EVP_DigestUpdate(m,&c,sizeof(c))==1&&EVP_DigestFinal_ex(m,h,&hn)==1&&hn==32;EVP_MD_CTX_free(m);if(!ok)return-1;static const char x[]="0123456789abcdef";for(int i=0;i<32;i++){out[i*2]=x[h[i]>>4];out[i*2+1]=x[h[i]&15];}out[64]=0;return 0;}
int qrx_aura_release_readiness_check(const QrxAuraProviderHostConfig*host,const QrxAuraRuntimePackageCatalog*rc,const QrxAuraModelCatalog*mc,const QrxAuraModelGovernanceState*gs,const QrxAuraModelLicensePolicy*lp,const QrxAuraReleaseModelEvidence*ev,size_t en,const QrxAuraModelProviderIndex*pi,uint64_t h,QrxAuraReleaseReadiness*out){if(!host||!rc||!mc||!gs||!lp||!pi||!out||en>QRX_AURA_RELEASE_MAX_EVIDENCE)return-1;QrxAuraReleaseReadiness r;memset(&r,0,sizeof(r));r.version=1;r.height=h;r.runtime_packages=rc->count;if(qrx_aura_provider_host_config_validate(host)==0&&(!host->enabled||(host->require_wallet_approval&&host->require_secure_dispatch&&host->enable_pq_hybrid_sessions)))r.host_secure=1;else r.failures++;
    QrxMoeRuntimeInventory inv;if(qrx_moe_runtime_discover_native(&inv)==0){r.discovered_devices=inv.device_count;QrxAuraRuntimeActivationPlan plan;if(qrx_aura_runtime_package_select(rc,&inv,h,QRX_AURA_POWER_BALANCED,&plan)==0){r.runtime_ready=1;snprintf(r.selected_runtime_package,sizeof(r.selected_runtime_package),"%s",plan.package.package_id);}else r.failures++;}else r.failures++;
    int gov_fail=0,dist_fail=0;for(uint32_t i=0;i<mc->count;i++){const QrxAuraModelCatalogAnnouncement*a=&mc->entries[i].announcement;if(h<a->valid_from_height||h>a->valid_until_height)continue;r.active_models++;if(a->recommended)r.recommended_models++;const QrxAuraModelProvenance*p=find_evidence(ev,en,a);char reason[QRX_AURA_MODEL_GOV_REASON_MAX];if(qrx_aura_model_governance_evaluate(gs,lp,a,p,h,reason)==0)r.governed_models++;else if(a->recommended){gov_fail=1;r.failures++;}else r.warnings++;uint32_t pc=model_provider_count(pi,a,h);if(pc||a->manifest.origin_uri[0])r.distributable_models++;else if(a->recommended){dist_fail=1;r.failures++;}else r.warnings++;}
    if(!r.recommended_models){r.failures++;gov_fail=1;}r.model_governance_ready=!gov_fail&&r.governed_models>=r.recommended_models;r.distribution_ready=!dist_fail&&r.distributable_models>=r.recommended_models;r.ready=r.failures==0&&r.host_secure&&r.runtime_ready&&r.model_governance_ready&&r.distribution_ready;if(qrx_aura_release_readiness_commitment(&r,r.readiness_commitment))return-2;*out=r;return 0;}
