#include "compute/qrx_pouc_liveness.h"
#include "compute/qrx_pouc_pipeline.h"
#include <openssl/evp.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <limits.h>

#define VERIFY_PREFIX "consensus:compute:verify:"
#define CHALLENGE_VOTE_PREFIX "consensus:compute:challenge_vote:"
#define CHALLENGE_PREFIX "consensus:compute:challenge:"
typedef struct{char a[QRX_POUC_VERIFIER_ADDRESS_MAX];uint64_t power;uint8_t used;} Cand;typedef struct{Cand c[QRX_POUC_VERIFIER_MAX_CANDIDATES];uint32_t n;} CandSet;
static int safe(const char*s){return s&&s[0]&&!strchr(s,'|')&&!strchr(s,';')&&!strchr(s,'\n')&&!strchr(s,'\r');}
static int hex64(const char*s){if(!s||strlen(s)!=64)return 0;for(int i=0;i<64;i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return 0;}return 1;}
static int u64p(const char*s,uint64_t*out){if(!s||!*s||!out||*s=='-')return -1;errno=0;char*e=NULL;unsigned long long v=strtoull(s,&e,10);if(errno||!e||*e)return -1;*out=v;return 0;}
static int dbu(QrxDB*d,const char*k,uint64_t*out){char b[128];return qrxdb_get(d,k,b,sizeof(b))||u64p(b,out)?-1:0;}
static int putu(QrxDBBatch*b,const char*k,uint64_t v){char x[64];snprintf(x,sizeof(x),"%llu",(unsigned long long)v);return qrxdb_batch_put(b,k,x);}
static int exists(QrxDB*d,const char*k){char b[8];return qrxdb_get(d,k,b,sizeof(b))==0;}
int qrx_pouc_liveness_params_validate(const QrxPoucLivenessParams*p){if(!p||p->version!=QRX_POUC_LIVENESS_PARAMS_VERSION||!p->verifier_miss_threshold||!p->verifier_miss_jail_blocks)return -1;if(p->verifier_miss_threshold>1000000ULL||p->verifier_miss_jail_blocks>100000000ULL)return -2;return 0;}
int qrx_pouc_liveness_params_get(QrxDB*d,QrxPoucLivenessParams*p){if(!d||!p)return -1;memset(p,0,sizeof(*p));p->version=QRX_POUC_LIVENESS_PARAMS_VERSION;if(dbu(d,QRX_POUC_MISS_THRESHOLD_KEY,&p->verifier_miss_threshold)||dbu(d,QRX_POUC_MISS_JAIL_BLOCKS_KEY,&p->verifier_miss_jail_blocks))return -2;return qrx_pouc_liveness_params_validate(p);}
int qrx_pouc_liveness_params_stage(QrxDBBatch*b,const QrxPoucLivenessParams*p){if(!b||qrx_pouc_liveness_params_validate(p))return -1;if(putu(b,QRX_POUC_MISS_THRESHOLD_KEY,p->verifier_miss_threshold)||putu(b,QRX_POUC_MISS_JAIL_BLOCKS_KEY,p->verifier_miss_jail_blocks))return -2;return 0;}
static int add(CandSet*s,const char*a,uint64_t p){if(!safe(a)||!p)return 0;for(uint32_t i=0;i<s->n;i++)if(!strcmp(s->c[i].a,a)){if(UINT64_MAX-s->c[i].power<p)return -1;s->c[i].power+=p;return 0;}if(s->n>=QRX_POUC_VERIFIER_MAX_CANDIDATES)return -1;snprintf(s->c[s->n].a,sizeof(s->c[s->n].a),"%s",a);s->c[s->n].power=p;s->n++;return 0;}
static int scanstake(const char*k,const char*v,uint32_t n,void*ctx){(void)n;CandSet*s=ctx;uint64_t p=0;if(u64p(v,&p)||!p)return 0;const char*a=NULL;if(!strncmp(k,"staking:self:",13))a=k+13;else if(!strncmp(k,"staking:delegated_total:",24))a=k+24;else return 0;return add(s,a,p);}
static int scangen(const char*k,const char*v,uint32_t n,void*ctx){(void)n;CandSet*s=ctx;const char*p="genesis:validator:",*suf=":amount_atoms";size_t pl=strlen(p),sl=strlen(suf),kl=strlen(k);if(kl<=pl+sl||strncmp(k,p,pl)||strcmp(k+kl-sl,suf))return 0;char a[160];size_t al=kl-pl-sl;if(al>=sizeof(a))return -1;memcpy(a,k+pl,al);a[al]=0;uint64_t x=0;if(u64p(v,&x)||!x)return 0;return add(s,a,x);}
static int excluded(const QrxPoucLivenessState*st,const QrxPoucVerifierSelection*sel,const char*a,const char*owner,const char*provider){if(!strcmp(a,owner)||!strcmp(a,provider))return 1;for(uint32_t i=0;i<st->excluded_count;i++)if(!strcmp(a,st->excluded[i]))return 1;for(uint32_t i=0;i<sel->primary_count;i++)if(!strcmp(a,sel->primary[i]))return 1;for(uint32_t i=0;i<sel->challenge_count;i++)if(!strcmp(a,sel->challenger[i]))return 1;return 0;}
static int collect(QrxDB*d,const QrxPoucLivenessState*st,const QrxPoucVerifierSelection*sel,const char*owner,const char*provider,uint64_t h,CandSet*out){memset(out,0,sizeof(*out));if(qrxdb_scan_prefix(d,"staking:self:",scanstake,out)||qrxdb_scan_prefix(d,"staking:delegated_total:",scanstake,out)||qrxdb_scan_prefix(d,"genesis:validator:",scangen,out))return -1;uint32_t w=0;for(uint32_t i=0;i<out->n;i++){if(excluded(st,sel,out->c[i].a,owner,provider)||qrx_pouc_verifier_is_compute_jailed(d,out->c[i].a,h))continue;if(w!=i)out->c[w]=out->c[i];w++;}out->n=w;return 0;}
static int fld(EVP_MD_CTX*c,const void*p,size_t n){unsigned char z[8];uint64_t v=n;for(int i=0;i<8;i++)z[i]=(unsigned char)(v>>(56-8*i));return EVP_DigestUpdate(c,z,8)!=1||(n&&EVP_DigestUpdate(c,p,n)!=1)?-1:0;}
static int fld_u32(EVP_MD_CTX*c,uint32_t v){unsigned char b[4]={(unsigned char)(v>>24),(unsigned char)(v>>16),(unsigned char)(v>>8),(unsigned char)v};return fld(c,b,sizeof(b));}
static int hashpick(const char*block,const char*rc,const char*prev,uint32_t round,uint32_t phase,uint32_t slot,uint64_t*out){EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned char h[32];unsigned int hn=0;const char dom[]="QRX/POUC/VERIFIER-RESELECTION/RANDOM/V1";int ok=c&&EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1;if(ok&&fld(c,dom,sizeof(dom)-1))ok=0;if(ok&&fld(c,block,strlen(block)))ok=0;if(ok&&fld(c,rc,64))ok=0;if(ok&&fld(c,prev,64))ok=0;if(ok&&fld_u32(c,round))ok=0;if(ok&&fld_u32(c,phase))ok=0;if(ok&&fld_u32(c,slot))ok=0;if(ok&&EVP_DigestFinal_ex(c,h,&hn)!=1)ok=0;if(c)EVP_MD_CTX_free(c);if(!ok||hn!=32)return -1;uint64_t x=0;for(int i=0;i<8;i++)x=(x<<8)|h[i];*out=x;return 0;}
static int pick(CandSet*s,const char*block,const char*rc,const char*prev,uint32_t round,uint32_t phase,uint32_t slot,char out[160]){uint64_t total=0;for(uint32_t i=0;i<s->n;i++)if(!s->c[i].used){if(UINT64_MAX-total<s->c[i].power)return -1;total+=s->c[i].power;}if(!total)return -1;uint64_t r=0;if(hashpick(block,rc,prev,round,phase,slot,&r))return -1;uint64_t t=r%total,a=0;for(uint32_t i=0;i<s->n;i++)if(!s->c[i].used){a+=s->c[i].power;if(t<a){s->c[i].used=1;snprintf(out,160,"%s",s->c[i].a);return 0;}}return -1;}
static int state_enc(const QrxPoucLivenessState*s,char*out,size_t n){int z=snprintf(out,n,"%u|%s|%u|%u|%llu",s->version,s->receipt_commitment,s->round,s->excluded_count,(unsigned long long)s->last_reselection_height);if(z<0||(size_t)z>=n)return -1;size_t off=z;for(uint32_t i=0;i<s->excluded_count;i++){z=snprintf(out+off,n-off,"|%s",s->excluded[i]);if(z<0||(size_t)z>=n-off)return -1;off+=z;}return 0;}
static int state_dec(const char*s,QrxPoucLivenessState*out){if(!s||!out)return -1;memset(out,0,sizeof(*out));char *tmp=strdup(s);if(!tmp)return -1;char*save=NULL,*t=strtok_r(tmp,"|",&save);if(!t){free(tmp);return -1;}out->version=strtoul(t,NULL,10);t=strtok_r(NULL,"|",&save);if(!t||!hex64(t)){free(tmp);return -1;}snprintf(out->receipt_commitment,65,"%s",t);t=strtok_r(NULL,"|",&save);if(!t){free(tmp);return -1;}out->round=strtoul(t,NULL,10);t=strtok_r(NULL,"|",&save);if(!t){free(tmp);return -1;}out->excluded_count=strtoul(t,NULL,10);t=strtok_r(NULL,"|",&save);if(!t||u64p(t,&out->last_reselection_height)||out->excluded_count>QRX_POUC_LIVENESS_MAX_EXCLUDED){free(tmp);return -1;}for(uint32_t i=0;i<out->excluded_count;i++){t=strtok_r(NULL,"|",&save);if(!t||!safe(t)){free(tmp);return -1;}snprintf(out->excluded[i],160,"%s",t);}free(tmp);return out->version==1?0:-1;}
int qrx_pouc_liveness_get(QrxDB*d,const char rc[65],QrxPoucLivenessState*out){if(!d||!hex64(rc)||!out)return -1;char k[200],v[12000];snprintf(k,sizeof(k),"%s%s",QRX_POUC_LIVENESS_PREFIX,rc);if(qrxdb_get(d,k,v,sizeof(v))){memset(out,0,sizeof(*out));out->version=1;snprintf(out->receipt_commitment,65,"%s",rc);return 0;}return state_dec(v,out);}
static int sel_enc(const QrxPoucVerifierSelection*s,char*out,size_t n){int z=snprintf(out,n,"%u|%s|%llu|%s|%u|%u|%u|%u|%llu|%llu|%llu|%llu|%s|%s|%s|%s|%s|%s|%s",s->version,s->receipt_commitment,(unsigned long long)s->entropy_height,s->entropy_block_hash,s->verification_mode,s->target_verifiers,s->primary_count,s->challenge_count,(unsigned long long)s->primary_reward_atoms,(unsigned long long)s->challenge_reward_atoms,(unsigned long long)s->verification_deadline_height,(unsigned long long)s->challenge_deadline_height,s->primary[0][0]?s->primary[0]:"-",s->primary[1][0]?s->primary[1]:"-",s->primary[2][0]?s->primary[2]:"-",s->challenger[0][0]?s->challenger[0]:"-",s->challenger[1][0]?s->challenger[1]:"-",s->challenger[2][0]?s->challenger[2]:"-",s->selection_commitment);return z>0&&(size_t)z<n?0:-1;}
static int sel_dec(const char*s,QrxPoucVerifierSelection*out){unsigned v=0,m=0,t=0,pc=0,cc=0;unsigned long long eh=0,pr=0,cr=0,vd=0,cd=0;char rc[65]={0},bh[129]={0},p0[160]={0},p1[160]={0},p2[160]={0},c0[160]={0},c1[160]={0},c2[160]={0},sc[65]={0};if(sscanf(s,"%u|%64[^|]|%llu|%128[^|]|%u|%u|%u|%u|%llu|%llu|%llu|%llu|%159[^|]|%159[^|]|%159[^|]|%159[^|]|%159[^|]|%159[^|]|%64s",&v,rc,&eh,bh,&m,&t,&pc,&cc,&pr,&cr,&vd,&cd,p0,p1,p2,c0,c1,c2,sc)!=19)return -1;memset(out,0,sizeof(*out));out->version=v;snprintf(out->receipt_commitment,65,"%s",rc);out->entropy_height=eh;snprintf(out->entropy_block_hash,129,"%s",bh);out->verification_mode=m;out->target_verifiers=t;out->primary_count=pc;out->challenge_count=cc;out->primary_reward_atoms=pr;out->challenge_reward_atoms=cr;out->verification_deadline_height=vd;out->challenge_deadline_height=cd;char*pp[6]={p0,p1,p2,c0,c1,c2};for(int i=0;i<6;i++)if(!strcmp(pp[i],"-"))pp[i][0]=0;snprintf(out->primary[0],160,"%s",p0);snprintf(out->primary[1],160,"%s",p1);snprintf(out->primary[2],160,"%s",p2);snprintf(out->challenger[0],160,"%s",c0);snprintf(out->challenger[1],160,"%s",c1);snprintf(out->challenger[2],160,"%s",c2);snprintf(out->selection_commitment,65,"%s",sc);char chk[65];return qrx_pouc_verifier_selection_commitment(out,chk)||strcmp(chk,sc)?-1:0;}
static int penalty_id(const char*rc,const char*v,uint32_t phase,uint32_t round,char out[65]){EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned char h[32];unsigned int n=0;const char dom[]="QRX/POUC/VERIFIER-MISS-PENALTY/V1";int ok=c&&EVP_DigestInit_ex(c,EVP_sha3_256(),NULL)==1;if(ok&&fld(c,dom,sizeof(dom)-1))ok=0;if(ok&&fld(c,rc,64))ok=0;if(ok&&fld(c,v,strlen(v)))ok=0;if(ok&&fld_u32(c,phase))ok=0;if(ok&&fld_u32(c,round))ok=0;if(ok&&EVP_DigestFinal_ex(c,h,&n)!=1)ok=0;if(c)EVP_MD_CTX_free(c);if(!ok||n!=32)return -1;static const char hx[]="0123456789abcdef";for(int i=0;i<32;i++){out[2*i]=hx[h[i]>>4];out[2*i+1]=hx[h[i]&15];}out[64]=0;return 0;}
int qrx_pouc_reselection_prepare(QrxDB*d,const char rc[65],uint64_t h,QrxPoucReselectionEffect*out){if(!d||!hex64(rc)||!h||!out||h<2)return -1;memset(out,0,sizeof(*out));out->version=1;snprintf(out->receipt_commitment,65,"%s",rc);QrxPoucReceipt r;QrxPoucAssignment a;if(qrx_pouc_pipeline_get_receipt(d,rc,&r)||qrx_pouc_pipeline_get_assignment(d,r.graph_commitment,&a)||qrx_pouc_verifier_selection_get(d,rc,&out->before)||qrx_pouc_liveness_get(d,rc,&out->state_before))return -2;out->after=out->before;out->state_after=out->state_before;out->round=out->state_before.round+1;out->apply_height=h;uint64_t threshold=0,jail_blocks=0;if(dbu(d,QRX_POUC_MISS_THRESHOLD_KEY,&threshold)||!threshold||dbu(d,QRX_POUC_MISS_JAIL_BLOCKS_KEY,&jail_blocks)||!jail_blocks)return -3;
 QrxPoucVerificationAggregate ag={0};int agok=qrx_pouc_pipeline_get_verification(d,rc,&ag)==0;char ck[200],cv[32]={0};snprintf(ck,sizeof(ck),"%s%s",CHALLENGE_PREFIX,rc);int challenge_pending=qrxdb_get(d,ck,cv,sizeof(cv))==0&&!strcmp(cv,"PENDING");if((!agok||!ag.finalized)&&h>out->before.verification_deadline_height)out->phase=QRX_POUC_TIMEOUT_PRIMARY;else if(agok&&ag.finalized&&challenge_pending&&h>out->before.challenge_deadline_height)out->phase=QRX_POUC_TIMEOUT_CHALLENGE;else return -4;
 uint32_t count=out->phase==QRX_POUC_TIMEOUT_PRIMARY?out->before.primary_count:out->before.challenge_count;for(uint32_t i=0;i<count;i++){const char*v=out->phase==QRX_POUC_TIMEOUT_PRIMARY?out->before.primary[i]:out->before.challenger[i];snprintf(ck,sizeof(ck),"%s%s:%s",out->phase==QRX_POUC_TIMEOUT_PRIMARY?VERIFY_PREFIX:CHALLENGE_VOTE_PREFIX,rc,v);if(!exists(d,ck)){if(out->timeout_count>=3||out->state_after.excluded_count>=QRX_POUC_LIVENESS_MAX_EXCLUDED)return -5;uint32_t z=out->timeout_count++;snprintf(out->timed_out[z],160,"%s",v);snprintf(out->state_after.excluded[out->state_after.excluded_count++],160,"%s",v);char mk[256];snprintf(mk,sizeof(mk),"%s%s",QRX_POUC_MISS_COUNT_PREFIX,v);uint64_t mb=0;(void)dbu(d,mk,&mb);out->miss_before[z]=mb;out->miss_after[z]=mb+1;if(out->miss_after[z]%threshold==0){out->jail_applied[z]=1;if(penalty_id(rc,v,out->phase,out->round,out->penalty_id[z]))return -6;}}}if(!out->timeout_count)return -7;
 char block[129];if(qrxdb_chain_get_block_hash_by_height(d,h-1,block,sizeof(block)))return -8;CandSet set;if(collect(d,&out->state_after,&out->before,a.owner,a.provider,h-1,&set)||set.n<out->timeout_count)return -9;for(uint32_t z=0;z<out->timeout_count;z++){uint32_t slot=UINT32_MAX;for(uint32_t i=0;i<count;i++){const char*v=out->phase==QRX_POUC_TIMEOUT_PRIMARY?out->before.primary[i]:out->before.challenger[i];if(!strcmp(v,out->timed_out[z])){slot=i;break;}}if(slot==UINT32_MAX)return -10;char nv[160];if(pick(&set,block,rc,out->before.selection_commitment,out->round,out->phase,slot,nv))return -11;if(out->phase==QRX_POUC_TIMEOUT_PRIMARY)snprintf(out->after.primary[slot],160,"%s",nv);else snprintf(out->after.challenger[slot],160,"%s",nv);}
 out->after.entropy_height=h-1;snprintf(out->after.entropy_block_hash,129,"%s",block);if(out->phase==QRX_POUC_TIMEOUT_PRIMARY){out->after.verification_deadline_height=h+QRX_POUC_VERIFY_WINDOW_BLOCKS;out->after.challenge_deadline_height=out->after.verification_deadline_height+QRX_POUC_CHALLENGE_WINDOW_BLOCKS;}else out->after.challenge_deadline_height=h+QRX_POUC_CHALLENGE_WINDOW_BLOCKS;if(qrx_pouc_verifier_selection_commitment(&out->after,out->after.selection_commitment))return -12;out->state_after.round=out->round;out->state_after.last_reselection_height=h;return 0;}
int qrx_pouc_reselection_stage(QrxDB*d,QrxDBBatch*b,const QrxPoucReselectionEffect*e,const char*txid){if(!d||!b||!e||e->version!=1||!txid||!*txid||!e->timeout_count)return -1;QrxPoucVerifierSelection cur;if(qrx_pouc_verifier_selection_get(d,e->receipt_commitment,&cur)||strcmp(cur.selection_commitment,e->before.selection_commitment))return -2;char k[256],v[20000],sb[4096],sa[12000];if(sel_enc(&e->before,sb,sizeof(sb))||state_enc(&e->state_after,sa,sizeof(sa)))return -3;snprintf(k,sizeof(k),"%s%s:%010u",QRX_POUC_LIVENESS_HISTORY_PREFIX,e->receipt_commitment,e->round);snprintf(v,sizeof(v),"APPLIED|%llu|%u|%u|%u|%s|%s",(unsigned long long)e->apply_height,(unsigned)e->phase,e->round,e->state_before.excluded_count,e->before.selection_commitment,txid);if(qrxdb_batch_put(b,k,v))return -4;snprintf(k,sizeof(k),"%s%s:%010u:selection",QRX_POUC_LIVENESS_HISTORY_PREFIX,e->receipt_commitment,e->round);if(qrxdb_batch_put(b,k,sb)||qrx_pouc_verifier_selection_stage(b,&e->after))return -5;snprintf(k,sizeof(k),"%s%s",QRX_POUC_LIVENESS_PREFIX,e->receipt_commitment);if(qrxdb_batch_put(b,k,sa))return -6;uint64_t threshold=0,jail_blocks=0;if(dbu(d,QRX_POUC_MISS_THRESHOLD_KEY,&threshold)||dbu(d,QRX_POUC_MISS_JAIL_BLOCKS_KEY,&jail_blocks))return -7;for(uint32_t i=0;i<e->timeout_count;i++){char mk[256];snprintf(mk,sizeof(mk),"%s%s",QRX_POUC_MISS_COUNT_PREFIX,e->timed_out[i]);if(putu(b,mk,e->miss_after[i]))return -8;snprintf(k,sizeof(k),"%s%s:%010u:miss:%u",QRX_POUC_LIVENESS_HISTORY_PREFIX,e->receipt_commitment,e->round,i);snprintf(v,sizeof(v),"%s|%llu|%llu|%u|%s",e->timed_out[i],(unsigned long long)e->miss_before[i],(unsigned long long)e->miss_after[i],(unsigned)e->jail_applied[i],e->penalty_id[i][0]?e->penalty_id[i]:"-");if(qrxdb_batch_put(b,k,v))return -9;if(e->jail_applied[i]){uint64_t sl=0,ju=0;if(qrx_pouc_stage_consensus_penalty_custom(d,b,e->timed_out[i],e->penalty_id[i],e->receipt_commitment,e->apply_height,0,jail_blocks,&sl,&ju))return -10;}}return 0;}
typedef struct{char rc[65];uint32_t round;uint64_t h;uint32_t phase;uint32_t before_ex;} Hist;typedef struct{Hist h[512];uint32_t n;} HistSet;
static int scanhist(const char*k,const char*v,uint32_t n,void*ctx){(void)n;if(strstr(k,":selection")||strstr(k,":miss:"))return 0;HistSet*s=ctx;const char*p=QRX_POUC_LIVENESS_HISTORY_PREFIX;size_t pl=strlen(p);if(strncmp(k,p,pl)||s->n>=512)return 0;char st[16],oldc[65],tx[160];unsigned long long h=0;unsigned ph=0,r=0,be=0;if(sscanf(v,"%15[^|]|%llu|%u|%u|%u|%64[^|]|%159s",st,&h,&ph,&r,&be,oldc,tx)!=7||strcmp(st,"APPLIED"))return 0;const char*q=k+pl;const char*col=strchr(q,':');if(!col||col-q!=64)return 0;memcpy(s->h[s->n].rc,q,64);s->h[s->n].rc[64]=0;s->h[s->n].round=r;s->h[s->n].h=h;s->h[s->n].phase=ph;s->h[s->n].before_ex=be;s->n++;return 0;}
static int cmph(const void*a,const void*b){const Hist*x=a,*y=b;return x->h<y->h?1:x->h>y->h?-1:x->round<y->round?1:-1;}
int qrx_pouc_liveness_revert_above_height(QrxDB*d,uint64_t canon,uint32_t*out){
 if(!d)return -1;HistSet s;memset(&s,0,sizeof(s));if(qrxdb_scan_prefix(d,QRX_POUC_LIVENESS_HISTORY_PREFIX,scanhist,&s))return -2;qsort(s.h,s.n,sizeof(s.h[0]),cmph);uint32_t reverted=0;
 /* Commit each historical step separately in descending height order. This is
    intentional: the next rollback step must observe the state restored by the
    previous one when multiple reselection rounds are orphaned at once. */
 for(uint32_t z=0;z<s.n;z++){Hist*h=&s.h[z];if(h->h<=canon)continue;char k[256],v[20000];snprintf(k,sizeof(k),"%s%s:%010u:selection",QRX_POUC_LIVENESS_HISTORY_PREFIX,h->rc,h->round);if(qrxdb_get(d,k,v,sizeof(v)))return -4;QrxPoucVerifierSelection old;if(sel_dec(v,&old))return -5;QrxPoucLivenessState st;if(qrx_pouc_liveness_get(d,h->rc,&st))return -6;st.round=h->round-1;st.excluded_count=h->before_ex;st.last_reselection_height=0;for(uint32_t j=0;j<s.n;j++)if(s.h[j].h<=canon&&!strcmp(s.h[j].rc,h->rc)&&s.h[j].round<=st.round&&s.h[j].h>st.last_reselection_height)st.last_reselection_height=s.h[j].h;char se[12000];if(state_enc(&st,se,sizeof(se)))return -7;QrxDBBatch b;if(qrxdb_batch_begin(d,&b))return -3;if(qrx_pouc_verifier_selection_stage(&b,&old)){qrxdb_batch_abort(&b);return -5;}snprintf(k,sizeof(k),"%s%s",QRX_POUC_LIVENESS_PREFIX,h->rc);if(qrxdb_batch_put(&b,k,se)){qrxdb_batch_abort(&b);return -8;}for(uint32_t i=0;i<3;i++){snprintf(k,sizeof(k),"%s%s:%010u:miss:%u",QRX_POUC_LIVENESS_HISTORY_PREFIX,h->rc,h->round,i);if(qrxdb_get(d,k,v,sizeof(v)))break;char val[160],pid[65];unsigned long long mb=0,ma=0;unsigned ja=0;if(sscanf(v,"%159[^|]|%llu|%llu|%u|%64s",val,&mb,&ma,&ja,pid)!=5)continue;snprintf(k,sizeof(k),"%s%s",QRX_POUC_MISS_COUNT_PREFIX,val);if(putu(&b,k,mb)){qrxdb_batch_abort(&b);return -9;}}snprintf(k,sizeof(k),"%s%s:%010u",QRX_POUC_LIVENESS_HISTORY_PREFIX,h->rc,h->round);snprintf(v,sizeof(v),"REVERTED|%llu",(unsigned long long)h->h);if(qrxdb_batch_put(&b,k,v)){qrxdb_batch_abort(&b);return -10;}if(qrxdb_batch_commit(&b)){qrxdb_batch_abort(&b);return -11;}reverted++;}
 uint32_t pr=0;if(qrx_pouc_penalty_journal_revert_above_height(d,canon,&pr))return -12;if(out)*out=reverted;return 0;
}
